package com.boresjo.play.api.google.gkeonprem

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putListSchemaOperation: Conversion[List[Schema.Operation], Option[List[Schema.Operation]]] = (fun: List[Schema.Operation]) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaBareMetalClusterStateEnum: Conversion[Schema.BareMetalCluster.StateEnum, Option[Schema.BareMetalCluster.StateEnum]] = (fun: Schema.BareMetalCluster.StateEnum) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putSchemaBareMetalNetworkConfig: Conversion[Schema.BareMetalNetworkConfig, Option[Schema.BareMetalNetworkConfig]] = (fun: Schema.BareMetalNetworkConfig) => Option(fun)
		given putSchemaBareMetalControlPlaneConfig: Conversion[Schema.BareMetalControlPlaneConfig, Option[Schema.BareMetalControlPlaneConfig]] = (fun: Schema.BareMetalControlPlaneConfig) => Option(fun)
		given putSchemaBareMetalLoadBalancerConfig: Conversion[Schema.BareMetalLoadBalancerConfig, Option[Schema.BareMetalLoadBalancerConfig]] = (fun: Schema.BareMetalLoadBalancerConfig) => Option(fun)
		given putSchemaBareMetalStorageConfig: Conversion[Schema.BareMetalStorageConfig, Option[Schema.BareMetalStorageConfig]] = (fun: Schema.BareMetalStorageConfig) => Option(fun)
		given putSchemaBareMetalProxyConfig: Conversion[Schema.BareMetalProxyConfig, Option[Schema.BareMetalProxyConfig]] = (fun: Schema.BareMetalProxyConfig) => Option(fun)
		given putSchemaBareMetalClusterOperationsConfig: Conversion[Schema.BareMetalClusterOperationsConfig, Option[Schema.BareMetalClusterOperationsConfig]] = (fun: Schema.BareMetalClusterOperationsConfig) => Option(fun)
		given putSchemaBareMetalMaintenanceConfig: Conversion[Schema.BareMetalMaintenanceConfig, Option[Schema.BareMetalMaintenanceConfig]] = (fun: Schema.BareMetalMaintenanceConfig) => Option(fun)
		given putSchemaBareMetalWorkloadNodeConfig: Conversion[Schema.BareMetalWorkloadNodeConfig, Option[Schema.BareMetalWorkloadNodeConfig]] = (fun: Schema.BareMetalWorkloadNodeConfig) => Option(fun)
		given putSchemaFleet: Conversion[Schema.Fleet, Option[Schema.Fleet]] = (fun: Schema.Fleet) => Option(fun)
		given putSchemaResourceStatus: Conversion[Schema.ResourceStatus, Option[Schema.ResourceStatus]] = (fun: Schema.ResourceStatus) => Option(fun)
		given putSchemaValidationCheck: Conversion[Schema.ValidationCheck, Option[Schema.ValidationCheck]] = (fun: Schema.ValidationCheck) => Option(fun)
		given putSchemaBareMetalSecurityConfig: Conversion[Schema.BareMetalSecurityConfig, Option[Schema.BareMetalSecurityConfig]] = (fun: Schema.BareMetalSecurityConfig) => Option(fun)
		given putSchemaBareMetalMaintenanceStatus: Conversion[Schema.BareMetalMaintenanceStatus, Option[Schema.BareMetalMaintenanceStatus]] = (fun: Schema.BareMetalMaintenanceStatus) => Option(fun)
		given putSchemaBareMetalNodeAccessConfig: Conversion[Schema.BareMetalNodeAccessConfig, Option[Schema.BareMetalNodeAccessConfig]] = (fun: Schema.BareMetalNodeAccessConfig) => Option(fun)
		given putSchemaBareMetalOsEnvironmentConfig: Conversion[Schema.BareMetalOsEnvironmentConfig, Option[Schema.BareMetalOsEnvironmentConfig]] = (fun: Schema.BareMetalOsEnvironmentConfig) => Option(fun)
		given putSchemaBinaryAuthorization: Conversion[Schema.BinaryAuthorization, Option[Schema.BinaryAuthorization]] = (fun: Schema.BinaryAuthorization) => Option(fun)
		given putSchemaBareMetalClusterUpgradePolicy: Conversion[Schema.BareMetalClusterUpgradePolicy, Option[Schema.BareMetalClusterUpgradePolicy]] = (fun: Schema.BareMetalClusterUpgradePolicy) => Option(fun)
		given putSchemaBareMetalIslandModeCidrConfig: Conversion[Schema.BareMetalIslandModeCidrConfig, Option[Schema.BareMetalIslandModeCidrConfig]] = (fun: Schema.BareMetalIslandModeCidrConfig) => Option(fun)
		given putSchemaBareMetalMultipleNetworkInterfacesConfig: Conversion[Schema.BareMetalMultipleNetworkInterfacesConfig, Option[Schema.BareMetalMultipleNetworkInterfacesConfig]] = (fun: Schema.BareMetalMultipleNetworkInterfacesConfig) => Option(fun)
		given putSchemaBareMetalSrIovConfig: Conversion[Schema.BareMetalSrIovConfig, Option[Schema.BareMetalSrIovConfig]] = (fun: Schema.BareMetalSrIovConfig) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaBareMetalControlPlaneNodePoolConfig: Conversion[Schema.BareMetalControlPlaneNodePoolConfig, Option[Schema.BareMetalControlPlaneNodePoolConfig]] = (fun: Schema.BareMetalControlPlaneNodePoolConfig) => Option(fun)
		given putListSchemaBareMetalApiServerArgument: Conversion[List[Schema.BareMetalApiServerArgument], Option[List[Schema.BareMetalApiServerArgument]]] = (fun: List[Schema.BareMetalApiServerArgument]) => Option(fun)
		given putSchemaBareMetalNodePoolConfig: Conversion[Schema.BareMetalNodePoolConfig, Option[Schema.BareMetalNodePoolConfig]] = (fun: Schema.BareMetalNodePoolConfig) => Option(fun)
		given putListSchemaBareMetalNodeConfig: Conversion[List[Schema.BareMetalNodeConfig], Option[List[Schema.BareMetalNodeConfig]]] = (fun: List[Schema.BareMetalNodeConfig]) => Option(fun)
		given putSchemaBareMetalNodePoolConfigOperatingSystemEnum: Conversion[Schema.BareMetalNodePoolConfig.OperatingSystemEnum, Option[Schema.BareMetalNodePoolConfig.OperatingSystemEnum]] = (fun: Schema.BareMetalNodePoolConfig.OperatingSystemEnum) => Option(fun)
		given putListSchemaNodeTaint: Conversion[List[Schema.NodeTaint], Option[List[Schema.NodeTaint]]] = (fun: List[Schema.NodeTaint]) => Option(fun)
		given putSchemaBareMetalKubeletConfig: Conversion[Schema.BareMetalKubeletConfig, Option[Schema.BareMetalKubeletConfig]] = (fun: Schema.BareMetalKubeletConfig) => Option(fun)
		given putSchemaNodeTaintEffectEnum: Conversion[Schema.NodeTaint.EffectEnum, Option[Schema.NodeTaint.EffectEnum]] = (fun: Schema.NodeTaint.EffectEnum) => Option(fun)
		given putSchemaBareMetalVipConfig: Conversion[Schema.BareMetalVipConfig, Option[Schema.BareMetalVipConfig]] = (fun: Schema.BareMetalVipConfig) => Option(fun)
		given putSchemaBareMetalPortConfig: Conversion[Schema.BareMetalPortConfig, Option[Schema.BareMetalPortConfig]] = (fun: Schema.BareMetalPortConfig) => Option(fun)
		given putSchemaBareMetalMetalLbConfig: Conversion[Schema.BareMetalMetalLbConfig, Option[Schema.BareMetalMetalLbConfig]] = (fun: Schema.BareMetalMetalLbConfig) => Option(fun)
		given putSchemaBareMetalManualLbConfig: Conversion[Schema.BareMetalManualLbConfig, Option[Schema.BareMetalManualLbConfig]] = (fun: Schema.BareMetalManualLbConfig) => Option(fun)
		given putSchemaBareMetalBgpLbConfig: Conversion[Schema.BareMetalBgpLbConfig, Option[Schema.BareMetalBgpLbConfig]] = (fun: Schema.BareMetalBgpLbConfig) => Option(fun)
		given putListSchemaBareMetalLoadBalancerAddressPool: Conversion[List[Schema.BareMetalLoadBalancerAddressPool], Option[List[Schema.BareMetalLoadBalancerAddressPool]]] = (fun: List[Schema.BareMetalLoadBalancerAddressPool]) => Option(fun)
		given putSchemaBareMetalLoadBalancerNodePoolConfig: Conversion[Schema.BareMetalLoadBalancerNodePoolConfig, Option[Schema.BareMetalLoadBalancerNodePoolConfig]] = (fun: Schema.BareMetalLoadBalancerNodePoolConfig) => Option(fun)
		given putListSchemaBareMetalBgpPeerConfig: Conversion[List[Schema.BareMetalBgpPeerConfig], Option[List[Schema.BareMetalBgpPeerConfig]]] = (fun: List[Schema.BareMetalBgpPeerConfig]) => Option(fun)
		given putSchemaBareMetalLvpShareConfig: Conversion[Schema.BareMetalLvpShareConfig, Option[Schema.BareMetalLvpShareConfig]] = (fun: Schema.BareMetalLvpShareConfig) => Option(fun)
		given putSchemaBareMetalLvpConfig: Conversion[Schema.BareMetalLvpConfig, Option[Schema.BareMetalLvpConfig]] = (fun: Schema.BareMetalLvpConfig) => Option(fun)
		given putSchemaBareMetalWorkloadNodeConfigContainerRuntimeEnum: Conversion[Schema.BareMetalWorkloadNodeConfig.ContainerRuntimeEnum, Option[Schema.BareMetalWorkloadNodeConfig.ContainerRuntimeEnum]] = (fun: Schema.BareMetalWorkloadNodeConfig.ContainerRuntimeEnum) => Option(fun)
		given putListSchemaResourceCondition: Conversion[List[Schema.ResourceCondition], Option[List[Schema.ResourceCondition]]] = (fun: List[Schema.ResourceCondition]) => Option(fun)
		given putSchemaVersions: Conversion[Schema.Versions, Option[Schema.Versions]] = (fun: Schema.Versions) => Option(fun)
		given putSchemaResourceConditionStateEnum: Conversion[Schema.ResourceCondition.StateEnum, Option[Schema.ResourceCondition.StateEnum]] = (fun: Schema.ResourceCondition.StateEnum) => Option(fun)
		given putListSchemaVersion: Conversion[List[Schema.Version], Option[List[Schema.Version]]] = (fun: List[Schema.Version]) => Option(fun)
		given putSchemaValidationCheckOptionEnum: Conversion[Schema.ValidationCheck.OptionEnum, Option[Schema.ValidationCheck.OptionEnum]] = (fun: Schema.ValidationCheck.OptionEnum) => Option(fun)
		given putSchemaValidationCheckStatus: Conversion[Schema.ValidationCheckStatus, Option[Schema.ValidationCheckStatus]] = (fun: Schema.ValidationCheckStatus) => Option(fun)
		given putSchemaValidationCheckScenarioEnum: Conversion[Schema.ValidationCheck.ScenarioEnum, Option[Schema.ValidationCheck.ScenarioEnum]] = (fun: Schema.ValidationCheck.ScenarioEnum) => Option(fun)
		given putListSchemaValidationCheckResult: Conversion[List[Schema.ValidationCheckResult], Option[List[Schema.ValidationCheckResult]]] = (fun: List[Schema.ValidationCheckResult]) => Option(fun)
		given putSchemaValidationCheckResultStateEnum: Conversion[Schema.ValidationCheckResult.StateEnum, Option[Schema.ValidationCheckResult.StateEnum]] = (fun: Schema.ValidationCheckResult.StateEnum) => Option(fun)
		given putSchemaAuthorization: Conversion[Schema.Authorization, Option[Schema.Authorization]] = (fun: Schema.Authorization) => Option(fun)
		given putListSchemaClusterUser: Conversion[List[Schema.ClusterUser], Option[List[Schema.ClusterUser]]] = (fun: List[Schema.ClusterUser]) => Option(fun)
		given putSchemaBareMetalMachineDrainStatus: Conversion[Schema.BareMetalMachineDrainStatus, Option[Schema.BareMetalMachineDrainStatus]] = (fun: Schema.BareMetalMachineDrainStatus) => Option(fun)
		given putListSchemaBareMetalDrainingMachine: Conversion[List[Schema.BareMetalDrainingMachine], Option[List[Schema.BareMetalDrainingMachine]]] = (fun: List[Schema.BareMetalDrainingMachine]) => Option(fun)
		given putListSchemaBareMetalDrainedMachine: Conversion[List[Schema.BareMetalDrainedMachine], Option[List[Schema.BareMetalDrainedMachine]]] = (fun: List[Schema.BareMetalDrainedMachine]) => Option(fun)
		given putSchemaBinaryAuthorizationEvaluationModeEnum: Conversion[Schema.BinaryAuthorization.EvaluationModeEnum, Option[Schema.BinaryAuthorization.EvaluationModeEnum]] = (fun: Schema.BinaryAuthorization.EvaluationModeEnum) => Option(fun)
		given putSchemaBareMetalClusterUpgradePolicyPolicyEnum: Conversion[Schema.BareMetalClusterUpgradePolicy.PolicyEnum, Option[Schema.BareMetalClusterUpgradePolicy.PolicyEnum]] = (fun: Schema.BareMetalClusterUpgradePolicy.PolicyEnum) => Option(fun)
		given putListSchemaBareMetalCluster: Conversion[List[Schema.BareMetalCluster], Option[List[Schema.BareMetalCluster]]] = (fun: List[Schema.BareMetalCluster]) => Option(fun)
		given putListSchemaBareMetalVersionInfo: Conversion[List[Schema.BareMetalVersionInfo], Option[List[Schema.BareMetalVersionInfo]]] = (fun: List[Schema.BareMetalVersionInfo]) => Option(fun)
		given putListSchemaUpgradeDependency: Conversion[List[Schema.UpgradeDependency], Option[List[Schema.UpgradeDependency]]] = (fun: List[Schema.UpgradeDependency]) => Option(fun)
		given putSchemaVmwareClusterStateEnum: Conversion[Schema.VmwareCluster.StateEnum, Option[Schema.VmwareCluster.StateEnum]] = (fun: Schema.VmwareCluster.StateEnum) => Option(fun)
		given putSchemaVmwareControlPlaneNodeConfig: Conversion[Schema.VmwareControlPlaneNodeConfig, Option[Schema.VmwareControlPlaneNodeConfig]] = (fun: Schema.VmwareControlPlaneNodeConfig) => Option(fun)
		given putSchemaVmwareAAGConfig: Conversion[Schema.VmwareAAGConfig, Option[Schema.VmwareAAGConfig]] = (fun: Schema.VmwareAAGConfig) => Option(fun)
		given putSchemaVmwareStorageConfig: Conversion[Schema.VmwareStorageConfig, Option[Schema.VmwareStorageConfig]] = (fun: Schema.VmwareStorageConfig) => Option(fun)
		given putSchemaVmwareNetworkConfig: Conversion[Schema.VmwareNetworkConfig, Option[Schema.VmwareNetworkConfig]] = (fun: Schema.VmwareNetworkConfig) => Option(fun)
		given putSchemaVmwareLoadBalancerConfig: Conversion[Schema.VmwareLoadBalancerConfig, Option[Schema.VmwareLoadBalancerConfig]] = (fun: Schema.VmwareLoadBalancerConfig) => Option(fun)
		given putSchemaVmwareVCenterConfig: Conversion[Schema.VmwareVCenterConfig, Option[Schema.VmwareVCenterConfig]] = (fun: Schema.VmwareVCenterConfig) => Option(fun)
		given putSchemaVmwareDataplaneV2Config: Conversion[Schema.VmwareDataplaneV2Config, Option[Schema.VmwareDataplaneV2Config]] = (fun: Schema.VmwareDataplaneV2Config) => Option(fun)
		given putSchemaVmwareAutoRepairConfig: Conversion[Schema.VmwareAutoRepairConfig, Option[Schema.VmwareAutoRepairConfig]] = (fun: Schema.VmwareAutoRepairConfig) => Option(fun)
		given putSchemaVmwareClusterUpgradePolicy: Conversion[Schema.VmwareClusterUpgradePolicy, Option[Schema.VmwareClusterUpgradePolicy]] = (fun: Schema.VmwareClusterUpgradePolicy) => Option(fun)
		given putSchemaVmwareAutoResizeConfig: Conversion[Schema.VmwareAutoResizeConfig, Option[Schema.VmwareAutoResizeConfig]] = (fun: Schema.VmwareAutoResizeConfig) => Option(fun)
		given putSchemaVmwareControlPlaneVsphereConfig: Conversion[Schema.VmwareControlPlaneVsphereConfig, Option[Schema.VmwareControlPlaneVsphereConfig]] = (fun: Schema.VmwareControlPlaneVsphereConfig) => Option(fun)
		given putSchemaVmwareStaticIpConfig: Conversion[Schema.VmwareStaticIpConfig, Option[Schema.VmwareStaticIpConfig]] = (fun: Schema.VmwareStaticIpConfig) => Option(fun)
		given putSchemaVmwareDhcpIpConfig: Conversion[Schema.VmwareDhcpIpConfig, Option[Schema.VmwareDhcpIpConfig]] = (fun: Schema.VmwareDhcpIpConfig) => Option(fun)
		given putSchemaVmwareHostConfig: Conversion[Schema.VmwareHostConfig, Option[Schema.VmwareHostConfig]] = (fun: Schema.VmwareHostConfig) => Option(fun)
		given putSchemaVmwareControlPlaneV2Config: Conversion[Schema.VmwareControlPlaneV2Config, Option[Schema.VmwareControlPlaneV2Config]] = (fun: Schema.VmwareControlPlaneV2Config) => Option(fun)
		given putListSchemaVmwareIpBlock: Conversion[List[Schema.VmwareIpBlock], Option[List[Schema.VmwareIpBlock]]] = (fun: List[Schema.VmwareIpBlock]) => Option(fun)
		given putListSchemaVmwareHostIp: Conversion[List[Schema.VmwareHostIp], Option[List[Schema.VmwareHostIp]]] = (fun: List[Schema.VmwareHostIp]) => Option(fun)
		given putSchemaVmwareIpBlock: Conversion[Schema.VmwareIpBlock, Option[Schema.VmwareIpBlock]] = (fun: Schema.VmwareIpBlock) => Option(fun)
		given putSchemaVmwareVipConfig: Conversion[Schema.VmwareVipConfig, Option[Schema.VmwareVipConfig]] = (fun: Schema.VmwareVipConfig) => Option(fun)
		given putSchemaVmwareF5BigIpConfig: Conversion[Schema.VmwareF5BigIpConfig, Option[Schema.VmwareF5BigIpConfig]] = (fun: Schema.VmwareF5BigIpConfig) => Option(fun)
		given putSchemaVmwareManualLbConfig: Conversion[Schema.VmwareManualLbConfig, Option[Schema.VmwareManualLbConfig]] = (fun: Schema.VmwareManualLbConfig) => Option(fun)
		given putSchemaVmwareSeesawConfig: Conversion[Schema.VmwareSeesawConfig, Option[Schema.VmwareSeesawConfig]] = (fun: Schema.VmwareSeesawConfig) => Option(fun)
		given putSchemaVmwareMetalLbConfig: Conversion[Schema.VmwareMetalLbConfig, Option[Schema.VmwareMetalLbConfig]] = (fun: Schema.VmwareMetalLbConfig) => Option(fun)
		given putListSchemaVmwareAddressPool: Conversion[List[Schema.VmwareAddressPool], Option[List[Schema.VmwareAddressPool]]] = (fun: List[Schema.VmwareAddressPool]) => Option(fun)
		given putListSchemaVmwareCluster: Conversion[List[Schema.VmwareCluster], Option[List[Schema.VmwareCluster]]] = (fun: List[Schema.VmwareCluster]) => Option(fun)
		given putSchemaBareMetalNodePoolStateEnum: Conversion[Schema.BareMetalNodePool.StateEnum, Option[Schema.BareMetalNodePool.StateEnum]] = (fun: Schema.BareMetalNodePool.StateEnum) => Option(fun)
		given putSchemaBareMetalNodePoolUpgradePolicy: Conversion[Schema.BareMetalNodePoolUpgradePolicy, Option[Schema.BareMetalNodePoolUpgradePolicy]] = (fun: Schema.BareMetalNodePoolUpgradePolicy) => Option(fun)
		given putSchemaBareMetalParallelUpgradeConfig: Conversion[Schema.BareMetalParallelUpgradeConfig, Option[Schema.BareMetalParallelUpgradeConfig]] = (fun: Schema.BareMetalParallelUpgradeConfig) => Option(fun)
		given putListSchemaBareMetalNodePool: Conversion[List[Schema.BareMetalNodePool], Option[List[Schema.BareMetalNodePool]]] = (fun: List[Schema.BareMetalNodePool]) => Option(fun)
		given putSchemaVmwareNodePoolStateEnum: Conversion[Schema.VmwareNodePool.StateEnum, Option[Schema.VmwareNodePool.StateEnum]] = (fun: Schema.VmwareNodePool.StateEnum) => Option(fun)
		given putSchemaVmwareNodePoolAutoscalingConfig: Conversion[Schema.VmwareNodePoolAutoscalingConfig, Option[Schema.VmwareNodePoolAutoscalingConfig]] = (fun: Schema.VmwareNodePoolAutoscalingConfig) => Option(fun)
		given putSchemaVmwareNodeConfig: Conversion[Schema.VmwareNodeConfig, Option[Schema.VmwareNodeConfig]] = (fun: Schema.VmwareNodeConfig) => Option(fun)
		given putSchemaVmwareVsphereConfig: Conversion[Schema.VmwareVsphereConfig, Option[Schema.VmwareVsphereConfig]] = (fun: Schema.VmwareVsphereConfig) => Option(fun)
		given putListSchemaVmwareVsphereTag: Conversion[List[Schema.VmwareVsphereTag], Option[List[Schema.VmwareVsphereTag]]] = (fun: List[Schema.VmwareVsphereTag]) => Option(fun)
		given putListSchemaVmwareNodePool: Conversion[List[Schema.VmwareNodePool], Option[List[Schema.VmwareNodePool]]] = (fun: List[Schema.VmwareNodePool]) => Option(fun)
		given putSchemaVmwareAdminClusterStateEnum: Conversion[Schema.VmwareAdminCluster.StateEnum, Option[Schema.VmwareAdminCluster.StateEnum]] = (fun: Schema.VmwareAdminCluster.StateEnum) => Option(fun)
		given putSchemaVmwareAdminVCenterConfig: Conversion[Schema.VmwareAdminVCenterConfig, Option[Schema.VmwareAdminVCenterConfig]] = (fun: Schema.VmwareAdminVCenterConfig) => Option(fun)
		given putSchemaVmwareAdminNetworkConfig: Conversion[Schema.VmwareAdminNetworkConfig, Option[Schema.VmwareAdminNetworkConfig]] = (fun: Schema.VmwareAdminNetworkConfig) => Option(fun)
		given putSchemaVmwareAdminLoadBalancerConfig: Conversion[Schema.VmwareAdminLoadBalancerConfig, Option[Schema.VmwareAdminLoadBalancerConfig]] = (fun: Schema.VmwareAdminLoadBalancerConfig) => Option(fun)
		given putSchemaVmwareAdminControlPlaneNodeConfig: Conversion[Schema.VmwareAdminControlPlaneNodeConfig, Option[Schema.VmwareAdminControlPlaneNodeConfig]] = (fun: Schema.VmwareAdminControlPlaneNodeConfig) => Option(fun)
		given putSchemaVmwareAdminAddonNodeConfig: Conversion[Schema.VmwareAdminAddonNodeConfig, Option[Schema.VmwareAdminAddonNodeConfig]] = (fun: Schema.VmwareAdminAddonNodeConfig) => Option(fun)
		given putSchemaVmwarePlatformConfig: Conversion[Schema.VmwarePlatformConfig, Option[Schema.VmwarePlatformConfig]] = (fun: Schema.VmwarePlatformConfig) => Option(fun)
		given putSchemaVmwareAdminPreparedSecretsConfig: Conversion[Schema.VmwareAdminPreparedSecretsConfig, Option[Schema.VmwareAdminPreparedSecretsConfig]] = (fun: Schema.VmwareAdminPreparedSecretsConfig) => Option(fun)
		given putSchemaVmwareAdminAuthorizationConfig: Conversion[Schema.VmwareAdminAuthorizationConfig, Option[Schema.VmwareAdminAuthorizationConfig]] = (fun: Schema.VmwareAdminAuthorizationConfig) => Option(fun)
		given putSchemaVmwareAdminHAControlPlaneConfig: Conversion[Schema.VmwareAdminHAControlPlaneConfig, Option[Schema.VmwareAdminHAControlPlaneConfig]] = (fun: Schema.VmwareAdminHAControlPlaneConfig) => Option(fun)
		given putSchemaVmwareAdminVipConfig: Conversion[Schema.VmwareAdminVipConfig, Option[Schema.VmwareAdminVipConfig]] = (fun: Schema.VmwareAdminVipConfig) => Option(fun)
		given putSchemaVmwareAdminF5BigIpConfig: Conversion[Schema.VmwareAdminF5BigIpConfig, Option[Schema.VmwareAdminF5BigIpConfig]] = (fun: Schema.VmwareAdminF5BigIpConfig) => Option(fun)
		given putSchemaVmwareAdminManualLbConfig: Conversion[Schema.VmwareAdminManualLbConfig, Option[Schema.VmwareAdminManualLbConfig]] = (fun: Schema.VmwareAdminManualLbConfig) => Option(fun)
		given putSchemaVmwareAdminMetalLbConfig: Conversion[Schema.VmwareAdminMetalLbConfig, Option[Schema.VmwareAdminMetalLbConfig]] = (fun: Schema.VmwareAdminMetalLbConfig) => Option(fun)
		given putSchemaVmwareAdminSeesawConfig: Conversion[Schema.VmwareAdminSeesawConfig, Option[Schema.VmwareAdminSeesawConfig]] = (fun: Schema.VmwareAdminSeesawConfig) => Option(fun)
		given putListSchemaVmwareBundleConfig: Conversion[List[Schema.VmwareBundleConfig], Option[List[Schema.VmwareBundleConfig]]] = (fun: List[Schema.VmwareBundleConfig]) => Option(fun)
		given putListSchemaVmwareAdminCluster: Conversion[List[Schema.VmwareAdminCluster], Option[List[Schema.VmwareAdminCluster]]] = (fun: List[Schema.VmwareAdminCluster]) => Option(fun)
		given putListSchemaVmwareVersionInfo: Conversion[List[Schema.VmwareVersionInfo], Option[List[Schema.VmwareVersionInfo]]] = (fun: List[Schema.VmwareVersionInfo]) => Option(fun)
		given putSchemaBareMetalAdminClusterStateEnum: Conversion[Schema.BareMetalAdminCluster.StateEnum, Option[Schema.BareMetalAdminCluster.StateEnum]] = (fun: Schema.BareMetalAdminCluster.StateEnum) => Option(fun)
		given putSchemaBareMetalAdminNetworkConfig: Conversion[Schema.BareMetalAdminNetworkConfig, Option[Schema.BareMetalAdminNetworkConfig]] = (fun: Schema.BareMetalAdminNetworkConfig) => Option(fun)
		given putSchemaBareMetalAdminControlPlaneConfig: Conversion[Schema.BareMetalAdminControlPlaneConfig, Option[Schema.BareMetalAdminControlPlaneConfig]] = (fun: Schema.BareMetalAdminControlPlaneConfig) => Option(fun)
		given putSchemaBareMetalAdminLoadBalancerConfig: Conversion[Schema.BareMetalAdminLoadBalancerConfig, Option[Schema.BareMetalAdminLoadBalancerConfig]] = (fun: Schema.BareMetalAdminLoadBalancerConfig) => Option(fun)
		given putSchemaBareMetalAdminStorageConfig: Conversion[Schema.BareMetalAdminStorageConfig, Option[Schema.BareMetalAdminStorageConfig]] = (fun: Schema.BareMetalAdminStorageConfig) => Option(fun)
		given putSchemaBareMetalAdminClusterOperationsConfig: Conversion[Schema.BareMetalAdminClusterOperationsConfig, Option[Schema.BareMetalAdminClusterOperationsConfig]] = (fun: Schema.BareMetalAdminClusterOperationsConfig) => Option(fun)
		given putSchemaBareMetalAdminMaintenanceConfig: Conversion[Schema.BareMetalAdminMaintenanceConfig, Option[Schema.BareMetalAdminMaintenanceConfig]] = (fun: Schema.BareMetalAdminMaintenanceConfig) => Option(fun)
		given putSchemaBareMetalAdminMaintenanceStatus: Conversion[Schema.BareMetalAdminMaintenanceStatus, Option[Schema.BareMetalAdminMaintenanceStatus]] = (fun: Schema.BareMetalAdminMaintenanceStatus) => Option(fun)
		given putSchemaBareMetalAdminWorkloadNodeConfig: Conversion[Schema.BareMetalAdminWorkloadNodeConfig, Option[Schema.BareMetalAdminWorkloadNodeConfig]] = (fun: Schema.BareMetalAdminWorkloadNodeConfig) => Option(fun)
		given putSchemaBareMetalAdminProxyConfig: Conversion[Schema.BareMetalAdminProxyConfig, Option[Schema.BareMetalAdminProxyConfig]] = (fun: Schema.BareMetalAdminProxyConfig) => Option(fun)
		given putSchemaBareMetalAdminSecurityConfig: Conversion[Schema.BareMetalAdminSecurityConfig, Option[Schema.BareMetalAdminSecurityConfig]] = (fun: Schema.BareMetalAdminSecurityConfig) => Option(fun)
		given putSchemaBareMetalAdminNodeAccessConfig: Conversion[Schema.BareMetalAdminNodeAccessConfig, Option[Schema.BareMetalAdminNodeAccessConfig]] = (fun: Schema.BareMetalAdminNodeAccessConfig) => Option(fun)
		given putSchemaBareMetalAdminOsEnvironmentConfig: Conversion[Schema.BareMetalAdminOsEnvironmentConfig, Option[Schema.BareMetalAdminOsEnvironmentConfig]] = (fun: Schema.BareMetalAdminOsEnvironmentConfig) => Option(fun)
		given putSchemaBareMetalAdminIslandModeCidrConfig: Conversion[Schema.BareMetalAdminIslandModeCidrConfig, Option[Schema.BareMetalAdminIslandModeCidrConfig]] = (fun: Schema.BareMetalAdminIslandModeCidrConfig) => Option(fun)
		given putSchemaBareMetalAdminControlPlaneNodePoolConfig: Conversion[Schema.BareMetalAdminControlPlaneNodePoolConfig, Option[Schema.BareMetalAdminControlPlaneNodePoolConfig]] = (fun: Schema.BareMetalAdminControlPlaneNodePoolConfig) => Option(fun)
		given putListSchemaBareMetalAdminApiServerArgument: Conversion[List[Schema.BareMetalAdminApiServerArgument], Option[List[Schema.BareMetalAdminApiServerArgument]]] = (fun: List[Schema.BareMetalAdminApiServerArgument]) => Option(fun)
		given putSchemaBareMetalAdminVipConfig: Conversion[Schema.BareMetalAdminVipConfig, Option[Schema.BareMetalAdminVipConfig]] = (fun: Schema.BareMetalAdminVipConfig) => Option(fun)
		given putSchemaBareMetalAdminPortConfig: Conversion[Schema.BareMetalAdminPortConfig, Option[Schema.BareMetalAdminPortConfig]] = (fun: Schema.BareMetalAdminPortConfig) => Option(fun)
		given putSchemaBareMetalAdminManualLbConfig: Conversion[Schema.BareMetalAdminManualLbConfig, Option[Schema.BareMetalAdminManualLbConfig]] = (fun: Schema.BareMetalAdminManualLbConfig) => Option(fun)
		given putSchemaBareMetalAdminMachineDrainStatus: Conversion[Schema.BareMetalAdminMachineDrainStatus, Option[Schema.BareMetalAdminMachineDrainStatus]] = (fun: Schema.BareMetalAdminMachineDrainStatus) => Option(fun)
		given putListSchemaBareMetalAdminDrainingMachine: Conversion[List[Schema.BareMetalAdminDrainingMachine], Option[List[Schema.BareMetalAdminDrainingMachine]]] = (fun: List[Schema.BareMetalAdminDrainingMachine]) => Option(fun)
		given putListSchemaBareMetalAdminDrainedMachine: Conversion[List[Schema.BareMetalAdminDrainedMachine], Option[List[Schema.BareMetalAdminDrainedMachine]]] = (fun: List[Schema.BareMetalAdminDrainedMachine]) => Option(fun)
		given putListSchemaBareMetalAdminCluster: Conversion[List[Schema.BareMetalAdminCluster], Option[List[Schema.BareMetalAdminCluster]]] = (fun: List[Schema.BareMetalAdminCluster]) => Option(fun)
		given putListSchemaLocation: Conversion[List[Schema.Location], Option[List[Schema.Location]]] = (fun: List[Schema.Location]) => Option(fun)
		given putSchemaPolicy: Conversion[Schema.Policy, Option[Schema.Policy]] = (fun: Schema.Policy) => Option(fun)
		given putListSchemaBinding: Conversion[List[Schema.Binding], Option[List[Schema.Binding]]] = (fun: List[Schema.Binding]) => Option(fun)
		given putSchemaExpr: Conversion[Schema.Expr, Option[Schema.Expr]] = (fun: Schema.Expr) => Option(fun)
		given putSchemaOperationMetadataTypeEnum: Conversion[Schema.OperationMetadata.TypeEnum, Option[Schema.OperationMetadata.TypeEnum]] = (fun: Schema.OperationMetadata.TypeEnum) => Option(fun)
		given putSchemaOperationProgress: Conversion[Schema.OperationProgress, Option[Schema.OperationProgress]] = (fun: Schema.OperationProgress) => Option(fun)
		given putListSchemaOperationStage: Conversion[List[Schema.OperationStage], Option[List[Schema.OperationStage]]] = (fun: List[Schema.OperationStage]) => Option(fun)
		given putSchemaOperationStageStageEnum: Conversion[Schema.OperationStage.StageEnum, Option[Schema.OperationStage.StageEnum]] = (fun: Schema.OperationStage.StageEnum) => Option(fun)
		given putListSchemaMetric: Conversion[List[Schema.Metric], Option[List[Schema.Metric]]] = (fun: List[Schema.Metric]) => Option(fun)
		given putSchemaOperationStageStateEnum: Conversion[Schema.OperationStage.StateEnum, Option[Schema.OperationStage.StateEnum]] = (fun: Schema.OperationStage.StateEnum) => Option(fun)
		given putSchemaMetricMetricEnum: Conversion[Schema.Metric.MetricEnum, Option[Schema.Metric.MetricEnum]] = (fun: Schema.Metric.MetricEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
