package com.boresjo.play.api.google.cloudresourcemanager

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListLiensResponse: Format[Schema.ListLiensResponse] = Json.format[Schema.ListLiensResponse]
	given fmtLien: Format[Schema.Lien] = Json.format[Schema.Lien]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtFolder: Format[Schema.Folder] = Json.format[Schema.Folder]
	given fmtFolderStateEnum: Format[Schema.Folder.StateEnum] = JsonEnumFormat[Schema.Folder.StateEnum]
	given fmtListFoldersResponse: Format[Schema.ListFoldersResponse] = Json.format[Schema.ListFoldersResponse]
	given fmtSearchFoldersResponse: Format[Schema.SearchFoldersResponse] = Json.format[Schema.SearchFoldersResponse]
	given fmtMoveFolderRequest: Format[Schema.MoveFolderRequest] = Json.format[Schema.MoveFolderRequest]
	given fmtUndeleteFolderRequest: Format[Schema.UndeleteFolderRequest] = Json.format[Schema.UndeleteFolderRequest]
	given fmtGetIamPolicyRequest: Format[Schema.GetIamPolicyRequest] = Json.format[Schema.GetIamPolicyRequest]
	given fmtGetPolicyOptions: Format[Schema.GetPolicyOptions] = Json.format[Schema.GetPolicyOptions]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtOrganization: Format[Schema.Organization] = Json.format[Schema.Organization]
	given fmtOrganizationStateEnum: Format[Schema.Organization.StateEnum] = JsonEnumFormat[Schema.Organization.StateEnum]
	given fmtSearchOrganizationsResponse: Format[Schema.SearchOrganizationsResponse] = Json.format[Schema.SearchOrganizationsResponse]
	given fmtProject: Format[Schema.Project] = Json.format[Schema.Project]
	given fmtProjectStateEnum: Format[Schema.Project.StateEnum] = JsonEnumFormat[Schema.Project.StateEnum]
	given fmtListProjectsResponse: Format[Schema.ListProjectsResponse] = Json.format[Schema.ListProjectsResponse]
	given fmtSearchProjectsResponse: Format[Schema.SearchProjectsResponse] = Json.format[Schema.SearchProjectsResponse]
	given fmtMoveProjectRequest: Format[Schema.MoveProjectRequest] = Json.format[Schema.MoveProjectRequest]
	given fmtUndeleteProjectRequest: Format[Schema.UndeleteProjectRequest] = Json.format[Schema.UndeleteProjectRequest]
	given fmtListTagBindingsResponse: Format[Schema.ListTagBindingsResponse] = Json.format[Schema.ListTagBindingsResponse]
	given fmtTagBinding: Format[Schema.TagBinding] = Json.format[Schema.TagBinding]
	given fmtListEffectiveTagsResponse: Format[Schema.ListEffectiveTagsResponse] = Json.format[Schema.ListEffectiveTagsResponse]
	given fmtEffectiveTag: Format[Schema.EffectiveTag] = Json.format[Schema.EffectiveTag]
	given fmtTagHold: Format[Schema.TagHold] = Json.format[Schema.TagHold]
	given fmtListTagHoldsResponse: Format[Schema.ListTagHoldsResponse] = Json.format[Schema.ListTagHoldsResponse]
	given fmtListTagKeysResponse: Format[Schema.ListTagKeysResponse] = Json.format[Schema.ListTagKeysResponse]
	given fmtTagKey: Format[Schema.TagKey] = Json.format[Schema.TagKey]
	given fmtTagKeyPurposeEnum: Format[Schema.TagKey.PurposeEnum] = JsonEnumFormat[Schema.TagKey.PurposeEnum]
	given fmtListTagValuesResponse: Format[Schema.ListTagValuesResponse] = Json.format[Schema.ListTagValuesResponse]
	given fmtTagValue: Format[Schema.TagValue] = Json.format[Schema.TagValue]
	given fmtProjectCreationStatus: Format[Schema.ProjectCreationStatus] = Json.format[Schema.ProjectCreationStatus]
	given fmtCloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperation: Format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperation] = Json.format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperation]
	given fmtCloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperationOperationTypeEnum: Format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperation.OperationTypeEnum] = JsonEnumFormat[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2alpha1FolderOperation.OperationTypeEnum]
	given fmtFolderOperationError: Format[Schema.FolderOperationError] = Json.format[Schema.FolderOperationError]
	given fmtFolderOperationErrorErrorMessageIdEnum: Format[Schema.FolderOperationError.ErrorMessageIdEnum] = JsonEnumFormat[Schema.FolderOperationError.ErrorMessageIdEnum]
	given fmtCloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperation: Format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperation] = Json.format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperation]
	given fmtCloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperationOperationTypeEnum: Format[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperation.OperationTypeEnum] = JsonEnumFormat[Schema.CloudresourcemanagerGoogleCloudResourcemanagerV2beta1FolderOperation.OperationTypeEnum]
	given fmtFolderOperation: Format[Schema.FolderOperation] = Json.format[Schema.FolderOperation]
	given fmtFolderOperationOperationTypeEnum: Format[Schema.FolderOperation.OperationTypeEnum] = JsonEnumFormat[Schema.FolderOperation.OperationTypeEnum]
	given fmtDeleteOrganizationMetadata: Format[Schema.DeleteOrganizationMetadata] = Json.format[Schema.DeleteOrganizationMetadata]
	given fmtUndeleteOrganizationMetadata: Format[Schema.UndeleteOrganizationMetadata] = Json.format[Schema.UndeleteOrganizationMetadata]
	given fmtCreateFolderMetadata: Format[Schema.CreateFolderMetadata] = Json.format[Schema.CreateFolderMetadata]
	given fmtUpdateFolderMetadata: Format[Schema.UpdateFolderMetadata] = Json.format[Schema.UpdateFolderMetadata]
	given fmtMoveFolderMetadata: Format[Schema.MoveFolderMetadata] = Json.format[Schema.MoveFolderMetadata]
	given fmtDeleteFolderMetadata: Format[Schema.DeleteFolderMetadata] = Json.format[Schema.DeleteFolderMetadata]
	given fmtUndeleteFolderMetadata: Format[Schema.UndeleteFolderMetadata] = Json.format[Schema.UndeleteFolderMetadata]
	given fmtCreateProjectMetadata: Format[Schema.CreateProjectMetadata] = Json.format[Schema.CreateProjectMetadata]
	given fmtUpdateProjectMetadata: Format[Schema.UpdateProjectMetadata] = Json.format[Schema.UpdateProjectMetadata]
	given fmtMoveProjectMetadata: Format[Schema.MoveProjectMetadata] = Json.format[Schema.MoveProjectMetadata]
	given fmtDeleteProjectMetadata: Format[Schema.DeleteProjectMetadata] = Json.format[Schema.DeleteProjectMetadata]
	given fmtUndeleteProjectMetadata: Format[Schema.UndeleteProjectMetadata] = Json.format[Schema.UndeleteProjectMetadata]
	given fmtCreateTagKeyMetadata: Format[Schema.CreateTagKeyMetadata] = Json.format[Schema.CreateTagKeyMetadata]
	given fmtUpdateTagKeyMetadata: Format[Schema.UpdateTagKeyMetadata] = Json.format[Schema.UpdateTagKeyMetadata]
	given fmtDeleteTagKeyMetadata: Format[Schema.DeleteTagKeyMetadata] = Json.format[Schema.DeleteTagKeyMetadata]
	given fmtCreateTagValueMetadata: Format[Schema.CreateTagValueMetadata] = Json.format[Schema.CreateTagValueMetadata]
	given fmtUpdateTagValueMetadata: Format[Schema.UpdateTagValueMetadata] = Json.format[Schema.UpdateTagValueMetadata]
	given fmtDeleteTagValueMetadata: Format[Schema.DeleteTagValueMetadata] = Json.format[Schema.DeleteTagValueMetadata]
	given fmtCreateTagBindingMetadata: Format[Schema.CreateTagBindingMetadata] = Json.format[Schema.CreateTagBindingMetadata]
	given fmtDeleteTagBindingMetadata: Format[Schema.DeleteTagBindingMetadata] = Json.format[Schema.DeleteTagBindingMetadata]
}
