package com.boresjo.play.api.google.networkmanagement

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtListConnectivityTestsResponse: Format[Schema.ListConnectivityTestsResponse] = Json.format[Schema.ListConnectivityTestsResponse]
	given fmtConnectivityTest: Format[Schema.ConnectivityTest] = Json.format[Schema.ConnectivityTest]
	given fmtEndpoint: Format[Schema.Endpoint] = Json.format[Schema.Endpoint]
	given fmtReachabilityDetails: Format[Schema.ReachabilityDetails] = Json.format[Schema.ReachabilityDetails]
	given fmtProbingDetails: Format[Schema.ProbingDetails] = Json.format[Schema.ProbingDetails]
	given fmtEndpointForwardingRuleTargetEnum: Format[Schema.Endpoint.ForwardingRuleTargetEnum] = JsonEnumFormat[Schema.Endpoint.ForwardingRuleTargetEnum]
	given fmtEndpointLoadBalancerTypeEnum: Format[Schema.Endpoint.LoadBalancerTypeEnum] = JsonEnumFormat[Schema.Endpoint.LoadBalancerTypeEnum]
	given fmtCloudFunctionEndpoint: Format[Schema.CloudFunctionEndpoint] = Json.format[Schema.CloudFunctionEndpoint]
	given fmtAppEngineVersionEndpoint: Format[Schema.AppEngineVersionEndpoint] = Json.format[Schema.AppEngineVersionEndpoint]
	given fmtCloudRunRevisionEndpoint: Format[Schema.CloudRunRevisionEndpoint] = Json.format[Schema.CloudRunRevisionEndpoint]
	given fmtEndpointNetworkTypeEnum: Format[Schema.Endpoint.NetworkTypeEnum] = JsonEnumFormat[Schema.Endpoint.NetworkTypeEnum]
	given fmtReachabilityDetailsResultEnum: Format[Schema.ReachabilityDetails.ResultEnum] = JsonEnumFormat[Schema.ReachabilityDetails.ResultEnum]
	given fmtTrace: Format[Schema.Trace] = Json.format[Schema.Trace]
	given fmtEndpointInfo: Format[Schema.EndpointInfo] = Json.format[Schema.EndpointInfo]
	given fmtStep: Format[Schema.Step] = Json.format[Schema.Step]
	given fmtStepStateEnum: Format[Schema.Step.StateEnum] = JsonEnumFormat[Schema.Step.StateEnum]
	given fmtInstanceInfo: Format[Schema.InstanceInfo] = Json.format[Schema.InstanceInfo]
	given fmtFirewallInfo: Format[Schema.FirewallInfo] = Json.format[Schema.FirewallInfo]
	given fmtRouteInfo: Format[Schema.RouteInfo] = Json.format[Schema.RouteInfo]
	given fmtGoogleServiceInfo: Format[Schema.GoogleServiceInfo] = Json.format[Schema.GoogleServiceInfo]
	given fmtForwardingRuleInfo: Format[Schema.ForwardingRuleInfo] = Json.format[Schema.ForwardingRuleInfo]
	given fmtVpnGatewayInfo: Format[Schema.VpnGatewayInfo] = Json.format[Schema.VpnGatewayInfo]
	given fmtVpnTunnelInfo: Format[Schema.VpnTunnelInfo] = Json.format[Schema.VpnTunnelInfo]
	given fmtVpcConnectorInfo: Format[Schema.VpcConnectorInfo] = Json.format[Schema.VpcConnectorInfo]
	given fmtDeliverInfo: Format[Schema.DeliverInfo] = Json.format[Schema.DeliverInfo]
	given fmtForwardInfo: Format[Schema.ForwardInfo] = Json.format[Schema.ForwardInfo]
	given fmtAbortInfo: Format[Schema.AbortInfo] = Json.format[Schema.AbortInfo]
	given fmtDropInfo: Format[Schema.DropInfo] = Json.format[Schema.DropInfo]
	given fmtLoadBalancerInfo: Format[Schema.LoadBalancerInfo] = Json.format[Schema.LoadBalancerInfo]
	given fmtNetworkInfo: Format[Schema.NetworkInfo] = Json.format[Schema.NetworkInfo]
	given fmtGKEMasterInfo: Format[Schema.GKEMasterInfo] = Json.format[Schema.GKEMasterInfo]
	given fmtCloudSQLInstanceInfo: Format[Schema.CloudSQLInstanceInfo] = Json.format[Schema.CloudSQLInstanceInfo]
	given fmtRedisInstanceInfo: Format[Schema.RedisInstanceInfo] = Json.format[Schema.RedisInstanceInfo]
	given fmtRedisClusterInfo: Format[Schema.RedisClusterInfo] = Json.format[Schema.RedisClusterInfo]
	given fmtCloudFunctionInfo: Format[Schema.CloudFunctionInfo] = Json.format[Schema.CloudFunctionInfo]
	given fmtAppEngineVersionInfo: Format[Schema.AppEngineVersionInfo] = Json.format[Schema.AppEngineVersionInfo]
	given fmtCloudRunRevisionInfo: Format[Schema.CloudRunRevisionInfo] = Json.format[Schema.CloudRunRevisionInfo]
	given fmtNatInfo: Format[Schema.NatInfo] = Json.format[Schema.NatInfo]
	given fmtProxyConnectionInfo: Format[Schema.ProxyConnectionInfo] = Json.format[Schema.ProxyConnectionInfo]
	given fmtLoadBalancerBackendInfo: Format[Schema.LoadBalancerBackendInfo] = Json.format[Schema.LoadBalancerBackendInfo]
	given fmtStorageBucketInfo: Format[Schema.StorageBucketInfo] = Json.format[Schema.StorageBucketInfo]
	given fmtServerlessNegInfo: Format[Schema.ServerlessNegInfo] = Json.format[Schema.ServerlessNegInfo]
	given fmtFirewallInfoFirewallRuleTypeEnum: Format[Schema.FirewallInfo.FirewallRuleTypeEnum] = JsonEnumFormat[Schema.FirewallInfo.FirewallRuleTypeEnum]
	given fmtRouteInfoRouteTypeEnum: Format[Schema.RouteInfo.RouteTypeEnum] = JsonEnumFormat[Schema.RouteInfo.RouteTypeEnum]
	given fmtRouteInfoNextHopTypeEnum: Format[Schema.RouteInfo.NextHopTypeEnum] = JsonEnumFormat[Schema.RouteInfo.NextHopTypeEnum]
	given fmtRouteInfoRouteScopeEnum: Format[Schema.RouteInfo.RouteScopeEnum] = JsonEnumFormat[Schema.RouteInfo.RouteScopeEnum]
	given fmtGoogleServiceInfoGoogleServiceTypeEnum: Format[Schema.GoogleServiceInfo.GoogleServiceTypeEnum] = JsonEnumFormat[Schema.GoogleServiceInfo.GoogleServiceTypeEnum]
	given fmtVpnTunnelInfoRoutingTypeEnum: Format[Schema.VpnTunnelInfo.RoutingTypeEnum] = JsonEnumFormat[Schema.VpnTunnelInfo.RoutingTypeEnum]
	given fmtDeliverInfoTargetEnum: Format[Schema.DeliverInfo.TargetEnum] = JsonEnumFormat[Schema.DeliverInfo.TargetEnum]
	given fmtForwardInfoTargetEnum: Format[Schema.ForwardInfo.TargetEnum] = JsonEnumFormat[Schema.ForwardInfo.TargetEnum]
	given fmtAbortInfoCauseEnum: Format[Schema.AbortInfo.CauseEnum] = JsonEnumFormat[Schema.AbortInfo.CauseEnum]
	given fmtDropInfoCauseEnum: Format[Schema.DropInfo.CauseEnum] = JsonEnumFormat[Schema.DropInfo.CauseEnum]
	given fmtLoadBalancerInfoLoadBalancerTypeEnum: Format[Schema.LoadBalancerInfo.LoadBalancerTypeEnum] = JsonEnumFormat[Schema.LoadBalancerInfo.LoadBalancerTypeEnum]
	given fmtLoadBalancerBackend: Format[Schema.LoadBalancerBackend] = Json.format[Schema.LoadBalancerBackend]
	given fmtLoadBalancerInfoBackendTypeEnum: Format[Schema.LoadBalancerInfo.BackendTypeEnum] = JsonEnumFormat[Schema.LoadBalancerInfo.BackendTypeEnum]
	given fmtLoadBalancerBackendHealthCheckFirewallStateEnum: Format[Schema.LoadBalancerBackend.HealthCheckFirewallStateEnum] = JsonEnumFormat[Schema.LoadBalancerBackend.HealthCheckFirewallStateEnum]
	given fmtNatInfoTypeEnum: Format[Schema.NatInfo.TypeEnum] = JsonEnumFormat[Schema.NatInfo.TypeEnum]
	given fmtLoadBalancerBackendInfoHealthCheckFirewallsConfigStateEnum: Format[Schema.LoadBalancerBackendInfo.HealthCheckFirewallsConfigStateEnum] = JsonEnumFormat[Schema.LoadBalancerBackendInfo.HealthCheckFirewallsConfigStateEnum]
	given fmtProbingDetailsResultEnum: Format[Schema.ProbingDetails.ResultEnum] = JsonEnumFormat[Schema.ProbingDetails.ResultEnum]
	given fmtProbingDetailsAbortCauseEnum: Format[Schema.ProbingDetails.AbortCauseEnum] = JsonEnumFormat[Schema.ProbingDetails.AbortCauseEnum]
	given fmtLatencyDistribution: Format[Schema.LatencyDistribution] = Json.format[Schema.LatencyDistribution]
	given fmtEdgeLocation: Format[Schema.EdgeLocation] = Json.format[Schema.EdgeLocation]
	given fmtLatencyPercentile: Format[Schema.LatencyPercentile] = Json.format[Schema.LatencyPercentile]
	given fmtRerunConnectivityTestRequest: Format[Schema.RerunConnectivityTestRequest] = Json.format[Schema.RerunConnectivityTestRequest]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
