package com.boresjo.play.api.google.youtubeAnalytics

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Schema {
	case class ListGroupItemsResponse(
	  /** Identifies the API resource's type. The value will be `youtube#groupItemListResponse`. */
		kind: Option[String] = None,
	  /** A list of groups that match the API request parameters. Each item in the list represents a `groupItem` resource. */
		items: Option[List[Schema.GroupItem]] = None,
	  /** The Etag of this resource. */
		etag: Option[String] = None,
	  /** Apiary error details */
		errors: Option[Schema.Errors] = None
	)
	
	case class GroupItemResource(
	  /** The channel, video, playlist, or asset ID that YouTube uses to uniquely identify the item that is being added to the group. */
		id: Option[String] = None,
	  /** Identifies the type of resource being added to the group. Valid values for this property are: &#42; `youtube#channel` &#42; `youtube#playlist` &#42; `youtube#video` &#42; `youtubePartner#asset` */
		kind: Option[String] = None
	)
	
	case class GroupSnippet(
	  /** The group name. The value must be a non-empty string. */
		title: Option[String] = None,
	  /** The date and time that the group was created. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format. */
		publishedAt: Option[String] = None
	)
	
	case class EmptyResponse(
	  /** Apiary error details */
		errors: Option[Schema.Errors] = None
	)
	
	case class ResultTableColumnHeader(
	  /** The type of the column (`DIMENSION` or `METRIC`). */
		columnType: Option[String] = None,
	  /** The type of the data in the column (`STRING`, `INTEGER`, `FLOAT`, etc.). */
		dataType: Option[String] = None,
	  /** The name of the dimension or metric. */
		name: Option[String] = None
	)
	
	object Errors {
		enum CodeEnum extends Enum[CodeEnum] { case BAD_REQUEST, FORBIDDEN, NOT_FOUND, CONFLICT, GONE, PRECONDITION_FAILED, INTERNAL_ERROR, SERVICE_UNAVAILABLE }
	}
	case class Errors(
	  /** Request identifier generated by the service, which can be used to identify the error in the logs */
		requestId: Option[String] = None,
	  /** Specific error description and codes */
		error: Option[List[Schema.ErrorProto]] = None,
	  /** Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead. */
		code: Option[Schema.Errors.CodeEnum] = None
	)
	
	case class QueryResponse(
	  /** The list contains all rows of the result table. Each item in the list is an array that contains comma-delimited data corresponding to a single row of data. The order of the comma-delimited data fields will match the order of the columns listed in the `columnHeaders` field. If no data is available for the given query, the `rows` element will be omitted from the response. The response for a query with the `day` dimension will not contain rows for the most recent days. */
		rows: Option[List[List[JsValue]]] = None,
	  /** This value specifies the type of data included in the API response. For the query method, the kind property value will be `youtubeAnalytics#resultTable`. */
		kind: Option[String] = None,
	  /** When set, indicates that the operation failed. */
		errors: Option[Schema.Errors] = None,
	  /** This value specifies information about the data returned in the `rows` fields. Each item in the `columnHeaders` list identifies a field returned in the `rows` value, which contains a list of comma-delimited data. The `columnHeaders` list will begin with the dimensions specified in the API request, which will be followed by the metrics specified in the API request. The order of both dimensions and metrics will match the ordering in the API request. For example, if the API request contains the parameters `dimensions=ageGroup,gender&metrics=viewerPercentage`, the API response will return columns in this order: `ageGroup`, `gender`, `viewerPercentage`. */
		columnHeaders: Option[List[Schema.ResultTableColumnHeader]] = None
	)
	
	case class GroupItem(
	  /** Identifies the API resource's type. The value will be `youtube#groupItem`. */
		kind: Option[String] = None,
	  /** The Etag of this resource. */
		etag: Option[String] = None,
	  /** The `resource` object contains information that identifies the item being added to the group. */
		resource: Option[Schema.GroupItemResource] = None,
	  /** Apiary error details */
		errors: Option[Schema.Errors] = None,
	  /** The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is included in the group. Note that this ID refers specifically to the inclusion of that resource in a particular group and is different than the channel ID, video ID, playlist ID, or asset ID that uniquely identifies the resource itself. The `resource.id` property's value specifies the unique channel, video, playlist, or asset ID. */
		id: Option[String] = None,
	  /** The ID that YouTube uses to uniquely identify the group that contains the item. */
		groupId: Option[String] = None
	)
	
	case class Group(
	  /** The ID that YouTube uses to uniquely identify the group. */
		id: Option[String] = None,
	  /** The Etag of this resource. */
		etag: Option[String] = None,
	  /** The `contentDetails` object contains additional information about the group, such as the number and type of items that it contains. */
		contentDetails: Option[Schema.GroupContentDetails] = None,
	  /** Identifies the API resource's type. The value will be `youtube#group`. */
		kind: Option[String] = None,
	  /** The `snippet` object contains basic information about the group, including its creation date and name. */
		snippet: Option[Schema.GroupSnippet] = None,
	  /** Apiary error details */
		errors: Option[Schema.Errors] = None
	)
	
	case class GroupContentDetails(
	  /** The number of items in the group. */
		itemCount: Option[String] = None,
	  /** The type of resources that the group contains. Valid values for this property are: &#42; `youtube#channel` &#42; `youtube#playlist` &#42; `youtube#video` &#42; `youtubePartner#asset` */
		itemType: Option[String] = None
	)
	
	object ErrorProto {
		enum LocationTypeEnum extends Enum[LocationTypeEnum] { case PATH, OTHER, PARAMETER }
	}
	case class ErrorProto(
		locationType: Option[Schema.ErrorProto.LocationTypeEnum] = None,
	  /** A short explanation for the error, which can be shared outside Google. Please set domain, code and arguments whenever possible instead of this error message so that external APIs can build safe error messages themselves. External messages built in a RoSy interface will most likely refer to information and concepts that are not available externally and should not be exposed. It is safer if external APIs can understand the errors and decide what the error message should look like. */
		externalErrorMessage: Option[String] = None,
	  /** Error arguments, to be used when building user-friendly error messages given the error domain and code. Different error codes require different arguments. */
		argument: Option[List[String]] = None,
	  /** Debugging information, which should not be shared externally. */
		debugInfo: Option[String] = None,
	  /** Error code in the error domain. This should correspond to a value of the enum type whose name is in domain. See the core error domain in error_domain.proto. */
		code: Option[String] = None,
	  /** Location of the error, as specified by the location type. If location_type is PATH, this should be a path to a field that's relative to the request, using FieldPath notation (net/proto2/util/public/field_path.h). Examples: authenticated_user.gaia_id resource.address[2].country */
		location: Option[String] = None,
	  /** Error domain. RoSy services can define their own domain and error codes. This should normally be the name of an enum type, such as: gdata.CoreErrorDomain */
		domain: Option[String] = None
	)
	
	case class ListGroupsResponse(
	  /** Apiary error details */
		errors: Option[Schema.Errors] = None,
	  /** The Etag of this resource. */
		etag: Option[String] = None,
	  /** The token that can be used as the value of the `pageToken` parameter to retrieve the next page in the result set. */
		nextPageToken: Option[String] = None,
	  /** A list of groups that match the API request parameters. Each item in the list represents a `group` resource. */
		items: Option[List[Schema.Group]] = None,
	  /** Identifies the API resource's type. The value will be `youtube#groupListResponse`. */
		kind: Option[String] = None
	)
}
