package com.boresjo.play.api.google.ml

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putSchemaGoogleCloudMlV1TrainingInput: Conversion[Schema.GoogleCloudMlV1__TrainingInput, Option[Schema.GoogleCloudMlV1__TrainingInput]] = (fun: Schema.GoogleCloudMlV1__TrainingInput) => Option(fun)
		given putSchemaGoogleCloudMlV1PredictionInput: Conversion[Schema.GoogleCloudMlV1__PredictionInput, Option[Schema.GoogleCloudMlV1__PredictionInput]] = (fun: Schema.GoogleCloudMlV1__PredictionInput) => Option(fun)
		given putSchemaGoogleCloudMlV1JobStateEnum: Conversion[Schema.GoogleCloudMlV1__Job.StateEnum, Option[Schema.GoogleCloudMlV1__Job.StateEnum]] = (fun: Schema.GoogleCloudMlV1__Job.StateEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1TrainingOutput: Conversion[Schema.GoogleCloudMlV1__TrainingOutput, Option[Schema.GoogleCloudMlV1__TrainingOutput]] = (fun: Schema.GoogleCloudMlV1__TrainingOutput) => Option(fun)
		given putSchemaGoogleCloudMlV1PredictionOutput: Conversion[Schema.GoogleCloudMlV1__PredictionOutput, Option[Schema.GoogleCloudMlV1__PredictionOutput]] = (fun: Schema.GoogleCloudMlV1__PredictionOutput) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putSchemaGoogleCloudMlV1TrainingInputScaleTierEnum: Conversion[Schema.GoogleCloudMlV1__TrainingInput.ScaleTierEnum, Option[Schema.GoogleCloudMlV1__TrainingInput.ScaleTierEnum]] = (fun: Schema.GoogleCloudMlV1__TrainingInput.ScaleTierEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1ReplicaConfig: Conversion[Schema.GoogleCloudMlV1__ReplicaConfig, Option[Schema.GoogleCloudMlV1__ReplicaConfig]] = (fun: Schema.GoogleCloudMlV1__ReplicaConfig) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaGoogleCloudMlV1HyperparameterSpec: Conversion[Schema.GoogleCloudMlV1__HyperparameterSpec, Option[Schema.GoogleCloudMlV1__HyperparameterSpec]] = (fun: Schema.GoogleCloudMlV1__HyperparameterSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1EncryptionConfig: Conversion[Schema.GoogleCloudMlV1__EncryptionConfig, Option[Schema.GoogleCloudMlV1__EncryptionConfig]] = (fun: Schema.GoogleCloudMlV1__EncryptionConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1Scheduling: Conversion[Schema.GoogleCloudMlV1__Scheduling, Option[Schema.GoogleCloudMlV1__Scheduling]] = (fun: Schema.GoogleCloudMlV1__Scheduling) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaGoogleCloudMlV1AcceleratorConfig: Conversion[Schema.GoogleCloudMlV1__AcceleratorConfig, Option[Schema.GoogleCloudMlV1__AcceleratorConfig]] = (fun: Schema.GoogleCloudMlV1__AcceleratorConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1DiskConfig: Conversion[Schema.GoogleCloudMlV1__DiskConfig, Option[Schema.GoogleCloudMlV1__DiskConfig]] = (fun: Schema.GoogleCloudMlV1__DiskConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1AcceleratorConfigTypeEnum: Conversion[Schema.GoogleCloudMlV1__AcceleratorConfig.TypeEnum, Option[Schema.GoogleCloudMlV1__AcceleratorConfig.TypeEnum]] = (fun: Schema.GoogleCloudMlV1__AcceleratorConfig.TypeEnum) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putSchemaGoogleCloudMlV1HyperparameterSpecGoalEnum: Conversion[Schema.GoogleCloudMlV1__HyperparameterSpec.GoalEnum, Option[Schema.GoogleCloudMlV1__HyperparameterSpec.GoalEnum]] = (fun: Schema.GoogleCloudMlV1__HyperparameterSpec.GoalEnum) => Option(fun)
		given putListSchemaGoogleCloudMlV1ParameterSpec: Conversion[List[Schema.GoogleCloudMlV1__ParameterSpec], Option[List[Schema.GoogleCloudMlV1__ParameterSpec]]] = (fun: List[Schema.GoogleCloudMlV1__ParameterSpec]) => Option(fun)
		given putSchemaGoogleCloudMlV1HyperparameterSpecAlgorithmEnum: Conversion[Schema.GoogleCloudMlV1__HyperparameterSpec.AlgorithmEnum, Option[Schema.GoogleCloudMlV1__HyperparameterSpec.AlgorithmEnum]] = (fun: Schema.GoogleCloudMlV1__HyperparameterSpec.AlgorithmEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1ParameterSpecTypeEnum: Conversion[Schema.GoogleCloudMlV1__ParameterSpec.TypeEnum, Option[Schema.GoogleCloudMlV1__ParameterSpec.TypeEnum]] = (fun: Schema.GoogleCloudMlV1__ParameterSpec.TypeEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putListBigDecimal: Conversion[List[BigDecimal], Option[List[BigDecimal]]] = (fun: List[BigDecimal]) => Option(fun)
		given putSchemaGoogleCloudMlV1ParameterSpecScaleTypeEnum: Conversion[Schema.GoogleCloudMlV1__ParameterSpec.ScaleTypeEnum, Option[Schema.GoogleCloudMlV1__ParameterSpec.ScaleTypeEnum]] = (fun: Schema.GoogleCloudMlV1__ParameterSpec.ScaleTypeEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1PredictionInputDataFormatEnum: Conversion[Schema.GoogleCloudMlV1__PredictionInput.DataFormatEnum, Option[Schema.GoogleCloudMlV1__PredictionInput.DataFormatEnum]] = (fun: Schema.GoogleCloudMlV1__PredictionInput.DataFormatEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1PredictionInputOutputDataFormatEnum: Conversion[Schema.GoogleCloudMlV1__PredictionInput.OutputDataFormatEnum, Option[Schema.GoogleCloudMlV1__PredictionInput.OutputDataFormatEnum]] = (fun: Schema.GoogleCloudMlV1__PredictionInput.OutputDataFormatEnum) => Option(fun)
		given putListSchemaGoogleCloudMlV1HyperparameterOutput: Conversion[List[Schema.GoogleCloudMlV1__HyperparameterOutput], Option[List[Schema.GoogleCloudMlV1__HyperparameterOutput]]] = (fun: List[Schema.GoogleCloudMlV1__HyperparameterOutput]) => Option(fun)
		given putSchemaGoogleCloudMlV1BuiltInAlgorithmOutput: Conversion[Schema.GoogleCloudMlV1__BuiltInAlgorithmOutput, Option[Schema.GoogleCloudMlV1__BuiltInAlgorithmOutput]] = (fun: Schema.GoogleCloudMlV1__BuiltInAlgorithmOutput) => Option(fun)
		given putSchemaGoogleCloudMlV1HyperparameterOutputStateEnum: Conversion[Schema.GoogleCloudMlV1__HyperparameterOutput.StateEnum, Option[Schema.GoogleCloudMlV1__HyperparameterOutput.StateEnum]] = (fun: Schema.GoogleCloudMlV1__HyperparameterOutput.StateEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1HyperparameterOutputHyperparameterMetric: Conversion[Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric, Option[Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric]] = (fun: Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric) => Option(fun)
		given putListSchemaGoogleCloudMlV1HyperparameterOutputHyperparameterMetric: Conversion[List[Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric], Option[List[Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric]]] = (fun: List[Schema.GoogleCloudMlV1_HyperparameterOutput_HyperparameterMetric]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Job: Conversion[List[Schema.GoogleCloudMlV1__Job], Option[List[Schema.GoogleCloudMlV1__Job]]] = (fun: List[Schema.GoogleCloudMlV1__Job]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Capability: Conversion[List[Schema.GoogleCloudMlV1__Capability], Option[List[Schema.GoogleCloudMlV1__Capability]]] = (fun: List[Schema.GoogleCloudMlV1__Capability]) => Option(fun)
		given putSchemaGoogleCloudMlV1CapabilityTypeEnum: Conversion[Schema.GoogleCloudMlV1__Capability.TypeEnum, Option[Schema.GoogleCloudMlV1__Capability.TypeEnum]] = (fun: Schema.GoogleCloudMlV1__Capability.TypeEnum) => Option(fun)
		given putListSchemaGoogleCloudMlV1CapabilityAvailableAcceleratorsEnum: Conversion[List[Schema.GoogleCloudMlV1__Capability.AvailableAcceleratorsEnum], Option[List[Schema.GoogleCloudMlV1__Capability.AvailableAcceleratorsEnum]]] = (fun: List[Schema.GoogleCloudMlV1__Capability.AvailableAcceleratorsEnum]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Location: Conversion[List[Schema.GoogleCloudMlV1__Location], Option[List[Schema.GoogleCloudMlV1__Location]]] = (fun: List[Schema.GoogleCloudMlV1__Location]) => Option(fun)
		given putListSchemaGoogleLongrunningOperation: Conversion[List[Schema.GoogleLongrunning__Operation], Option[List[Schema.GoogleLongrunning__Operation]]] = (fun: List[Schema.GoogleLongrunning__Operation]) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putSchemaGoogleRpcStatus: Conversion[Schema.GoogleRpc__Status, Option[Schema.GoogleRpc__Status]] = (fun: Schema.GoogleRpc__Status) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaGoogleCloudMlV1Version: Conversion[Schema.GoogleCloudMlV1__Version, Option[Schema.GoogleCloudMlV1__Version]] = (fun: Schema.GoogleCloudMlV1__Version) => Option(fun)
		given putSchemaGoogleCloudMlV1AutoScaling: Conversion[Schema.GoogleCloudMlV1__AutoScaling, Option[Schema.GoogleCloudMlV1__AutoScaling]] = (fun: Schema.GoogleCloudMlV1__AutoScaling) => Option(fun)
		given putSchemaGoogleCloudMlV1ManualScaling: Conversion[Schema.GoogleCloudMlV1__ManualScaling, Option[Schema.GoogleCloudMlV1__ManualScaling]] = (fun: Schema.GoogleCloudMlV1__ManualScaling) => Option(fun)
		given putSchemaGoogleCloudMlV1VersionStateEnum: Conversion[Schema.GoogleCloudMlV1__Version.StateEnum, Option[Schema.GoogleCloudMlV1__Version.StateEnum]] = (fun: Schema.GoogleCloudMlV1__Version.StateEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1VersionFrameworkEnum: Conversion[Schema.GoogleCloudMlV1__Version.FrameworkEnum, Option[Schema.GoogleCloudMlV1__Version.FrameworkEnum]] = (fun: Schema.GoogleCloudMlV1__Version.FrameworkEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1RequestLoggingConfig: Conversion[Schema.GoogleCloudMlV1__RequestLoggingConfig, Option[Schema.GoogleCloudMlV1__RequestLoggingConfig]] = (fun: Schema.GoogleCloudMlV1__RequestLoggingConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1ExplanationConfig: Conversion[Schema.GoogleCloudMlV1__ExplanationConfig, Option[Schema.GoogleCloudMlV1__ExplanationConfig]] = (fun: Schema.GoogleCloudMlV1__ExplanationConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1ContainerSpec: Conversion[Schema.GoogleCloudMlV1__ContainerSpec, Option[Schema.GoogleCloudMlV1__ContainerSpec]] = (fun: Schema.GoogleCloudMlV1__ContainerSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1RouteMap: Conversion[Schema.GoogleCloudMlV1__RouteMap, Option[Schema.GoogleCloudMlV1__RouteMap]] = (fun: Schema.GoogleCloudMlV1__RouteMap) => Option(fun)
		given putListSchemaGoogleCloudMlV1MetricSpec: Conversion[List[Schema.GoogleCloudMlV1__MetricSpec], Option[List[Schema.GoogleCloudMlV1__MetricSpec]]] = (fun: List[Schema.GoogleCloudMlV1__MetricSpec]) => Option(fun)
		given putSchemaGoogleCloudMlV1MetricSpecNameEnum: Conversion[Schema.GoogleCloudMlV1__MetricSpec.NameEnum, Option[Schema.GoogleCloudMlV1__MetricSpec.NameEnum]] = (fun: Schema.GoogleCloudMlV1__MetricSpec.NameEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1IntegratedGradientsAttribution: Conversion[Schema.GoogleCloudMlV1__IntegratedGradientsAttribution, Option[Schema.GoogleCloudMlV1__IntegratedGradientsAttribution]] = (fun: Schema.GoogleCloudMlV1__IntegratedGradientsAttribution) => Option(fun)
		given putSchemaGoogleCloudMlV1SampledShapleyAttribution: Conversion[Schema.GoogleCloudMlV1__SampledShapleyAttribution, Option[Schema.GoogleCloudMlV1__SampledShapleyAttribution]] = (fun: Schema.GoogleCloudMlV1__SampledShapleyAttribution) => Option(fun)
		given putSchemaGoogleCloudMlV1XraiAttribution: Conversion[Schema.GoogleCloudMlV1__XraiAttribution, Option[Schema.GoogleCloudMlV1__XraiAttribution]] = (fun: Schema.GoogleCloudMlV1__XraiAttribution) => Option(fun)
		given putListSchemaGoogleCloudMlV1ContainerPort: Conversion[List[Schema.GoogleCloudMlV1__ContainerPort], Option[List[Schema.GoogleCloudMlV1__ContainerPort]]] = (fun: List[Schema.GoogleCloudMlV1__ContainerPort]) => Option(fun)
		given putListSchemaGoogleCloudMlV1EnvVar: Conversion[List[Schema.GoogleCloudMlV1__EnvVar], Option[List[Schema.GoogleCloudMlV1__EnvVar]]] = (fun: List[Schema.GoogleCloudMlV1__EnvVar]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Model: Conversion[List[Schema.GoogleCloudMlV1__Model], Option[List[Schema.GoogleCloudMlV1__Model]]] = (fun: List[Schema.GoogleCloudMlV1__Model]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Version: Conversion[List[Schema.GoogleCloudMlV1__Version], Option[List[Schema.GoogleCloudMlV1__Version]]] = (fun: List[Schema.GoogleCloudMlV1__Version]) => Option(fun)
		given putSchemaGoogleApiHttpBody: Conversion[Schema.GoogleApi__HttpBody, Option[Schema.GoogleApi__HttpBody]] = (fun: Schema.GoogleApi__HttpBody) => Option(fun)
		given putSchemaGoogleCloudMlV1Config: Conversion[Schema.GoogleCloudMlV1__Config, Option[Schema.GoogleCloudMlV1__Config]] = (fun: Schema.GoogleCloudMlV1__Config) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfig: Conversion[Schema.GoogleCloudMlV1__StudyConfig, Option[Schema.GoogleCloudMlV1__StudyConfig]] = (fun: Schema.GoogleCloudMlV1__StudyConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyStateEnum: Conversion[Schema.GoogleCloudMlV1__Study.StateEnum, Option[Schema.GoogleCloudMlV1__Study.StateEnum]] = (fun: Schema.GoogleCloudMlV1__Study.StateEnum) => Option(fun)
		given putListSchemaGoogleCloudMlV1StudyConfigMetricSpec: Conversion[List[Schema.GoogleCloudMlV1_StudyConfig_MetricSpec], Option[List[Schema.GoogleCloudMlV1_StudyConfig_MetricSpec]]] = (fun: List[Schema.GoogleCloudMlV1_StudyConfig_MetricSpec]) => Option(fun)
		given putListSchemaGoogleCloudMlV1StudyConfigParameterSpec: Conversion[List[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec], Option[List[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec]]] = (fun: List[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec]) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigAlgorithmEnum: Conversion[Schema.GoogleCloudMlV1__StudyConfig.AlgorithmEnum, Option[Schema.GoogleCloudMlV1__StudyConfig.AlgorithmEnum]] = (fun: Schema.GoogleCloudMlV1__StudyConfig.AlgorithmEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1AutomatedStoppingConfig: Conversion[Schema.GoogleCloudMlV1__AutomatedStoppingConfig, Option[Schema.GoogleCloudMlV1__AutomatedStoppingConfig]] = (fun: Schema.GoogleCloudMlV1__AutomatedStoppingConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigMetricSpecGoalEnum: Conversion[Schema.GoogleCloudMlV1_StudyConfig_MetricSpec.GoalEnum, Option[Schema.GoogleCloudMlV1_StudyConfig_MetricSpec.GoalEnum]] = (fun: Schema.GoogleCloudMlV1_StudyConfig_MetricSpec.GoalEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecTypeEnum: Conversion[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.TypeEnum, Option[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.TypeEnum]] = (fun: Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.TypeEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecDoubleValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DoubleValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecIntegerValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_IntegerValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecCategoricalValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_CategoricalValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecDiscreteValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_DiscreteValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecScaleTypeEnum: Conversion[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.ScaleTypeEnum, Option[Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.ScaleTypeEnum]] = (fun: Schema.GoogleCloudMlV1_StudyConfig_ParameterSpec.ScaleTypeEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecMatchingParentDiscreteValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentDiscreteValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecMatchingParentIntValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentIntValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1StudyConfigParameterSpecMatchingParentCategoricalValueSpec: Conversion[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpec, Option[Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpec]] = (fun: Schema.GoogleCloudMlV1_StudyConfigParameterSpec_MatchingParentCategoricalValueSpec) => Option(fun)
		given putSchemaGoogleCloudMlV1AutomatedStoppingConfigDecayCurveAutomatedStoppingConfig: Conversion[Schema.GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfig, Option[Schema.GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfig]] = (fun: Schema.GoogleCloudMlV1_AutomatedStoppingConfig_DecayCurveAutomatedStoppingConfig) => Option(fun)
		given putSchemaGoogleCloudMlV1AutomatedStoppingConfigMedianAutomatedStoppingConfig: Conversion[Schema.GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfig, Option[Schema.GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfig]] = (fun: Schema.GoogleCloudMlV1_AutomatedStoppingConfig_MedianAutomatedStoppingConfig) => Option(fun)
		given putListSchemaGoogleCloudMlV1Study: Conversion[List[Schema.GoogleCloudMlV1__Study], Option[List[Schema.GoogleCloudMlV1__Study]]] = (fun: List[Schema.GoogleCloudMlV1__Study]) => Option(fun)
		given putSchemaGoogleCloudMlV1TrialStateEnum: Conversion[Schema.GoogleCloudMlV1__Trial.StateEnum, Option[Schema.GoogleCloudMlV1__Trial.StateEnum]] = (fun: Schema.GoogleCloudMlV1__Trial.StateEnum) => Option(fun)
		given putListSchemaGoogleCloudMlV1TrialParameter: Conversion[List[Schema.GoogleCloudMlV1_Trial_Parameter], Option[List[Schema.GoogleCloudMlV1_Trial_Parameter]]] = (fun: List[Schema.GoogleCloudMlV1_Trial_Parameter]) => Option(fun)
		given putSchemaGoogleCloudMlV1Measurement: Conversion[Schema.GoogleCloudMlV1__Measurement, Option[Schema.GoogleCloudMlV1__Measurement]] = (fun: Schema.GoogleCloudMlV1__Measurement) => Option(fun)
		given putListSchemaGoogleCloudMlV1Measurement: Conversion[List[Schema.GoogleCloudMlV1__Measurement], Option[List[Schema.GoogleCloudMlV1__Measurement]]] = (fun: List[Schema.GoogleCloudMlV1__Measurement]) => Option(fun)
		given putListSchemaGoogleCloudMlV1MeasurementMetric: Conversion[List[Schema.GoogleCloudMlV1_Measurement_Metric], Option[List[Schema.GoogleCloudMlV1_Measurement_Metric]]] = (fun: List[Schema.GoogleCloudMlV1_Measurement_Metric]) => Option(fun)
		given putListSchemaGoogleCloudMlV1Trial: Conversion[List[Schema.GoogleCloudMlV1__Trial], Option[List[Schema.GoogleCloudMlV1__Trial]]] = (fun: List[Schema.GoogleCloudMlV1__Trial]) => Option(fun)
		given putSchemaGoogleIamV1Policy: Conversion[Schema.GoogleIamV1__Policy, Option[Schema.GoogleIamV1__Policy]] = (fun: Schema.GoogleIamV1__Policy) => Option(fun)
		given putListSchemaGoogleIamV1Binding: Conversion[List[Schema.GoogleIamV1__Binding], Option[List[Schema.GoogleIamV1__Binding]]] = (fun: List[Schema.GoogleIamV1__Binding]) => Option(fun)
		given putListSchemaGoogleIamV1AuditConfig: Conversion[List[Schema.GoogleIamV1__AuditConfig], Option[List[Schema.GoogleIamV1__AuditConfig]]] = (fun: List[Schema.GoogleIamV1__AuditConfig]) => Option(fun)
		given putSchemaGoogleTypeExpr: Conversion[Schema.GoogleType__Expr, Option[Schema.GoogleType__Expr]] = (fun: Schema.GoogleType__Expr) => Option(fun)
		given putListSchemaGoogleIamV1AuditLogConfig: Conversion[List[Schema.GoogleIamV1__AuditLogConfig], Option[List[Schema.GoogleIamV1__AuditLogConfig]]] = (fun: List[Schema.GoogleIamV1__AuditLogConfig]) => Option(fun)
		given putSchemaGoogleIamV1AuditLogConfigLogTypeEnum: Conversion[Schema.GoogleIamV1__AuditLogConfig.LogTypeEnum, Option[Schema.GoogleIamV1__AuditLogConfig.LogTypeEnum]] = (fun: Schema.GoogleIamV1__AuditLogConfig.LogTypeEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1OperationMetadataOperationTypeEnum: Conversion[Schema.GoogleCloudMlV1__OperationMetadata.OperationTypeEnum, Option[Schema.GoogleCloudMlV1__OperationMetadata.OperationTypeEnum]] = (fun: Schema.GoogleCloudMlV1__OperationMetadata.OperationTypeEnum) => Option(fun)
		given putSchemaGoogleCloudMlV1SuggestTrialsResponseStudyStateEnum: Conversion[Schema.GoogleCloudMlV1__SuggestTrialsResponse.StudyStateEnum, Option[Schema.GoogleCloudMlV1__SuggestTrialsResponse.StudyStateEnum]] = (fun: Schema.GoogleCloudMlV1__SuggestTrialsResponse.StudyStateEnum) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
