package com.boresjo.play.api.google.alertcenter

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListAlertsResponse: Format[Schema.ListAlertsResponse] = Json.format[Schema.ListAlertsResponse]
	given fmtAlert: Format[Schema.Alert] = Json.format[Schema.Alert]
	given fmtAlertMetadata: Format[Schema.AlertMetadata] = Json.format[Schema.AlertMetadata]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtUndeleteAlertRequest: Format[Schema.UndeleteAlertRequest] = Json.format[Schema.UndeleteAlertRequest]
	given fmtAlertFeedback: Format[Schema.AlertFeedback] = Json.format[Schema.AlertFeedback]
	given fmtAlertFeedbackTypeEnum: Format[Schema.AlertFeedback.TypeEnum] = JsonEnumFormat[Schema.AlertFeedback.TypeEnum]
	given fmtListAlertFeedbackResponse: Format[Schema.ListAlertFeedbackResponse] = Json.format[Schema.ListAlertFeedbackResponse]
	given fmtSettings: Format[Schema.Settings] = Json.format[Schema.Settings]
	given fmtNotification: Format[Schema.Notification] = Json.format[Schema.Notification]
	given fmtCloudPubsubTopic: Format[Schema.CloudPubsubTopic] = Json.format[Schema.CloudPubsubTopic]
	given fmtCloudPubsubTopicPayloadFormatEnum: Format[Schema.CloudPubsubTopic.PayloadFormatEnum] = JsonEnumFormat[Schema.CloudPubsubTopic.PayloadFormatEnum]
	given fmtBatchDeleteAlertsRequest: Format[Schema.BatchDeleteAlertsRequest] = Json.format[Schema.BatchDeleteAlertsRequest]
	given fmtBatchDeleteAlertsResponse: Format[Schema.BatchDeleteAlertsResponse] = Json.format[Schema.BatchDeleteAlertsResponse]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtBatchUndeleteAlertsRequest: Format[Schema.BatchUndeleteAlertsRequest] = Json.format[Schema.BatchUndeleteAlertsRequest]
	given fmtBatchUndeleteAlertsResponse: Format[Schema.BatchUndeleteAlertsResponse] = Json.format[Schema.BatchUndeleteAlertsResponse]
	given fmtBadWhitelist: Format[Schema.BadWhitelist] = Json.format[Schema.BadWhitelist]
	given fmtDomainId: Format[Schema.DomainId] = Json.format[Schema.DomainId]
	given fmtMaliciousEntity: Format[Schema.MaliciousEntity] = Json.format[Schema.MaliciousEntity]
	given fmtGmailMessageInfo: Format[Schema.GmailMessageInfo] = Json.format[Schema.GmailMessageInfo]
	given fmtUser: Format[Schema.User] = Json.format[Schema.User]
	given fmtDeviceCompromised: Format[Schema.DeviceCompromised] = Json.format[Schema.DeviceCompromised]
	given fmtDeviceCompromisedSecurityDetail: Format[Schema.DeviceCompromisedSecurityDetail] = Json.format[Schema.DeviceCompromisedSecurityDetail]
	given fmtGoogleOperations: Format[Schema.GoogleOperations] = Json.format[Schema.GoogleOperations]
	given fmtAttachment: Format[Schema.Attachment] = Json.format[Schema.Attachment]
	given fmtCsv: Format[Schema.Csv] = Json.format[Schema.Csv]
	given fmtCsvRow: Format[Schema.CsvRow] = Json.format[Schema.CsvRow]
	given fmtMailPhishing: Format[Schema.MailPhishing] = Json.format[Schema.MailPhishing]
	given fmtMailPhishingSystemActionTypeEnum: Format[Schema.MailPhishing.SystemActionTypeEnum] = JsonEnumFormat[Schema.MailPhishing.SystemActionTypeEnum]
	given fmtPhishingSpike: Format[Schema.PhishingSpike] = Json.format[Schema.PhishingSpike]
	given fmtSuspiciousActivity: Format[Schema.SuspiciousActivity] = Json.format[Schema.SuspiciousActivity]
	given fmtSuspiciousActivitySecurityDetail: Format[Schema.SuspiciousActivitySecurityDetail] = Json.format[Schema.SuspiciousActivitySecurityDetail]
	given fmtDomainWideTakeoutInitiated: Format[Schema.DomainWideTakeoutInitiated] = Json.format[Schema.DomainWideTakeoutInitiated]
	given fmtStateSponsoredAttack: Format[Schema.StateSponsoredAttack] = Json.format[Schema.StateSponsoredAttack]
	given fmtAccountWarning: Format[Schema.AccountWarning] = Json.format[Schema.AccountWarning]
	given fmtLoginDetails: Format[Schema.LoginDetails] = Json.format[Schema.LoginDetails]
	given fmtAppMakerSqlSetupNotification: Format[Schema.AppMakerSqlSetupNotification] = Json.format[Schema.AppMakerSqlSetupNotification]
	given fmtRequestInfo: Format[Schema.RequestInfo] = Json.format[Schema.RequestInfo]
	given fmtActivityRule: Format[Schema.ActivityRule] = Json.format[Schema.ActivityRule]
	given fmtReportingRule: Format[Schema.ReportingRule] = Json.format[Schema.ReportingRule]
	given fmtAppSettingsChanged: Format[Schema.AppSettingsChanged] = Json.format[Schema.AppSettingsChanged]
	given fmtUserChanges: Format[Schema.UserChanges] = Json.format[Schema.UserChanges]
	given fmtDlpRuleViolation: Format[Schema.DlpRuleViolation] = Json.format[Schema.DlpRuleViolation]
	given fmtRuleViolationInfo: Format[Schema.RuleViolationInfo] = Json.format[Schema.RuleViolationInfo]
	given fmtRuleInfo: Format[Schema.RuleInfo] = Json.format[Schema.RuleInfo]
	given fmtRuleViolationInfoDataSourceEnum: Format[Schema.RuleViolationInfo.DataSourceEnum] = JsonEnumFormat[Schema.RuleViolationInfo.DataSourceEnum]
	given fmtRuleViolationInfoTriggerEnum: Format[Schema.RuleViolationInfo.TriggerEnum] = JsonEnumFormat[Schema.RuleViolationInfo.TriggerEnum]
	given fmtResourceInfo: Format[Schema.ResourceInfo] = Json.format[Schema.ResourceInfo]
	given fmtMatchInfo: Format[Schema.MatchInfo] = Json.format[Schema.MatchInfo]
	given fmtRuleViolationInfoTriggeredActionTypesEnum: Format[Schema.RuleViolationInfo.TriggeredActionTypesEnum] = JsonEnumFormat[Schema.RuleViolationInfo.TriggeredActionTypesEnum]
	given fmtActionInfo: Format[Schema.ActionInfo] = Json.format[Schema.ActionInfo]
	given fmtRuleViolationInfoSuppressedActionTypesEnum: Format[Schema.RuleViolationInfo.SuppressedActionTypesEnum] = JsonEnumFormat[Schema.RuleViolationInfo.SuppressedActionTypesEnum]
	given fmtRuleViolationInfoEventTypeEnum: Format[Schema.RuleViolationInfo.EventTypeEnum] = JsonEnumFormat[Schema.RuleViolationInfo.EventTypeEnum]
	given fmtUserDefinedDetectorInfo: Format[Schema.UserDefinedDetectorInfo] = Json.format[Schema.UserDefinedDetectorInfo]
	given fmtPredefinedDetectorInfo: Format[Schema.PredefinedDetectorInfo] = Json.format[Schema.PredefinedDetectorInfo]
	given fmtVoiceMisconfiguration: Format[Schema.VoiceMisconfiguration] = Json.format[Schema.VoiceMisconfiguration]
	given fmtVoiceMisconfigurationEntityTypeEnum: Format[Schema.VoiceMisconfiguration.EntityTypeEnum] = JsonEnumFormat[Schema.VoiceMisconfiguration.EntityTypeEnum]
	given fmtVoicemailMisconfiguration: Format[Schema.VoicemailMisconfiguration] = Json.format[Schema.VoicemailMisconfiguration]
	given fmtTransferMisconfiguration: Format[Schema.TransferMisconfiguration] = Json.format[Schema.TransferMisconfiguration]
	given fmtVoicemailRecipientError: Format[Schema.VoicemailRecipientError] = Json.format[Schema.VoicemailRecipientError]
	given fmtVoicemailRecipientErrorInvalidReasonEnum: Format[Schema.VoicemailRecipientError.InvalidReasonEnum] = JsonEnumFormat[Schema.VoicemailRecipientError.InvalidReasonEnum]
	given fmtTransferError: Format[Schema.TransferError] = Json.format[Schema.TransferError]
	given fmtTransferErrorEntityTypeEnum: Format[Schema.TransferError.EntityTypeEnum] = JsonEnumFormat[Schema.TransferError.EntityTypeEnum]
	given fmtTransferErrorInvalidReasonEnum: Format[Schema.TransferError.InvalidReasonEnum] = JsonEnumFormat[Schema.TransferError.InvalidReasonEnum]
	given fmtAccountSuspensionWarning: Format[Schema.AccountSuspensionWarning] = Json.format[Schema.AccountSuspensionWarning]
	given fmtAccountSuspensionWarningStateEnum: Format[Schema.AccountSuspensionWarning.StateEnum] = JsonEnumFormat[Schema.AccountSuspensionWarning.StateEnum]
	given fmtAccountSuspensionDetails: Format[Schema.AccountSuspensionDetails] = Json.format[Schema.AccountSuspensionDetails]
	given fmtAccountSuspensionDetailsAbuseReasonEnum: Format[Schema.AccountSuspensionDetails.AbuseReasonEnum] = JsonEnumFormat[Schema.AccountSuspensionDetails.AbuseReasonEnum]
	given fmtAppsOutage: Format[Schema.AppsOutage] = Json.format[Schema.AppsOutage]
	given fmtAppsOutageStatusEnum: Format[Schema.AppsOutage.StatusEnum] = JsonEnumFormat[Schema.AppsOutage.StatusEnum]
	given fmtMergeInfo: Format[Schema.MergeInfo] = Json.format[Schema.MergeInfo]
	given fmtAccessApproval: Format[Schema.AccessApproval] = Json.format[Schema.AccessApproval]
	given fmtSupportTicket: Format[Schema.SupportTicket] = Json.format[Schema.SupportTicket]
	given fmtAccessApprovalJustificationReasonEnum: Format[Schema.AccessApproval.JustificationReasonEnum] = JsonEnumFormat[Schema.AccessApproval.JustificationReasonEnum]
	given fmtMandatoryServiceAnnouncement: Format[Schema.MandatoryServiceAnnouncement] = Json.format[Schema.MandatoryServiceAnnouncement]
	given fmtSensitiveAdminAction: Format[Schema.SensitiveAdminAction] = Json.format[Schema.SensitiveAdminAction]
	given fmtPrimaryAdminChangedEvent: Format[Schema.PrimaryAdminChangedEvent] = Json.format[Schema.PrimaryAdminChangedEvent]
	given fmtSSOProfileCreatedEvent: Format[Schema.SSOProfileCreatedEvent] = Json.format[Schema.SSOProfileCreatedEvent]
	given fmtSSOProfileUpdatedEvent: Format[Schema.SSOProfileUpdatedEvent] = Json.format[Schema.SSOProfileUpdatedEvent]
	given fmtSSOProfileDeletedEvent: Format[Schema.SSOProfileDeletedEvent] = Json.format[Schema.SSOProfileDeletedEvent]
	given fmtSuperAdminPasswordResetEvent: Format[Schema.SuperAdminPasswordResetEvent] = Json.format[Schema.SuperAdminPasswordResetEvent]
	given fmtApnsCertificateExpirationInfo: Format[Schema.ApnsCertificateExpirationInfo] = Json.format[Schema.ApnsCertificateExpirationInfo]
	given fmtAbuseDetected: Format[Schema.AbuseDetected] = Json.format[Schema.AbuseDetected]
	given fmtEntityList: Format[Schema.EntityList] = Json.format[Schema.EntityList]
	given fmtAbuseDetectedVariationTypeEnum: Format[Schema.AbuseDetected.VariationTypeEnum] = JsonEnumFormat[Schema.AbuseDetected.VariationTypeEnum]
	given fmtEntity: Format[Schema.Entity] = Json.format[Schema.Entity]
	given fmtDeviceManagementRule: Format[Schema.DeviceManagementRule] = Json.format[Schema.DeviceManagementRule]
}
