package com.boresjo.play.api.google.baremetalsolution

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListInstancesResponse: Format[Schema.ListInstancesResponse] = Json.format[Schema.ListInstancesResponse]
	given fmtInstance: Format[Schema.Instance] = Json.format[Schema.Instance]
	given fmtInstanceStateEnum: Format[Schema.Instance.StateEnum] = JsonEnumFormat[Schema.Instance.StateEnum]
	given fmtLun: Format[Schema.Lun] = Json.format[Schema.Lun]
	given fmtVolume: Format[Schema.Volume] = Json.format[Schema.Volume]
	given fmtNetwork: Format[Schema.Network] = Json.format[Schema.Network]
	given fmtGoogleCloudBaremetalsolutionV2LogicalInterface: Format[Schema.GoogleCloudBaremetalsolutionV2LogicalInterface] = Json.format[Schema.GoogleCloudBaremetalsolutionV2LogicalInterface]
	given fmtInstanceWorkloadProfileEnum: Format[Schema.Instance.WorkloadProfileEnum] = JsonEnumFormat[Schema.Instance.WorkloadProfileEnum]
	given fmtLunStateEnum: Format[Schema.Lun.StateEnum] = JsonEnumFormat[Schema.Lun.StateEnum]
	given fmtLunMultiprotocolTypeEnum: Format[Schema.Lun.MultiprotocolTypeEnum] = JsonEnumFormat[Schema.Lun.MultiprotocolTypeEnum]
	given fmtLunStorageTypeEnum: Format[Schema.Lun.StorageTypeEnum] = JsonEnumFormat[Schema.Lun.StorageTypeEnum]
	given fmtVolumeStorageTypeEnum: Format[Schema.Volume.StorageTypeEnum] = JsonEnumFormat[Schema.Volume.StorageTypeEnum]
	given fmtVolumeStateEnum: Format[Schema.Volume.StateEnum] = JsonEnumFormat[Schema.Volume.StateEnum]
	given fmtSnapshotReservationDetail: Format[Schema.SnapshotReservationDetail] = Json.format[Schema.SnapshotReservationDetail]
	given fmtVolumeSnapshotAutoDeleteBehaviorEnum: Format[Schema.Volume.SnapshotAutoDeleteBehaviorEnum] = JsonEnumFormat[Schema.Volume.SnapshotAutoDeleteBehaviorEnum]
	given fmtVolumeProtocolEnum: Format[Schema.Volume.ProtocolEnum] = JsonEnumFormat[Schema.Volume.ProtocolEnum]
	given fmtVolumePerformanceTierEnum: Format[Schema.Volume.PerformanceTierEnum] = JsonEnumFormat[Schema.Volume.PerformanceTierEnum]
	given fmtVolumeWorkloadProfileEnum: Format[Schema.Volume.WorkloadProfileEnum] = JsonEnumFormat[Schema.Volume.WorkloadProfileEnum]
	given fmtNetworkTypeEnum: Format[Schema.Network.TypeEnum] = JsonEnumFormat[Schema.Network.TypeEnum]
	given fmtNetworkStateEnum: Format[Schema.Network.StateEnum] = JsonEnumFormat[Schema.Network.StateEnum]
	given fmtVRF: Format[Schema.VRF] = Json.format[Schema.VRF]
	given fmtNetworkAddressReservation: Format[Schema.NetworkAddressReservation] = Json.format[Schema.NetworkAddressReservation]
	given fmtNetworkMountPoint: Format[Schema.NetworkMountPoint] = Json.format[Schema.NetworkMountPoint]
	given fmtVRFStateEnum: Format[Schema.VRF.StateEnum] = JsonEnumFormat[Schema.VRF.StateEnum]
	given fmtQosPolicy: Format[Schema.QosPolicy] = Json.format[Schema.QosPolicy]
	given fmtVlanAttachment: Format[Schema.VlanAttachment] = Json.format[Schema.VlanAttachment]
	given fmtLogicalNetworkInterface: Format[Schema.LogicalNetworkInterface] = Json.format[Schema.LogicalNetworkInterface]
	given fmtLogicalNetworkInterfaceNetworkTypeEnum: Format[Schema.LogicalNetworkInterface.NetworkTypeEnum] = JsonEnumFormat[Schema.LogicalNetworkInterface.NetworkTypeEnum]
	given fmtLoadInstanceAuthInfoResponse: Format[Schema.LoadInstanceAuthInfoResponse] = Json.format[Schema.LoadInstanceAuthInfoResponse]
	given fmtUserAccount: Format[Schema.UserAccount] = Json.format[Schema.UserAccount]
	given fmtSSHKey: Format[Schema.SSHKey] = Json.format[Schema.SSHKey]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtReimageInstanceRequest: Format[Schema.ReimageInstanceRequest] = Json.format[Schema.ReimageInstanceRequest]
	given fmtEnableHyperthreadingRequest: Format[Schema.EnableHyperthreadingRequest] = Json.format[Schema.EnableHyperthreadingRequest]
	given fmtDisableHyperthreadingRequest: Format[Schema.DisableHyperthreadingRequest] = Json.format[Schema.DisableHyperthreadingRequest]
	given fmtRenameInstanceRequest: Format[Schema.RenameInstanceRequest] = Json.format[Schema.RenameInstanceRequest]
	given fmtResetInstanceRequest: Format[Schema.ResetInstanceRequest] = Json.format[Schema.ResetInstanceRequest]
	given fmtStartInstanceRequest: Format[Schema.StartInstanceRequest] = Json.format[Schema.StartInstanceRequest]
	given fmtStopInstanceRequest: Format[Schema.StopInstanceRequest] = Json.format[Schema.StopInstanceRequest]
	given fmtEnableInteractiveSerialConsoleRequest: Format[Schema.EnableInteractiveSerialConsoleRequest] = Json.format[Schema.EnableInteractiveSerialConsoleRequest]
	given fmtDisableInteractiveSerialConsoleRequest: Format[Schema.DisableInteractiveSerialConsoleRequest] = Json.format[Schema.DisableInteractiveSerialConsoleRequest]
	given fmtDetachLunRequest: Format[Schema.DetachLunRequest] = Json.format[Schema.DetachLunRequest]
	given fmtListSSHKeysResponse: Format[Schema.ListSSHKeysResponse] = Json.format[Schema.ListSSHKeysResponse]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtListVolumesResponse: Format[Schema.ListVolumesResponse] = Json.format[Schema.ListVolumesResponse]
	given fmtRenameVolumeRequest: Format[Schema.RenameVolumeRequest] = Json.format[Schema.RenameVolumeRequest]
	given fmtEvictVolumeRequest: Format[Schema.EvictVolumeRequest] = Json.format[Schema.EvictVolumeRequest]
	given fmtResizeVolumeRequest: Format[Schema.ResizeVolumeRequest] = Json.format[Schema.ResizeVolumeRequest]
	given fmtListNetworksResponse: Format[Schema.ListNetworksResponse] = Json.format[Schema.ListNetworksResponse]
	given fmtListNetworkUsageResponse: Format[Schema.ListNetworkUsageResponse] = Json.format[Schema.ListNetworkUsageResponse]
	given fmtNetworkUsage: Format[Schema.NetworkUsage] = Json.format[Schema.NetworkUsage]
	given fmtVolumeSnapshot: Format[Schema.VolumeSnapshot] = Json.format[Schema.VolumeSnapshot]
	given fmtVolumeSnapshotTypeEnum: Format[Schema.VolumeSnapshot.TypeEnum] = JsonEnumFormat[Schema.VolumeSnapshot.TypeEnum]
	given fmtRestoreVolumeSnapshotRequest: Format[Schema.RestoreVolumeSnapshotRequest] = Json.format[Schema.RestoreVolumeSnapshotRequest]
	given fmtListVolumeSnapshotsResponse: Format[Schema.ListVolumeSnapshotsResponse] = Json.format[Schema.ListVolumeSnapshotsResponse]
	given fmtListLunsResponse: Format[Schema.ListLunsResponse] = Json.format[Schema.ListLunsResponse]
	given fmtEvictLunRequest: Format[Schema.EvictLunRequest] = Json.format[Schema.EvictLunRequest]
	given fmtNfsShare: Format[Schema.NfsShare] = Json.format[Schema.NfsShare]
	given fmtNfsShareStateEnum: Format[Schema.NfsShare.StateEnum] = JsonEnumFormat[Schema.NfsShare.StateEnum]
	given fmtAllowedClient: Format[Schema.AllowedClient] = Json.format[Schema.AllowedClient]
	given fmtNfsShareStorageTypeEnum: Format[Schema.NfsShare.StorageTypeEnum] = JsonEnumFormat[Schema.NfsShare.StorageTypeEnum]
	given fmtAllowedClientMountPermissionsEnum: Format[Schema.AllowedClient.MountPermissionsEnum] = JsonEnumFormat[Schema.AllowedClient.MountPermissionsEnum]
	given fmtListNfsSharesResponse: Format[Schema.ListNfsSharesResponse] = Json.format[Schema.ListNfsSharesResponse]
	given fmtRenameNfsShareRequest: Format[Schema.RenameNfsShareRequest] = Json.format[Schema.RenameNfsShareRequest]
	given fmtListProvisioningQuotasResponse: Format[Schema.ListProvisioningQuotasResponse] = Json.format[Schema.ListProvisioningQuotasResponse]
	given fmtProvisioningQuota: Format[Schema.ProvisioningQuota] = Json.format[Schema.ProvisioningQuota]
	given fmtProvisioningQuotaAssetTypeEnum: Format[Schema.ProvisioningQuota.AssetTypeEnum] = JsonEnumFormat[Schema.ProvisioningQuota.AssetTypeEnum]
	given fmtInstanceQuota: Format[Schema.InstanceQuota] = Json.format[Schema.InstanceQuota]
	given fmtSubmitProvisioningConfigRequest: Format[Schema.SubmitProvisioningConfigRequest] = Json.format[Schema.SubmitProvisioningConfigRequest]
	given fmtProvisioningConfig: Format[Schema.ProvisioningConfig] = Json.format[Schema.ProvisioningConfig]
	given fmtInstanceConfig: Format[Schema.InstanceConfig] = Json.format[Schema.InstanceConfig]
	given fmtNetworkConfig: Format[Schema.NetworkConfig] = Json.format[Schema.NetworkConfig]
	given fmtVolumeConfig: Format[Schema.VolumeConfig] = Json.format[Schema.VolumeConfig]
	given fmtProvisioningConfigStateEnum: Format[Schema.ProvisioningConfig.StateEnum] = JsonEnumFormat[Schema.ProvisioningConfig.StateEnum]
	given fmtNetworkAddress: Format[Schema.NetworkAddress] = Json.format[Schema.NetworkAddress]
	given fmtInstanceConfigNetworkConfigEnum: Format[Schema.InstanceConfig.NetworkConfigEnum] = JsonEnumFormat[Schema.InstanceConfig.NetworkConfigEnum]
	given fmtNetworkConfigTypeEnum: Format[Schema.NetworkConfig.TypeEnum] = JsonEnumFormat[Schema.NetworkConfig.TypeEnum]
	given fmtNetworkConfigBandwidthEnum: Format[Schema.NetworkConfig.BandwidthEnum] = JsonEnumFormat[Schema.NetworkConfig.BandwidthEnum]
	given fmtIntakeVlanAttachment: Format[Schema.IntakeVlanAttachment] = Json.format[Schema.IntakeVlanAttachment]
	given fmtNetworkConfigServiceCidrEnum: Format[Schema.NetworkConfig.ServiceCidrEnum] = JsonEnumFormat[Schema.NetworkConfig.ServiceCidrEnum]
	given fmtVolumeConfigTypeEnum: Format[Schema.VolumeConfig.TypeEnum] = JsonEnumFormat[Schema.VolumeConfig.TypeEnum]
	given fmtVolumeConfigProtocolEnum: Format[Schema.VolumeConfig.ProtocolEnum] = JsonEnumFormat[Schema.VolumeConfig.ProtocolEnum]
	given fmtLunRange: Format[Schema.LunRange] = Json.format[Schema.LunRange]
	given fmtNfsExport: Format[Schema.NfsExport] = Json.format[Schema.NfsExport]
	given fmtVolumeConfigPerformanceTierEnum: Format[Schema.VolumeConfig.PerformanceTierEnum] = JsonEnumFormat[Schema.VolumeConfig.PerformanceTierEnum]
	given fmtNfsExportPermissionsEnum: Format[Schema.NfsExport.PermissionsEnum] = JsonEnumFormat[Schema.NfsExport.PermissionsEnum]
	given fmtSubmitProvisioningConfigResponse: Format[Schema.SubmitProvisioningConfigResponse] = Json.format[Schema.SubmitProvisioningConfigResponse]
	given fmtRenameNetworkRequest: Format[Schema.RenameNetworkRequest] = Json.format[Schema.RenameNetworkRequest]
	given fmtListOSImagesResponse: Format[Schema.ListOSImagesResponse] = Json.format[Schema.ListOSImagesResponse]
	given fmtOSImage: Format[Schema.OSImage] = Json.format[Schema.OSImage]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtResetInstanceResponse: Format[Schema.ResetInstanceResponse] = Json.format[Schema.ResetInstanceResponse]
	given fmtServerNetworkTemplate: Format[Schema.ServerNetworkTemplate] = Json.format[Schema.ServerNetworkTemplate]
	given fmtGoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface: Format[Schema.GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface] = Json.format[Schema.GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface]
	given fmtGoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterfaceTypeEnum: Format[Schema.GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface.TypeEnum] = JsonEnumFormat[Schema.GoogleCloudBaremetalsolutionV2ServerNetworkTemplateLogicalInterface.TypeEnum]
	given fmtStartInstanceResponse: Format[Schema.StartInstanceResponse] = Json.format[Schema.StartInstanceResponse]
	given fmtStopInstanceResponse: Format[Schema.StopInstanceResponse] = Json.format[Schema.StopInstanceResponse]
	given fmtEnableInteractiveSerialConsoleResponse: Format[Schema.EnableInteractiveSerialConsoleResponse] = Json.format[Schema.EnableInteractiveSerialConsoleResponse]
	given fmtDisableInteractiveSerialConsoleResponse: Format[Schema.DisableInteractiveSerialConsoleResponse] = Json.format[Schema.DisableInteractiveSerialConsoleResponse]
}
