package com.boresjo.play.api.google.analyticsreporting

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGetReportsRequest: Format[Schema.GetReportsRequest] = Json.format[Schema.GetReportsRequest]
	given fmtReportRequest: Format[Schema.ReportRequest] = Json.format[Schema.ReportRequest]
	given fmtDateRange: Format[Schema.DateRange] = Json.format[Schema.DateRange]
	given fmtReportRequestSamplingLevelEnum: Format[Schema.ReportRequest.SamplingLevelEnum] = JsonEnumFormat[Schema.ReportRequest.SamplingLevelEnum]
	given fmtDimension: Format[Schema.Dimension] = Json.format[Schema.Dimension]
	given fmtDimensionFilterClause: Format[Schema.DimensionFilterClause] = Json.format[Schema.DimensionFilterClause]
	given fmtMetric: Format[Schema.Metric] = Json.format[Schema.Metric]
	given fmtMetricFilterClause: Format[Schema.MetricFilterClause] = Json.format[Schema.MetricFilterClause]
	given fmtOrderBy: Format[Schema.OrderBy] = Json.format[Schema.OrderBy]
	given fmtSegment: Format[Schema.Segment] = Json.format[Schema.Segment]
	given fmtPivot: Format[Schema.Pivot] = Json.format[Schema.Pivot]
	given fmtCohortGroup: Format[Schema.CohortGroup] = Json.format[Schema.CohortGroup]
	given fmtDimensionFilterClauseOperatorEnum: Format[Schema.DimensionFilterClause.OperatorEnum] = JsonEnumFormat[Schema.DimensionFilterClause.OperatorEnum]
	given fmtDimensionFilter: Format[Schema.DimensionFilter] = Json.format[Schema.DimensionFilter]
	given fmtDimensionFilterOperatorEnum: Format[Schema.DimensionFilter.OperatorEnum] = JsonEnumFormat[Schema.DimensionFilter.OperatorEnum]
	given fmtMetricFormattingTypeEnum: Format[Schema.Metric.FormattingTypeEnum] = JsonEnumFormat[Schema.Metric.FormattingTypeEnum]
	given fmtMetricFilterClauseOperatorEnum: Format[Schema.MetricFilterClause.OperatorEnum] = JsonEnumFormat[Schema.MetricFilterClause.OperatorEnum]
	given fmtMetricFilter: Format[Schema.MetricFilter] = Json.format[Schema.MetricFilter]
	given fmtMetricFilterOperatorEnum: Format[Schema.MetricFilter.OperatorEnum] = JsonEnumFormat[Schema.MetricFilter.OperatorEnum]
	given fmtOrderByOrderTypeEnum: Format[Schema.OrderBy.OrderTypeEnum] = JsonEnumFormat[Schema.OrderBy.OrderTypeEnum]
	given fmtOrderBySortOrderEnum: Format[Schema.OrderBy.SortOrderEnum] = JsonEnumFormat[Schema.OrderBy.SortOrderEnum]
	given fmtDynamicSegment: Format[Schema.DynamicSegment] = Json.format[Schema.DynamicSegment]
	given fmtSegmentDefinition: Format[Schema.SegmentDefinition] = Json.format[Schema.SegmentDefinition]
	given fmtSegmentFilter: Format[Schema.SegmentFilter] = Json.format[Schema.SegmentFilter]
	given fmtSimpleSegment: Format[Schema.SimpleSegment] = Json.format[Schema.SimpleSegment]
	given fmtSequenceSegment: Format[Schema.SequenceSegment] = Json.format[Schema.SequenceSegment]
	given fmtOrFiltersForSegment: Format[Schema.OrFiltersForSegment] = Json.format[Schema.OrFiltersForSegment]
	given fmtSegmentFilterClause: Format[Schema.SegmentFilterClause] = Json.format[Schema.SegmentFilterClause]
	given fmtSegmentDimensionFilter: Format[Schema.SegmentDimensionFilter] = Json.format[Schema.SegmentDimensionFilter]
	given fmtSegmentMetricFilter: Format[Schema.SegmentMetricFilter] = Json.format[Schema.SegmentMetricFilter]
	given fmtSegmentDimensionFilterOperatorEnum: Format[Schema.SegmentDimensionFilter.OperatorEnum] = JsonEnumFormat[Schema.SegmentDimensionFilter.OperatorEnum]
	given fmtSegmentMetricFilterScopeEnum: Format[Schema.SegmentMetricFilter.ScopeEnum] = JsonEnumFormat[Schema.SegmentMetricFilter.ScopeEnum]
	given fmtSegmentMetricFilterOperatorEnum: Format[Schema.SegmentMetricFilter.OperatorEnum] = JsonEnumFormat[Schema.SegmentMetricFilter.OperatorEnum]
	given fmtSegmentSequenceStep: Format[Schema.SegmentSequenceStep] = Json.format[Schema.SegmentSequenceStep]
	given fmtSegmentSequenceStepMatchTypeEnum: Format[Schema.SegmentSequenceStep.MatchTypeEnum] = JsonEnumFormat[Schema.SegmentSequenceStep.MatchTypeEnum]
	given fmtCohort: Format[Schema.Cohort] = Json.format[Schema.Cohort]
	given fmtCohortTypeEnum: Format[Schema.Cohort.TypeEnum] = JsonEnumFormat[Schema.Cohort.TypeEnum]
	given fmtGetReportsResponse: Format[Schema.GetReportsResponse] = Json.format[Schema.GetReportsResponse]
	given fmtReport: Format[Schema.Report] = Json.format[Schema.Report]
	given fmtResourceQuotasRemaining: Format[Schema.ResourceQuotasRemaining] = Json.format[Schema.ResourceQuotasRemaining]
	given fmtColumnHeader: Format[Schema.ColumnHeader] = Json.format[Schema.ColumnHeader]
	given fmtReportData: Format[Schema.ReportData] = Json.format[Schema.ReportData]
	given fmtMetricHeader: Format[Schema.MetricHeader] = Json.format[Schema.MetricHeader]
	given fmtMetricHeaderEntry: Format[Schema.MetricHeaderEntry] = Json.format[Schema.MetricHeaderEntry]
	given fmtPivotHeader: Format[Schema.PivotHeader] = Json.format[Schema.PivotHeader]
	given fmtMetricHeaderEntryTypeEnum: Format[Schema.MetricHeaderEntry.TypeEnum] = JsonEnumFormat[Schema.MetricHeaderEntry.TypeEnum]
	given fmtPivotHeaderEntry: Format[Schema.PivotHeaderEntry] = Json.format[Schema.PivotHeaderEntry]
	given fmtReportRow: Format[Schema.ReportRow] = Json.format[Schema.ReportRow]
	given fmtDateRangeValues: Format[Schema.DateRangeValues] = Json.format[Schema.DateRangeValues]
	given fmtPivotValueRegion: Format[Schema.PivotValueRegion] = Json.format[Schema.PivotValueRegion]
	given fmtSearchUserActivityRequest: Format[Schema.SearchUserActivityRequest] = Json.format[Schema.SearchUserActivityRequest]
	given fmtUser: Format[Schema.User] = Json.format[Schema.User]
	given fmtSearchUserActivityRequestActivityTypesEnum: Format[Schema.SearchUserActivityRequest.ActivityTypesEnum] = JsonEnumFormat[Schema.SearchUserActivityRequest.ActivityTypesEnum]
	given fmtUserTypeEnum: Format[Schema.User.TypeEnum] = JsonEnumFormat[Schema.User.TypeEnum]
	given fmtSearchUserActivityResponse: Format[Schema.SearchUserActivityResponse] = Json.format[Schema.SearchUserActivityResponse]
	given fmtUserActivitySession: Format[Schema.UserActivitySession] = Json.format[Schema.UserActivitySession]
	given fmtActivity: Format[Schema.Activity] = Json.format[Schema.Activity]
	given fmtActivityActivityTypeEnum: Format[Schema.Activity.ActivityTypeEnum] = JsonEnumFormat[Schema.Activity.ActivityTypeEnum]
	given fmtCustomDimension: Format[Schema.CustomDimension] = Json.format[Schema.CustomDimension]
	given fmtPageviewData: Format[Schema.PageviewData] = Json.format[Schema.PageviewData]
	given fmtScreenviewData: Format[Schema.ScreenviewData] = Json.format[Schema.ScreenviewData]
	given fmtEcommerceData: Format[Schema.EcommerceData] = Json.format[Schema.EcommerceData]
	given fmtGoalSetData: Format[Schema.GoalSetData] = Json.format[Schema.GoalSetData]
	given fmtEventData: Format[Schema.EventData] = Json.format[Schema.EventData]
	given fmtEcommerceDataActionTypeEnum: Format[Schema.EcommerceData.ActionTypeEnum] = JsonEnumFormat[Schema.EcommerceData.ActionTypeEnum]
	given fmtTransactionData: Format[Schema.TransactionData] = Json.format[Schema.TransactionData]
	given fmtProductData: Format[Schema.ProductData] = Json.format[Schema.ProductData]
	given fmtEcommerceDataEcommerceTypeEnum: Format[Schema.EcommerceData.EcommerceTypeEnum] = JsonEnumFormat[Schema.EcommerceData.EcommerceTypeEnum]
	given fmtGoalData: Format[Schema.GoalData] = Json.format[Schema.GoalData]
}
