package com.boresjo.play.api.google.policysimulator

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putSchemaGoogleCloudOrgpolicyV2Policy: Conversion[Schema.GoogleCloudOrgpolicyV2Policy, Option[Schema.GoogleCloudOrgpolicyV2Policy]] = (fun: Schema.GoogleCloudOrgpolicyV2Policy) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV2PolicySpec: Conversion[Schema.GoogleCloudOrgpolicyV2PolicySpec, Option[Schema.GoogleCloudOrgpolicyV2PolicySpec]] = (fun: Schema.GoogleCloudOrgpolicyV2PolicySpec) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1alphaCreateOrgPolicyViolationsPreviewOperationMetadataStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1alphaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1alphaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1alphaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV2CustomConstraintActionTypeEnum: Conversion[Schema.GoogleCloudOrgpolicyV2CustomConstraint.ActionTypeEnum, Option[Schema.GoogleCloudOrgpolicyV2CustomConstraint.ActionTypeEnum]] = (fun: Schema.GoogleCloudOrgpolicyV2CustomConstraint.ActionTypeEnum) => Option(fun)
		given putListSchemaGoogleCloudOrgpolicyV2CustomConstraintMethodTypesEnum: Conversion[List[Schema.GoogleCloudOrgpolicyV2CustomConstraint.MethodTypesEnum], Option[List[Schema.GoogleCloudOrgpolicyV2CustomConstraint.MethodTypesEnum]]] = (fun: List[Schema.GoogleCloudOrgpolicyV2CustomConstraint.MethodTypesEnum]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayCustomConstraintOverlay: Conversion[List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayCustomConstraintOverlay], Option[List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayCustomConstraintOverlay]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayCustomConstraintOverlay]) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayPolicyOverlay: Conversion[List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayPolicyOverlay], Option[List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayPolicyOverlay]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlayPolicyOverlay]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ExplainedAccess: Conversion[Schema.GoogleCloudPolicysimulatorV1ExplainedAccess, Option[Schema.GoogleCloudPolicysimulatorV1ExplainedAccess]] = (fun: Schema.GoogleCloudPolicysimulatorV1ExplainedAccess) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1AccessStateDiffAccessChangeEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1AccessStateDiff.AccessChangeEnum, Option[Schema.GoogleCloudPolicysimulatorV1AccessStateDiff.AccessChangeEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1AccessStateDiff.AccessChangeEnum) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1betaCreateOrgPolicyViolationsPreviewOperationMetadataStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1betaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1betaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1betaCreateOrgPolicyViolationsPreviewOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleRpcStatus: Conversion[Schema.GoogleRpcStatus, Option[Schema.GoogleRpcStatus]] = (fun: Schema.GoogleRpcStatus) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1AccessTuple: Conversion[Schema.GoogleCloudPolicysimulatorV1AccessTuple, Option[Schema.GoogleCloudPolicysimulatorV1AccessTuple]] = (fun: Schema.GoogleCloudPolicysimulatorV1AccessTuple) => Option(fun)
		given putSchemaGoogleTypeDate: Conversion[Schema.GoogleTypeDate, Option[Schema.GoogleTypeDate]] = (fun: Schema.GoogleTypeDate) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ReplayDiff: Conversion[Schema.GoogleCloudPolicysimulatorV1ReplayDiff, Option[Schema.GoogleCloudPolicysimulatorV1ReplayDiff]] = (fun: Schema.GoogleCloudPolicysimulatorV1ReplayDiff) => Option(fun)
		given putSchemaGoogleTypeExpr: Conversion[Schema.GoogleTypeExpr, Option[Schema.GoogleTypeExpr]] = (fun: Schema.GoogleTypeExpr) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues: Conversion[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues, Option[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues]] = (fun: Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1betaGenerateOrgPolicyViolationsPreviewOperationMetadataStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1betaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1betaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1betaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1AccessStateDiff: Conversion[Schema.GoogleCloudPolicysimulatorV1AccessStateDiff, Option[Schema.GoogleCloudPolicysimulatorV1AccessStateDiff]] = (fun: Schema.GoogleCloudPolicysimulatorV1AccessStateDiff) => Option(fun)
		given putListSchemaGoogleLongrunningOperation: Conversion[List[Schema.GoogleLongrunningOperation], Option[List[Schema.GoogleLongrunningOperation]]] = (fun: List[Schema.GoogleLongrunningOperation]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ReplayStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1Replay.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1Replay.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1Replay.StateEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ReplayConfig: Conversion[Schema.GoogleCloudPolicysimulatorV1ReplayConfig, Option[Schema.GoogleCloudPolicysimulatorV1ReplayConfig]] = (fun: Schema.GoogleCloudPolicysimulatorV1ReplayConfig) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ReplayResultsSummary: Conversion[Schema.GoogleCloudPolicysimulatorV1ReplayResultsSummary, Option[Schema.GoogleCloudPolicysimulatorV1ReplayResultsSummary]] = (fun: Schema.GoogleCloudPolicysimulatorV1ReplayResultsSummary) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1ReplayResult: Conversion[List[Schema.GoogleCloudPolicysimulatorV1ReplayResult], Option[List[Schema.GoogleCloudPolicysimulatorV1ReplayResult]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1ReplayResult]) => Option(fun)
		given putListSchemaGoogleCloudOrgpolicyV2PolicySpecPolicyRule: Conversion[List[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRule], Option[List[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRule]]] = (fun: List[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRule]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreviewResourceCounts: Conversion[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreviewResourceCounts, Option[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreviewResourceCounts]] = (fun: Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreviewResourceCounts) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1alphaOrgPolicyOverlay: Conversion[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlay, Option[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlay]] = (fun: Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyOverlay) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreviewStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreview.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreview.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1alphaOrgPolicyViolationsPreview.StateEnum) => Option(fun)
		given putMapStringSchemaGoogleIamV1Policy: Conversion[Map[String, Schema.GoogleIamV1Policy], Option[Map[String, Schema.GoogleIamV1Policy]]] = (fun: Map[String, Schema.GoogleIamV1Policy]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ReplayConfigLogSourceEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1ReplayConfig.LogSourceEnum, Option[Schema.GoogleCloudPolicysimulatorV1ReplayConfig.LogSourceEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1ReplayConfig.LogSourceEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1alphaGenerateOrgPolicyViolationsPreviewOperationMetadataStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1alphaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1alphaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1alphaGenerateOrgPolicyViolationsPreviewOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ExplainedPolicyAccessEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.AccessEnum, Option[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.AccessEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.AccessEnum) => Option(fun)
		given putSchemaGoogleIamV1Policy: Conversion[Schema.GoogleIamV1Policy, Option[Schema.GoogleIamV1Policy]] = (fun: Schema.GoogleIamV1Policy) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1BindingExplanation: Conversion[List[Schema.GoogleCloudPolicysimulatorV1BindingExplanation], Option[List[Schema.GoogleCloudPolicysimulatorV1BindingExplanation]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1BindingExplanation]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ExplainedPolicyRelevanceEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.RelevanceEnum, Option[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.RelevanceEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy.RelevanceEnum) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1ExplainedPolicy: Conversion[List[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy], Option[List[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1ExplainedPolicy]) => Option(fun)
		given putListSchemaGoogleRpcStatus: Conversion[List[Schema.GoogleRpcStatus], Option[List[Schema.GoogleRpcStatus]]] = (fun: List[Schema.GoogleRpcStatus]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1ExplainedAccessAccessStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1ExplainedAccess.AccessStateEnum, Option[Schema.GoogleCloudPolicysimulatorV1ExplainedAccess.AccessStateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1ExplainedAccess.AccessStateEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipMembershipEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.MembershipEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.MembershipEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.MembershipEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembershipRelevanceEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.RelevanceEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.RelevanceEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership.RelevanceEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreviewResourceCounts: Conversion[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreviewResourceCounts, Option[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreviewResourceCounts]] = (fun: Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreviewResourceCounts) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1betaOrgPolicyOverlay: Conversion[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlay, Option[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlay]] = (fun: Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlay) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreviewStateEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreview.StateEnum, Option[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreview.StateEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyViolationsPreview.StateEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationRolePermissionEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionEnum) => Option(fun)
		given putMapStringSchemaGoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership: Conversion[Map[String, Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership], Option[Map[String, Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership]]] = (fun: Map[String, Schema.GoogleCloudPolicysimulatorV1BindingExplanationAnnotatedMembership]) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationRelevanceEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RelevanceEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RelevanceEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RelevanceEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationAccessEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.AccessEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.AccessEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanation.AccessEnum) => Option(fun)
		given putSchemaGoogleCloudPolicysimulatorV1BindingExplanationRolePermissionRelevanceEnum: Conversion[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionRelevanceEnum, Option[Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionRelevanceEnum]] = (fun: Schema.GoogleCloudPolicysimulatorV1BindingExplanation.RolePermissionRelevanceEnum) => Option(fun)
		given putListSchemaGoogleIamV1AuditLogConfig: Conversion[List[Schema.GoogleIamV1AuditLogConfig], Option[List[Schema.GoogleIamV1AuditLogConfig]]] = (fun: List[Schema.GoogleIamV1AuditLogConfig]) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV2AlternatePolicySpec: Conversion[Schema.GoogleCloudOrgpolicyV2AlternatePolicySpec, Option[Schema.GoogleCloudOrgpolicyV2AlternatePolicySpec]] = (fun: Schema.GoogleCloudOrgpolicyV2AlternatePolicySpec) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV2CustomConstraint: Conversion[Schema.GoogleCloudOrgpolicyV2CustomConstraint, Option[Schema.GoogleCloudOrgpolicyV2CustomConstraint]] = (fun: Schema.GoogleCloudOrgpolicyV2CustomConstraint) => Option(fun)
		given putListSchemaGoogleIamV1AuditConfig: Conversion[List[Schema.GoogleIamV1AuditConfig], Option[List[Schema.GoogleIamV1AuditConfig]]] = (fun: List[Schema.GoogleIamV1AuditConfig]) => Option(fun)
		given putListSchemaGoogleIamV1Binding: Conversion[List[Schema.GoogleIamV1Binding], Option[List[Schema.GoogleIamV1Binding]]] = (fun: List[Schema.GoogleIamV1Binding]) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1betaOrgPolicyOverlayPolicyOverlay: Conversion[List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayPolicyOverlay], Option[List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayPolicyOverlay]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayPolicyOverlay]) => Option(fun)
		given putListSchemaGoogleCloudPolicysimulatorV1betaOrgPolicyOverlayCustomConstraintOverlay: Conversion[List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayCustomConstraintOverlay], Option[List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayCustomConstraintOverlay]]] = (fun: List[Schema.GoogleCloudPolicysimulatorV1betaOrgPolicyOverlayCustomConstraintOverlay]) => Option(fun)
		given putSchemaGoogleIamV1AuditLogConfigLogTypeEnum: Conversion[Schema.GoogleIamV1AuditLogConfig.LogTypeEnum, Option[Schema.GoogleIamV1AuditLogConfig.LogTypeEnum]] = (fun: Schema.GoogleIamV1AuditLogConfig.LogTypeEnum) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
