package com.boresjo.play.api.google.firestore

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putListSchemaLocation: Conversion[List[Schema.Location], Option[List[Schema.Location]]] = (fun: List[Schema.Location]) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putListSchemaGoogleLongrunningOperation: Conversion[List[Schema.GoogleLongrunningOperation], Option[List[Schema.GoogleLongrunningOperation]]] = (fun: List[Schema.GoogleLongrunningOperation]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexQueryScopeEnum: Conversion[Schema.GoogleFirestoreAdminV1Index.QueryScopeEnum, Option[Schema.GoogleFirestoreAdminV1Index.QueryScopeEnum]] = (fun: Schema.GoogleFirestoreAdminV1Index.QueryScopeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexApiScopeEnum: Conversion[Schema.GoogleFirestoreAdminV1Index.ApiScopeEnum, Option[Schema.GoogleFirestoreAdminV1Index.ApiScopeEnum]] = (fun: Schema.GoogleFirestoreAdminV1Index.ApiScopeEnum) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1IndexField: Conversion[List[Schema.GoogleFirestoreAdminV1IndexField], Option[List[Schema.GoogleFirestoreAdminV1IndexField]]] = (fun: List[Schema.GoogleFirestoreAdminV1IndexField]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexStateEnum: Conversion[Schema.GoogleFirestoreAdminV1Index.StateEnum, Option[Schema.GoogleFirestoreAdminV1Index.StateEnum]] = (fun: Schema.GoogleFirestoreAdminV1Index.StateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexFieldOrderEnum: Conversion[Schema.GoogleFirestoreAdminV1IndexField.OrderEnum, Option[Schema.GoogleFirestoreAdminV1IndexField.OrderEnum]] = (fun: Schema.GoogleFirestoreAdminV1IndexField.OrderEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexFieldArrayConfigEnum: Conversion[Schema.GoogleFirestoreAdminV1IndexField.ArrayConfigEnum, Option[Schema.GoogleFirestoreAdminV1IndexField.ArrayConfigEnum]] = (fun: Schema.GoogleFirestoreAdminV1IndexField.ArrayConfigEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1VectorConfig: Conversion[Schema.GoogleFirestoreAdminV1VectorConfig, Option[Schema.GoogleFirestoreAdminV1VectorConfig]] = (fun: Schema.GoogleFirestoreAdminV1VectorConfig) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1FlatIndex: Conversion[Schema.GoogleFirestoreAdminV1FlatIndex, Option[Schema.GoogleFirestoreAdminV1FlatIndex]] = (fun: Schema.GoogleFirestoreAdminV1FlatIndex) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1Index: Conversion[List[Schema.GoogleFirestoreAdminV1Index], Option[List[Schema.GoogleFirestoreAdminV1Index]]] = (fun: List[Schema.GoogleFirestoreAdminV1Index]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexConfig: Conversion[Schema.GoogleFirestoreAdminV1IndexConfig, Option[Schema.GoogleFirestoreAdminV1IndexConfig]] = (fun: Schema.GoogleFirestoreAdminV1IndexConfig) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1TtlConfig: Conversion[Schema.GoogleFirestoreAdminV1TtlConfig, Option[Schema.GoogleFirestoreAdminV1TtlConfig]] = (fun: Schema.GoogleFirestoreAdminV1TtlConfig) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1TtlConfigStateEnum: Conversion[Schema.GoogleFirestoreAdminV1TtlConfig.StateEnum, Option[Schema.GoogleFirestoreAdminV1TtlConfig.StateEnum]] = (fun: Schema.GoogleFirestoreAdminV1TtlConfig.StateEnum) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1Field: Conversion[List[Schema.GoogleFirestoreAdminV1Field], Option[List[Schema.GoogleFirestoreAdminV1Field]]] = (fun: List[Schema.GoogleFirestoreAdminV1Field]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DatabaseTypeEnum: Conversion[Schema.GoogleFirestoreAdminV1Database.TypeEnum, Option[Schema.GoogleFirestoreAdminV1Database.TypeEnum]] = (fun: Schema.GoogleFirestoreAdminV1Database.TypeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DatabaseConcurrencyModeEnum: Conversion[Schema.GoogleFirestoreAdminV1Database.ConcurrencyModeEnum, Option[Schema.GoogleFirestoreAdminV1Database.ConcurrencyModeEnum]] = (fun: Schema.GoogleFirestoreAdminV1Database.ConcurrencyModeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DatabasePointInTimeRecoveryEnablementEnum: Conversion[Schema.GoogleFirestoreAdminV1Database.PointInTimeRecoveryEnablementEnum, Option[Schema.GoogleFirestoreAdminV1Database.PointInTimeRecoveryEnablementEnum]] = (fun: Schema.GoogleFirestoreAdminV1Database.PointInTimeRecoveryEnablementEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DatabaseAppEngineIntegrationModeEnum: Conversion[Schema.GoogleFirestoreAdminV1Database.AppEngineIntegrationModeEnum, Option[Schema.GoogleFirestoreAdminV1Database.AppEngineIntegrationModeEnum]] = (fun: Schema.GoogleFirestoreAdminV1Database.AppEngineIntegrationModeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DatabaseDeleteProtectionStateEnum: Conversion[Schema.GoogleFirestoreAdminV1Database.DeleteProtectionStateEnum, Option[Schema.GoogleFirestoreAdminV1Database.DeleteProtectionStateEnum]] = (fun: Schema.GoogleFirestoreAdminV1Database.DeleteProtectionStateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1CmekConfig: Conversion[Schema.GoogleFirestoreAdminV1CmekConfig, Option[Schema.GoogleFirestoreAdminV1CmekConfig]] = (fun: Schema.GoogleFirestoreAdminV1CmekConfig) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1SourceInfo: Conversion[Schema.GoogleFirestoreAdminV1SourceInfo, Option[Schema.GoogleFirestoreAdminV1SourceInfo]] = (fun: Schema.GoogleFirestoreAdminV1SourceInfo) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1BackupSource: Conversion[Schema.GoogleFirestoreAdminV1BackupSource, Option[Schema.GoogleFirestoreAdminV1BackupSource]] = (fun: Schema.GoogleFirestoreAdminV1BackupSource) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1Database: Conversion[List[Schema.GoogleFirestoreAdminV1Database], Option[List[Schema.GoogleFirestoreAdminV1Database]]] = (fun: List[Schema.GoogleFirestoreAdminV1Database]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1Stats: Conversion[Schema.GoogleFirestoreAdminV1Stats, Option[Schema.GoogleFirestoreAdminV1Stats]] = (fun: Schema.GoogleFirestoreAdminV1Stats) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1BackupStateEnum: Conversion[Schema.GoogleFirestoreAdminV1Backup.StateEnum, Option[Schema.GoogleFirestoreAdminV1Backup.StateEnum]] = (fun: Schema.GoogleFirestoreAdminV1Backup.StateEnum) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1Backup: Conversion[List[Schema.GoogleFirestoreAdminV1Backup], Option[List[Schema.GoogleFirestoreAdminV1Backup]]] = (fun: List[Schema.GoogleFirestoreAdminV1Backup]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1EncryptionConfig: Conversion[Schema.GoogleFirestoreAdminV1EncryptionConfig, Option[Schema.GoogleFirestoreAdminV1EncryptionConfig]] = (fun: Schema.GoogleFirestoreAdminV1EncryptionConfig) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1GoogleDefaultEncryptionOptions: Conversion[Schema.GoogleFirestoreAdminV1GoogleDefaultEncryptionOptions, Option[Schema.GoogleFirestoreAdminV1GoogleDefaultEncryptionOptions]] = (fun: Schema.GoogleFirestoreAdminV1GoogleDefaultEncryptionOptions) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1SourceEncryptionOptions: Conversion[Schema.GoogleFirestoreAdminV1SourceEncryptionOptions, Option[Schema.GoogleFirestoreAdminV1SourceEncryptionOptions]] = (fun: Schema.GoogleFirestoreAdminV1SourceEncryptionOptions) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1CustomerManagedEncryptionOptions: Conversion[Schema.GoogleFirestoreAdminV1CustomerManagedEncryptionOptions, Option[Schema.GoogleFirestoreAdminV1CustomerManagedEncryptionOptions]] = (fun: Schema.GoogleFirestoreAdminV1CustomerManagedEncryptionOptions) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1DailyRecurrence: Conversion[Schema.GoogleFirestoreAdminV1DailyRecurrence, Option[Schema.GoogleFirestoreAdminV1DailyRecurrence]] = (fun: Schema.GoogleFirestoreAdminV1DailyRecurrence) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1WeeklyRecurrence: Conversion[Schema.GoogleFirestoreAdminV1WeeklyRecurrence, Option[Schema.GoogleFirestoreAdminV1WeeklyRecurrence]] = (fun: Schema.GoogleFirestoreAdminV1WeeklyRecurrence) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1WeeklyRecurrenceDayEnum: Conversion[Schema.GoogleFirestoreAdminV1WeeklyRecurrence.DayEnum, Option[Schema.GoogleFirestoreAdminV1WeeklyRecurrence.DayEnum]] = (fun: Schema.GoogleFirestoreAdminV1WeeklyRecurrence.DayEnum) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1BackupSchedule: Conversion[List[Schema.GoogleFirestoreAdminV1BackupSchedule], Option[List[Schema.GoogleFirestoreAdminV1BackupSchedule]]] = (fun: List[Schema.GoogleFirestoreAdminV1BackupSchedule]) => Option(fun)
		given putMapStringSchemaValue: Conversion[Map[String, Schema.Value], Option[Map[String, Schema.Value]]] = (fun: Map[String, Schema.Value]) => Option(fun)
		given putSchemaValueNullValueEnum: Conversion[Schema.Value.NullValueEnum, Option[Schema.Value.NullValueEnum]] = (fun: Schema.Value.NullValueEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putSchemaLatLng: Conversion[Schema.LatLng, Option[Schema.LatLng]] = (fun: Schema.LatLng) => Option(fun)
		given putSchemaArrayValue: Conversion[Schema.ArrayValue, Option[Schema.ArrayValue]] = (fun: Schema.ArrayValue) => Option(fun)
		given putSchemaMapValue: Conversion[Schema.MapValue, Option[Schema.MapValue]] = (fun: Schema.MapValue) => Option(fun)
		given putListSchemaValue: Conversion[List[Schema.Value], Option[List[Schema.Value]]] = (fun: List[Schema.Value]) => Option(fun)
		given putListSchemaDocument: Conversion[List[Schema.Document], Option[List[Schema.Document]]] = (fun: List[Schema.Document]) => Option(fun)
		given putSchemaDocumentMask: Conversion[Schema.DocumentMask, Option[Schema.DocumentMask]] = (fun: Schema.DocumentMask) => Option(fun)
		given putSchemaTransactionOptions: Conversion[Schema.TransactionOptions, Option[Schema.TransactionOptions]] = (fun: Schema.TransactionOptions) => Option(fun)
		given putSchemaReadOnly: Conversion[Schema.ReadOnly, Option[Schema.ReadOnly]] = (fun: Schema.ReadOnly) => Option(fun)
		given putSchemaReadWrite: Conversion[Schema.ReadWrite, Option[Schema.ReadWrite]] = (fun: Schema.ReadWrite) => Option(fun)
		given putSchemaDocument: Conversion[Schema.Document, Option[Schema.Document]] = (fun: Schema.Document) => Option(fun)
		given putListSchemaWrite: Conversion[List[Schema.Write], Option[List[Schema.Write]]] = (fun: List[Schema.Write]) => Option(fun)
		given putSchemaDocumentTransform: Conversion[Schema.DocumentTransform, Option[Schema.DocumentTransform]] = (fun: Schema.DocumentTransform) => Option(fun)
		given putListSchemaFieldTransform: Conversion[List[Schema.FieldTransform], Option[List[Schema.FieldTransform]]] = (fun: List[Schema.FieldTransform]) => Option(fun)
		given putSchemaPrecondition: Conversion[Schema.Precondition, Option[Schema.Precondition]] = (fun: Schema.Precondition) => Option(fun)
		given putSchemaFieldTransformSetToServerValueEnum: Conversion[Schema.FieldTransform.SetToServerValueEnum, Option[Schema.FieldTransform.SetToServerValueEnum]] = (fun: Schema.FieldTransform.SetToServerValueEnum) => Option(fun)
		given putSchemaValue: Conversion[Schema.Value, Option[Schema.Value]] = (fun: Schema.Value) => Option(fun)
		given putListSchemaWriteResult: Conversion[List[Schema.WriteResult], Option[List[Schema.WriteResult]]] = (fun: List[Schema.WriteResult]) => Option(fun)
		given putSchemaStructuredQuery: Conversion[Schema.StructuredQuery, Option[Schema.StructuredQuery]] = (fun: Schema.StructuredQuery) => Option(fun)
		given putSchemaExplainOptions: Conversion[Schema.ExplainOptions, Option[Schema.ExplainOptions]] = (fun: Schema.ExplainOptions) => Option(fun)
		given putSchemaProjection: Conversion[Schema.Projection, Option[Schema.Projection]] = (fun: Schema.Projection) => Option(fun)
		given putListSchemaCollectionSelector: Conversion[List[Schema.CollectionSelector], Option[List[Schema.CollectionSelector]]] = (fun: List[Schema.CollectionSelector]) => Option(fun)
		given putSchemaFilter: Conversion[Schema.Filter, Option[Schema.Filter]] = (fun: Schema.Filter) => Option(fun)
		given putListSchemaOrder: Conversion[List[Schema.Order], Option[List[Schema.Order]]] = (fun: List[Schema.Order]) => Option(fun)
		given putSchemaCursor: Conversion[Schema.Cursor, Option[Schema.Cursor]] = (fun: Schema.Cursor) => Option(fun)
		given putSchemaFindNearest: Conversion[Schema.FindNearest, Option[Schema.FindNearest]] = (fun: Schema.FindNearest) => Option(fun)
		given putListSchemaFieldReference: Conversion[List[Schema.FieldReference], Option[List[Schema.FieldReference]]] = (fun: List[Schema.FieldReference]) => Option(fun)
		given putSchemaCompositeFilter: Conversion[Schema.CompositeFilter, Option[Schema.CompositeFilter]] = (fun: Schema.CompositeFilter) => Option(fun)
		given putSchemaFieldFilter: Conversion[Schema.FieldFilter, Option[Schema.FieldFilter]] = (fun: Schema.FieldFilter) => Option(fun)
		given putSchemaUnaryFilter: Conversion[Schema.UnaryFilter, Option[Schema.UnaryFilter]] = (fun: Schema.UnaryFilter) => Option(fun)
		given putSchemaCompositeFilterOpEnum: Conversion[Schema.CompositeFilter.OpEnum, Option[Schema.CompositeFilter.OpEnum]] = (fun: Schema.CompositeFilter.OpEnum) => Option(fun)
		given putListSchemaFilter: Conversion[List[Schema.Filter], Option[List[Schema.Filter]]] = (fun: List[Schema.Filter]) => Option(fun)
		given putSchemaFieldReference: Conversion[Schema.FieldReference, Option[Schema.FieldReference]] = (fun: Schema.FieldReference) => Option(fun)
		given putSchemaFieldFilterOpEnum: Conversion[Schema.FieldFilter.OpEnum, Option[Schema.FieldFilter.OpEnum]] = (fun: Schema.FieldFilter.OpEnum) => Option(fun)
		given putSchemaUnaryFilterOpEnum: Conversion[Schema.UnaryFilter.OpEnum, Option[Schema.UnaryFilter.OpEnum]] = (fun: Schema.UnaryFilter.OpEnum) => Option(fun)
		given putSchemaOrderDirectionEnum: Conversion[Schema.Order.DirectionEnum, Option[Schema.Order.DirectionEnum]] = (fun: Schema.Order.DirectionEnum) => Option(fun)
		given putSchemaFindNearestDistanceMeasureEnum: Conversion[Schema.FindNearest.DistanceMeasureEnum, Option[Schema.FindNearest.DistanceMeasureEnum]] = (fun: Schema.FindNearest.DistanceMeasureEnum) => Option(fun)
		given putSchemaExplainMetrics: Conversion[Schema.ExplainMetrics, Option[Schema.ExplainMetrics]] = (fun: Schema.ExplainMetrics) => Option(fun)
		given putSchemaPlanSummary: Conversion[Schema.PlanSummary, Option[Schema.PlanSummary]] = (fun: Schema.PlanSummary) => Option(fun)
		given putSchemaExecutionStats: Conversion[Schema.ExecutionStats, Option[Schema.ExecutionStats]] = (fun: Schema.ExecutionStats) => Option(fun)
		given putSchemaStructuredAggregationQuery: Conversion[Schema.StructuredAggregationQuery, Option[Schema.StructuredAggregationQuery]] = (fun: Schema.StructuredAggregationQuery) => Option(fun)
		given putListSchemaAggregation: Conversion[List[Schema.Aggregation], Option[List[Schema.Aggregation]]] = (fun: List[Schema.Aggregation]) => Option(fun)
		given putSchemaCount: Conversion[Schema.Count, Option[Schema.Count]] = (fun: Schema.Count) => Option(fun)
		given putSchemaSum: Conversion[Schema.Sum, Option[Schema.Sum]] = (fun: Schema.Sum) => Option(fun)
		given putSchemaAvg: Conversion[Schema.Avg, Option[Schema.Avg]] = (fun: Schema.Avg) => Option(fun)
		given putSchemaAggregationResult: Conversion[Schema.AggregationResult, Option[Schema.AggregationResult]] = (fun: Schema.AggregationResult) => Option(fun)
		given putListSchemaCursor: Conversion[List[Schema.Cursor], Option[List[Schema.Cursor]]] = (fun: List[Schema.Cursor]) => Option(fun)
		given putSchemaTarget: Conversion[Schema.Target, Option[Schema.Target]] = (fun: Schema.Target) => Option(fun)
		given putSchemaQueryTarget: Conversion[Schema.QueryTarget, Option[Schema.QueryTarget]] = (fun: Schema.QueryTarget) => Option(fun)
		given putSchemaDocumentsTarget: Conversion[Schema.DocumentsTarget, Option[Schema.DocumentsTarget]] = (fun: Schema.DocumentsTarget) => Option(fun)
		given putSchemaTargetChange: Conversion[Schema.TargetChange, Option[Schema.TargetChange]] = (fun: Schema.TargetChange) => Option(fun)
		given putSchemaDocumentChange: Conversion[Schema.DocumentChange, Option[Schema.DocumentChange]] = (fun: Schema.DocumentChange) => Option(fun)
		given putSchemaDocumentDelete: Conversion[Schema.DocumentDelete, Option[Schema.DocumentDelete]] = (fun: Schema.DocumentDelete) => Option(fun)
		given putSchemaDocumentRemove: Conversion[Schema.DocumentRemove, Option[Schema.DocumentRemove]] = (fun: Schema.DocumentRemove) => Option(fun)
		given putSchemaExistenceFilter: Conversion[Schema.ExistenceFilter, Option[Schema.ExistenceFilter]] = (fun: Schema.ExistenceFilter) => Option(fun)
		given putSchemaTargetChangeTargetChangeTypeEnum: Conversion[Schema.TargetChange.TargetChangeTypeEnum, Option[Schema.TargetChange.TargetChangeTypeEnum]] = (fun: Schema.TargetChange.TargetChangeTypeEnum) => Option(fun)
		given putListInt: Conversion[List[Int], Option[List[Int]]] = (fun: List[Int]) => Option(fun)
		given putSchemaBloomFilter: Conversion[Schema.BloomFilter, Option[Schema.BloomFilter]] = (fun: Schema.BloomFilter) => Option(fun)
		given putSchemaBitSequence: Conversion[Schema.BitSequence, Option[Schema.BitSequence]] = (fun: Schema.BitSequence) => Option(fun)
		given putListSchemaStatus: Conversion[List[Schema.Status], Option[List[Schema.Status]]] = (fun: List[Schema.Status]) => Option(fun)
		given putListSchemaGoogleFirestoreAdminV1IndexConfigDelta: Conversion[List[Schema.GoogleFirestoreAdminV1IndexConfigDelta], Option[List[Schema.GoogleFirestoreAdminV1IndexConfigDelta]]] = (fun: List[Schema.GoogleFirestoreAdminV1IndexConfigDelta]) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1FieldOperationMetadataStateEnum: Conversion[Schema.GoogleFirestoreAdminV1FieldOperationMetadata.StateEnum, Option[Schema.GoogleFirestoreAdminV1FieldOperationMetadata.StateEnum]] = (fun: Schema.GoogleFirestoreAdminV1FieldOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1Progress: Conversion[Schema.GoogleFirestoreAdminV1Progress, Option[Schema.GoogleFirestoreAdminV1Progress]] = (fun: Schema.GoogleFirestoreAdminV1Progress) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1TtlConfigDelta: Conversion[Schema.GoogleFirestoreAdminV1TtlConfigDelta, Option[Schema.GoogleFirestoreAdminV1TtlConfigDelta]] = (fun: Schema.GoogleFirestoreAdminV1TtlConfigDelta) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexConfigDeltaChangeTypeEnum: Conversion[Schema.GoogleFirestoreAdminV1IndexConfigDelta.ChangeTypeEnum, Option[Schema.GoogleFirestoreAdminV1IndexConfigDelta.ChangeTypeEnum]] = (fun: Schema.GoogleFirestoreAdminV1IndexConfigDelta.ChangeTypeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1Index: Conversion[Schema.GoogleFirestoreAdminV1Index, Option[Schema.GoogleFirestoreAdminV1Index]] = (fun: Schema.GoogleFirestoreAdminV1Index) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1TtlConfigDeltaChangeTypeEnum: Conversion[Schema.GoogleFirestoreAdminV1TtlConfigDelta.ChangeTypeEnum, Option[Schema.GoogleFirestoreAdminV1TtlConfigDelta.ChangeTypeEnum]] = (fun: Schema.GoogleFirestoreAdminV1TtlConfigDelta.ChangeTypeEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1IndexOperationMetadataStateEnum: Conversion[Schema.GoogleFirestoreAdminV1IndexOperationMetadata.StateEnum, Option[Schema.GoogleFirestoreAdminV1IndexOperationMetadata.StateEnum]] = (fun: Schema.GoogleFirestoreAdminV1IndexOperationMetadata.StateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1ExportDocumentsMetadataOperationStateEnum: Conversion[Schema.GoogleFirestoreAdminV1ExportDocumentsMetadata.OperationStateEnum, Option[Schema.GoogleFirestoreAdminV1ExportDocumentsMetadata.OperationStateEnum]] = (fun: Schema.GoogleFirestoreAdminV1ExportDocumentsMetadata.OperationStateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1BulkDeleteDocumentsMetadataOperationStateEnum: Conversion[Schema.GoogleFirestoreAdminV1BulkDeleteDocumentsMetadata.OperationStateEnum, Option[Schema.GoogleFirestoreAdminV1BulkDeleteDocumentsMetadata.OperationStateEnum]] = (fun: Schema.GoogleFirestoreAdminV1BulkDeleteDocumentsMetadata.OperationStateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1ImportDocumentsMetadataOperationStateEnum: Conversion[Schema.GoogleFirestoreAdminV1ImportDocumentsMetadata.OperationStateEnum, Option[Schema.GoogleFirestoreAdminV1ImportDocumentsMetadata.OperationStateEnum]] = (fun: Schema.GoogleFirestoreAdminV1ImportDocumentsMetadata.OperationStateEnum) => Option(fun)
		given putSchemaGoogleFirestoreAdminV1RestoreDatabaseMetadataOperationStateEnum: Conversion[Schema.GoogleFirestoreAdminV1RestoreDatabaseMetadata.OperationStateEnum, Option[Schema.GoogleFirestoreAdminV1RestoreDatabaseMetadata.OperationStateEnum]] = (fun: Schema.GoogleFirestoreAdminV1RestoreDatabaseMetadata.OperationStateEnum) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
