package com.boresjo.play.api.google.oracledatabase

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtListCloudExadataInfrastructuresResponse: Format[Schema.ListCloudExadataInfrastructuresResponse] = Json.format[Schema.ListCloudExadataInfrastructuresResponse]
	given fmtCloudExadataInfrastructure: Format[Schema.CloudExadataInfrastructure] = Json.format[Schema.CloudExadataInfrastructure]
	given fmtCloudExadataInfrastructureProperties: Format[Schema.CloudExadataInfrastructureProperties] = Json.format[Schema.CloudExadataInfrastructureProperties]
	given fmtMaintenanceWindow: Format[Schema.MaintenanceWindow] = Json.format[Schema.MaintenanceWindow]
	given fmtCloudExadataInfrastructurePropertiesStateEnum: Format[Schema.CloudExadataInfrastructureProperties.StateEnum] = JsonEnumFormat[Schema.CloudExadataInfrastructureProperties.StateEnum]
	given fmtCustomerContact: Format[Schema.CustomerContact] = Json.format[Schema.CustomerContact]
	given fmtMaintenanceWindowPreferenceEnum: Format[Schema.MaintenanceWindow.PreferenceEnum] = JsonEnumFormat[Schema.MaintenanceWindow.PreferenceEnum]
	given fmtMaintenanceWindowMonthsEnum: Format[Schema.MaintenanceWindow.MonthsEnum] = JsonEnumFormat[Schema.MaintenanceWindow.MonthsEnum]
	given fmtMaintenanceWindowDaysOfWeekEnum: Format[Schema.MaintenanceWindow.DaysOfWeekEnum] = JsonEnumFormat[Schema.MaintenanceWindow.DaysOfWeekEnum]
	given fmtMaintenanceWindowPatchingModeEnum: Format[Schema.MaintenanceWindow.PatchingModeEnum] = JsonEnumFormat[Schema.MaintenanceWindow.PatchingModeEnum]
	given fmtListCloudVmClustersResponse: Format[Schema.ListCloudVmClustersResponse] = Json.format[Schema.ListCloudVmClustersResponse]
	given fmtCloudVmCluster: Format[Schema.CloudVmCluster] = Json.format[Schema.CloudVmCluster]
	given fmtCloudVmClusterProperties: Format[Schema.CloudVmClusterProperties] = Json.format[Schema.CloudVmClusterProperties]
	given fmtCloudVmClusterPropertiesLicenseTypeEnum: Format[Schema.CloudVmClusterProperties.LicenseTypeEnum] = JsonEnumFormat[Schema.CloudVmClusterProperties.LicenseTypeEnum]
	given fmtTimeZone: Format[Schema.TimeZone] = Json.format[Schema.TimeZone]
	given fmtCloudVmClusterPropertiesDiskRedundancyEnum: Format[Schema.CloudVmClusterProperties.DiskRedundancyEnum] = JsonEnumFormat[Schema.CloudVmClusterProperties.DiskRedundancyEnum]
	given fmtDataCollectionOptions: Format[Schema.DataCollectionOptions] = Json.format[Schema.DataCollectionOptions]
	given fmtCloudVmClusterPropertiesStateEnum: Format[Schema.CloudVmClusterProperties.StateEnum] = JsonEnumFormat[Schema.CloudVmClusterProperties.StateEnum]
	given fmtListEntitlementsResponse: Format[Schema.ListEntitlementsResponse] = Json.format[Schema.ListEntitlementsResponse]
	given fmtEntitlement: Format[Schema.Entitlement] = Json.format[Schema.Entitlement]
	given fmtCloudAccountDetails: Format[Schema.CloudAccountDetails] = Json.format[Schema.CloudAccountDetails]
	given fmtEntitlementStateEnum: Format[Schema.Entitlement.StateEnum] = JsonEnumFormat[Schema.Entitlement.StateEnum]
	given fmtListDbServersResponse: Format[Schema.ListDbServersResponse] = Json.format[Schema.ListDbServersResponse]
	given fmtDbServer: Format[Schema.DbServer] = Json.format[Schema.DbServer]
	given fmtDbServerProperties: Format[Schema.DbServerProperties] = Json.format[Schema.DbServerProperties]
	given fmtDbServerPropertiesStateEnum: Format[Schema.DbServerProperties.StateEnum] = JsonEnumFormat[Schema.DbServerProperties.StateEnum]
	given fmtListDbNodesResponse: Format[Schema.ListDbNodesResponse] = Json.format[Schema.ListDbNodesResponse]
	given fmtDbNode: Format[Schema.DbNode] = Json.format[Schema.DbNode]
	given fmtDbNodeProperties: Format[Schema.DbNodeProperties] = Json.format[Schema.DbNodeProperties]
	given fmtDbNodePropertiesStateEnum: Format[Schema.DbNodeProperties.StateEnum] = JsonEnumFormat[Schema.DbNodeProperties.StateEnum]
	given fmtListGiVersionsResponse: Format[Schema.ListGiVersionsResponse] = Json.format[Schema.ListGiVersionsResponse]
	given fmtGiVersion: Format[Schema.GiVersion] = Json.format[Schema.GiVersion]
	given fmtListDbSystemShapesResponse: Format[Schema.ListDbSystemShapesResponse] = Json.format[Schema.ListDbSystemShapesResponse]
	given fmtDbSystemShape: Format[Schema.DbSystemShape] = Json.format[Schema.DbSystemShape]
	given fmtListAutonomousDatabasesResponse: Format[Schema.ListAutonomousDatabasesResponse] = Json.format[Schema.ListAutonomousDatabasesResponse]
	given fmtAutonomousDatabase: Format[Schema.AutonomousDatabase] = Json.format[Schema.AutonomousDatabase]
	given fmtAutonomousDatabaseProperties: Format[Schema.AutonomousDatabaseProperties] = Json.format[Schema.AutonomousDatabaseProperties]
	given fmtAutonomousDatabasePropertiesDbWorkloadEnum: Format[Schema.AutonomousDatabaseProperties.DbWorkloadEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.DbWorkloadEnum]
	given fmtAutonomousDatabasePropertiesDbEditionEnum: Format[Schema.AutonomousDatabaseProperties.DbEditionEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.DbEditionEnum]
	given fmtAutonomousDatabasePropertiesLicenseTypeEnum: Format[Schema.AutonomousDatabaseProperties.LicenseTypeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.LicenseTypeEnum]
	given fmtAutonomousDatabasePropertiesMaintenanceScheduleTypeEnum: Format[Schema.AutonomousDatabaseProperties.MaintenanceScheduleTypeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.MaintenanceScheduleTypeEnum]
	given fmtAutonomousDatabaseApex: Format[Schema.AutonomousDatabaseApex] = Json.format[Schema.AutonomousDatabaseApex]
	given fmtAutonomousDatabasePropertiesStateEnum: Format[Schema.AutonomousDatabaseProperties.StateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.StateEnum]
	given fmtAutonomousDatabaseConnectionStrings: Format[Schema.AutonomousDatabaseConnectionStrings] = Json.format[Schema.AutonomousDatabaseConnectionStrings]
	given fmtAutonomousDatabaseConnectionUrls: Format[Schema.AutonomousDatabaseConnectionUrls] = Json.format[Schema.AutonomousDatabaseConnectionUrls]
	given fmtAutonomousDatabaseStandbySummary: Format[Schema.AutonomousDatabaseStandbySummary] = Json.format[Schema.AutonomousDatabaseStandbySummary]
	given fmtAutonomousDatabasePropertiesLocalDisasterRecoveryTypeEnum: Format[Schema.AutonomousDatabaseProperties.LocalDisasterRecoveryTypeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.LocalDisasterRecoveryTypeEnum]
	given fmtAutonomousDatabasePropertiesDataSafeStateEnum: Format[Schema.AutonomousDatabaseProperties.DataSafeStateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.DataSafeStateEnum]
	given fmtAutonomousDatabasePropertiesDatabaseManagementStateEnum: Format[Schema.AutonomousDatabaseProperties.DatabaseManagementStateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.DatabaseManagementStateEnum]
	given fmtAutonomousDatabasePropertiesOpenModeEnum: Format[Schema.AutonomousDatabaseProperties.OpenModeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.OpenModeEnum]
	given fmtAutonomousDatabasePropertiesOperationsInsightsStateEnum: Format[Schema.AutonomousDatabaseProperties.OperationsInsightsStateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.OperationsInsightsStateEnum]
	given fmtAutonomousDatabasePropertiesPermissionLevelEnum: Format[Schema.AutonomousDatabaseProperties.PermissionLevelEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.PermissionLevelEnum]
	given fmtAutonomousDatabasePropertiesRefreshableModeEnum: Format[Schema.AutonomousDatabaseProperties.RefreshableModeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.RefreshableModeEnum]
	given fmtAutonomousDatabasePropertiesRefreshableStateEnum: Format[Schema.AutonomousDatabaseProperties.RefreshableStateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.RefreshableStateEnum]
	given fmtAutonomousDatabasePropertiesRoleEnum: Format[Schema.AutonomousDatabaseProperties.RoleEnum] = JsonEnumFormat[Schema.AutonomousDatabaseProperties.RoleEnum]
	given fmtScheduledOperationDetails: Format[Schema.ScheduledOperationDetails] = Json.format[Schema.ScheduledOperationDetails]
	given fmtAllConnectionStrings: Format[Schema.AllConnectionStrings] = Json.format[Schema.AllConnectionStrings]
	given fmtDatabaseConnectionStringProfile: Format[Schema.DatabaseConnectionStringProfile] = Json.format[Schema.DatabaseConnectionStringProfile]
	given fmtDatabaseConnectionStringProfileConsumerGroupEnum: Format[Schema.DatabaseConnectionStringProfile.ConsumerGroupEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.ConsumerGroupEnum]
	given fmtDatabaseConnectionStringProfileHostFormatEnum: Format[Schema.DatabaseConnectionStringProfile.HostFormatEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.HostFormatEnum]
	given fmtDatabaseConnectionStringProfileProtocolEnum: Format[Schema.DatabaseConnectionStringProfile.ProtocolEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.ProtocolEnum]
	given fmtDatabaseConnectionStringProfileSessionModeEnum: Format[Schema.DatabaseConnectionStringProfile.SessionModeEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.SessionModeEnum]
	given fmtDatabaseConnectionStringProfileSyntaxFormatEnum: Format[Schema.DatabaseConnectionStringProfile.SyntaxFormatEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.SyntaxFormatEnum]
	given fmtDatabaseConnectionStringProfileTlsAuthenticationEnum: Format[Schema.DatabaseConnectionStringProfile.TlsAuthenticationEnum] = JsonEnumFormat[Schema.DatabaseConnectionStringProfile.TlsAuthenticationEnum]
	given fmtAutonomousDatabaseStandbySummaryStateEnum: Format[Schema.AutonomousDatabaseStandbySummary.StateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseStandbySummary.StateEnum]
	given fmtScheduledOperationDetailsDayOfWeekEnum: Format[Schema.ScheduledOperationDetails.DayOfWeekEnum] = JsonEnumFormat[Schema.ScheduledOperationDetails.DayOfWeekEnum]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtRestoreAutonomousDatabaseRequest: Format[Schema.RestoreAutonomousDatabaseRequest] = Json.format[Schema.RestoreAutonomousDatabaseRequest]
	given fmtGenerateAutonomousDatabaseWalletRequest: Format[Schema.GenerateAutonomousDatabaseWalletRequest] = Json.format[Schema.GenerateAutonomousDatabaseWalletRequest]
	given fmtGenerateAutonomousDatabaseWalletRequestTypeEnum: Format[Schema.GenerateAutonomousDatabaseWalletRequest.TypeEnum] = JsonEnumFormat[Schema.GenerateAutonomousDatabaseWalletRequest.TypeEnum]
	given fmtGenerateAutonomousDatabaseWalletResponse: Format[Schema.GenerateAutonomousDatabaseWalletResponse] = Json.format[Schema.GenerateAutonomousDatabaseWalletResponse]
	given fmtListAutonomousDbVersionsResponse: Format[Schema.ListAutonomousDbVersionsResponse] = Json.format[Schema.ListAutonomousDbVersionsResponse]
	given fmtAutonomousDbVersion: Format[Schema.AutonomousDbVersion] = Json.format[Schema.AutonomousDbVersion]
	given fmtAutonomousDbVersionDbWorkloadEnum: Format[Schema.AutonomousDbVersion.DbWorkloadEnum] = JsonEnumFormat[Schema.AutonomousDbVersion.DbWorkloadEnum]
	given fmtListAutonomousDatabaseCharacterSetsResponse: Format[Schema.ListAutonomousDatabaseCharacterSetsResponse] = Json.format[Schema.ListAutonomousDatabaseCharacterSetsResponse]
	given fmtAutonomousDatabaseCharacterSet: Format[Schema.AutonomousDatabaseCharacterSet] = Json.format[Schema.AutonomousDatabaseCharacterSet]
	given fmtAutonomousDatabaseCharacterSetCharacterSetTypeEnum: Format[Schema.AutonomousDatabaseCharacterSet.CharacterSetTypeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseCharacterSet.CharacterSetTypeEnum]
	given fmtListAutonomousDatabaseBackupsResponse: Format[Schema.ListAutonomousDatabaseBackupsResponse] = Json.format[Schema.ListAutonomousDatabaseBackupsResponse]
	given fmtAutonomousDatabaseBackup: Format[Schema.AutonomousDatabaseBackup] = Json.format[Schema.AutonomousDatabaseBackup]
	given fmtAutonomousDatabaseBackupProperties: Format[Schema.AutonomousDatabaseBackupProperties] = Json.format[Schema.AutonomousDatabaseBackupProperties]
	given fmtAutonomousDatabaseBackupPropertiesLifecycleStateEnum: Format[Schema.AutonomousDatabaseBackupProperties.LifecycleStateEnum] = JsonEnumFormat[Schema.AutonomousDatabaseBackupProperties.LifecycleStateEnum]
	given fmtAutonomousDatabaseBackupPropertiesTypeEnum: Format[Schema.AutonomousDatabaseBackupProperties.TypeEnum] = JsonEnumFormat[Schema.AutonomousDatabaseBackupProperties.TypeEnum]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
	given fmtLocationMetadata: Format[Schema.LocationMetadata] = Json.format[Schema.LocationMetadata]
}
