package com.boresjo.play.api.google.dns

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtResourceRecordSetsListResponse: Format[Schema.ResourceRecordSetsListResponse] = Json.format[Schema.ResourceRecordSetsListResponse]
	given fmtResourceRecordSet: Format[Schema.ResourceRecordSet] = Json.format[Schema.ResourceRecordSet]
	given fmtRRSetRoutingPolicy: Format[Schema.RRSetRoutingPolicy] = Json.format[Schema.RRSetRoutingPolicy]
	given fmtRRSetRoutingPolicyGeoPolicy: Format[Schema.RRSetRoutingPolicyGeoPolicy] = Json.format[Schema.RRSetRoutingPolicyGeoPolicy]
	given fmtRRSetRoutingPolicyWrrPolicy: Format[Schema.RRSetRoutingPolicyWrrPolicy] = Json.format[Schema.RRSetRoutingPolicyWrrPolicy]
	given fmtRRSetRoutingPolicyPrimaryBackupPolicy: Format[Schema.RRSetRoutingPolicyPrimaryBackupPolicy] = Json.format[Schema.RRSetRoutingPolicyPrimaryBackupPolicy]
	given fmtRRSetRoutingPolicyGeoPolicyGeoPolicyItem: Format[Schema.RRSetRoutingPolicyGeoPolicyGeoPolicyItem] = Json.format[Schema.RRSetRoutingPolicyGeoPolicyGeoPolicyItem]
	given fmtRRSetRoutingPolicyHealthCheckTargets: Format[Schema.RRSetRoutingPolicyHealthCheckTargets] = Json.format[Schema.RRSetRoutingPolicyHealthCheckTargets]
	given fmtRRSetRoutingPolicyLoadBalancerTarget: Format[Schema.RRSetRoutingPolicyLoadBalancerTarget] = Json.format[Schema.RRSetRoutingPolicyLoadBalancerTarget]
	given fmtRRSetRoutingPolicyLoadBalancerTargetLoadBalancerTypeEnum: Format[Schema.RRSetRoutingPolicyLoadBalancerTarget.LoadBalancerTypeEnum] = JsonEnumFormat[Schema.RRSetRoutingPolicyLoadBalancerTarget.LoadBalancerTypeEnum]
	given fmtRRSetRoutingPolicyLoadBalancerTargetIpProtocolEnum: Format[Schema.RRSetRoutingPolicyLoadBalancerTarget.IpProtocolEnum] = JsonEnumFormat[Schema.RRSetRoutingPolicyLoadBalancerTarget.IpProtocolEnum]
	given fmtRRSetRoutingPolicyWrrPolicyWrrPolicyItem: Format[Schema.RRSetRoutingPolicyWrrPolicyWrrPolicyItem] = Json.format[Schema.RRSetRoutingPolicyWrrPolicyWrrPolicyItem]
	given fmtResourceRecordSetsDeleteResponse: Format[Schema.ResourceRecordSetsDeleteResponse] = Json.format[Schema.ResourceRecordSetsDeleteResponse]
	given fmtChange: Format[Schema.Change] = Json.format[Schema.Change]
	given fmtChangeStatusEnum: Format[Schema.Change.StatusEnum] = JsonEnumFormat[Schema.Change.StatusEnum]
	given fmtChangesListResponse: Format[Schema.ChangesListResponse] = Json.format[Schema.ChangesListResponse]
	given fmtDnsKey: Format[Schema.DnsKey] = Json.format[Schema.DnsKey]
	given fmtDnsKeyAlgorithmEnum: Format[Schema.DnsKey.AlgorithmEnum] = JsonEnumFormat[Schema.DnsKey.AlgorithmEnum]
	given fmtDnsKeyTypeEnum: Format[Schema.DnsKey.TypeEnum] = JsonEnumFormat[Schema.DnsKey.TypeEnum]
	given fmtDnsKeyDigest: Format[Schema.DnsKeyDigest] = Json.format[Schema.DnsKeyDigest]
	given fmtDnsKeyDigestTypeEnum: Format[Schema.DnsKeyDigest.TypeEnum] = JsonEnumFormat[Schema.DnsKeyDigest.TypeEnum]
	given fmtDnsKeysListResponse: Format[Schema.DnsKeysListResponse] = Json.format[Schema.DnsKeysListResponse]
	given fmtProject: Format[Schema.Project] = Json.format[Schema.Project]
	given fmtQuota: Format[Schema.Quota] = Json.format[Schema.Quota]
	given fmtDnsKeySpec: Format[Schema.DnsKeySpec] = Json.format[Schema.DnsKeySpec]
	given fmtDnsKeySpecKeyTypeEnum: Format[Schema.DnsKeySpec.KeyTypeEnum] = JsonEnumFormat[Schema.DnsKeySpec.KeyTypeEnum]
	given fmtDnsKeySpecAlgorithmEnum: Format[Schema.DnsKeySpec.AlgorithmEnum] = JsonEnumFormat[Schema.DnsKeySpec.AlgorithmEnum]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtOperationStatusEnum: Format[Schema.Operation.StatusEnum] = JsonEnumFormat[Schema.Operation.StatusEnum]
	given fmtOperationManagedZoneContext: Format[Schema.OperationManagedZoneContext] = Json.format[Schema.OperationManagedZoneContext]
	given fmtOperationDnsKeyContext: Format[Schema.OperationDnsKeyContext] = Json.format[Schema.OperationDnsKeyContext]
	given fmtManagedZone: Format[Schema.ManagedZone] = Json.format[Schema.ManagedZone]
	given fmtManagedZoneDnsSecConfig: Format[Schema.ManagedZoneDnsSecConfig] = Json.format[Schema.ManagedZoneDnsSecConfig]
	given fmtManagedZoneVisibilityEnum: Format[Schema.ManagedZone.VisibilityEnum] = JsonEnumFormat[Schema.ManagedZone.VisibilityEnum]
	given fmtManagedZonePrivateVisibilityConfig: Format[Schema.ManagedZonePrivateVisibilityConfig] = Json.format[Schema.ManagedZonePrivateVisibilityConfig]
	given fmtManagedZoneForwardingConfig: Format[Schema.ManagedZoneForwardingConfig] = Json.format[Schema.ManagedZoneForwardingConfig]
	given fmtManagedZonePeeringConfig: Format[Schema.ManagedZonePeeringConfig] = Json.format[Schema.ManagedZonePeeringConfig]
	given fmtManagedZoneReverseLookupConfig: Format[Schema.ManagedZoneReverseLookupConfig] = Json.format[Schema.ManagedZoneReverseLookupConfig]
	given fmtManagedZoneServiceDirectoryConfig: Format[Schema.ManagedZoneServiceDirectoryConfig] = Json.format[Schema.ManagedZoneServiceDirectoryConfig]
	given fmtManagedZoneCloudLoggingConfig: Format[Schema.ManagedZoneCloudLoggingConfig] = Json.format[Schema.ManagedZoneCloudLoggingConfig]
	given fmtManagedZoneDnsSecConfigStateEnum: Format[Schema.ManagedZoneDnsSecConfig.StateEnum] = JsonEnumFormat[Schema.ManagedZoneDnsSecConfig.StateEnum]
	given fmtManagedZoneDnsSecConfigNonExistenceEnum: Format[Schema.ManagedZoneDnsSecConfig.NonExistenceEnum] = JsonEnumFormat[Schema.ManagedZoneDnsSecConfig.NonExistenceEnum]
	given fmtManagedZonePrivateVisibilityConfigNetwork: Format[Schema.ManagedZonePrivateVisibilityConfigNetwork] = Json.format[Schema.ManagedZonePrivateVisibilityConfigNetwork]
	given fmtManagedZonePrivateVisibilityConfigGKECluster: Format[Schema.ManagedZonePrivateVisibilityConfigGKECluster] = Json.format[Schema.ManagedZonePrivateVisibilityConfigGKECluster]
	given fmtManagedZoneForwardingConfigNameServerTarget: Format[Schema.ManagedZoneForwardingConfigNameServerTarget] = Json.format[Schema.ManagedZoneForwardingConfigNameServerTarget]
	given fmtManagedZoneForwardingConfigNameServerTargetForwardingPathEnum: Format[Schema.ManagedZoneForwardingConfigNameServerTarget.ForwardingPathEnum] = JsonEnumFormat[Schema.ManagedZoneForwardingConfigNameServerTarget.ForwardingPathEnum]
	given fmtManagedZonePeeringConfigTargetNetwork: Format[Schema.ManagedZonePeeringConfigTargetNetwork] = Json.format[Schema.ManagedZonePeeringConfigTargetNetwork]
	given fmtManagedZoneServiceDirectoryConfigNamespace: Format[Schema.ManagedZoneServiceDirectoryConfigNamespace] = Json.format[Schema.ManagedZoneServiceDirectoryConfigNamespace]
	given fmtManagedZoneOperationsListResponse: Format[Schema.ManagedZoneOperationsListResponse] = Json.format[Schema.ManagedZoneOperationsListResponse]
	given fmtManagedZonesListResponse: Format[Schema.ManagedZonesListResponse] = Json.format[Schema.ManagedZonesListResponse]
	given fmtGoogleIamV1SetIamPolicyRequest: Format[Schema.GoogleIamV1SetIamPolicyRequest] = Json.format[Schema.GoogleIamV1SetIamPolicyRequest]
	given fmtGoogleIamV1Policy: Format[Schema.GoogleIamV1Policy] = Json.format[Schema.GoogleIamV1Policy]
	given fmtGoogleIamV1Binding: Format[Schema.GoogleIamV1Binding] = Json.format[Schema.GoogleIamV1Binding]
	given fmtGoogleIamV1AuditConfig: Format[Schema.GoogleIamV1AuditConfig] = Json.format[Schema.GoogleIamV1AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtGoogleIamV1AuditLogConfig: Format[Schema.GoogleIamV1AuditLogConfig] = Json.format[Schema.GoogleIamV1AuditLogConfig]
	given fmtGoogleIamV1AuditLogConfigLogTypeEnum: Format[Schema.GoogleIamV1AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.GoogleIamV1AuditLogConfig.LogTypeEnum]
	given fmtGoogleIamV1GetIamPolicyRequest: Format[Schema.GoogleIamV1GetIamPolicyRequest] = Json.format[Schema.GoogleIamV1GetIamPolicyRequest]
	given fmtGoogleIamV1GetPolicyOptions: Format[Schema.GoogleIamV1GetPolicyOptions] = Json.format[Schema.GoogleIamV1GetPolicyOptions]
	given fmtGoogleIamV1TestIamPermissionsRequest: Format[Schema.GoogleIamV1TestIamPermissionsRequest] = Json.format[Schema.GoogleIamV1TestIamPermissionsRequest]
	given fmtGoogleIamV1TestIamPermissionsResponse: Format[Schema.GoogleIamV1TestIamPermissionsResponse] = Json.format[Schema.GoogleIamV1TestIamPermissionsResponse]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtPolicyNetwork: Format[Schema.PolicyNetwork] = Json.format[Schema.PolicyNetwork]
	given fmtPolicyAlternativeNameServerConfig: Format[Schema.PolicyAlternativeNameServerConfig] = Json.format[Schema.PolicyAlternativeNameServerConfig]
	given fmtPolicyAlternativeNameServerConfigTargetNameServer: Format[Schema.PolicyAlternativeNameServerConfigTargetNameServer] = Json.format[Schema.PolicyAlternativeNameServerConfigTargetNameServer]
	given fmtPolicyAlternativeNameServerConfigTargetNameServerForwardingPathEnum: Format[Schema.PolicyAlternativeNameServerConfigTargetNameServer.ForwardingPathEnum] = JsonEnumFormat[Schema.PolicyAlternativeNameServerConfigTargetNameServer.ForwardingPathEnum]
	given fmtPoliciesListResponse: Format[Schema.PoliciesListResponse] = Json.format[Schema.PoliciesListResponse]
	given fmtPoliciesPatchResponse: Format[Schema.PoliciesPatchResponse] = Json.format[Schema.PoliciesPatchResponse]
	given fmtPoliciesUpdateResponse: Format[Schema.PoliciesUpdateResponse] = Json.format[Schema.PoliciesUpdateResponse]
	given fmtResponsePolicy: Format[Schema.ResponsePolicy] = Json.format[Schema.ResponsePolicy]
	given fmtResponsePolicyNetwork: Format[Schema.ResponsePolicyNetwork] = Json.format[Schema.ResponsePolicyNetwork]
	given fmtResponsePolicyGKECluster: Format[Schema.ResponsePolicyGKECluster] = Json.format[Schema.ResponsePolicyGKECluster]
	given fmtResponsePoliciesListResponse: Format[Schema.ResponsePoliciesListResponse] = Json.format[Schema.ResponsePoliciesListResponse]
	given fmtResponsePoliciesPatchResponse: Format[Schema.ResponsePoliciesPatchResponse] = Json.format[Schema.ResponsePoliciesPatchResponse]
	given fmtResponsePoliciesUpdateResponse: Format[Schema.ResponsePoliciesUpdateResponse] = Json.format[Schema.ResponsePoliciesUpdateResponse]
	given fmtResponsePolicyRule: Format[Schema.ResponsePolicyRule] = Json.format[Schema.ResponsePolicyRule]
	given fmtResponsePolicyRuleLocalData: Format[Schema.ResponsePolicyRuleLocalData] = Json.format[Schema.ResponsePolicyRuleLocalData]
	given fmtResponsePolicyRuleBehaviorEnum: Format[Schema.ResponsePolicyRule.BehaviorEnum] = JsonEnumFormat[Schema.ResponsePolicyRule.BehaviorEnum]
	given fmtResponsePolicyRulesListResponse: Format[Schema.ResponsePolicyRulesListResponse] = Json.format[Schema.ResponsePolicyRulesListResponse]
	given fmtResponsePolicyRulesPatchResponse: Format[Schema.ResponsePolicyRulesPatchResponse] = Json.format[Schema.ResponsePolicyRulesPatchResponse]
	given fmtResponsePolicyRulesUpdateResponse: Format[Schema.ResponsePolicyRulesUpdateResponse] = Json.format[Schema.ResponsePolicyRulesUpdateResponse]
}
