package com.boresjo.play.api.google.firebaseappcheck

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleFirebaseAppcheckV1BatchGetDeviceCheckConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetDeviceCheckConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetDeviceCheckConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1DeviceCheckConfig: Format[Schema.GoogleFirebaseAppcheckV1DeviceCheckConfig] = Json.format[Schema.GoogleFirebaseAppcheckV1DeviceCheckConfig]
	given fmtGoogleFirebaseAppcheckV1ListDebugTokensResponse: Format[Schema.GoogleFirebaseAppcheckV1ListDebugTokensResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1ListDebugTokensResponse]
	given fmtGoogleFirebaseAppcheckV1DebugToken: Format[Schema.GoogleFirebaseAppcheckV1DebugToken] = Json.format[Schema.GoogleFirebaseAppcheckV1DebugToken]
	given fmtGoogleFirebaseAppcheckV1ExchangeCustomTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeCustomTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeCustomTokenRequest]
	given fmtGoogleFirebaseAppcheckV1GenerateAppAttestChallengeResponse: Format[Schema.GoogleFirebaseAppcheckV1GenerateAppAttestChallengeResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1GenerateAppAttestChallengeResponse]
	given fmtGoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeRequest: Format[Schema.GoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeRequest]
	given fmtGoogleFirebaseAppcheckV1ExchangeDebugTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeDebugTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeDebugTokenRequest]
	given fmtGoogleProtobufEmpty: Format[Schema.GoogleProtobufEmpty] = Json.format[Schema.GoogleProtobufEmpty]
	given fmtGoogleFirebaseAppcheckV1ListServicesResponse: Format[Schema.GoogleFirebaseAppcheckV1ListServicesResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1ListServicesResponse]
	given fmtGoogleFirebaseAppcheckV1Service: Format[Schema.GoogleFirebaseAppcheckV1Service] = Json.format[Schema.GoogleFirebaseAppcheckV1Service]
	given fmtGoogleFirebaseAppcheckV1ExchangeRecaptchaV3TokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeRecaptchaV3TokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeRecaptchaV3TokenRequest]
	given fmtGoogleFirebaseAppcheckV1ListResourcePoliciesResponse: Format[Schema.GoogleFirebaseAppcheckV1ListResourcePoliciesResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1ListResourcePoliciesResponse]
	given fmtGoogleFirebaseAppcheckV1ResourcePolicy: Format[Schema.GoogleFirebaseAppcheckV1ResourcePolicy] = Json.format[Schema.GoogleFirebaseAppcheckV1ResourcePolicy]
	given fmtGoogleFirebaseAppcheckV1SafetyNetConfig: Format[Schema.GoogleFirebaseAppcheckV1SafetyNetConfig] = Json.format[Schema.GoogleFirebaseAppcheckV1SafetyNetConfig]
	given fmtGoogleFirebaseAppcheckV1ExchangeAppAttestAttestationRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAttestationRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAttestationRequest]
	given fmtGoogleFirebaseAppcheckV1PlayIntegrityConfig: Format[Schema.GoogleFirebaseAppcheckV1PlayIntegrityConfig] = Json.format[Schema.GoogleFirebaseAppcheckV1PlayIntegrityConfig]
	given fmtGoogleFirebaseAppcheckV1ResourcePolicyEnforcementModeEnum: Format[Schema.GoogleFirebaseAppcheckV1ResourcePolicy.EnforcementModeEnum] = JsonEnumFormat[Schema.GoogleFirebaseAppcheckV1ResourcePolicy.EnforcementModeEnum]
	given fmtGoogleFirebaseAppcheckV1BatchGetRecaptchaV3ConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetRecaptchaV3ConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetRecaptchaV3ConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1RecaptchaV3Config: Format[Schema.GoogleFirebaseAppcheckV1RecaptchaV3Config] = Json.format[Schema.GoogleFirebaseAppcheckV1RecaptchaV3Config]
	given fmtGoogleFirebaseAppcheckV1ExchangeRecaptchaEnterpriseTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeRecaptchaEnterpriseTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeRecaptchaEnterpriseTokenRequest]
	given fmtGoogleFirebaseAppcheckV1ExchangeDeviceCheckTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeDeviceCheckTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeDeviceCheckTokenRequest]
	given fmtGoogleFirebaseAppcheckV1PublicJwk: Format[Schema.GoogleFirebaseAppcheckV1PublicJwk] = Json.format[Schema.GoogleFirebaseAppcheckV1PublicJwk]
	given fmtGoogleFirebaseAppcheckV1BatchUpdateServicesRequest: Format[Schema.GoogleFirebaseAppcheckV1BatchUpdateServicesRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchUpdateServicesRequest]
	given fmtGoogleFirebaseAppcheckV1UpdateServiceRequest: Format[Schema.GoogleFirebaseAppcheckV1UpdateServiceRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1UpdateServiceRequest]
	given fmtGoogleFirebaseAppcheckV1ExchangeAppAttestAttestationResponse: Format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAttestationResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAttestationResponse]
	given fmtGoogleFirebaseAppcheckV1AppCheckToken: Format[Schema.GoogleFirebaseAppcheckV1AppCheckToken] = Json.format[Schema.GoogleFirebaseAppcheckV1AppCheckToken]
	given fmtGoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeResponse: Format[Schema.GoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1GeneratePlayIntegrityChallengeResponse]
	given fmtGoogleFirebaseAppcheckV1BatchGetPlayIntegrityConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetPlayIntegrityConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetPlayIntegrityConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1ExchangeSafetyNetTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeSafetyNetTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeSafetyNetTokenRequest]
	given fmtGoogleFirebaseAppcheckV1RecaptchaEnterpriseConfig: Format[Schema.GoogleFirebaseAppcheckV1RecaptchaEnterpriseConfig] = Json.format[Schema.GoogleFirebaseAppcheckV1RecaptchaEnterpriseConfig]
	given fmtGoogleFirebaseAppcheckV1BatchGetRecaptchaEnterpriseConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetRecaptchaEnterpriseConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetRecaptchaEnterpriseConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1PublicJwkSet: Format[Schema.GoogleFirebaseAppcheckV1PublicJwkSet] = Json.format[Schema.GoogleFirebaseAppcheckV1PublicJwkSet]
	given fmtGoogleFirebaseAppcheckV1AppAttestConfig: Format[Schema.GoogleFirebaseAppcheckV1AppAttestConfig] = Json.format[Schema.GoogleFirebaseAppcheckV1AppAttestConfig]
	given fmtGoogleFirebaseAppcheckV1BatchUpdateServicesResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchUpdateServicesResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchUpdateServicesResponse]
	given fmtGoogleFirebaseAppcheckV1ExchangeAppAttestAssertionRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAssertionRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangeAppAttestAssertionRequest]
	given fmtGoogleFirebaseAppcheckV1ServiceEnforcementModeEnum: Format[Schema.GoogleFirebaseAppcheckV1Service.EnforcementModeEnum] = JsonEnumFormat[Schema.GoogleFirebaseAppcheckV1Service.EnforcementModeEnum]
	given fmtGoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesResponse]
	given fmtGoogleFirebaseAppcheckV1BatchGetAppAttestConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetAppAttestConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetAppAttestConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1UpdateResourcePolicyRequest: Format[Schema.GoogleFirebaseAppcheckV1UpdateResourcePolicyRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1UpdateResourcePolicyRequest]
	given fmtGoogleFirebaseAppcheckV1ExchangePlayIntegrityTokenRequest: Format[Schema.GoogleFirebaseAppcheckV1ExchangePlayIntegrityTokenRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1ExchangePlayIntegrityTokenRequest]
	given fmtGoogleFirebaseAppcheckV1BatchGetSafetyNetConfigsResponse: Format[Schema.GoogleFirebaseAppcheckV1BatchGetSafetyNetConfigsResponse] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchGetSafetyNetConfigsResponse]
	given fmtGoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesRequest: Format[Schema.GoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1BatchUpdateResourcePoliciesRequest]
	given fmtGoogleFirebaseAppcheckV1GenerateAppAttestChallengeRequest: Format[Schema.GoogleFirebaseAppcheckV1GenerateAppAttestChallengeRequest] = Json.format[Schema.GoogleFirebaseAppcheckV1GenerateAppAttestChallengeRequest]
}
