package com.boresjo.play.api.google.mybusinessbusinessinformation

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListAttributeMetadataResponse: Format[Schema.ListAttributeMetadataResponse] = Json.format[Schema.ListAttributeMetadataResponse]
	given fmtAttributeMetadata: Format[Schema.AttributeMetadata] = Json.format[Schema.AttributeMetadata]
	given fmtAttributeMetadataValueTypeEnum: Format[Schema.AttributeMetadata.ValueTypeEnum] = JsonEnumFormat[Schema.AttributeMetadata.ValueTypeEnum]
	given fmtAttributeValueMetadata: Format[Schema.AttributeValueMetadata] = Json.format[Schema.AttributeValueMetadata]
	given fmtAttributes: Format[Schema.Attributes] = Json.format[Schema.Attributes]
	given fmtAttribute: Format[Schema.Attribute] = Json.format[Schema.Attribute]
	given fmtAttributeValueTypeEnum: Format[Schema.Attribute.ValueTypeEnum] = JsonEnumFormat[Schema.Attribute.ValueTypeEnum]
	given fmtRepeatedEnumAttributeValue: Format[Schema.RepeatedEnumAttributeValue] = Json.format[Schema.RepeatedEnumAttributeValue]
	given fmtUriAttributeValue: Format[Schema.UriAttributeValue] = Json.format[Schema.UriAttributeValue]
	given fmtListCategoriesResponse: Format[Schema.ListCategoriesResponse] = Json.format[Schema.ListCategoriesResponse]
	given fmtCategory: Format[Schema.Category] = Json.format[Schema.Category]
	given fmtServiceType: Format[Schema.ServiceType] = Json.format[Schema.ServiceType]
	given fmtMoreHoursType: Format[Schema.MoreHoursType] = Json.format[Schema.MoreHoursType]
	given fmtBatchGetCategoriesResponse: Format[Schema.BatchGetCategoriesResponse] = Json.format[Schema.BatchGetCategoriesResponse]
	given fmtChain: Format[Schema.Chain] = Json.format[Schema.Chain]
	given fmtChainName: Format[Schema.ChainName] = Json.format[Schema.ChainName]
	given fmtChainUri: Format[Schema.ChainUri] = Json.format[Schema.ChainUri]
	given fmtSearchChainsResponse: Format[Schema.SearchChainsResponse] = Json.format[Schema.SearchChainsResponse]
	given fmtSearchGoogleLocationsRequest: Format[Schema.SearchGoogleLocationsRequest] = Json.format[Schema.SearchGoogleLocationsRequest]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtPhoneNumbers: Format[Schema.PhoneNumbers] = Json.format[Schema.PhoneNumbers]
	given fmtCategories: Format[Schema.Categories] = Json.format[Schema.Categories]
	given fmtPostalAddress: Format[Schema.PostalAddress] = Json.format[Schema.PostalAddress]
	given fmtBusinessHours: Format[Schema.BusinessHours] = Json.format[Schema.BusinessHours]
	given fmtSpecialHours: Format[Schema.SpecialHours] = Json.format[Schema.SpecialHours]
	given fmtServiceAreaBusiness: Format[Schema.ServiceAreaBusiness] = Json.format[Schema.ServiceAreaBusiness]
	given fmtAdWordsLocationExtensions: Format[Schema.AdWordsLocationExtensions] = Json.format[Schema.AdWordsLocationExtensions]
	given fmtLatLng: Format[Schema.LatLng] = Json.format[Schema.LatLng]
	given fmtOpenInfo: Format[Schema.OpenInfo] = Json.format[Schema.OpenInfo]
	given fmtMetadata: Format[Schema.Metadata] = Json.format[Schema.Metadata]
	given fmtProfile: Format[Schema.Profile] = Json.format[Schema.Profile]
	given fmtRelationshipData: Format[Schema.RelationshipData] = Json.format[Schema.RelationshipData]
	given fmtMoreHours: Format[Schema.MoreHours] = Json.format[Schema.MoreHours]
	given fmtServiceItem: Format[Schema.ServiceItem] = Json.format[Schema.ServiceItem]
	given fmtTimePeriod: Format[Schema.TimePeriod] = Json.format[Schema.TimePeriod]
	given fmtTimePeriodOpenDayEnum: Format[Schema.TimePeriod.OpenDayEnum] = JsonEnumFormat[Schema.TimePeriod.OpenDayEnum]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtTimePeriodCloseDayEnum: Format[Schema.TimePeriod.CloseDayEnum] = JsonEnumFormat[Schema.TimePeriod.CloseDayEnum]
	given fmtSpecialHourPeriod: Format[Schema.SpecialHourPeriod] = Json.format[Schema.SpecialHourPeriod]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
	given fmtServiceAreaBusinessBusinessTypeEnum: Format[Schema.ServiceAreaBusiness.BusinessTypeEnum] = JsonEnumFormat[Schema.ServiceAreaBusiness.BusinessTypeEnum]
	given fmtPlaces: Format[Schema.Places] = Json.format[Schema.Places]
	given fmtPlaceInfo: Format[Schema.PlaceInfo] = Json.format[Schema.PlaceInfo]
	given fmtOpenInfoStatusEnum: Format[Schema.OpenInfo.StatusEnum] = JsonEnumFormat[Schema.OpenInfo.StatusEnum]
	given fmtRelevantLocation: Format[Schema.RelevantLocation] = Json.format[Schema.RelevantLocation]
	given fmtRelevantLocationRelationTypeEnum: Format[Schema.RelevantLocation.RelationTypeEnum] = JsonEnumFormat[Schema.RelevantLocation.RelationTypeEnum]
	given fmtStructuredServiceItem: Format[Schema.StructuredServiceItem] = Json.format[Schema.StructuredServiceItem]
	given fmtFreeFormServiceItem: Format[Schema.FreeFormServiceItem] = Json.format[Schema.FreeFormServiceItem]
	given fmtMoney: Format[Schema.Money] = Json.format[Schema.Money]
	given fmtLabel: Format[Schema.Label] = Json.format[Schema.Label]
	given fmtSearchGoogleLocationsResponse: Format[Schema.SearchGoogleLocationsResponse] = Json.format[Schema.SearchGoogleLocationsResponse]
	given fmtGoogleLocation: Format[Schema.GoogleLocation] = Json.format[Schema.GoogleLocation]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtGoogleUpdatedLocation: Format[Schema.GoogleUpdatedLocation] = Json.format[Schema.GoogleUpdatedLocation]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
}
