package com.boresjo.play.api.google.cloudidentity

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceOwnerTypeEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device.OwnerTypeEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1Device.OwnerTypeEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device.OwnerTypeEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceDeviceTypeEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device.DeviceTypeEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1Device.DeviceTypeEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device.DeviceTypeEnum) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceEncryptionStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device.EncryptionStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1Device.EncryptionStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device.EncryptionStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1AndroidAttributes: Conversion[Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes, Option[Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceManagementStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device.ManagementStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1Device.ManagementStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device.ManagementStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceCompromisedStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device.CompromisedStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1Device.CompromisedStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device.CompromisedStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1EndpointVerificationSpecificAttributes: Conversion[Schema.GoogleAppsCloudidentityDevicesV1EndpointVerificationSpecificAttributes, Option[Schema.GoogleAppsCloudidentityDevicesV1EndpointVerificationSpecificAttributes]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1EndpointVerificationSpecificAttributes) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1AndroidAttributesOwnershipPrivilegeEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes.OwnershipPrivilegeEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes.OwnershipPrivilegeEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1AndroidAttributes.OwnershipPrivilegeEnum) => Option(fun)
		given putListSchemaGoogleAppsCloudidentityDevicesV1CertificateAttributes: Conversion[List[Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes], Option[List[Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes]]] = (fun: List[Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes]) => Option(fun)
		given putListSchemaGoogleAppsCloudidentityDevicesV1BrowserAttributes: Conversion[List[Schema.GoogleAppsCloudidentityDevicesV1BrowserAttributes], Option[List[Schema.GoogleAppsCloudidentityDevicesV1BrowserAttributes]]] = (fun: List[Schema.GoogleAppsCloudidentityDevicesV1BrowserAttributes]) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1CertificateAttributesValidationStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes.ValidationStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes.ValidationStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1CertificateAttributes.ValidationStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1CertificateTemplate: Conversion[Schema.GoogleAppsCloudidentityDevicesV1CertificateTemplate, Option[Schema.GoogleAppsCloudidentityDevicesV1CertificateTemplate]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1CertificateTemplate) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1BrowserInfo: Conversion[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo, Option[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1BrowserInfoBrowserManagementStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.BrowserManagementStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.BrowserManagementStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.BrowserManagementStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1BrowserInfoSafeBrowsingProtectionLevelEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.SafeBrowsingProtectionLevelEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.SafeBrowsingProtectionLevelEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.SafeBrowsingProtectionLevelEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1BrowserInfoPasswordProtectionWarningTriggerEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.PasswordProtectionWarningTriggerEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.PasswordProtectionWarningTriggerEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1BrowserInfo.PasswordProtectionWarningTriggerEnum) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putListSchemaGoogleAppsCloudidentityDevicesV1Device: Conversion[List[Schema.GoogleAppsCloudidentityDevicesV1Device], Option[List[Schema.GoogleAppsCloudidentityDevicesV1Device]]] = (fun: List[Schema.GoogleAppsCloudidentityDevicesV1Device]) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceUserManagementStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.ManagementStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.ManagementStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.ManagementStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceUserCompromisedStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.CompromisedStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.CompromisedStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.CompromisedStateEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceUserPasswordStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.PasswordStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.PasswordStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1DeviceUser.PasswordStateEnum) => Option(fun)
		given putListSchemaGoogleAppsCloudidentityDevicesV1DeviceUser: Conversion[List[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser], Option[List[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser]]] = (fun: List[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser]) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1ClientStateHealthScoreEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1ClientState.HealthScoreEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1ClientState.HealthScoreEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1ClientState.HealthScoreEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1ClientStateManagedEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1ClientState.ManagedEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1ClientState.ManagedEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1ClientState.ManagedEnum) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1ClientStateComplianceStateEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1ClientState.ComplianceStateEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1ClientState.ComplianceStateEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1ClientState.ComplianceStateEnum) => Option(fun)
		given putMapStringSchemaGoogleAppsCloudidentityDevicesV1CustomAttributeValue: Conversion[Map[String, Schema.GoogleAppsCloudidentityDevicesV1CustomAttributeValue], Option[Map[String, Schema.GoogleAppsCloudidentityDevicesV1CustomAttributeValue]]] = (fun: Map[String, Schema.GoogleAppsCloudidentityDevicesV1CustomAttributeValue]) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1ClientStateOwnerTypeEnum: Conversion[Schema.GoogleAppsCloudidentityDevicesV1ClientState.OwnerTypeEnum, Option[Schema.GoogleAppsCloudidentityDevicesV1ClientState.OwnerTypeEnum]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1ClientState.OwnerTypeEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putListSchemaGoogleAppsCloudidentityDevicesV1ClientState: Conversion[List[Schema.GoogleAppsCloudidentityDevicesV1ClientState], Option[List[Schema.GoogleAppsCloudidentityDevicesV1ClientState]]] = (fun: List[Schema.GoogleAppsCloudidentityDevicesV1ClientState]) => Option(fun)
		given putSchemaEntityKey: Conversion[Schema.EntityKey, Option[Schema.EntityKey]] = (fun: Schema.EntityKey) => Option(fun)
		given putListSchemaEntityKey: Conversion[List[Schema.EntityKey], Option[List[Schema.EntityKey]]] = (fun: List[Schema.EntityKey]) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putSchemaDynamicGroupMetadata: Conversion[Schema.DynamicGroupMetadata, Option[Schema.DynamicGroupMetadata]] = (fun: Schema.DynamicGroupMetadata) => Option(fun)
		given putListSchemaDynamicGroupQuery: Conversion[List[Schema.DynamicGroupQuery], Option[List[Schema.DynamicGroupQuery]]] = (fun: List[Schema.DynamicGroupQuery]) => Option(fun)
		given putSchemaDynamicGroupStatus: Conversion[Schema.DynamicGroupStatus, Option[Schema.DynamicGroupStatus]] = (fun: Schema.DynamicGroupStatus) => Option(fun)
		given putSchemaDynamicGroupQueryResourceTypeEnum: Conversion[Schema.DynamicGroupQuery.ResourceTypeEnum, Option[Schema.DynamicGroupQuery.ResourceTypeEnum]] = (fun: Schema.DynamicGroupQuery.ResourceTypeEnum) => Option(fun)
		given putSchemaDynamicGroupStatusStatusEnum: Conversion[Schema.DynamicGroupStatus.StatusEnum, Option[Schema.DynamicGroupStatus.StatusEnum]] = (fun: Schema.DynamicGroupStatus.StatusEnum) => Option(fun)
		given putSchemaMemberRestriction: Conversion[Schema.MemberRestriction, Option[Schema.MemberRestriction]] = (fun: Schema.MemberRestriction) => Option(fun)
		given putSchemaRestrictionEvaluation: Conversion[Schema.RestrictionEvaluation, Option[Schema.RestrictionEvaluation]] = (fun: Schema.RestrictionEvaluation) => Option(fun)
		given putSchemaRestrictionEvaluationStateEnum: Conversion[Schema.RestrictionEvaluation.StateEnum, Option[Schema.RestrictionEvaluation.StateEnum]] = (fun: Schema.RestrictionEvaluation.StateEnum) => Option(fun)
		given putListSchemaGroup: Conversion[List[Schema.Group], Option[List[Schema.Group]]] = (fun: List[Schema.Group]) => Option(fun)
		given putListSchemaMembershipRole: Conversion[List[Schema.MembershipRole], Option[List[Schema.MembershipRole]]] = (fun: List[Schema.MembershipRole]) => Option(fun)
		given putSchemaMembershipTypeEnum: Conversion[Schema.Membership.TypeEnum, Option[Schema.Membership.TypeEnum]] = (fun: Schema.Membership.TypeEnum) => Option(fun)
		given putSchemaMembershipDeliverySettingEnum: Conversion[Schema.Membership.DeliverySettingEnum, Option[Schema.Membership.DeliverySettingEnum]] = (fun: Schema.Membership.DeliverySettingEnum) => Option(fun)
		given putSchemaExpiryDetail: Conversion[Schema.ExpiryDetail, Option[Schema.ExpiryDetail]] = (fun: Schema.ExpiryDetail) => Option(fun)
		given putSchemaRestrictionEvaluations: Conversion[Schema.RestrictionEvaluations, Option[Schema.RestrictionEvaluations]] = (fun: Schema.RestrictionEvaluations) => Option(fun)
		given putSchemaMembershipRoleRestrictionEvaluation: Conversion[Schema.MembershipRoleRestrictionEvaluation, Option[Schema.MembershipRoleRestrictionEvaluation]] = (fun: Schema.MembershipRoleRestrictionEvaluation) => Option(fun)
		given putSchemaMembershipRoleRestrictionEvaluationStateEnum: Conversion[Schema.MembershipRoleRestrictionEvaluation.StateEnum, Option[Schema.MembershipRoleRestrictionEvaluation.StateEnum]] = (fun: Schema.MembershipRoleRestrictionEvaluation.StateEnum) => Option(fun)
		given putListSchemaMembership: Conversion[List[Schema.Membership], Option[List[Schema.Membership]]] = (fun: List[Schema.Membership]) => Option(fun)
		given putListSchemaUpdateMembershipRolesParams: Conversion[List[Schema.UpdateMembershipRolesParams], Option[List[Schema.UpdateMembershipRolesParams]]] = (fun: List[Schema.UpdateMembershipRolesParams]) => Option(fun)
		given putSchemaMembershipRole: Conversion[Schema.MembershipRole, Option[Schema.MembershipRole]] = (fun: Schema.MembershipRole) => Option(fun)
		given putSchemaMembership: Conversion[Schema.Membership, Option[Schema.Membership]] = (fun: Schema.Membership) => Option(fun)
		given putListSchemaMemberRelation: Conversion[List[Schema.MemberRelation], Option[List[Schema.MemberRelation]]] = (fun: List[Schema.MemberRelation]) => Option(fun)
		given putListSchemaTransitiveMembershipRole: Conversion[List[Schema.TransitiveMembershipRole], Option[List[Schema.TransitiveMembershipRole]]] = (fun: List[Schema.TransitiveMembershipRole]) => Option(fun)
		given putSchemaMemberRelationRelationTypeEnum: Conversion[Schema.MemberRelation.RelationTypeEnum, Option[Schema.MemberRelation.RelationTypeEnum]] = (fun: Schema.MemberRelation.RelationTypeEnum) => Option(fun)
		given putListSchemaGroupRelation: Conversion[List[Schema.GroupRelation], Option[List[Schema.GroupRelation]]] = (fun: List[Schema.GroupRelation]) => Option(fun)
		given putSchemaGroupRelationRelationTypeEnum: Conversion[Schema.GroupRelation.RelationTypeEnum, Option[Schema.GroupRelation.RelationTypeEnum]] = (fun: Schema.GroupRelation.RelationTypeEnum) => Option(fun)
		given putListSchemaMembershipRelation: Conversion[List[Schema.MembershipRelation], Option[List[Schema.MembershipRelation]]] = (fun: List[Schema.MembershipRelation]) => Option(fun)
		given putSchemaSamlIdpConfig: Conversion[Schema.SamlIdpConfig, Option[Schema.SamlIdpConfig]] = (fun: Schema.SamlIdpConfig) => Option(fun)
		given putSchemaSamlSpConfig: Conversion[Schema.SamlSpConfig, Option[Schema.SamlSpConfig]] = (fun: Schema.SamlSpConfig) => Option(fun)
		given putListSchemaInboundSamlSsoProfile: Conversion[List[Schema.InboundSamlSsoProfile], Option[List[Schema.InboundSamlSsoProfile]]] = (fun: List[Schema.InboundSamlSsoProfile]) => Option(fun)
		given putSchemaRsaPublicKeyInfo: Conversion[Schema.RsaPublicKeyInfo, Option[Schema.RsaPublicKeyInfo]] = (fun: Schema.RsaPublicKeyInfo) => Option(fun)
		given putSchemaDsaPublicKeyInfo: Conversion[Schema.DsaPublicKeyInfo, Option[Schema.DsaPublicKeyInfo]] = (fun: Schema.DsaPublicKeyInfo) => Option(fun)
		given putListSchemaIdpCredential: Conversion[List[Schema.IdpCredential], Option[List[Schema.IdpCredential]]] = (fun: List[Schema.IdpCredential]) => Option(fun)
		given putSchemaInboundSsoAssignmentSsoModeEnum: Conversion[Schema.InboundSsoAssignment.SsoModeEnum, Option[Schema.InboundSsoAssignment.SsoModeEnum]] = (fun: Schema.InboundSsoAssignment.SsoModeEnum) => Option(fun)
		given putSchemaSamlSsoInfo: Conversion[Schema.SamlSsoInfo, Option[Schema.SamlSsoInfo]] = (fun: Schema.SamlSsoInfo) => Option(fun)
		given putSchemaSignInBehavior: Conversion[Schema.SignInBehavior, Option[Schema.SignInBehavior]] = (fun: Schema.SignInBehavior) => Option(fun)
		given putSchemaSignInBehaviorRedirectConditionEnum: Conversion[Schema.SignInBehavior.RedirectConditionEnum, Option[Schema.SignInBehavior.RedirectConditionEnum]] = (fun: Schema.SignInBehavior.RedirectConditionEnum) => Option(fun)
		given putListSchemaInboundSsoAssignment: Conversion[List[Schema.InboundSsoAssignment], Option[List[Schema.InboundSsoAssignment]]] = (fun: List[Schema.InboundSsoAssignment]) => Option(fun)
		given putSchemaUserInvitationStateEnum: Conversion[Schema.UserInvitation.StateEnum, Option[Schema.UserInvitation.StateEnum]] = (fun: Schema.UserInvitation.StateEnum) => Option(fun)
		given putListSchemaUserInvitation: Conversion[List[Schema.UserInvitation], Option[List[Schema.UserInvitation]]] = (fun: List[Schema.UserInvitation]) => Option(fun)
		given putListSchemaMembershipAdjacencyList: Conversion[List[Schema.MembershipAdjacencyList], Option[List[Schema.MembershipAdjacencyList]]] = (fun: List[Schema.MembershipAdjacencyList]) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1DeviceUser: Conversion[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser, Option[Schema.GoogleAppsCloudidentityDevicesV1DeviceUser]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1DeviceUser) => Option(fun)
		given putSchemaGoogleAppsCloudidentityDevicesV1Device: Conversion[Schema.GoogleAppsCloudidentityDevicesV1Device, Option[Schema.GoogleAppsCloudidentityDevicesV1Device]] = (fun: Schema.GoogleAppsCloudidentityDevicesV1Device) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
