package com.boresjo.play.api.google.batch

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtJob: Format[Schema.Job] = Json.format[Schema.Job]
	given fmtTaskGroup: Format[Schema.TaskGroup] = Json.format[Schema.TaskGroup]
	given fmtAllocationPolicy: Format[Schema.AllocationPolicy] = Json.format[Schema.AllocationPolicy]
	given fmtJobStatus: Format[Schema.JobStatus] = Json.format[Schema.JobStatus]
	given fmtLogsPolicy: Format[Schema.LogsPolicy] = Json.format[Schema.LogsPolicy]
	given fmtJobNotification: Format[Schema.JobNotification] = Json.format[Schema.JobNotification]
	given fmtTaskSpec: Format[Schema.TaskSpec] = Json.format[Schema.TaskSpec]
	given fmtTaskGroupSchedulingPolicyEnum: Format[Schema.TaskGroup.SchedulingPolicyEnum] = JsonEnumFormat[Schema.TaskGroup.SchedulingPolicyEnum]
	given fmtEnvironment: Format[Schema.Environment] = Json.format[Schema.Environment]
	given fmtRunnable: Format[Schema.Runnable] = Json.format[Schema.Runnable]
	given fmtComputeResource: Format[Schema.ComputeResource] = Json.format[Schema.ComputeResource]
	given fmtLifecyclePolicy: Format[Schema.LifecyclePolicy] = Json.format[Schema.LifecyclePolicy]
	given fmtVolume: Format[Schema.Volume] = Json.format[Schema.Volume]
	given fmtContainer: Format[Schema.Container] = Json.format[Schema.Container]
	given fmtScript: Format[Schema.Script] = Json.format[Schema.Script]
	given fmtBarrier: Format[Schema.Barrier] = Json.format[Schema.Barrier]
	given fmtKMSEnvMap: Format[Schema.KMSEnvMap] = Json.format[Schema.KMSEnvMap]
	given fmtLifecyclePolicyActionEnum: Format[Schema.LifecyclePolicy.ActionEnum] = JsonEnumFormat[Schema.LifecyclePolicy.ActionEnum]
	given fmtActionCondition: Format[Schema.ActionCondition] = Json.format[Schema.ActionCondition]
	given fmtNFS: Format[Schema.NFS] = Json.format[Schema.NFS]
	given fmtGCS: Format[Schema.GCS] = Json.format[Schema.GCS]
	given fmtLocationPolicy: Format[Schema.LocationPolicy] = Json.format[Schema.LocationPolicy]
	given fmtInstancePolicyOrTemplate: Format[Schema.InstancePolicyOrTemplate] = Json.format[Schema.InstancePolicyOrTemplate]
	given fmtServiceAccount: Format[Schema.ServiceAccount] = Json.format[Schema.ServiceAccount]
	given fmtNetworkPolicy: Format[Schema.NetworkPolicy] = Json.format[Schema.NetworkPolicy]
	given fmtPlacementPolicy: Format[Schema.PlacementPolicy] = Json.format[Schema.PlacementPolicy]
	given fmtInstancePolicy: Format[Schema.InstancePolicy] = Json.format[Schema.InstancePolicy]
	given fmtInstancePolicyProvisioningModelEnum: Format[Schema.InstancePolicy.ProvisioningModelEnum] = JsonEnumFormat[Schema.InstancePolicy.ProvisioningModelEnum]
	given fmtAccelerator: Format[Schema.Accelerator] = Json.format[Schema.Accelerator]
	given fmtDisk: Format[Schema.Disk] = Json.format[Schema.Disk]
	given fmtAttachedDisk: Format[Schema.AttachedDisk] = Json.format[Schema.AttachedDisk]
	given fmtNetworkInterface: Format[Schema.NetworkInterface] = Json.format[Schema.NetworkInterface]
	given fmtJobStatusStateEnum: Format[Schema.JobStatus.StateEnum] = JsonEnumFormat[Schema.JobStatus.StateEnum]
	given fmtStatusEvent: Format[Schema.StatusEvent] = Json.format[Schema.StatusEvent]
	given fmtTaskGroupStatus: Format[Schema.TaskGroupStatus] = Json.format[Schema.TaskGroupStatus]
	given fmtTaskExecution: Format[Schema.TaskExecution] = Json.format[Schema.TaskExecution]
	given fmtStatusEventTaskStateEnum: Format[Schema.StatusEvent.TaskStateEnum] = JsonEnumFormat[Schema.StatusEvent.TaskStateEnum]
	given fmtInstanceStatus: Format[Schema.InstanceStatus] = Json.format[Schema.InstanceStatus]
	given fmtInstanceStatusProvisioningModelEnum: Format[Schema.InstanceStatus.ProvisioningModelEnum] = JsonEnumFormat[Schema.InstanceStatus.ProvisioningModelEnum]
	given fmtLogsPolicyDestinationEnum: Format[Schema.LogsPolicy.DestinationEnum] = JsonEnumFormat[Schema.LogsPolicy.DestinationEnum]
	given fmtCloudLoggingOption: Format[Schema.CloudLoggingOption] = Json.format[Schema.CloudLoggingOption]
	given fmtMessage: Format[Schema.Message] = Json.format[Schema.Message]
	given fmtMessageTypeEnum: Format[Schema.Message.TypeEnum] = JsonEnumFormat[Schema.Message.TypeEnum]
	given fmtMessageNewJobStateEnum: Format[Schema.Message.NewJobStateEnum] = JsonEnumFormat[Schema.Message.NewJobStateEnum]
	given fmtMessageNewTaskStateEnum: Format[Schema.Message.NewTaskStateEnum] = JsonEnumFormat[Schema.Message.NewTaskStateEnum]
	given fmtListJobsResponse: Format[Schema.ListJobsResponse] = Json.format[Schema.ListJobsResponse]
	given fmtTask: Format[Schema.Task] = Json.format[Schema.Task]
	given fmtTaskStatus: Format[Schema.TaskStatus] = Json.format[Schema.TaskStatus]
	given fmtTaskStatusStateEnum: Format[Schema.TaskStatus.StateEnum] = JsonEnumFormat[Schema.TaskStatus.StateEnum]
	given fmtListTasksResponse: Format[Schema.ListTasksResponse] = Json.format[Schema.ListTasksResponse]
	given fmtReportAgentStateRequest: Format[Schema.ReportAgentStateRequest] = Json.format[Schema.ReportAgentStateRequest]
	given fmtAgentMetadata: Format[Schema.AgentMetadata] = Json.format[Schema.AgentMetadata]
	given fmtAgentInfo: Format[Schema.AgentInfo] = Json.format[Schema.AgentInfo]
	given fmtAgentTimingInfo: Format[Schema.AgentTimingInfo] = Json.format[Schema.AgentTimingInfo]
	given fmtAgentInfoStateEnum: Format[Schema.AgentInfo.StateEnum] = JsonEnumFormat[Schema.AgentInfo.StateEnum]
	given fmtAgentTaskInfo: Format[Schema.AgentTaskInfo] = Json.format[Schema.AgentTaskInfo]
	given fmtReportAgentStateResponse: Format[Schema.ReportAgentStateResponse] = Json.format[Schema.ReportAgentStateResponse]
	given fmtAgentTask: Format[Schema.AgentTask] = Json.format[Schema.AgentTask]
	given fmtAgentTaskSpec: Format[Schema.AgentTaskSpec] = Json.format[Schema.AgentTaskSpec]
	given fmtAgentTaskIntendedStateEnum: Format[Schema.AgentTask.IntendedStateEnum] = JsonEnumFormat[Schema.AgentTask.IntendedStateEnum]
	given fmtAgentTaskTaskSourceEnum: Format[Schema.AgentTask.TaskSourceEnum] = JsonEnumFormat[Schema.AgentTask.TaskSourceEnum]
	given fmtAgentTaskRunnable: Format[Schema.AgentTaskRunnable] = Json.format[Schema.AgentTaskRunnable]
	given fmtAgentEnvironment: Format[Schema.AgentEnvironment] = Json.format[Schema.AgentEnvironment]
	given fmtAgentTaskUserAccount: Format[Schema.AgentTaskUserAccount] = Json.format[Schema.AgentTaskUserAccount]
	given fmtAgentTaskLoggingOption: Format[Schema.AgentTaskLoggingOption] = Json.format[Schema.AgentTaskLoggingOption]
	given fmtAgentContainer: Format[Schema.AgentContainer] = Json.format[Schema.AgentContainer]
	given fmtAgentScript: Format[Schema.AgentScript] = Json.format[Schema.AgentScript]
	given fmtAgentKMSEnvMap: Format[Schema.AgentKMSEnvMap] = Json.format[Schema.AgentKMSEnvMap]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
