package com.boresjo.play.api.google.playdeveloperreporting

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putSchemaGooglePlayDeveloperReportingV1beta1MetricsRowAggregationPeriodEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1MetricsRow.AggregationPeriodEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1MetricsRow.AggregationPeriodEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1MetricsRow.AggregationPeriodEnum) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1DimensionValue: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1DimensionValue], Option[List[Schema.GooglePlayDeveloperReportingV1beta1DimensionValue]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1DimensionValue]) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1MetricValue: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1MetricValue], Option[List[Schema.GooglePlayDeveloperReportingV1beta1MetricValue]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1MetricValue]) => Option(fun)
		given putSchemaGoogleTypeDateTime: Conversion[Schema.GoogleTypeDateTime, Option[Schema.GoogleTypeDateTime]] = (fun: Schema.GoogleTypeDateTime) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1MetricsRow: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1MetricsRow], Option[List[Schema.GooglePlayDeveloperReportingV1beta1MetricsRow]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1MetricsRow]) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1FreshnessInfo: Conversion[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfo, Option[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfo]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfo) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1Release: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1Release], Option[List[Schema.GooglePlayDeveloperReportingV1beta1Release]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1Release]) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1App: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1App], Option[List[Schema.GooglePlayDeveloperReportingV1beta1App]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1App]) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1ErrorIssue: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue], Option[List[Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue]) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1DeviceId: Conversion[Schema.GooglePlayDeveloperReportingV1beta1DeviceId, Option[Schema.GooglePlayDeveloperReportingV1beta1DeviceId]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1DeviceId) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1TimelineSpecAggregationPeriodEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec.AggregationPeriodEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec.AggregationPeriodEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec.AggregationPeriodEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QueryCrashRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1TimelineSpec: Conversion[Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec, Option[Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1TimelineSpec) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QuerySlowStartRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QueryStuckBackgroundWakelockRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1ErrorReport: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1ErrorReport], Option[List[Schema.GooglePlayDeveloperReportingV1beta1ErrorReport]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1ErrorReport]) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1MetricValue: Conversion[Schema.GooglePlayDeveloperReportingV1beta1MetricValue, Option[Schema.GooglePlayDeveloperReportingV1beta1MetricValue]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1MetricValue) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QueryExcessiveWakeupRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1Track: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1Track], Option[List[Schema.GooglePlayDeveloperReportingV1beta1Track]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1Track]) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1Anomaly: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1Anomaly], Option[List[Schema.GooglePlayDeveloperReportingV1beta1Anomaly]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1Anomaly]) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QueryAnrRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1OsVersion: Conversion[Schema.GooglePlayDeveloperReportingV1beta1OsVersion, Option[Schema.GooglePlayDeveloperReportingV1beta1OsVersion]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1OsVersion) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1AppVersion: Conversion[Schema.GooglePlayDeveloperReportingV1beta1AppVersion, Option[Schema.GooglePlayDeveloperReportingV1beta1AppVersion]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1AppVersion) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1IssueAnnotation: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1IssueAnnotation], Option[List[Schema.GooglePlayDeveloperReportingV1beta1IssueAnnotation]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1IssueAnnotation]) => Option(fun)
		given putSchemaGoogleTypeDecimal: Conversion[Schema.GoogleTypeDecimal, Option[Schema.GoogleTypeDecimal]] = (fun: Schema.GoogleTypeDecimal) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1ErrorIssueTypeEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue.TypeEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue.TypeEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1ErrorIssue.TypeEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1DecimalConfidenceInterval: Conversion[Schema.GooglePlayDeveloperReportingV1beta1DecimalConfidenceInterval, Option[Schema.GooglePlayDeveloperReportingV1beta1DecimalConfidenceInterval]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1DecimalConfidenceInterval) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequestUserCohortEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequest.UserCohortEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequest.UserCohortEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1QuerySlowRenderingRateMetricSetRequest.UserCohortEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1FreshnessInfoFreshnessAggregationPeriodEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness.AggregationPeriodEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness.AggregationPeriodEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness.AggregationPeriodEnum) => Option(fun)
		given putSchemaGoogleTypeTimeZone: Conversion[Schema.GoogleTypeTimeZone, Option[Schema.GoogleTypeTimeZone]] = (fun: Schema.GoogleTypeTimeZone) => Option(fun)
		given putListSchemaGooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness: Conversion[List[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness], Option[List[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness]]] = (fun: List[Schema.GooglePlayDeveloperReportingV1beta1FreshnessInfoFreshness]) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1ErrorReportTypeEnum: Conversion[Schema.GooglePlayDeveloperReportingV1beta1ErrorReport.TypeEnum, Option[Schema.GooglePlayDeveloperReportingV1beta1ErrorReport.TypeEnum]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1ErrorReport.TypeEnum) => Option(fun)
		given putSchemaGooglePlayDeveloperReportingV1beta1DeviceModelSummary: Conversion[Schema.GooglePlayDeveloperReportingV1beta1DeviceModelSummary, Option[Schema.GooglePlayDeveloperReportingV1beta1DeviceModelSummary]] = (fun: Schema.GooglePlayDeveloperReportingV1beta1DeviceModelSummary) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
