package com.boresjo.play.api.google.eventarc

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleLongrunningListOperationsResponse: Format[Schema.GoogleLongrunningListOperationsResponse] = Json.format[Schema.GoogleLongrunningListOperationsResponse]
	given fmtGoogleLongrunningOperation: Format[Schema.GoogleLongrunningOperation] = Json.format[Schema.GoogleLongrunningOperation]
	given fmtGoogleRpcStatus: Format[Schema.GoogleRpcStatus] = Json.format[Schema.GoogleRpcStatus]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtGoogleLongrunningCancelOperationRequest: Format[Schema.GoogleLongrunningCancelOperationRequest] = Json.format[Schema.GoogleLongrunningCancelOperationRequest]
	given fmtTrigger: Format[Schema.Trigger] = Json.format[Schema.Trigger]
	given fmtEventFilter: Format[Schema.EventFilter] = Json.format[Schema.EventFilter]
	given fmtDestination: Format[Schema.Destination] = Json.format[Schema.Destination]
	given fmtTransport: Format[Schema.Transport] = Json.format[Schema.Transport]
	given fmtStateCondition: Format[Schema.StateCondition] = Json.format[Schema.StateCondition]
	given fmtCloudRun: Format[Schema.CloudRun] = Json.format[Schema.CloudRun]
	given fmtGKE: Format[Schema.GKE] = Json.format[Schema.GKE]
	given fmtHttpEndpoint: Format[Schema.HttpEndpoint] = Json.format[Schema.HttpEndpoint]
	given fmtNetworkConfig: Format[Schema.NetworkConfig] = Json.format[Schema.NetworkConfig]
	given fmtPubsub: Format[Schema.Pubsub] = Json.format[Schema.Pubsub]
	given fmtStateConditionCodeEnum: Format[Schema.StateCondition.CodeEnum] = JsonEnumFormat[Schema.StateCondition.CodeEnum]
	given fmtListTriggersResponse: Format[Schema.ListTriggersResponse] = Json.format[Schema.ListTriggersResponse]
	given fmtChannel: Format[Schema.Channel] = Json.format[Schema.Channel]
	given fmtChannelStateEnum: Format[Schema.Channel.StateEnum] = JsonEnumFormat[Schema.Channel.StateEnum]
	given fmtListChannelsResponse: Format[Schema.ListChannelsResponse] = Json.format[Schema.ListChannelsResponse]
	given fmtProvider: Format[Schema.Provider] = Json.format[Schema.Provider]
	given fmtEventType: Format[Schema.EventType] = Json.format[Schema.EventType]
	given fmtFilteringAttribute: Format[Schema.FilteringAttribute] = Json.format[Schema.FilteringAttribute]
	given fmtListProvidersResponse: Format[Schema.ListProvidersResponse] = Json.format[Schema.ListProvidersResponse]
	given fmtChannelConnection: Format[Schema.ChannelConnection] = Json.format[Schema.ChannelConnection]
	given fmtListChannelConnectionsResponse: Format[Schema.ListChannelConnectionsResponse] = Json.format[Schema.ListChannelConnectionsResponse]
	given fmtGoogleChannelConfig: Format[Schema.GoogleChannelConfig] = Json.format[Schema.GoogleChannelConfig]
	given fmtMessageBus: Format[Schema.MessageBus] = Json.format[Schema.MessageBus]
	given fmtLoggingConfig: Format[Schema.LoggingConfig] = Json.format[Schema.LoggingConfig]
	given fmtLoggingConfigLogSeverityEnum: Format[Schema.LoggingConfig.LogSeverityEnum] = JsonEnumFormat[Schema.LoggingConfig.LogSeverityEnum]
	given fmtListMessageBusesResponse: Format[Schema.ListMessageBusesResponse] = Json.format[Schema.ListMessageBusesResponse]
	given fmtListMessageBusEnrollmentsResponse: Format[Schema.ListMessageBusEnrollmentsResponse] = Json.format[Schema.ListMessageBusEnrollmentsResponse]
	given fmtEnrollment: Format[Schema.Enrollment] = Json.format[Schema.Enrollment]
	given fmtListEnrollmentsResponse: Format[Schema.ListEnrollmentsResponse] = Json.format[Schema.ListEnrollmentsResponse]
	given fmtPipeline: Format[Schema.Pipeline] = Json.format[Schema.Pipeline]
	given fmtGoogleCloudEventarcV1PipelineDestination: Format[Schema.GoogleCloudEventarcV1PipelineDestination] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestination]
	given fmtGoogleCloudEventarcV1PipelineMediation: Format[Schema.GoogleCloudEventarcV1PipelineMediation] = Json.format[Schema.GoogleCloudEventarcV1PipelineMediation]
	given fmtGoogleCloudEventarcV1PipelineMessagePayloadFormat: Format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormat] = Json.format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormat]
	given fmtGoogleCloudEventarcV1PipelineRetryPolicy: Format[Schema.GoogleCloudEventarcV1PipelineRetryPolicy] = Json.format[Schema.GoogleCloudEventarcV1PipelineRetryPolicy]
	given fmtGoogleCloudEventarcV1PipelineDestinationNetworkConfig: Format[Schema.GoogleCloudEventarcV1PipelineDestinationNetworkConfig] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestinationNetworkConfig]
	given fmtGoogleCloudEventarcV1PipelineDestinationHttpEndpoint: Format[Schema.GoogleCloudEventarcV1PipelineDestinationHttpEndpoint] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestinationHttpEndpoint]
	given fmtGoogleCloudEventarcV1PipelineDestinationAuthenticationConfig: Format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfig] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfig]
	given fmtGoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOidcToken: Format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOidcToken] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOidcToken]
	given fmtGoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOAuthToken: Format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOAuthToken] = Json.format[Schema.GoogleCloudEventarcV1PipelineDestinationAuthenticationConfigOAuthToken]
	given fmtGoogleCloudEventarcV1PipelineMessagePayloadFormatProtobufFormat: Format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatProtobufFormat] = Json.format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatProtobufFormat]
	given fmtGoogleCloudEventarcV1PipelineMessagePayloadFormatAvroFormat: Format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatAvroFormat] = Json.format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatAvroFormat]
	given fmtGoogleCloudEventarcV1PipelineMessagePayloadFormatJsonFormat: Format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatJsonFormat] = Json.format[Schema.GoogleCloudEventarcV1PipelineMessagePayloadFormatJsonFormat]
	given fmtGoogleCloudEventarcV1PipelineMediationTransformation: Format[Schema.GoogleCloudEventarcV1PipelineMediationTransformation] = Json.format[Schema.GoogleCloudEventarcV1PipelineMediationTransformation]
	given fmtListPipelinesResponse: Format[Schema.ListPipelinesResponse] = Json.format[Schema.ListPipelinesResponse]
	given fmtGoogleApiSource: Format[Schema.GoogleApiSource] = Json.format[Schema.GoogleApiSource]
	given fmtListGoogleApiSourcesResponse: Format[Schema.ListGoogleApiSourcesResponse] = Json.format[Schema.ListGoogleApiSourcesResponse]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
