package com.boresjo.play.api.google.publicca

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Schema {
	case class ExternalAccountKey(
	  /** Output only. Resource name. projects/{project}/locations/{location}/externalAccountKeys/{key_id} */
		name: Option[String] = None,
	  /** Output only. Key ID. It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created */
		keyId: Option[String] = None,
	  /** Output only. Base64-URL-encoded HS256 key. It is generated by the PublicCertificateAuthorityService when the ExternalAccountKey is created */
		b64MacKey: Option[String] = None
	)
}
