package com.boresjo.play.api.google.file

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtListInstancesResponse: Format[Schema.ListInstancesResponse] = Json.format[Schema.ListInstancesResponse]
	given fmtInstance: Format[Schema.Instance] = Json.format[Schema.Instance]
	given fmtInstanceStateEnum: Format[Schema.Instance.StateEnum] = JsonEnumFormat[Schema.Instance.StateEnum]
	given fmtInstanceTierEnum: Format[Schema.Instance.TierEnum] = JsonEnumFormat[Schema.Instance.TierEnum]
	given fmtFileShareConfig: Format[Schema.FileShareConfig] = Json.format[Schema.FileShareConfig]
	given fmtNetworkConfig: Format[Schema.NetworkConfig] = Json.format[Schema.NetworkConfig]
	given fmtInstanceSuspensionReasonsEnum: Format[Schema.Instance.SuspensionReasonsEnum] = JsonEnumFormat[Schema.Instance.SuspensionReasonsEnum]
	given fmtReplication: Format[Schema.Replication] = Json.format[Schema.Replication]
	given fmtInstanceProtocolEnum: Format[Schema.Instance.ProtocolEnum] = JsonEnumFormat[Schema.Instance.ProtocolEnum]
	given fmtPerformanceConfig: Format[Schema.PerformanceConfig] = Json.format[Schema.PerformanceConfig]
	given fmtPerformanceLimits: Format[Schema.PerformanceLimits] = Json.format[Schema.PerformanceLimits]
	given fmtNfsExportOptions: Format[Schema.NfsExportOptions] = Json.format[Schema.NfsExportOptions]
	given fmtNfsExportOptionsAccessModeEnum: Format[Schema.NfsExportOptions.AccessModeEnum] = JsonEnumFormat[Schema.NfsExportOptions.AccessModeEnum]
	given fmtNfsExportOptionsSquashModeEnum: Format[Schema.NfsExportOptions.SquashModeEnum] = JsonEnumFormat[Schema.NfsExportOptions.SquashModeEnum]
	given fmtNetworkConfigModesEnum: Format[Schema.NetworkConfig.ModesEnum] = JsonEnumFormat[Schema.NetworkConfig.ModesEnum]
	given fmtNetworkConfigConnectModeEnum: Format[Schema.NetworkConfig.ConnectModeEnum] = JsonEnumFormat[Schema.NetworkConfig.ConnectModeEnum]
	given fmtReplicationRoleEnum: Format[Schema.Replication.RoleEnum] = JsonEnumFormat[Schema.Replication.RoleEnum]
	given fmtReplicaConfig: Format[Schema.ReplicaConfig] = Json.format[Schema.ReplicaConfig]
	given fmtReplicaConfigStateEnum: Format[Schema.ReplicaConfig.StateEnum] = JsonEnumFormat[Schema.ReplicaConfig.StateEnum]
	given fmtReplicaConfigStateReasonsEnum: Format[Schema.ReplicaConfig.StateReasonsEnum] = JsonEnumFormat[Schema.ReplicaConfig.StateReasonsEnum]
	given fmtIOPSPerTB: Format[Schema.IOPSPerTB] = Json.format[Schema.IOPSPerTB]
	given fmtFixedIOPS: Format[Schema.FixedIOPS] = Json.format[Schema.FixedIOPS]
	given fmtRestoreInstanceRequest: Format[Schema.RestoreInstanceRequest] = Json.format[Schema.RestoreInstanceRequest]
	given fmtRevertInstanceRequest: Format[Schema.RevertInstanceRequest] = Json.format[Schema.RevertInstanceRequest]
	given fmtListSnapshotsResponse: Format[Schema.ListSnapshotsResponse] = Json.format[Schema.ListSnapshotsResponse]
	given fmtSnapshot: Format[Schema.Snapshot] = Json.format[Schema.Snapshot]
	given fmtSnapshotStateEnum: Format[Schema.Snapshot.StateEnum] = JsonEnumFormat[Schema.Snapshot.StateEnum]
	given fmtListBackupsResponse: Format[Schema.ListBackupsResponse] = Json.format[Schema.ListBackupsResponse]
	given fmtBackup: Format[Schema.Backup] = Json.format[Schema.Backup]
	given fmtBackupStateEnum: Format[Schema.Backup.StateEnum] = JsonEnumFormat[Schema.Backup.StateEnum]
	given fmtBackupSourceInstanceTierEnum: Format[Schema.Backup.SourceInstanceTierEnum] = JsonEnumFormat[Schema.Backup.SourceInstanceTierEnum]
	given fmtBackupFileSystemProtocolEnum: Format[Schema.Backup.FileSystemProtocolEnum] = JsonEnumFormat[Schema.Backup.FileSystemProtocolEnum]
	given fmtPromoteReplicaRequest: Format[Schema.PromoteReplicaRequest] = Json.format[Schema.PromoteReplicaRequest]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1Instance: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1InstanceStateEnum: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance.StateEnum] = JsonEnumFormat[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance.StateEnum]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1SloMetadata: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1SloEligibility: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility]
	given fmtMaintenancePolicy: Format[Schema.MaintenancePolicy] = Json.format[Schema.MaintenancePolicy]
	given fmtMaintenancePolicyStateEnum: Format[Schema.MaintenancePolicy.StateEnum] = JsonEnumFormat[Schema.MaintenancePolicy.StateEnum]
	given fmtUpdatePolicy: Format[Schema.UpdatePolicy] = Json.format[Schema.UpdatePolicy]
	given fmtMaintenanceWindow: Format[Schema.MaintenanceWindow] = Json.format[Schema.MaintenanceWindow]
	given fmtUpdatePolicyChannelEnum: Format[Schema.UpdatePolicy.ChannelEnum] = JsonEnumFormat[Schema.UpdatePolicy.ChannelEnum]
	given fmtDenyMaintenancePeriod: Format[Schema.DenyMaintenancePeriod] = Json.format[Schema.DenyMaintenancePeriod]
	given fmtDailyCycle: Format[Schema.DailyCycle] = Json.format[Schema.DailyCycle]
	given fmtWeeklyCycle: Format[Schema.WeeklyCycle] = Json.format[Schema.WeeklyCycle]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtSchedule: Format[Schema.Schedule] = Json.format[Schema.Schedule]
	given fmtScheduleDayEnum: Format[Schema.Schedule.DayEnum] = JsonEnumFormat[Schema.Schedule.DayEnum]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
}
