package com.boresjo.play.api.google.kmsinventory

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleCloudKmsV1CryptoKeyVersionTemplate: Format[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate] = Json.format[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate]
	given fmtGoogleCloudKmsV1CryptoKeyVersionTemplateAlgorithmEnum: Format[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate.AlgorithmEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate.AlgorithmEnum]
	given fmtGoogleCloudKmsV1CryptoKeyVersionTemplateProtectionLevelEnum: Format[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate.ProtectionLevelEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKeyVersionTemplate.ProtectionLevelEnum]
	given fmtGoogleCloudKmsV1ExternalProtectionLevelOptions: Format[Schema.GoogleCloudKmsV1ExternalProtectionLevelOptions] = Json.format[Schema.GoogleCloudKmsV1ExternalProtectionLevelOptions]
	given fmtGoogleCloudKmsV1KeyAccessJustificationsPolicy: Format[Schema.GoogleCloudKmsV1KeyAccessJustificationsPolicy] = Json.format[Schema.GoogleCloudKmsV1KeyAccessJustificationsPolicy]
	given fmtGoogleCloudKmsV1KeyAccessJustificationsPolicyAllowedAccessReasonsEnum: Format[Schema.GoogleCloudKmsV1KeyAccessJustificationsPolicy.AllowedAccessReasonsEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1KeyAccessJustificationsPolicy.AllowedAccessReasonsEnum]
	given fmtGoogleCloudKmsV1CryptoKeyVersion: Format[Schema.GoogleCloudKmsV1CryptoKeyVersion] = Json.format[Schema.GoogleCloudKmsV1CryptoKeyVersion]
	given fmtGoogleCloudKmsV1CryptoKeyVersionProtectionLevelEnum: Format[Schema.GoogleCloudKmsV1CryptoKeyVersion.ProtectionLevelEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKeyVersion.ProtectionLevelEnum]
	given fmtGoogleCloudKmsV1KeyOperationAttestation: Format[Schema.GoogleCloudKmsV1KeyOperationAttestation] = Json.format[Schema.GoogleCloudKmsV1KeyOperationAttestation]
	given fmtGoogleCloudKmsV1CryptoKeyVersionAlgorithmEnum: Format[Schema.GoogleCloudKmsV1CryptoKeyVersion.AlgorithmEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKeyVersion.AlgorithmEnum]
	given fmtGoogleCloudKmsV1CryptoKeyVersionStateEnum: Format[Schema.GoogleCloudKmsV1CryptoKeyVersion.StateEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKeyVersion.StateEnum]
	given fmtGoogleCloudKmsInventoryV1SearchProtectedResourcesResponse: Format[Schema.GoogleCloudKmsInventoryV1SearchProtectedResourcesResponse] = Json.format[Schema.GoogleCloudKmsInventoryV1SearchProtectedResourcesResponse]
	given fmtGoogleCloudKmsInventoryV1ProtectedResource: Format[Schema.GoogleCloudKmsInventoryV1ProtectedResource] = Json.format[Schema.GoogleCloudKmsInventoryV1ProtectedResource]
	given fmtGoogleCloudKmsInventoryV1ListCryptoKeysResponse: Format[Schema.GoogleCloudKmsInventoryV1ListCryptoKeysResponse] = Json.format[Schema.GoogleCloudKmsInventoryV1ListCryptoKeysResponse]
	given fmtGoogleCloudKmsV1CryptoKey: Format[Schema.GoogleCloudKmsV1CryptoKey] = Json.format[Schema.GoogleCloudKmsV1CryptoKey]
	given fmtGoogleCloudKmsV1KeyOperationAttestationCertificateChains: Format[Schema.GoogleCloudKmsV1KeyOperationAttestationCertificateChains] = Json.format[Schema.GoogleCloudKmsV1KeyOperationAttestationCertificateChains]
	given fmtGoogleCloudKmsV1KeyOperationAttestationFormatEnum: Format[Schema.GoogleCloudKmsV1KeyOperationAttestation.FormatEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1KeyOperationAttestation.FormatEnum]
	given fmtGoogleCloudKmsInventoryV1ProtectedResourcesSummary: Format[Schema.GoogleCloudKmsInventoryV1ProtectedResourcesSummary] = Json.format[Schema.GoogleCloudKmsInventoryV1ProtectedResourcesSummary]
	given fmtGoogleCloudKmsV1CryptoKeyPurposeEnum: Format[Schema.GoogleCloudKmsV1CryptoKey.PurposeEnum] = JsonEnumFormat[Schema.GoogleCloudKmsV1CryptoKey.PurposeEnum]
}
