package com.boresjo.play.api.google.people

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtPerson: Format[Schema.Person] = Json.format[Schema.Person]
	given fmtPersonMetadata: Format[Schema.PersonMetadata] = Json.format[Schema.PersonMetadata]
	given fmtAddress: Format[Schema.Address] = Json.format[Schema.Address]
	given fmtPersonAgeRangeEnum: Format[Schema.Person.AgeRangeEnum] = JsonEnumFormat[Schema.Person.AgeRangeEnum]
	given fmtAgeRangeType: Format[Schema.AgeRangeType] = Json.format[Schema.AgeRangeType]
	given fmtBiography: Format[Schema.Biography] = Json.format[Schema.Biography]
	given fmtBirthday: Format[Schema.Birthday] = Json.format[Schema.Birthday]
	given fmtBraggingRights: Format[Schema.BraggingRights] = Json.format[Schema.BraggingRights]
	given fmtCalendarUrl: Format[Schema.CalendarUrl] = Json.format[Schema.CalendarUrl]
	given fmtClientData: Format[Schema.ClientData] = Json.format[Schema.ClientData]
	given fmtCoverPhoto: Format[Schema.CoverPhoto] = Json.format[Schema.CoverPhoto]
	given fmtEmailAddress: Format[Schema.EmailAddress] = Json.format[Schema.EmailAddress]
	given fmtEvent: Format[Schema.Event] = Json.format[Schema.Event]
	given fmtExternalId: Format[Schema.ExternalId] = Json.format[Schema.ExternalId]
	given fmtFileAs: Format[Schema.FileAs] = Json.format[Schema.FileAs]
	given fmtGender: Format[Schema.Gender] = Json.format[Schema.Gender]
	given fmtImClient: Format[Schema.ImClient] = Json.format[Schema.ImClient]
	given fmtInterest: Format[Schema.Interest] = Json.format[Schema.Interest]
	given fmtLocale: Format[Schema.Locale] = Json.format[Schema.Locale]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtMembership: Format[Schema.Membership] = Json.format[Schema.Membership]
	given fmtMiscKeyword: Format[Schema.MiscKeyword] = Json.format[Schema.MiscKeyword]
	given fmtName: Format[Schema.Name] = Json.format[Schema.Name]
	given fmtNickname: Format[Schema.Nickname] = Json.format[Schema.Nickname]
	given fmtOccupation: Format[Schema.Occupation] = Json.format[Schema.Occupation]
	given fmtOrganization: Format[Schema.Organization] = Json.format[Schema.Organization]
	given fmtPhoneNumber: Format[Schema.PhoneNumber] = Json.format[Schema.PhoneNumber]
	given fmtPhoto: Format[Schema.Photo] = Json.format[Schema.Photo]
	given fmtRelation: Format[Schema.Relation] = Json.format[Schema.Relation]
	given fmtRelationshipInterest: Format[Schema.RelationshipInterest] = Json.format[Schema.RelationshipInterest]
	given fmtRelationshipStatus: Format[Schema.RelationshipStatus] = Json.format[Schema.RelationshipStatus]
	given fmtResidence: Format[Schema.Residence] = Json.format[Schema.Residence]
	given fmtSipAddress: Format[Schema.SipAddress] = Json.format[Schema.SipAddress]
	given fmtSkill: Format[Schema.Skill] = Json.format[Schema.Skill]
	given fmtTagline: Format[Schema.Tagline] = Json.format[Schema.Tagline]
	given fmtUrl: Format[Schema.Url] = Json.format[Schema.Url]
	given fmtUserDefined: Format[Schema.UserDefined] = Json.format[Schema.UserDefined]
	given fmtSource: Format[Schema.Source] = Json.format[Schema.Source]
	given fmtPersonMetadataObjectTypeEnum: Format[Schema.PersonMetadata.ObjectTypeEnum] = JsonEnumFormat[Schema.PersonMetadata.ObjectTypeEnum]
	given fmtSourceTypeEnum: Format[Schema.Source.TypeEnum] = JsonEnumFormat[Schema.Source.TypeEnum]
	given fmtProfileMetadata: Format[Schema.ProfileMetadata] = Json.format[Schema.ProfileMetadata]
	given fmtProfileMetadataObjectTypeEnum: Format[Schema.ProfileMetadata.ObjectTypeEnum] = JsonEnumFormat[Schema.ProfileMetadata.ObjectTypeEnum]
	given fmtProfileMetadataUserTypesEnum: Format[Schema.ProfileMetadata.UserTypesEnum] = JsonEnumFormat[Schema.ProfileMetadata.UserTypesEnum]
	given fmtFieldMetadata: Format[Schema.FieldMetadata] = Json.format[Schema.FieldMetadata]
	given fmtAgeRangeTypeAgeRangeEnum: Format[Schema.AgeRangeType.AgeRangeEnum] = JsonEnumFormat[Schema.AgeRangeType.AgeRangeEnum]
	given fmtBiographyContentTypeEnum: Format[Schema.Biography.ContentTypeEnum] = JsonEnumFormat[Schema.Biography.ContentTypeEnum]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
	given fmtContactGroupMembership: Format[Schema.ContactGroupMembership] = Json.format[Schema.ContactGroupMembership]
	given fmtDomainMembership: Format[Schema.DomainMembership] = Json.format[Schema.DomainMembership]
	given fmtMiscKeywordTypeEnum: Format[Schema.MiscKeyword.TypeEnum] = JsonEnumFormat[Schema.MiscKeyword.TypeEnum]
	given fmtNicknameTypeEnum: Format[Schema.Nickname.TypeEnum] = JsonEnumFormat[Schema.Nickname.TypeEnum]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtDeleteContactPhotoResponse: Format[Schema.DeleteContactPhotoResponse] = Json.format[Schema.DeleteContactPhotoResponse]
	given fmtUpdateContactPhotoRequest: Format[Schema.UpdateContactPhotoRequest] = Json.format[Schema.UpdateContactPhotoRequest]
	given fmtUpdateContactPhotoRequestSourcesEnum: Format[Schema.UpdateContactPhotoRequest.SourcesEnum] = JsonEnumFormat[Schema.UpdateContactPhotoRequest.SourcesEnum]
	given fmtUpdateContactPhotoResponse: Format[Schema.UpdateContactPhotoResponse] = Json.format[Schema.UpdateContactPhotoResponse]
	given fmtSearchResponse: Format[Schema.SearchResponse] = Json.format[Schema.SearchResponse]
	given fmtSearchResult: Format[Schema.SearchResult] = Json.format[Schema.SearchResult]
	given fmtBatchDeleteContactsRequest: Format[Schema.BatchDeleteContactsRequest] = Json.format[Schema.BatchDeleteContactsRequest]
	given fmtBatchCreateContactsRequest: Format[Schema.BatchCreateContactsRequest] = Json.format[Schema.BatchCreateContactsRequest]
	given fmtContactToCreate: Format[Schema.ContactToCreate] = Json.format[Schema.ContactToCreate]
	given fmtBatchCreateContactsRequestSourcesEnum: Format[Schema.BatchCreateContactsRequest.SourcesEnum] = JsonEnumFormat[Schema.BatchCreateContactsRequest.SourcesEnum]
	given fmtBatchCreateContactsResponse: Format[Schema.BatchCreateContactsResponse] = Json.format[Schema.BatchCreateContactsResponse]
	given fmtPersonResponse: Format[Schema.PersonResponse] = Json.format[Schema.PersonResponse]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtBatchUpdateContactsRequest: Format[Schema.BatchUpdateContactsRequest] = Json.format[Schema.BatchUpdateContactsRequest]
	given fmtBatchUpdateContactsRequestSourcesEnum: Format[Schema.BatchUpdateContactsRequest.SourcesEnum] = JsonEnumFormat[Schema.BatchUpdateContactsRequest.SourcesEnum]
	given fmtBatchUpdateContactsResponse: Format[Schema.BatchUpdateContactsResponse] = Json.format[Schema.BatchUpdateContactsResponse]
	given fmtListOtherContactsResponse: Format[Schema.ListOtherContactsResponse] = Json.format[Schema.ListOtherContactsResponse]
	given fmtCopyOtherContactToMyContactsGroupRequest: Format[Schema.CopyOtherContactToMyContactsGroupRequest] = Json.format[Schema.CopyOtherContactToMyContactsGroupRequest]
	given fmtCopyOtherContactToMyContactsGroupRequestSourcesEnum: Format[Schema.CopyOtherContactToMyContactsGroupRequest.SourcesEnum] = JsonEnumFormat[Schema.CopyOtherContactToMyContactsGroupRequest.SourcesEnum]
	given fmtGetPeopleResponse: Format[Schema.GetPeopleResponse] = Json.format[Schema.GetPeopleResponse]
	given fmtListConnectionsResponse: Format[Schema.ListConnectionsResponse] = Json.format[Schema.ListConnectionsResponse]
	given fmtListDirectoryPeopleResponse: Format[Schema.ListDirectoryPeopleResponse] = Json.format[Schema.ListDirectoryPeopleResponse]
	given fmtSearchDirectoryPeopleResponse: Format[Schema.SearchDirectoryPeopleResponse] = Json.format[Schema.SearchDirectoryPeopleResponse]
	given fmtBatchGetContactGroupsResponse: Format[Schema.BatchGetContactGroupsResponse] = Json.format[Schema.BatchGetContactGroupsResponse]
	given fmtContactGroupResponse: Format[Schema.ContactGroupResponse] = Json.format[Schema.ContactGroupResponse]
	given fmtContactGroup: Format[Schema.ContactGroup] = Json.format[Schema.ContactGroup]
	given fmtContactGroupMetadata: Format[Schema.ContactGroupMetadata] = Json.format[Schema.ContactGroupMetadata]
	given fmtContactGroupGroupTypeEnum: Format[Schema.ContactGroup.GroupTypeEnum] = JsonEnumFormat[Schema.ContactGroup.GroupTypeEnum]
	given fmtGroupClientData: Format[Schema.GroupClientData] = Json.format[Schema.GroupClientData]
	given fmtCreateContactGroupRequest: Format[Schema.CreateContactGroupRequest] = Json.format[Schema.CreateContactGroupRequest]
	given fmtListContactGroupsResponse: Format[Schema.ListContactGroupsResponse] = Json.format[Schema.ListContactGroupsResponse]
	given fmtUpdateContactGroupRequest: Format[Schema.UpdateContactGroupRequest] = Json.format[Schema.UpdateContactGroupRequest]
	given fmtModifyContactGroupMembersRequest: Format[Schema.ModifyContactGroupMembersRequest] = Json.format[Schema.ModifyContactGroupMembersRequest]
	given fmtModifyContactGroupMembersResponse: Format[Schema.ModifyContactGroupMembersResponse] = Json.format[Schema.ModifyContactGroupMembersResponse]
}
