package com.boresjo.play.api.google.analytics

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtAccount: Format[Schema.Account] = Json.format[Schema.Account]
	given fmtAccountChildLinkItem: Format[Schema.Account.ChildLinkItem] = Json.format[Schema.Account.ChildLinkItem]
	given fmtAccountPermissionsItem: Format[Schema.Account.PermissionsItem] = Json.format[Schema.Account.PermissionsItem]
	given fmtAccountRef: Format[Schema.AccountRef] = Json.format[Schema.AccountRef]
	given fmtAccountSummaries: Format[Schema.AccountSummaries] = Json.format[Schema.AccountSummaries]
	given fmtAccountSummary: Format[Schema.AccountSummary] = Json.format[Schema.AccountSummary]
	given fmtWebPropertySummary: Format[Schema.WebPropertySummary] = Json.format[Schema.WebPropertySummary]
	given fmtAccountTicket: Format[Schema.AccountTicket] = Json.format[Schema.AccountTicket]
	given fmtProfile: Format[Schema.Profile] = Json.format[Schema.Profile]
	given fmtWebproperty: Format[Schema.Webproperty] = Json.format[Schema.Webproperty]
	given fmtAccountTreeRequest: Format[Schema.AccountTreeRequest] = Json.format[Schema.AccountTreeRequest]
	given fmtAccountTreeResponse: Format[Schema.AccountTreeResponse] = Json.format[Schema.AccountTreeResponse]
	given fmtAccounts: Format[Schema.Accounts] = Json.format[Schema.Accounts]
	given fmtAdWordsAccount: Format[Schema.AdWordsAccount] = Json.format[Schema.AdWordsAccount]
	given fmtAnalyticsDataimportDeleteUploadDataRequest: Format[Schema.AnalyticsDataimportDeleteUploadDataRequest] = Json.format[Schema.AnalyticsDataimportDeleteUploadDataRequest]
	given fmtColumn: Format[Schema.Column] = Json.format[Schema.Column]
	given fmtColumns: Format[Schema.Columns] = Json.format[Schema.Columns]
	given fmtCustomDataSource: Format[Schema.CustomDataSource] = Json.format[Schema.CustomDataSource]
	given fmtCustomDataSourceChildLinkItem: Format[Schema.CustomDataSource.ChildLinkItem] = Json.format[Schema.CustomDataSource.ChildLinkItem]
	given fmtCustomDataSourceParentLinkItem: Format[Schema.CustomDataSource.ParentLinkItem] = Json.format[Schema.CustomDataSource.ParentLinkItem]
	given fmtCustomDataSources: Format[Schema.CustomDataSources] = Json.format[Schema.CustomDataSources]
	given fmtCustomDimension: Format[Schema.CustomDimension] = Json.format[Schema.CustomDimension]
	given fmtCustomDimensionParentLinkItem: Format[Schema.CustomDimension.ParentLinkItem] = Json.format[Schema.CustomDimension.ParentLinkItem]
	given fmtCustomDimensions: Format[Schema.CustomDimensions] = Json.format[Schema.CustomDimensions]
	given fmtCustomMetric: Format[Schema.CustomMetric] = Json.format[Schema.CustomMetric]
	given fmtCustomMetricParentLinkItem: Format[Schema.CustomMetric.ParentLinkItem] = Json.format[Schema.CustomMetric.ParentLinkItem]
	given fmtCustomMetrics: Format[Schema.CustomMetrics] = Json.format[Schema.CustomMetrics]
	given fmtEntityAdWordsLink: Format[Schema.EntityAdWordsLink] = Json.format[Schema.EntityAdWordsLink]
	given fmtEntityAdWordsLinkEntityItem: Format[Schema.EntityAdWordsLink.EntityItem] = Json.format[Schema.EntityAdWordsLink.EntityItem]
	given fmtWebPropertyRef: Format[Schema.WebPropertyRef] = Json.format[Schema.WebPropertyRef]
	given fmtEntityAdWordsLinks: Format[Schema.EntityAdWordsLinks] = Json.format[Schema.EntityAdWordsLinks]
	given fmtEntityUserLink: Format[Schema.EntityUserLink] = Json.format[Schema.EntityUserLink]
	given fmtEntityUserLinkEntityItem: Format[Schema.EntityUserLink.EntityItem] = Json.format[Schema.EntityUserLink.EntityItem]
	given fmtProfileRef: Format[Schema.ProfileRef] = Json.format[Schema.ProfileRef]
	given fmtEntityUserLinkPermissionsItem: Format[Schema.EntityUserLink.PermissionsItem] = Json.format[Schema.EntityUserLink.PermissionsItem]
	given fmtUserRef: Format[Schema.UserRef] = Json.format[Schema.UserRef]
	given fmtEntityUserLinks: Format[Schema.EntityUserLinks] = Json.format[Schema.EntityUserLinks]
	given fmtExperiment: Format[Schema.Experiment] = Json.format[Schema.Experiment]
	given fmtExperimentParentLinkItem: Format[Schema.Experiment.ParentLinkItem] = Json.format[Schema.Experiment.ParentLinkItem]
	given fmtExperimentVariationsItem: Format[Schema.Experiment.VariationsItem] = Json.format[Schema.Experiment.VariationsItem]
	given fmtExperiments: Format[Schema.Experiments] = Json.format[Schema.Experiments]
	given fmtFilter: Format[Schema.Filter] = Json.format[Schema.Filter]
	given fmtFilterAdvancedDetailsItem: Format[Schema.Filter.AdvancedDetailsItem] = Json.format[Schema.Filter.AdvancedDetailsItem]
	given fmtFilterExpression: Format[Schema.FilterExpression] = Json.format[Schema.FilterExpression]
	given fmtFilterLowercaseDetailsItem: Format[Schema.Filter.LowercaseDetailsItem] = Json.format[Schema.Filter.LowercaseDetailsItem]
	given fmtFilterParentLinkItem: Format[Schema.Filter.ParentLinkItem] = Json.format[Schema.Filter.ParentLinkItem]
	given fmtFilterSearchAndReplaceDetailsItem: Format[Schema.Filter.SearchAndReplaceDetailsItem] = Json.format[Schema.Filter.SearchAndReplaceDetailsItem]
	given fmtFilterUppercaseDetailsItem: Format[Schema.Filter.UppercaseDetailsItem] = Json.format[Schema.Filter.UppercaseDetailsItem]
	given fmtFilterRef: Format[Schema.FilterRef] = Json.format[Schema.FilterRef]
	given fmtFilters: Format[Schema.Filters] = Json.format[Schema.Filters]
	given fmtGaData: Format[Schema.GaData] = Json.format[Schema.GaData]
	given fmtGaDataColumnHeadersItem: Format[Schema.GaData.ColumnHeadersItem] = Json.format[Schema.GaData.ColumnHeadersItem]
	given fmtGaDataDataTableItem: Format[Schema.GaData.DataTableItem] = Json.format[Schema.GaData.DataTableItem]
	given fmtGaDataDataTableItemColsItem: Format[Schema.GaData.DataTableItem.ColsItem] = Json.format[Schema.GaData.DataTableItem.ColsItem]
	given fmtGaDataDataTableItemRowsItem: Format[Schema.GaData.DataTableItem.RowsItem] = Json.format[Schema.GaData.DataTableItem.RowsItem]
	given fmtGaDataDataTableItemRowsItemCItem: Format[Schema.GaData.DataTableItem.RowsItem.CItem] = Json.format[Schema.GaData.DataTableItem.RowsItem.CItem]
	given fmtGaDataProfileInfoItem: Format[Schema.GaData.ProfileInfoItem] = Json.format[Schema.GaData.ProfileInfoItem]
	given fmtGaDataQueryItem: Format[Schema.GaData.QueryItem] = Json.format[Schema.GaData.QueryItem]
	given fmtGoal: Format[Schema.Goal] = Json.format[Schema.Goal]
	given fmtGoalEventDetailsItem: Format[Schema.Goal.EventDetailsItem] = Json.format[Schema.Goal.EventDetailsItem]
	given fmtGoalEventDetailsItemEventConditionsItem: Format[Schema.Goal.EventDetailsItem.EventConditionsItem] = Json.format[Schema.Goal.EventDetailsItem.EventConditionsItem]
	given fmtGoalParentLinkItem: Format[Schema.Goal.ParentLinkItem] = Json.format[Schema.Goal.ParentLinkItem]
	given fmtGoalUrlDestinationDetailsItem: Format[Schema.Goal.UrlDestinationDetailsItem] = Json.format[Schema.Goal.UrlDestinationDetailsItem]
	given fmtGoalUrlDestinationDetailsItemStepsItem: Format[Schema.Goal.UrlDestinationDetailsItem.StepsItem] = Json.format[Schema.Goal.UrlDestinationDetailsItem.StepsItem]
	given fmtGoalVisitNumPagesDetailsItem: Format[Schema.Goal.VisitNumPagesDetailsItem] = Json.format[Schema.Goal.VisitNumPagesDetailsItem]
	given fmtGoalVisitTimeOnSiteDetailsItem: Format[Schema.Goal.VisitTimeOnSiteDetailsItem] = Json.format[Schema.Goal.VisitTimeOnSiteDetailsItem]
	given fmtGoals: Format[Schema.Goals] = Json.format[Schema.Goals]
	given fmtHashClientIdRequest: Format[Schema.HashClientIdRequest] = Json.format[Schema.HashClientIdRequest]
	given fmtHashClientIdResponse: Format[Schema.HashClientIdResponse] = Json.format[Schema.HashClientIdResponse]
	given fmtIncludeConditions: Format[Schema.IncludeConditions] = Json.format[Schema.IncludeConditions]
	given fmtLinkedForeignAccount: Format[Schema.LinkedForeignAccount] = Json.format[Schema.LinkedForeignAccount]
	given fmtMcfData: Format[Schema.McfData] = Json.format[Schema.McfData]
	given fmtMcfDataColumnHeadersItem: Format[Schema.McfData.ColumnHeadersItem] = Json.format[Schema.McfData.ColumnHeadersItem]
	given fmtMcfDataProfileInfoItem: Format[Schema.McfData.ProfileInfoItem] = Json.format[Schema.McfData.ProfileInfoItem]
	given fmtMcfDataQueryItem: Format[Schema.McfData.QueryItem] = Json.format[Schema.McfData.QueryItem]
	given fmtMcfDataRowsItem: Format[Schema.McfData.RowsItem] = Json.format[Schema.McfData.RowsItem]
	given fmtMcfDataRowsItemConversionPathValueItem: Format[Schema.McfData.RowsItem.ConversionPathValueItem] = Json.format[Schema.McfData.RowsItem.ConversionPathValueItem]
	given fmtProfileChildLinkItem: Format[Schema.Profile.ChildLinkItem] = Json.format[Schema.Profile.ChildLinkItem]
	given fmtProfileParentLinkItem: Format[Schema.Profile.ParentLinkItem] = Json.format[Schema.Profile.ParentLinkItem]
	given fmtProfilePermissionsItem: Format[Schema.Profile.PermissionsItem] = Json.format[Schema.Profile.PermissionsItem]
	given fmtProfileFilterLink: Format[Schema.ProfileFilterLink] = Json.format[Schema.ProfileFilterLink]
	given fmtProfileFilterLinks: Format[Schema.ProfileFilterLinks] = Json.format[Schema.ProfileFilterLinks]
	given fmtProfileSummary: Format[Schema.ProfileSummary] = Json.format[Schema.ProfileSummary]
	given fmtProfiles: Format[Schema.Profiles] = Json.format[Schema.Profiles]
	given fmtRealtimeData: Format[Schema.RealtimeData] = Json.format[Schema.RealtimeData]
	given fmtRealtimeDataColumnHeadersItem: Format[Schema.RealtimeData.ColumnHeadersItem] = Json.format[Schema.RealtimeData.ColumnHeadersItem]
	given fmtRealtimeDataProfileInfoItem: Format[Schema.RealtimeData.ProfileInfoItem] = Json.format[Schema.RealtimeData.ProfileInfoItem]
	given fmtRealtimeDataQueryItem: Format[Schema.RealtimeData.QueryItem] = Json.format[Schema.RealtimeData.QueryItem]
	given fmtRemarketingAudience: Format[Schema.RemarketingAudience] = Json.format[Schema.RemarketingAudience]
	given fmtRemarketingAudienceAudienceDefinitionItem: Format[Schema.RemarketingAudience.AudienceDefinitionItem] = Json.format[Schema.RemarketingAudience.AudienceDefinitionItem]
	given fmtRemarketingAudienceStateBasedAudienceDefinitionItem: Format[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem] = Json.format[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem]
	given fmtRemarketingAudienceStateBasedAudienceDefinitionItemExcludeConditionsItem: Format[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem.ExcludeConditionsItem] = Json.format[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem.ExcludeConditionsItem]
	given fmtRemarketingAudiences: Format[Schema.RemarketingAudiences] = Json.format[Schema.RemarketingAudiences]
	given fmtSegment: Format[Schema.Segment] = Json.format[Schema.Segment]
	given fmtSegments: Format[Schema.Segments] = Json.format[Schema.Segments]
	given fmtUnsampledReport: Format[Schema.UnsampledReport] = Json.format[Schema.UnsampledReport]
	given fmtUnsampledReportCloudStorageDownloadDetailsItem: Format[Schema.UnsampledReport.CloudStorageDownloadDetailsItem] = Json.format[Schema.UnsampledReport.CloudStorageDownloadDetailsItem]
	given fmtUnsampledReportDriveDownloadDetailsItem: Format[Schema.UnsampledReport.DriveDownloadDetailsItem] = Json.format[Schema.UnsampledReport.DriveDownloadDetailsItem]
	given fmtUnsampledReports: Format[Schema.UnsampledReports] = Json.format[Schema.UnsampledReports]
	given fmtUpload: Format[Schema.Upload] = Json.format[Schema.Upload]
	given fmtUploads: Format[Schema.Uploads] = Json.format[Schema.Uploads]
	given fmtUserDeletionRequest: Format[Schema.UserDeletionRequest] = Json.format[Schema.UserDeletionRequest]
	given fmtUserDeletionRequestIdItem: Format[Schema.UserDeletionRequest.IdItem] = Json.format[Schema.UserDeletionRequest.IdItem]
	given fmtWebproperties: Format[Schema.Webproperties] = Json.format[Schema.Webproperties]
	given fmtWebpropertyChildLinkItem: Format[Schema.Webproperty.ChildLinkItem] = Json.format[Schema.Webproperty.ChildLinkItem]
	given fmtWebpropertyParentLinkItem: Format[Schema.Webproperty.ParentLinkItem] = Json.format[Schema.Webproperty.ParentLinkItem]
	given fmtWebpropertyPermissionsItem: Format[Schema.Webproperty.PermissionsItem] = Json.format[Schema.Webproperty.PermissionsItem]
}
