package com.boresjo.play.api.google.analytics

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putSchemaAccountChildLinkItem: Conversion[Schema.Account.ChildLinkItem, Option[Schema.Account.ChildLinkItem]] = (fun: Schema.Account.ChildLinkItem) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putSchemaAccountPermissionsItem: Conversion[Schema.Account.PermissionsItem, Option[Schema.Account.PermissionsItem]] = (fun: Schema.Account.PermissionsItem) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putListSchemaAccountSummary: Conversion[List[Schema.AccountSummary], Option[List[Schema.AccountSummary]]] = (fun: List[Schema.AccountSummary]) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListSchemaWebPropertySummary: Conversion[List[Schema.WebPropertySummary], Option[List[Schema.WebPropertySummary]]] = (fun: List[Schema.WebPropertySummary]) => Option(fun)
		given putSchemaAccount: Conversion[Schema.Account, Option[Schema.Account]] = (fun: Schema.Account) => Option(fun)
		given putSchemaProfile: Conversion[Schema.Profile, Option[Schema.Profile]] = (fun: Schema.Profile) => Option(fun)
		given putSchemaWebproperty: Conversion[Schema.Webproperty, Option[Schema.Webproperty]] = (fun: Schema.Webproperty) => Option(fun)
		given putListSchemaAccount: Conversion[List[Schema.Account], Option[List[Schema.Account]]] = (fun: List[Schema.Account]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putListSchemaColumn: Conversion[List[Schema.Column], Option[List[Schema.Column]]] = (fun: List[Schema.Column]) => Option(fun)
		given putSchemaCustomDataSourceChildLinkItem: Conversion[Schema.CustomDataSource.ChildLinkItem, Option[Schema.CustomDataSource.ChildLinkItem]] = (fun: Schema.CustomDataSource.ChildLinkItem) => Option(fun)
		given putSchemaCustomDataSourceParentLinkItem: Conversion[Schema.CustomDataSource.ParentLinkItem, Option[Schema.CustomDataSource.ParentLinkItem]] = (fun: Schema.CustomDataSource.ParentLinkItem) => Option(fun)
		given putListSchemaCustomDataSource: Conversion[List[Schema.CustomDataSource], Option[List[Schema.CustomDataSource]]] = (fun: List[Schema.CustomDataSource]) => Option(fun)
		given putSchemaCustomDimensionParentLinkItem: Conversion[Schema.CustomDimension.ParentLinkItem, Option[Schema.CustomDimension.ParentLinkItem]] = (fun: Schema.CustomDimension.ParentLinkItem) => Option(fun)
		given putListSchemaCustomDimension: Conversion[List[Schema.CustomDimension], Option[List[Schema.CustomDimension]]] = (fun: List[Schema.CustomDimension]) => Option(fun)
		given putSchemaCustomMetricParentLinkItem: Conversion[Schema.CustomMetric.ParentLinkItem, Option[Schema.CustomMetric.ParentLinkItem]] = (fun: Schema.CustomMetric.ParentLinkItem) => Option(fun)
		given putListSchemaCustomMetric: Conversion[List[Schema.CustomMetric], Option[List[Schema.CustomMetric]]] = (fun: List[Schema.CustomMetric]) => Option(fun)
		given putListSchemaAdWordsAccount: Conversion[List[Schema.AdWordsAccount], Option[List[Schema.AdWordsAccount]]] = (fun: List[Schema.AdWordsAccount]) => Option(fun)
		given putSchemaEntityAdWordsLinkEntityItem: Conversion[Schema.EntityAdWordsLink.EntityItem, Option[Schema.EntityAdWordsLink.EntityItem]] = (fun: Schema.EntityAdWordsLink.EntityItem) => Option(fun)
		given putListSchemaEntityAdWordsLink: Conversion[List[Schema.EntityAdWordsLink], Option[List[Schema.EntityAdWordsLink]]] = (fun: List[Schema.EntityAdWordsLink]) => Option(fun)
		given putSchemaEntityUserLinkEntityItem: Conversion[Schema.EntityUserLink.EntityItem, Option[Schema.EntityUserLink.EntityItem]] = (fun: Schema.EntityUserLink.EntityItem) => Option(fun)
		given putSchemaEntityUserLinkPermissionsItem: Conversion[Schema.EntityUserLink.PermissionsItem, Option[Schema.EntityUserLink.PermissionsItem]] = (fun: Schema.EntityUserLink.PermissionsItem) => Option(fun)
		given putSchemaUserRef: Conversion[Schema.UserRef, Option[Schema.UserRef]] = (fun: Schema.UserRef) => Option(fun)
		given putListSchemaEntityUserLink: Conversion[List[Schema.EntityUserLink], Option[List[Schema.EntityUserLink]]] = (fun: List[Schema.EntityUserLink]) => Option(fun)
		given putSchemaExperimentParentLinkItem: Conversion[Schema.Experiment.ParentLinkItem, Option[Schema.Experiment.ParentLinkItem]] = (fun: Schema.Experiment.ParentLinkItem) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putListSchemaExperimentVariationsItem: Conversion[List[Schema.Experiment.VariationsItem], Option[List[Schema.Experiment.VariationsItem]]] = (fun: List[Schema.Experiment.VariationsItem]) => Option(fun)
		given putListSchemaExperiment: Conversion[List[Schema.Experiment], Option[List[Schema.Experiment]]] = (fun: List[Schema.Experiment]) => Option(fun)
		given putSchemaFilterAdvancedDetailsItem: Conversion[Schema.Filter.AdvancedDetailsItem, Option[Schema.Filter.AdvancedDetailsItem]] = (fun: Schema.Filter.AdvancedDetailsItem) => Option(fun)
		given putSchemaFilterExpression: Conversion[Schema.FilterExpression, Option[Schema.FilterExpression]] = (fun: Schema.FilterExpression) => Option(fun)
		given putSchemaFilterLowercaseDetailsItem: Conversion[Schema.Filter.LowercaseDetailsItem, Option[Schema.Filter.LowercaseDetailsItem]] = (fun: Schema.Filter.LowercaseDetailsItem) => Option(fun)
		given putSchemaFilterParentLinkItem: Conversion[Schema.Filter.ParentLinkItem, Option[Schema.Filter.ParentLinkItem]] = (fun: Schema.Filter.ParentLinkItem) => Option(fun)
		given putSchemaFilterSearchAndReplaceDetailsItem: Conversion[Schema.Filter.SearchAndReplaceDetailsItem, Option[Schema.Filter.SearchAndReplaceDetailsItem]] = (fun: Schema.Filter.SearchAndReplaceDetailsItem) => Option(fun)
		given putSchemaFilterUppercaseDetailsItem: Conversion[Schema.Filter.UppercaseDetailsItem, Option[Schema.Filter.UppercaseDetailsItem]] = (fun: Schema.Filter.UppercaseDetailsItem) => Option(fun)
		given putListSchemaFilter: Conversion[List[Schema.Filter], Option[List[Schema.Filter]]] = (fun: List[Schema.Filter]) => Option(fun)
		given putListSchemaGaDataColumnHeadersItem: Conversion[List[Schema.GaData.ColumnHeadersItem], Option[List[Schema.GaData.ColumnHeadersItem]]] = (fun: List[Schema.GaData.ColumnHeadersItem]) => Option(fun)
		given putSchemaGaDataDataTableItem: Conversion[Schema.GaData.DataTableItem, Option[Schema.GaData.DataTableItem]] = (fun: Schema.GaData.DataTableItem) => Option(fun)
		given putSchemaGaDataProfileInfoItem: Conversion[Schema.GaData.ProfileInfoItem, Option[Schema.GaData.ProfileInfoItem]] = (fun: Schema.GaData.ProfileInfoItem) => Option(fun)
		given putSchemaGaDataQueryItem: Conversion[Schema.GaData.QueryItem, Option[Schema.GaData.QueryItem]] = (fun: Schema.GaData.QueryItem) => Option(fun)
		given putListListString: Conversion[List[List[String]], Option[List[List[String]]]] = (fun: List[List[String]]) => Option(fun)
		given putSchemaGoalEventDetailsItem: Conversion[Schema.Goal.EventDetailsItem, Option[Schema.Goal.EventDetailsItem]] = (fun: Schema.Goal.EventDetailsItem) => Option(fun)
		given putSchemaGoalParentLinkItem: Conversion[Schema.Goal.ParentLinkItem, Option[Schema.Goal.ParentLinkItem]] = (fun: Schema.Goal.ParentLinkItem) => Option(fun)
		given putSchemaGoalUrlDestinationDetailsItem: Conversion[Schema.Goal.UrlDestinationDetailsItem, Option[Schema.Goal.UrlDestinationDetailsItem]] = (fun: Schema.Goal.UrlDestinationDetailsItem) => Option(fun)
		given putSchemaGoalVisitNumPagesDetailsItem: Conversion[Schema.Goal.VisitNumPagesDetailsItem, Option[Schema.Goal.VisitNumPagesDetailsItem]] = (fun: Schema.Goal.VisitNumPagesDetailsItem) => Option(fun)
		given putSchemaGoalVisitTimeOnSiteDetailsItem: Conversion[Schema.Goal.VisitTimeOnSiteDetailsItem, Option[Schema.Goal.VisitTimeOnSiteDetailsItem]] = (fun: Schema.Goal.VisitTimeOnSiteDetailsItem) => Option(fun)
		given putListSchemaGoal: Conversion[List[Schema.Goal], Option[List[Schema.Goal]]] = (fun: List[Schema.Goal]) => Option(fun)
		given putListSchemaMcfDataColumnHeadersItem: Conversion[List[Schema.McfData.ColumnHeadersItem], Option[List[Schema.McfData.ColumnHeadersItem]]] = (fun: List[Schema.McfData.ColumnHeadersItem]) => Option(fun)
		given putSchemaMcfDataProfileInfoItem: Conversion[Schema.McfData.ProfileInfoItem, Option[Schema.McfData.ProfileInfoItem]] = (fun: Schema.McfData.ProfileInfoItem) => Option(fun)
		given putSchemaMcfDataQueryItem: Conversion[Schema.McfData.QueryItem, Option[Schema.McfData.QueryItem]] = (fun: Schema.McfData.QueryItem) => Option(fun)
		given putListListSchemaMcfDataRowsItem: Conversion[List[List[Schema.McfData.RowsItem]], Option[List[List[Schema.McfData.RowsItem]]]] = (fun: List[List[Schema.McfData.RowsItem]]) => Option(fun)
		given putSchemaProfileChildLinkItem: Conversion[Schema.Profile.ChildLinkItem, Option[Schema.Profile.ChildLinkItem]] = (fun: Schema.Profile.ChildLinkItem) => Option(fun)
		given putSchemaProfileParentLinkItem: Conversion[Schema.Profile.ParentLinkItem, Option[Schema.Profile.ParentLinkItem]] = (fun: Schema.Profile.ParentLinkItem) => Option(fun)
		given putSchemaProfilePermissionsItem: Conversion[Schema.Profile.PermissionsItem, Option[Schema.Profile.PermissionsItem]] = (fun: Schema.Profile.PermissionsItem) => Option(fun)
		given putSchemaFilterRef: Conversion[Schema.FilterRef, Option[Schema.FilterRef]] = (fun: Schema.FilterRef) => Option(fun)
		given putSchemaProfileRef: Conversion[Schema.ProfileRef, Option[Schema.ProfileRef]] = (fun: Schema.ProfileRef) => Option(fun)
		given putListSchemaProfileFilterLink: Conversion[List[Schema.ProfileFilterLink], Option[List[Schema.ProfileFilterLink]]] = (fun: List[Schema.ProfileFilterLink]) => Option(fun)
		given putListSchemaProfile: Conversion[List[Schema.Profile], Option[List[Schema.Profile]]] = (fun: List[Schema.Profile]) => Option(fun)
		given putListSchemaRealtimeDataColumnHeadersItem: Conversion[List[Schema.RealtimeData.ColumnHeadersItem], Option[List[Schema.RealtimeData.ColumnHeadersItem]]] = (fun: List[Schema.RealtimeData.ColumnHeadersItem]) => Option(fun)
		given putSchemaRealtimeDataProfileInfoItem: Conversion[Schema.RealtimeData.ProfileInfoItem, Option[Schema.RealtimeData.ProfileInfoItem]] = (fun: Schema.RealtimeData.ProfileInfoItem) => Option(fun)
		given putSchemaRealtimeDataQueryItem: Conversion[Schema.RealtimeData.QueryItem, Option[Schema.RealtimeData.QueryItem]] = (fun: Schema.RealtimeData.QueryItem) => Option(fun)
		given putSchemaRemarketingAudienceAudienceDefinitionItem: Conversion[Schema.RemarketingAudience.AudienceDefinitionItem, Option[Schema.RemarketingAudience.AudienceDefinitionItem]] = (fun: Schema.RemarketingAudience.AudienceDefinitionItem) => Option(fun)
		given putListSchemaLinkedForeignAccount: Conversion[List[Schema.LinkedForeignAccount], Option[List[Schema.LinkedForeignAccount]]] = (fun: List[Schema.LinkedForeignAccount]) => Option(fun)
		given putSchemaRemarketingAudienceStateBasedAudienceDefinitionItem: Conversion[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem, Option[Schema.RemarketingAudience.StateBasedAudienceDefinitionItem]] = (fun: Schema.RemarketingAudience.StateBasedAudienceDefinitionItem) => Option(fun)
		given putListSchemaRemarketingAudience: Conversion[List[Schema.RemarketingAudience], Option[List[Schema.RemarketingAudience]]] = (fun: List[Schema.RemarketingAudience]) => Option(fun)
		given putListSchemaSegment: Conversion[List[Schema.Segment], Option[List[Schema.Segment]]] = (fun: List[Schema.Segment]) => Option(fun)
		given putSchemaUnsampledReportCloudStorageDownloadDetailsItem: Conversion[Schema.UnsampledReport.CloudStorageDownloadDetailsItem, Option[Schema.UnsampledReport.CloudStorageDownloadDetailsItem]] = (fun: Schema.UnsampledReport.CloudStorageDownloadDetailsItem) => Option(fun)
		given putSchemaUnsampledReportDriveDownloadDetailsItem: Conversion[Schema.UnsampledReport.DriveDownloadDetailsItem, Option[Schema.UnsampledReport.DriveDownloadDetailsItem]] = (fun: Schema.UnsampledReport.DriveDownloadDetailsItem) => Option(fun)
		given putListSchemaUnsampledReport: Conversion[List[Schema.UnsampledReport], Option[List[Schema.UnsampledReport]]] = (fun: List[Schema.UnsampledReport]) => Option(fun)
		given putListSchemaUpload: Conversion[List[Schema.Upload], Option[List[Schema.Upload]]] = (fun: List[Schema.Upload]) => Option(fun)
		given putSchemaUserDeletionRequestIdItem: Conversion[Schema.UserDeletionRequest.IdItem, Option[Schema.UserDeletionRequest.IdItem]] = (fun: Schema.UserDeletionRequest.IdItem) => Option(fun)
		given putListSchemaProfileSummary: Conversion[List[Schema.ProfileSummary], Option[List[Schema.ProfileSummary]]] = (fun: List[Schema.ProfileSummary]) => Option(fun)
		given putListSchemaWebproperty: Conversion[List[Schema.Webproperty], Option[List[Schema.Webproperty]]] = (fun: List[Schema.Webproperty]) => Option(fun)
		given putSchemaWebpropertyChildLinkItem: Conversion[Schema.Webproperty.ChildLinkItem, Option[Schema.Webproperty.ChildLinkItem]] = (fun: Schema.Webproperty.ChildLinkItem) => Option(fun)
		given putSchemaWebpropertyParentLinkItem: Conversion[Schema.Webproperty.ParentLinkItem, Option[Schema.Webproperty.ParentLinkItem]] = (fun: Schema.Webproperty.ParentLinkItem) => Option(fun)
		given putSchemaWebpropertyPermissionsItem: Conversion[Schema.Webproperty.PermissionsItem, Option[Schema.Webproperty.PermissionsItem]] = (fun: Schema.Webproperty.PermissionsItem) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
