package com.boresjo.play.api.google.orgpolicy

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleCloudOrgpolicyV2ListCustomConstraintsResponse: Format[Schema.GoogleCloudOrgpolicyV2ListCustomConstraintsResponse] = Json.format[Schema.GoogleCloudOrgpolicyV2ListCustomConstraintsResponse]
	given fmtGoogleCloudOrgpolicyV2CustomConstraint: Format[Schema.GoogleCloudOrgpolicyV2CustomConstraint] = Json.format[Schema.GoogleCloudOrgpolicyV2CustomConstraint]
	given fmtGoogleCloudOrgpolicyV2ListPoliciesResponse: Format[Schema.GoogleCloudOrgpolicyV2ListPoliciesResponse] = Json.format[Schema.GoogleCloudOrgpolicyV2ListPoliciesResponse]
	given fmtGoogleCloudOrgpolicyV2Policy: Format[Schema.GoogleCloudOrgpolicyV2Policy] = Json.format[Schema.GoogleCloudOrgpolicyV2Policy]
	given fmtGoogleCloudOrgpolicyV2Constraint: Format[Schema.GoogleCloudOrgpolicyV2Constraint] = Json.format[Schema.GoogleCloudOrgpolicyV2Constraint]
	given fmtGoogleCloudOrgpolicyV2ConstraintBooleanConstraint: Format[Schema.GoogleCloudOrgpolicyV2ConstraintBooleanConstraint] = Json.format[Schema.GoogleCloudOrgpolicyV2ConstraintBooleanConstraint]
	given fmtGoogleCloudOrgpolicyV2ConstraintListConstraint: Format[Schema.GoogleCloudOrgpolicyV2ConstraintListConstraint] = Json.format[Schema.GoogleCloudOrgpolicyV2ConstraintListConstraint]
	given fmtGoogleCloudOrgpolicyV2ConstraintConstraintDefaultEnum: Format[Schema.GoogleCloudOrgpolicyV2Constraint.ConstraintDefaultEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2Constraint.ConstraintDefaultEnum]
	given fmtGoogleCloudOrgpolicyV2CustomConstraintMethodTypesEnum: Format[Schema.GoogleCloudOrgpolicyV2CustomConstraint.MethodTypesEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2CustomConstraint.MethodTypesEnum]
	given fmtGoogleCloudOrgpolicyV2CustomConstraintActionTypeEnum: Format[Schema.GoogleCloudOrgpolicyV2CustomConstraint.ActionTypeEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2CustomConstraint.ActionTypeEnum]
	given fmtGoogleCloudOrgpolicyV2AlternatePolicySpec: Format[Schema.GoogleCloudOrgpolicyV2AlternatePolicySpec] = Json.format[Schema.GoogleCloudOrgpolicyV2AlternatePolicySpec]
	given fmtGoogleCloudOrgpolicyV2PolicySpec: Format[Schema.GoogleCloudOrgpolicyV2PolicySpec] = Json.format[Schema.GoogleCloudOrgpolicyV2PolicySpec]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter] = Json.format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameterTypeEnum: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter.TypeEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter.TypeEnum]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameterMetadata: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameterMetadata] = Json.format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameterMetadata]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameterItemEnum: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter.ItemEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionParameter.ItemEnum]
	given fmtGoogleProtobufEmpty: Format[Schema.GoogleProtobufEmpty] = Json.format[Schema.GoogleProtobufEmpty]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition] = Json.format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition]
	given fmtGoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues: Format[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues] = Json.format[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRuleStringValues]
	given fmtGoogleCloudOrgpolicyV2PolicySpecPolicyRule: Format[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRule] = Json.format[Schema.GoogleCloudOrgpolicyV2PolicySpecPolicyRule]
	given fmtGoogleTypeExpr: Format[Schema.GoogleTypeExpr] = Json.format[Schema.GoogleTypeExpr]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionMethodTypesEnum: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition.MethodTypesEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition.MethodTypesEnum]
	given fmtGoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinitionActionTypeEnum: Format[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition.ActionTypeEnum] = JsonEnumFormat[Schema.GoogleCloudOrgpolicyV2ConstraintCustomConstraintDefinition.ActionTypeEnum]
	given fmtGoogleCloudOrgpolicyV2ListConstraintsResponse: Format[Schema.GoogleCloudOrgpolicyV2ListConstraintsResponse] = Json.format[Schema.GoogleCloudOrgpolicyV2ListConstraintsResponse]
}
