package com.boresjo.play.api.google.deploymentmanager

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtDeployment: Format[Schema.Deployment] = Json.format[Schema.Deployment]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtDeploymentUpdate: Format[Schema.DeploymentUpdate] = Json.format[Schema.DeploymentUpdate]
	given fmtTargetConfiguration: Format[Schema.TargetConfiguration] = Json.format[Schema.TargetConfiguration]
	given fmtDeploymentLabelEntry: Format[Schema.DeploymentLabelEntry] = Json.format[Schema.DeploymentLabelEntry]
	given fmtOperationStatusEnum: Format[Schema.Operation.StatusEnum] = JsonEnumFormat[Schema.Operation.StatusEnum]
	given fmtOperationErrorItem: Format[Schema.Operation.ErrorItem] = Json.format[Schema.Operation.ErrorItem]
	given fmtOperationErrorItemErrorsItem: Format[Schema.Operation.ErrorItem.ErrorsItem] = Json.format[Schema.Operation.ErrorItem.ErrorsItem]
	given fmtDebugInfo: Format[Schema.DebugInfo] = Json.format[Schema.DebugInfo]
	given fmtOperationErrorItemErrorsItemErrorDetailsItem: Format[Schema.Operation.ErrorItem.ErrorsItem.ErrorDetailsItem] = Json.format[Schema.Operation.ErrorItem.ErrorsItem.ErrorDetailsItem]
	given fmtErrorInfo: Format[Schema.ErrorInfo] = Json.format[Schema.ErrorInfo]
	given fmtQuotaExceededInfo: Format[Schema.QuotaExceededInfo] = Json.format[Schema.QuotaExceededInfo]
	given fmtHelp: Format[Schema.Help] = Json.format[Schema.Help]
	given fmtLocalizedMessage: Format[Schema.LocalizedMessage] = Json.format[Schema.LocalizedMessage]
	given fmtOperationWarningsItem: Format[Schema.Operation.WarningsItem] = Json.format[Schema.Operation.WarningsItem]
	given fmtOperationWarningsItemCodeEnum: Format[Schema.Operation.WarningsItem.CodeEnum] = JsonEnumFormat[Schema.Operation.WarningsItem.CodeEnum]
	given fmtOperationWarningsItemDataItem: Format[Schema.Operation.WarningsItem.DataItem] = Json.format[Schema.Operation.WarningsItem.DataItem]
	given fmtSetCommonInstanceMetadataOperationMetadata: Format[Schema.SetCommonInstanceMetadataOperationMetadata] = Json.format[Schema.SetCommonInstanceMetadataOperationMetadata]
	given fmtInstancesBulkInsertOperationMetadata: Format[Schema.InstancesBulkInsertOperationMetadata] = Json.format[Schema.InstancesBulkInsertOperationMetadata]
	given fmtQuotaExceededInfoRolloutStatusEnum: Format[Schema.QuotaExceededInfo.RolloutStatusEnum] = JsonEnumFormat[Schema.QuotaExceededInfo.RolloutStatusEnum]
	given fmtHelpLink: Format[Schema.HelpLink] = Json.format[Schema.HelpLink]
	given fmtSetCommonInstanceMetadataOperationMetadataPerLocationOperationInfo: Format[Schema.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfo] = Json.format[Schema.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfo]
	given fmtSetCommonInstanceMetadataOperationMetadataPerLocationOperationInfoStateEnum: Format[Schema.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfo.StateEnum] = JsonEnumFormat[Schema.SetCommonInstanceMetadataOperationMetadataPerLocationOperationInfo.StateEnum]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtBulkInsertOperationStatus: Format[Schema.BulkInsertOperationStatus] = Json.format[Schema.BulkInsertOperationStatus]
	given fmtBulkInsertOperationStatusStatusEnum: Format[Schema.BulkInsertOperationStatus.StatusEnum] = JsonEnumFormat[Schema.BulkInsertOperationStatus.StatusEnum]
	given fmtDeploymentUpdateLabelEntry: Format[Schema.DeploymentUpdateLabelEntry] = Json.format[Schema.DeploymentUpdateLabelEntry]
	given fmtConfigFile: Format[Schema.ConfigFile] = Json.format[Schema.ConfigFile]
	given fmtImportFile: Format[Schema.ImportFile] = Json.format[Schema.ImportFile]
	given fmtDeploymentsListResponse: Format[Schema.DeploymentsListResponse] = Json.format[Schema.DeploymentsListResponse]
	given fmtDeploymentsCancelPreviewRequest: Format[Schema.DeploymentsCancelPreviewRequest] = Json.format[Schema.DeploymentsCancelPreviewRequest]
	given fmtDeploymentsStopRequest: Format[Schema.DeploymentsStopRequest] = Json.format[Schema.DeploymentsStopRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtGlobalSetPolicyRequest: Format[Schema.GlobalSetPolicyRequest] = Json.format[Schema.GlobalSetPolicyRequest]
	given fmtTestPermissionsRequest: Format[Schema.TestPermissionsRequest] = Json.format[Schema.TestPermissionsRequest]
	given fmtTestPermissionsResponse: Format[Schema.TestPermissionsResponse] = Json.format[Schema.TestPermissionsResponse]
	given fmtManifest: Format[Schema.Manifest] = Json.format[Schema.Manifest]
	given fmtManifestsListResponse: Format[Schema.ManifestsListResponse] = Json.format[Schema.ManifestsListResponse]
	given fmtOperationsListResponse: Format[Schema.OperationsListResponse] = Json.format[Schema.OperationsListResponse]
	given fmtResource: Format[Schema.Resource] = Json.format[Schema.Resource]
	given fmtResourceAccessControl: Format[Schema.ResourceAccessControl] = Json.format[Schema.ResourceAccessControl]
	given fmtResourceUpdate: Format[Schema.ResourceUpdate] = Json.format[Schema.ResourceUpdate]
	given fmtResourceWarningsItem: Format[Schema.Resource.WarningsItem] = Json.format[Schema.Resource.WarningsItem]
	given fmtResourceWarningsItemCodeEnum: Format[Schema.Resource.WarningsItem.CodeEnum] = JsonEnumFormat[Schema.Resource.WarningsItem.CodeEnum]
	given fmtResourceWarningsItemDataItem: Format[Schema.Resource.WarningsItem.DataItem] = Json.format[Schema.Resource.WarningsItem.DataItem]
	given fmtResourceUpdateErrorItem: Format[Schema.ResourceUpdate.ErrorItem] = Json.format[Schema.ResourceUpdate.ErrorItem]
	given fmtResourceUpdateErrorItemErrorsItem: Format[Schema.ResourceUpdate.ErrorItem.ErrorsItem] = Json.format[Schema.ResourceUpdate.ErrorItem.ErrorsItem]
	given fmtResourceUpdateErrorItemErrorsItemErrorDetailsItem: Format[Schema.ResourceUpdate.ErrorItem.ErrorsItem.ErrorDetailsItem] = Json.format[Schema.ResourceUpdate.ErrorItem.ErrorsItem.ErrorDetailsItem]
	given fmtResourceUpdateWarningsItem: Format[Schema.ResourceUpdate.WarningsItem] = Json.format[Schema.ResourceUpdate.WarningsItem]
	given fmtResourceUpdateWarningsItemCodeEnum: Format[Schema.ResourceUpdate.WarningsItem.CodeEnum] = JsonEnumFormat[Schema.ResourceUpdate.WarningsItem.CodeEnum]
	given fmtResourceUpdateWarningsItemDataItem: Format[Schema.ResourceUpdate.WarningsItem.DataItem] = Json.format[Schema.ResourceUpdate.WarningsItem.DataItem]
	given fmtResourceUpdateStateEnum: Format[Schema.ResourceUpdate.StateEnum] = JsonEnumFormat[Schema.ResourceUpdate.StateEnum]
	given fmtResourceUpdateIntentEnum: Format[Schema.ResourceUpdate.IntentEnum] = JsonEnumFormat[Schema.ResourceUpdate.IntentEnum]
	given fmtResourcesListResponse: Format[Schema.ResourcesListResponse] = Json.format[Schema.ResourcesListResponse]
	given fmtTypesListResponse: Format[Schema.TypesListResponse] = Json.format[Schema.TypesListResponse]
	given fmtType: Format[Schema.Type] = Json.format[Schema.Type]
}
