package com.boresjo.play.api.google.localservices

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleAdsHomeservicesLocalservicesV1AccountReport: Format[Schema.GoogleAdsHomeservicesLocalservicesV1AccountReport] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1AccountReport]
	given fmtGoogleAdsHomeservicesLocalservicesV1AggregatorInfo: Format[Schema.GoogleAdsHomeservicesLocalservicesV1AggregatorInfo] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1AggregatorInfo]
	given fmtGoogleAdsHomeservicesLocalservicesV1PhoneLead: Format[Schema.GoogleAdsHomeservicesLocalservicesV1PhoneLead] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1PhoneLead]
	given fmtGoogleAdsHomeservicesLocalservicesV1MessageLead: Format[Schema.GoogleAdsHomeservicesLocalservicesV1MessageLead] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1MessageLead]
	given fmtGoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse: Format[Schema.GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1SearchDetailedLeadReportsResponse]
	given fmtGoogleAdsHomeservicesLocalservicesV1DetailedLeadReport: Format[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport]
	given fmtGoogleTypeTimeZone: Format[Schema.GoogleTypeTimeZone] = Json.format[Schema.GoogleTypeTimeZone]
	given fmtGoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse: Format[Schema.GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1SearchAccountReportsResponse]
	given fmtGoogleAdsHomeservicesLocalservicesV1DetailedLeadReportChargeStatusEnum: Format[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport.ChargeStatusEnum] = JsonEnumFormat[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport.ChargeStatusEnum]
	given fmtGoogleAdsHomeservicesLocalservicesV1BookingLead: Format[Schema.GoogleAdsHomeservicesLocalservicesV1BookingLead] = Json.format[Schema.GoogleAdsHomeservicesLocalservicesV1BookingLead]
	given fmtGoogleAdsHomeservicesLocalservicesV1DetailedLeadReportLeadTypeEnum: Format[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport.LeadTypeEnum] = JsonEnumFormat[Schema.GoogleAdsHomeservicesLocalservicesV1DetailedLeadReport.LeadTypeEnum]
}
