package com.boresjo.play.api.google.gkehub

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putListSchemaOperation: Conversion[List[Schema.Operation], Option[List[Schema.Operation]]] = (fun: List[Schema.Operation]) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaGoogleRpcStatus: Conversion[Schema.GoogleRpcStatus, Option[Schema.GoogleRpcStatus]] = (fun: Schema.GoogleRpcStatus) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putSchemaFeatureConfigRef: Conversion[Schema.FeatureConfigRef, Option[Schema.FeatureConfigRef]] = (fun: Schema.FeatureConfigRef) => Option(fun)
		given putSchemaFeatureSpec: Conversion[Schema.FeatureSpec, Option[Schema.FeatureSpec]] = (fun: Schema.FeatureSpec) => Option(fun)
		given putSchemaFeatureState: Conversion[Schema.FeatureState, Option[Schema.FeatureState]] = (fun: Schema.FeatureState) => Option(fun)
		given putSchemaLifecycleState: Conversion[Schema.LifecycleState, Option[Schema.LifecycleState]] = (fun: Schema.LifecycleState) => Option(fun)
		given putSchemaWorkloadCertificateSpec: Conversion[Schema.WorkloadCertificateSpec, Option[Schema.WorkloadCertificateSpec]] = (fun: Schema.WorkloadCertificateSpec) => Option(fun)
		given putSchemaCloudBuildSpec: Conversion[Schema.CloudBuildSpec, Option[Schema.CloudBuildSpec]] = (fun: Schema.CloudBuildSpec) => Option(fun)
		given putSchemaPolicyControllerSpec: Conversion[Schema.PolicyControllerSpec, Option[Schema.PolicyControllerSpec]] = (fun: Schema.PolicyControllerSpec) => Option(fun)
		given putSchemaIdentityServiceSpec: Conversion[Schema.IdentityServiceSpec, Option[Schema.IdentityServiceSpec]] = (fun: Schema.IdentityServiceSpec) => Option(fun)
		given putSchemaServiceMeshSpec: Conversion[Schema.ServiceMeshSpec, Option[Schema.ServiceMeshSpec]] = (fun: Schema.ServiceMeshSpec) => Option(fun)
		given putSchemaConfigManagementSpec: Conversion[Schema.ConfigManagementSpec, Option[Schema.ConfigManagementSpec]] = (fun: Schema.ConfigManagementSpec) => Option(fun)
		given putSchemaOrigin: Conversion[Schema.Origin, Option[Schema.Origin]] = (fun: Schema.Origin) => Option(fun)
		given putSchemaWorkloadCertificateSpecCertificateManagementEnum: Conversion[Schema.WorkloadCertificateSpec.CertificateManagementEnum, Option[Schema.WorkloadCertificateSpec.CertificateManagementEnum]] = (fun: Schema.WorkloadCertificateSpec.CertificateManagementEnum) => Option(fun)
		given putSchemaCloudBuildSpecSecurityPolicyEnum: Conversion[Schema.CloudBuildSpec.SecurityPolicyEnum, Option[Schema.CloudBuildSpec.SecurityPolicyEnum]] = (fun: Schema.CloudBuildSpec.SecurityPolicyEnum) => Option(fun)
		given putSchemaPolicyControllerHubConfig: Conversion[Schema.PolicyControllerHubConfig, Option[Schema.PolicyControllerHubConfig]] = (fun: Schema.PolicyControllerHubConfig) => Option(fun)
		given putSchemaPolicyControllerHubConfigInstallSpecEnum: Conversion[Schema.PolicyControllerHubConfig.InstallSpecEnum, Option[Schema.PolicyControllerHubConfig.InstallSpecEnum]] = (fun: Schema.PolicyControllerHubConfig.InstallSpecEnum) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaPolicyControllerMonitoringConfig: Conversion[Schema.PolicyControllerMonitoringConfig, Option[Schema.PolicyControllerMonitoringConfig]] = (fun: Schema.PolicyControllerMonitoringConfig) => Option(fun)
		given putSchemaPolicyControllerPolicyContentSpec: Conversion[Schema.PolicyControllerPolicyContentSpec, Option[Schema.PolicyControllerPolicyContentSpec]] = (fun: Schema.PolicyControllerPolicyContentSpec) => Option(fun)
		given putMapStringSchemaPolicyControllerPolicyControllerDeploymentConfig: Conversion[Map[String, Schema.PolicyControllerPolicyControllerDeploymentConfig], Option[Map[String, Schema.PolicyControllerPolicyControllerDeploymentConfig]]] = (fun: Map[String, Schema.PolicyControllerPolicyControllerDeploymentConfig]) => Option(fun)
		given putListSchemaPolicyControllerMonitoringConfigBackendsEnum: Conversion[List[Schema.PolicyControllerMonitoringConfig.BackendsEnum], Option[List[Schema.PolicyControllerMonitoringConfig.BackendsEnum]]] = (fun: List[Schema.PolicyControllerMonitoringConfig.BackendsEnum]) => Option(fun)
		given putMapStringSchemaPolicyControllerBundleInstallSpec: Conversion[Map[String, Schema.PolicyControllerBundleInstallSpec], Option[Map[String, Schema.PolicyControllerBundleInstallSpec]]] = (fun: Map[String, Schema.PolicyControllerBundleInstallSpec]) => Option(fun)
		given putSchemaPolicyControllerTemplateLibraryConfig: Conversion[Schema.PolicyControllerTemplateLibraryConfig, Option[Schema.PolicyControllerTemplateLibraryConfig]] = (fun: Schema.PolicyControllerTemplateLibraryConfig) => Option(fun)
		given putSchemaPolicyControllerTemplateLibraryConfigInstallationEnum: Conversion[Schema.PolicyControllerTemplateLibraryConfig.InstallationEnum, Option[Schema.PolicyControllerTemplateLibraryConfig.InstallationEnum]] = (fun: Schema.PolicyControllerTemplateLibraryConfig.InstallationEnum) => Option(fun)
		given putSchemaPolicyControllerResourceRequirements: Conversion[Schema.PolicyControllerResourceRequirements, Option[Schema.PolicyControllerResourceRequirements]] = (fun: Schema.PolicyControllerResourceRequirements) => Option(fun)
		given putListSchemaPolicyControllerToleration: Conversion[List[Schema.PolicyControllerToleration], Option[List[Schema.PolicyControllerToleration]]] = (fun: List[Schema.PolicyControllerToleration]) => Option(fun)
		given putSchemaPolicyControllerPolicyControllerDeploymentConfigPodAffinityEnum: Conversion[Schema.PolicyControllerPolicyControllerDeploymentConfig.PodAffinityEnum, Option[Schema.PolicyControllerPolicyControllerDeploymentConfig.PodAffinityEnum]] = (fun: Schema.PolicyControllerPolicyControllerDeploymentConfig.PodAffinityEnum) => Option(fun)
		given putSchemaPolicyControllerResourceList: Conversion[Schema.PolicyControllerResourceList, Option[Schema.PolicyControllerResourceList]] = (fun: Schema.PolicyControllerResourceList) => Option(fun)
		given putListSchemaIdentityServiceAuthMethod: Conversion[List[Schema.IdentityServiceAuthMethod], Option[List[Schema.IdentityServiceAuthMethod]]] = (fun: List[Schema.IdentityServiceAuthMethod]) => Option(fun)
		given putSchemaIdentityServiceIdentityServiceOptions: Conversion[Schema.IdentityServiceIdentityServiceOptions, Option[Schema.IdentityServiceIdentityServiceOptions]] = (fun: Schema.IdentityServiceIdentityServiceOptions) => Option(fun)
		given putSchemaIdentityServiceOidcConfig: Conversion[Schema.IdentityServiceOidcConfig, Option[Schema.IdentityServiceOidcConfig]] = (fun: Schema.IdentityServiceOidcConfig) => Option(fun)
		given putSchemaIdentityServiceAzureADConfig: Conversion[Schema.IdentityServiceAzureADConfig, Option[Schema.IdentityServiceAzureADConfig]] = (fun: Schema.IdentityServiceAzureADConfig) => Option(fun)
		given putSchemaIdentityServiceGoogleConfig: Conversion[Schema.IdentityServiceGoogleConfig, Option[Schema.IdentityServiceGoogleConfig]] = (fun: Schema.IdentityServiceGoogleConfig) => Option(fun)
		given putSchemaIdentityServiceSamlConfig: Conversion[Schema.IdentityServiceSamlConfig, Option[Schema.IdentityServiceSamlConfig]] = (fun: Schema.IdentityServiceSamlConfig) => Option(fun)
		given putSchemaIdentityServiceLdapConfig: Conversion[Schema.IdentityServiceLdapConfig, Option[Schema.IdentityServiceLdapConfig]] = (fun: Schema.IdentityServiceLdapConfig) => Option(fun)
		given putSchemaIdentityServiceServerConfig: Conversion[Schema.IdentityServiceServerConfig, Option[Schema.IdentityServiceServerConfig]] = (fun: Schema.IdentityServiceServerConfig) => Option(fun)
		given putSchemaIdentityServiceUserConfig: Conversion[Schema.IdentityServiceUserConfig, Option[Schema.IdentityServiceUserConfig]] = (fun: Schema.IdentityServiceUserConfig) => Option(fun)
		given putSchemaIdentityServiceGroupConfig: Conversion[Schema.IdentityServiceGroupConfig, Option[Schema.IdentityServiceGroupConfig]] = (fun: Schema.IdentityServiceGroupConfig) => Option(fun)
		given putSchemaIdentityServiceServiceAccountConfig: Conversion[Schema.IdentityServiceServiceAccountConfig, Option[Schema.IdentityServiceServiceAccountConfig]] = (fun: Schema.IdentityServiceServiceAccountConfig) => Option(fun)
		given putSchemaIdentityServiceSimpleBindCredentials: Conversion[Schema.IdentityServiceSimpleBindCredentials, Option[Schema.IdentityServiceSimpleBindCredentials]] = (fun: Schema.IdentityServiceSimpleBindCredentials) => Option(fun)
		given putSchemaIdentityServiceDiagnosticInterface: Conversion[Schema.IdentityServiceDiagnosticInterface, Option[Schema.IdentityServiceDiagnosticInterface]] = (fun: Schema.IdentityServiceDiagnosticInterface) => Option(fun)
		given putSchemaServiceMeshSpecControlPlaneEnum: Conversion[Schema.ServiceMeshSpec.ControlPlaneEnum, Option[Schema.ServiceMeshSpec.ControlPlaneEnum]] = (fun: Schema.ServiceMeshSpec.ControlPlaneEnum) => Option(fun)
		given putSchemaServiceMeshSpecDefaultChannelEnum: Conversion[Schema.ServiceMeshSpec.DefaultChannelEnum, Option[Schema.ServiceMeshSpec.DefaultChannelEnum]] = (fun: Schema.ServiceMeshSpec.DefaultChannelEnum) => Option(fun)
		given putSchemaServiceMeshSpecManagementEnum: Conversion[Schema.ServiceMeshSpec.ManagementEnum, Option[Schema.ServiceMeshSpec.ManagementEnum]] = (fun: Schema.ServiceMeshSpec.ManagementEnum) => Option(fun)
		given putSchemaServiceMeshSpecConfigApiEnum: Conversion[Schema.ServiceMeshSpec.ConfigApiEnum, Option[Schema.ServiceMeshSpec.ConfigApiEnum]] = (fun: Schema.ServiceMeshSpec.ConfigApiEnum) => Option(fun)
		given putSchemaConfigManagementConfigSync: Conversion[Schema.ConfigManagementConfigSync, Option[Schema.ConfigManagementConfigSync]] = (fun: Schema.ConfigManagementConfigSync) => Option(fun)
		given putSchemaConfigManagementPolicyController: Conversion[Schema.ConfigManagementPolicyController, Option[Schema.ConfigManagementPolicyController]] = (fun: Schema.ConfigManagementPolicyController) => Option(fun)
		given putSchemaConfigManagementBinauthzConfig: Conversion[Schema.ConfigManagementBinauthzConfig, Option[Schema.ConfigManagementBinauthzConfig]] = (fun: Schema.ConfigManagementBinauthzConfig) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerConfig: Conversion[Schema.ConfigManagementHierarchyControllerConfig, Option[Schema.ConfigManagementHierarchyControllerConfig]] = (fun: Schema.ConfigManagementHierarchyControllerConfig) => Option(fun)
		given putSchemaConfigManagementSpecManagementEnum: Conversion[Schema.ConfigManagementSpec.ManagementEnum, Option[Schema.ConfigManagementSpec.ManagementEnum]] = (fun: Schema.ConfigManagementSpec.ManagementEnum) => Option(fun)
		given putSchemaConfigManagementGitConfig: Conversion[Schema.ConfigManagementGitConfig, Option[Schema.ConfigManagementGitConfig]] = (fun: Schema.ConfigManagementGitConfig) => Option(fun)
		given putSchemaConfigManagementOciConfig: Conversion[Schema.ConfigManagementOciConfig, Option[Schema.ConfigManagementOciConfig]] = (fun: Schema.ConfigManagementOciConfig) => Option(fun)
		given putSchemaConfigManagementPolicyControllerMonitoring: Conversion[Schema.ConfigManagementPolicyControllerMonitoring, Option[Schema.ConfigManagementPolicyControllerMonitoring]] = (fun: Schema.ConfigManagementPolicyControllerMonitoring) => Option(fun)
		given putListSchemaConfigManagementPolicyControllerMonitoringBackendsEnum: Conversion[List[Schema.ConfigManagementPolicyControllerMonitoring.BackendsEnum], Option[List[Schema.ConfigManagementPolicyControllerMonitoring.BackendsEnum]]] = (fun: List[Schema.ConfigManagementPolicyControllerMonitoring.BackendsEnum]) => Option(fun)
		given putSchemaOriginTypeEnum: Conversion[Schema.Origin.TypeEnum, Option[Schema.Origin.TypeEnum]] = (fun: Schema.Origin.TypeEnum) => Option(fun)
		given putSchemaClusterUpgradeState: Conversion[Schema.ClusterUpgradeState, Option[Schema.ClusterUpgradeState]] = (fun: Schema.ClusterUpgradeState) => Option(fun)
		given putSchemaIdentityServiceState: Conversion[Schema.IdentityServiceState, Option[Schema.IdentityServiceState]] = (fun: Schema.IdentityServiceState) => Option(fun)
		given putSchemaServiceMeshState: Conversion[Schema.ServiceMeshState, Option[Schema.ServiceMeshState]] = (fun: Schema.ServiceMeshState) => Option(fun)
		given putSchemaMeteringState: Conversion[Schema.MeteringState, Option[Schema.MeteringState]] = (fun: Schema.MeteringState) => Option(fun)
		given putSchemaConfigManagementState: Conversion[Schema.ConfigManagementState, Option[Schema.ConfigManagementState]] = (fun: Schema.ConfigManagementState) => Option(fun)
		given putSchemaPolicyControllerState: Conversion[Schema.PolicyControllerState, Option[Schema.PolicyControllerState]] = (fun: Schema.PolicyControllerState) => Option(fun)
		given putSchemaAppDevExperienceState: Conversion[Schema.AppDevExperienceState, Option[Schema.AppDevExperienceState]] = (fun: Schema.AppDevExperienceState) => Option(fun)
		given putSchemaState: Conversion[Schema.State, Option[Schema.State]] = (fun: Schema.State) => Option(fun)
		given putSchemaClusterUpgradeIgnoredMembership: Conversion[Schema.ClusterUpgradeIgnoredMembership, Option[Schema.ClusterUpgradeIgnoredMembership]] = (fun: Schema.ClusterUpgradeIgnoredMembership) => Option(fun)
		given putListSchemaClusterUpgradeMembershipGKEUpgradeState: Conversion[List[Schema.ClusterUpgradeMembershipGKEUpgradeState], Option[List[Schema.ClusterUpgradeMembershipGKEUpgradeState]]] = (fun: List[Schema.ClusterUpgradeMembershipGKEUpgradeState]) => Option(fun)
		given putSchemaClusterUpgradeGKEUpgrade: Conversion[Schema.ClusterUpgradeGKEUpgrade, Option[Schema.ClusterUpgradeGKEUpgrade]] = (fun: Schema.ClusterUpgradeGKEUpgrade) => Option(fun)
		given putSchemaClusterUpgradeUpgradeStatus: Conversion[Schema.ClusterUpgradeUpgradeStatus, Option[Schema.ClusterUpgradeUpgradeStatus]] = (fun: Schema.ClusterUpgradeUpgradeStatus) => Option(fun)
		given putSchemaClusterUpgradeUpgradeStatusCodeEnum: Conversion[Schema.ClusterUpgradeUpgradeStatus.CodeEnum, Option[Schema.ClusterUpgradeUpgradeStatus.CodeEnum]] = (fun: Schema.ClusterUpgradeUpgradeStatus.CodeEnum) => Option(fun)
		given putSchemaIdentityServiceStateStateEnum: Conversion[Schema.IdentityServiceState.StateEnum, Option[Schema.IdentityServiceState.StateEnum]] = (fun: Schema.IdentityServiceState.StateEnum) => Option(fun)
		given putListSchemaServiceMeshAnalysisMessage: Conversion[List[Schema.ServiceMeshAnalysisMessage], Option[List[Schema.ServiceMeshAnalysisMessage]]] = (fun: List[Schema.ServiceMeshAnalysisMessage]) => Option(fun)
		given putSchemaServiceMeshControlPlaneManagement: Conversion[Schema.ServiceMeshControlPlaneManagement, Option[Schema.ServiceMeshControlPlaneManagement]] = (fun: Schema.ServiceMeshControlPlaneManagement) => Option(fun)
		given putSchemaServiceMeshDataPlaneManagement: Conversion[Schema.ServiceMeshDataPlaneManagement, Option[Schema.ServiceMeshDataPlaneManagement]] = (fun: Schema.ServiceMeshDataPlaneManagement) => Option(fun)
		given putListSchemaServiceMeshCondition: Conversion[List[Schema.ServiceMeshCondition], Option[List[Schema.ServiceMeshCondition]]] = (fun: List[Schema.ServiceMeshCondition]) => Option(fun)
		given putSchemaServiceMeshAnalysisMessageBase: Conversion[Schema.ServiceMeshAnalysisMessageBase, Option[Schema.ServiceMeshAnalysisMessageBase]] = (fun: Schema.ServiceMeshAnalysisMessageBase) => Option(fun)
		given putSchemaServiceMeshType: Conversion[Schema.ServiceMeshType, Option[Schema.ServiceMeshType]] = (fun: Schema.ServiceMeshType) => Option(fun)
		given putSchemaServiceMeshAnalysisMessageBaseLevelEnum: Conversion[Schema.ServiceMeshAnalysisMessageBase.LevelEnum, Option[Schema.ServiceMeshAnalysisMessageBase.LevelEnum]] = (fun: Schema.ServiceMeshAnalysisMessageBase.LevelEnum) => Option(fun)
		given putListSchemaServiceMeshStatusDetails: Conversion[List[Schema.ServiceMeshStatusDetails], Option[List[Schema.ServiceMeshStatusDetails]]] = (fun: List[Schema.ServiceMeshStatusDetails]) => Option(fun)
		given putSchemaServiceMeshControlPlaneManagementStateEnum: Conversion[Schema.ServiceMeshControlPlaneManagement.StateEnum, Option[Schema.ServiceMeshControlPlaneManagement.StateEnum]] = (fun: Schema.ServiceMeshControlPlaneManagement.StateEnum) => Option(fun)
		given putSchemaServiceMeshControlPlaneManagementImplementationEnum: Conversion[Schema.ServiceMeshControlPlaneManagement.ImplementationEnum, Option[Schema.ServiceMeshControlPlaneManagement.ImplementationEnum]] = (fun: Schema.ServiceMeshControlPlaneManagement.ImplementationEnum) => Option(fun)
		given putSchemaServiceMeshDataPlaneManagementStateEnum: Conversion[Schema.ServiceMeshDataPlaneManagement.StateEnum, Option[Schema.ServiceMeshDataPlaneManagement.StateEnum]] = (fun: Schema.ServiceMeshDataPlaneManagement.StateEnum) => Option(fun)
		given putSchemaServiceMeshConditionCodeEnum: Conversion[Schema.ServiceMeshCondition.CodeEnum, Option[Schema.ServiceMeshCondition.CodeEnum]] = (fun: Schema.ServiceMeshCondition.CodeEnum) => Option(fun)
		given putSchemaServiceMeshConditionSeverityEnum: Conversion[Schema.ServiceMeshCondition.SeverityEnum, Option[Schema.ServiceMeshCondition.SeverityEnum]] = (fun: Schema.ServiceMeshCondition.SeverityEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putSchemaConfigManagementOperatorState: Conversion[Schema.ConfigManagementOperatorState, Option[Schema.ConfigManagementOperatorState]] = (fun: Schema.ConfigManagementOperatorState) => Option(fun)
		given putSchemaConfigManagementConfigSyncState: Conversion[Schema.ConfigManagementConfigSyncState, Option[Schema.ConfigManagementConfigSyncState]] = (fun: Schema.ConfigManagementConfigSyncState) => Option(fun)
		given putSchemaConfigManagementPolicyControllerState: Conversion[Schema.ConfigManagementPolicyControllerState, Option[Schema.ConfigManagementPolicyControllerState]] = (fun: Schema.ConfigManagementPolicyControllerState) => Option(fun)
		given putSchemaConfigManagementBinauthzState: Conversion[Schema.ConfigManagementBinauthzState, Option[Schema.ConfigManagementBinauthzState]] = (fun: Schema.ConfigManagementBinauthzState) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerState: Conversion[Schema.ConfigManagementHierarchyControllerState, Option[Schema.ConfigManagementHierarchyControllerState]] = (fun: Schema.ConfigManagementHierarchyControllerState) => Option(fun)
		given putSchemaConfigManagementOperatorStateDeploymentStateEnum: Conversion[Schema.ConfigManagementOperatorState.DeploymentStateEnum, Option[Schema.ConfigManagementOperatorState.DeploymentStateEnum]] = (fun: Schema.ConfigManagementOperatorState.DeploymentStateEnum) => Option(fun)
		given putListSchemaConfigManagementInstallError: Conversion[List[Schema.ConfigManagementInstallError], Option[List[Schema.ConfigManagementInstallError]]] = (fun: List[Schema.ConfigManagementInstallError]) => Option(fun)
		given putSchemaConfigManagementConfigSyncVersion: Conversion[Schema.ConfigManagementConfigSyncVersion, Option[Schema.ConfigManagementConfigSyncVersion]] = (fun: Schema.ConfigManagementConfigSyncVersion) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentState: Conversion[Schema.ConfigManagementConfigSyncDeploymentState, Option[Schema.ConfigManagementConfigSyncDeploymentState]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState) => Option(fun)
		given putSchemaConfigManagementSyncState: Conversion[Schema.ConfigManagementSyncState, Option[Schema.ConfigManagementSyncState]] = (fun: Schema.ConfigManagementSyncState) => Option(fun)
		given putListSchemaConfigManagementConfigSyncError: Conversion[List[Schema.ConfigManagementConfigSyncError], Option[List[Schema.ConfigManagementConfigSyncError]]] = (fun: List[Schema.ConfigManagementConfigSyncError]) => Option(fun)
		given putSchemaConfigManagementConfigSyncStateRootsyncCrdEnum: Conversion[Schema.ConfigManagementConfigSyncState.RootsyncCrdEnum, Option[Schema.ConfigManagementConfigSyncState.RootsyncCrdEnum]] = (fun: Schema.ConfigManagementConfigSyncState.RootsyncCrdEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncStateReposyncCrdEnum: Conversion[Schema.ConfigManagementConfigSyncState.ReposyncCrdEnum, Option[Schema.ConfigManagementConfigSyncState.ReposyncCrdEnum]] = (fun: Schema.ConfigManagementConfigSyncState.ReposyncCrdEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncStateStateEnum: Conversion[Schema.ConfigManagementConfigSyncState.StateEnum, Option[Schema.ConfigManagementConfigSyncState.StateEnum]] = (fun: Schema.ConfigManagementConfigSyncState.StateEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncStateClusterLevelStopSyncingStateEnum: Conversion[Schema.ConfigManagementConfigSyncState.ClusterLevelStopSyncingStateEnum, Option[Schema.ConfigManagementConfigSyncState.ClusterLevelStopSyncingStateEnum]] = (fun: Schema.ConfigManagementConfigSyncState.ClusterLevelStopSyncingStateEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateImporterEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.ImporterEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.ImporterEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.ImporterEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateSyncerEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.SyncerEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.SyncerEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.SyncerEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateGitSyncEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.GitSyncEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.GitSyncEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.GitSyncEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateMonitorEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.MonitorEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.MonitorEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.MonitorEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateReconcilerManagerEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.ReconcilerManagerEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.ReconcilerManagerEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.ReconcilerManagerEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateRootReconcilerEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.RootReconcilerEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.RootReconcilerEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.RootReconcilerEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateAdmissionWebhookEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.AdmissionWebhookEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.AdmissionWebhookEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.AdmissionWebhookEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateResourceGroupControllerManagerEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.ResourceGroupControllerManagerEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.ResourceGroupControllerManagerEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.ResourceGroupControllerManagerEnum) => Option(fun)
		given putSchemaConfigManagementConfigSyncDeploymentStateOtelCollectorEnum: Conversion[Schema.ConfigManagementConfigSyncDeploymentState.OtelCollectorEnum, Option[Schema.ConfigManagementConfigSyncDeploymentState.OtelCollectorEnum]] = (fun: Schema.ConfigManagementConfigSyncDeploymentState.OtelCollectorEnum) => Option(fun)
		given putSchemaConfigManagementSyncStateCodeEnum: Conversion[Schema.ConfigManagementSyncState.CodeEnum, Option[Schema.ConfigManagementSyncState.CodeEnum]] = (fun: Schema.ConfigManagementSyncState.CodeEnum) => Option(fun)
		given putListSchemaConfigManagementSyncError: Conversion[List[Schema.ConfigManagementSyncError], Option[List[Schema.ConfigManagementSyncError]]] = (fun: List[Schema.ConfigManagementSyncError]) => Option(fun)
		given putListSchemaConfigManagementErrorResource: Conversion[List[Schema.ConfigManagementErrorResource], Option[List[Schema.ConfigManagementErrorResource]]] = (fun: List[Schema.ConfigManagementErrorResource]) => Option(fun)
		given putSchemaConfigManagementGroupVersionKind: Conversion[Schema.ConfigManagementGroupVersionKind, Option[Schema.ConfigManagementGroupVersionKind]] = (fun: Schema.ConfigManagementGroupVersionKind) => Option(fun)
		given putSchemaConfigManagementPolicyControllerVersion: Conversion[Schema.ConfigManagementPolicyControllerVersion, Option[Schema.ConfigManagementPolicyControllerVersion]] = (fun: Schema.ConfigManagementPolicyControllerVersion) => Option(fun)
		given putSchemaConfigManagementGatekeeperDeploymentState: Conversion[Schema.ConfigManagementGatekeeperDeploymentState, Option[Schema.ConfigManagementGatekeeperDeploymentState]] = (fun: Schema.ConfigManagementGatekeeperDeploymentState) => Option(fun)
		given putSchemaConfigManagementPolicyControllerMigration: Conversion[Schema.ConfigManagementPolicyControllerMigration, Option[Schema.ConfigManagementPolicyControllerMigration]] = (fun: Schema.ConfigManagementPolicyControllerMigration) => Option(fun)
		given putSchemaConfigManagementGatekeeperDeploymentStateGatekeeperControllerManagerStateEnum: Conversion[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperControllerManagerStateEnum, Option[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperControllerManagerStateEnum]] = (fun: Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperControllerManagerStateEnum) => Option(fun)
		given putSchemaConfigManagementGatekeeperDeploymentStateGatekeeperAuditEnum: Conversion[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperAuditEnum, Option[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperAuditEnum]] = (fun: Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperAuditEnum) => Option(fun)
		given putSchemaConfigManagementGatekeeperDeploymentStateGatekeeperMutationEnum: Conversion[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperMutationEnum, Option[Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperMutationEnum]] = (fun: Schema.ConfigManagementGatekeeperDeploymentState.GatekeeperMutationEnum) => Option(fun)
		given putSchemaConfigManagementPolicyControllerMigrationStageEnum: Conversion[Schema.ConfigManagementPolicyControllerMigration.StageEnum, Option[Schema.ConfigManagementPolicyControllerMigration.StageEnum]] = (fun: Schema.ConfigManagementPolicyControllerMigration.StageEnum) => Option(fun)
		given putSchemaConfigManagementBinauthzStateWebhookEnum: Conversion[Schema.ConfigManagementBinauthzState.WebhookEnum, Option[Schema.ConfigManagementBinauthzState.WebhookEnum]] = (fun: Schema.ConfigManagementBinauthzState.WebhookEnum) => Option(fun)
		given putSchemaConfigManagementBinauthzVersion: Conversion[Schema.ConfigManagementBinauthzVersion, Option[Schema.ConfigManagementBinauthzVersion]] = (fun: Schema.ConfigManagementBinauthzVersion) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerVersion: Conversion[Schema.ConfigManagementHierarchyControllerVersion, Option[Schema.ConfigManagementHierarchyControllerVersion]] = (fun: Schema.ConfigManagementHierarchyControllerVersion) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerDeploymentState: Conversion[Schema.ConfigManagementHierarchyControllerDeploymentState, Option[Schema.ConfigManagementHierarchyControllerDeploymentState]] = (fun: Schema.ConfigManagementHierarchyControllerDeploymentState) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerDeploymentStateHncEnum: Conversion[Schema.ConfigManagementHierarchyControllerDeploymentState.HncEnum, Option[Schema.ConfigManagementHierarchyControllerDeploymentState.HncEnum]] = (fun: Schema.ConfigManagementHierarchyControllerDeploymentState.HncEnum) => Option(fun)
		given putSchemaConfigManagementHierarchyControllerDeploymentStateExtensionEnum: Conversion[Schema.ConfigManagementHierarchyControllerDeploymentState.ExtensionEnum, Option[Schema.ConfigManagementHierarchyControllerDeploymentState.ExtensionEnum]] = (fun: Schema.ConfigManagementHierarchyControllerDeploymentState.ExtensionEnum) => Option(fun)
		given putMapStringSchemaPolicyControllerOnClusterState: Conversion[Map[String, Schema.PolicyControllerOnClusterState], Option[Map[String, Schema.PolicyControllerOnClusterState]]] = (fun: Map[String, Schema.PolicyControllerOnClusterState]) => Option(fun)
		given putSchemaPolicyControllerStateStateEnum: Conversion[Schema.PolicyControllerState.StateEnum, Option[Schema.PolicyControllerState.StateEnum]] = (fun: Schema.PolicyControllerState.StateEnum) => Option(fun)
		given putSchemaPolicyControllerPolicyContentState: Conversion[Schema.PolicyControllerPolicyContentState, Option[Schema.PolicyControllerPolicyContentState]] = (fun: Schema.PolicyControllerPolicyContentState) => Option(fun)
		given putSchemaPolicyControllerOnClusterStateStateEnum: Conversion[Schema.PolicyControllerOnClusterState.StateEnum, Option[Schema.PolicyControllerOnClusterState.StateEnum]] = (fun: Schema.PolicyControllerOnClusterState.StateEnum) => Option(fun)
		given putSchemaPolicyControllerOnClusterState: Conversion[Schema.PolicyControllerOnClusterState, Option[Schema.PolicyControllerOnClusterState]] = (fun: Schema.PolicyControllerOnClusterState) => Option(fun)
		given putSchemaAppDevExperienceStatus: Conversion[Schema.AppDevExperienceStatus, Option[Schema.AppDevExperienceStatus]] = (fun: Schema.AppDevExperienceStatus) => Option(fun)
		given putSchemaAppDevExperienceStatusCodeEnum: Conversion[Schema.AppDevExperienceStatus.CodeEnum, Option[Schema.AppDevExperienceStatus.CodeEnum]] = (fun: Schema.AppDevExperienceStatus.CodeEnum) => Option(fun)
		given putSchemaStateCodeEnum: Conversion[Schema.State.CodeEnum, Option[Schema.State.CodeEnum]] = (fun: Schema.State.CodeEnum) => Option(fun)
		given putSchemaLifecycleStateStateEnum: Conversion[Schema.LifecycleState.StateEnum, Option[Schema.LifecycleState.StateEnum]] = (fun: Schema.LifecycleState.StateEnum) => Option(fun)
		given putListSchemaMembershipFeature: Conversion[List[Schema.MembershipFeature], Option[List[Schema.MembershipFeature]]] = (fun: List[Schema.MembershipFeature]) => Option(fun)
		given putListSchemaLocation: Conversion[List[Schema.Location], Option[List[Schema.Location]]] = (fun: List[Schema.Location]) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
