package com.boresjo.play.api.google.memcache

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtListInstancesResponse: Format[Schema.ListInstancesResponse] = Json.format[Schema.ListInstancesResponse]
	given fmtInstance: Format[Schema.Instance] = Json.format[Schema.Instance]
	given fmtNodeConfig: Format[Schema.NodeConfig] = Json.format[Schema.NodeConfig]
	given fmtInstanceMemcacheVersionEnum: Format[Schema.Instance.MemcacheVersionEnum] = JsonEnumFormat[Schema.Instance.MemcacheVersionEnum]
	given fmtMemcacheParameters: Format[Schema.MemcacheParameters] = Json.format[Schema.MemcacheParameters]
	given fmtNode: Format[Schema.Node] = Json.format[Schema.Node]
	given fmtInstanceStateEnum: Format[Schema.Instance.StateEnum] = JsonEnumFormat[Schema.Instance.StateEnum]
	given fmtInstanceMessage: Format[Schema.InstanceMessage] = Json.format[Schema.InstanceMessage]
	given fmtGoogleCloudMemcacheV1MaintenancePolicy: Format[Schema.GoogleCloudMemcacheV1MaintenancePolicy] = Json.format[Schema.GoogleCloudMemcacheV1MaintenancePolicy]
	given fmtMaintenanceSchedule: Format[Schema.MaintenanceSchedule] = Json.format[Schema.MaintenanceSchedule]
	given fmtNodeStateEnum: Format[Schema.Node.StateEnum] = JsonEnumFormat[Schema.Node.StateEnum]
	given fmtNodeMemcacheVersionEnum: Format[Schema.Node.MemcacheVersionEnum] = JsonEnumFormat[Schema.Node.MemcacheVersionEnum]
	given fmtInstanceMessageCodeEnum: Format[Schema.InstanceMessage.CodeEnum] = JsonEnumFormat[Schema.InstanceMessage.CodeEnum]
	given fmtWeeklyMaintenanceWindow: Format[Schema.WeeklyMaintenanceWindow] = Json.format[Schema.WeeklyMaintenanceWindow]
	given fmtWeeklyMaintenanceWindowDayEnum: Format[Schema.WeeklyMaintenanceWindow.DayEnum] = JsonEnumFormat[Schema.WeeklyMaintenanceWindow.DayEnum]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtUpdateParametersRequest: Format[Schema.UpdateParametersRequest] = Json.format[Schema.UpdateParametersRequest]
	given fmtApplyParametersRequest: Format[Schema.ApplyParametersRequest] = Json.format[Schema.ApplyParametersRequest]
	given fmtRescheduleMaintenanceRequest: Format[Schema.RescheduleMaintenanceRequest] = Json.format[Schema.RescheduleMaintenanceRequest]
	given fmtRescheduleMaintenanceRequestRescheduleTypeEnum: Format[Schema.RescheduleMaintenanceRequest.RescheduleTypeEnum] = JsonEnumFormat[Schema.RescheduleMaintenanceRequest.RescheduleTypeEnum]
	given fmtGoogleCloudMemcacheV1UpgradeInstanceRequest: Format[Schema.GoogleCloudMemcacheV1UpgradeInstanceRequest] = Json.format[Schema.GoogleCloudMemcacheV1UpgradeInstanceRequest]
	given fmtGoogleCloudMemcacheV1UpgradeInstanceRequestMemcacheVersionEnum: Format[Schema.GoogleCloudMemcacheV1UpgradeInstanceRequest.MemcacheVersionEnum] = JsonEnumFormat[Schema.GoogleCloudMemcacheV1UpgradeInstanceRequest.MemcacheVersionEnum]
	given fmtGoogleCloudMemcacheV1LocationMetadata: Format[Schema.GoogleCloudMemcacheV1LocationMetadata] = Json.format[Schema.GoogleCloudMemcacheV1LocationMetadata]
	given fmtGoogleCloudMemcacheV1ZoneMetadata: Format[Schema.GoogleCloudMemcacheV1ZoneMetadata] = Json.format[Schema.GoogleCloudMemcacheV1ZoneMetadata]
	given fmtLocationMetadata: Format[Schema.LocationMetadata] = Json.format[Schema.LocationMetadata]
	given fmtZoneMetadata: Format[Schema.ZoneMetadata] = Json.format[Schema.ZoneMetadata]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
	given fmtGoogleCloudMemcacheV1OperationMetadata: Format[Schema.GoogleCloudMemcacheV1OperationMetadata] = Json.format[Schema.GoogleCloudMemcacheV1OperationMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1Instance: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1InstanceStateEnum: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance.StateEnum] = JsonEnumFormat[Schema.GoogleCloudSaasacceleratorManagementProvidersV1Instance.StateEnum]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1ProvisionedResource]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1SloMetadata: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSchedule]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1MaintenanceSettings]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NotificationParameter]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1NodeSloMetadata]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1PerSliSloEligibility]
	given fmtGoogleCloudSaasacceleratorManagementProvidersV1SloEligibility: Format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility] = Json.format[Schema.GoogleCloudSaasacceleratorManagementProvidersV1SloEligibility]
	given fmtMaintenancePolicy: Format[Schema.MaintenancePolicy] = Json.format[Schema.MaintenancePolicy]
	given fmtMaintenancePolicyStateEnum: Format[Schema.MaintenancePolicy.StateEnum] = JsonEnumFormat[Schema.MaintenancePolicy.StateEnum]
	given fmtUpdatePolicy: Format[Schema.UpdatePolicy] = Json.format[Schema.UpdatePolicy]
	given fmtMaintenanceWindow: Format[Schema.MaintenanceWindow] = Json.format[Schema.MaintenanceWindow]
	given fmtUpdatePolicyChannelEnum: Format[Schema.UpdatePolicy.ChannelEnum] = JsonEnumFormat[Schema.UpdatePolicy.ChannelEnum]
	given fmtDenyMaintenancePeriod: Format[Schema.DenyMaintenancePeriod] = Json.format[Schema.DenyMaintenancePeriod]
	given fmtDailyCycle: Format[Schema.DailyCycle] = Json.format[Schema.DailyCycle]
	given fmtWeeklyCycle: Format[Schema.WeeklyCycle] = Json.format[Schema.WeeklyCycle]
	given fmtSchedule: Format[Schema.Schedule] = Json.format[Schema.Schedule]
	given fmtScheduleDayEnum: Format[Schema.Schedule.DayEnum] = JsonEnumFormat[Schema.Schedule.DayEnum]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
	given fmtAssetLocation: Format[Schema.AssetLocation] = Json.format[Schema.AssetLocation]
	given fmtIsolationExpectations: Format[Schema.IsolationExpectations] = Json.format[Schema.IsolationExpectations]
	given fmtLocationData: Format[Schema.LocationData] = Json.format[Schema.LocationData]
	given fmtCloudAsset: Format[Schema.CloudAsset] = Json.format[Schema.CloudAsset]
	given fmtExtraParameter: Format[Schema.ExtraParameter] = Json.format[Schema.ExtraParameter]
	given fmtIsolationExpectationsZoneIsolationEnum: Format[Schema.IsolationExpectations.ZoneIsolationEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZoneIsolationEnum]
	given fmtIsolationExpectationsZoneSeparationEnum: Format[Schema.IsolationExpectations.ZoneSeparationEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZoneSeparationEnum]
	given fmtIsolationExpectationsZsOrgPolicyEnum: Format[Schema.IsolationExpectations.ZsOrgPolicyEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZsOrgPolicyEnum]
	given fmtIsolationExpectationsZsRegionStateEnum: Format[Schema.IsolationExpectations.ZsRegionStateEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZsRegionStateEnum]
	given fmtIsolationExpectationsZiOrgPolicyEnum: Format[Schema.IsolationExpectations.ZiOrgPolicyEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZiOrgPolicyEnum]
	given fmtIsolationExpectationsZiRegionPolicyEnum: Format[Schema.IsolationExpectations.ZiRegionPolicyEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZiRegionPolicyEnum]
	given fmtIsolationExpectationsZiRegionStateEnum: Format[Schema.IsolationExpectations.ZiRegionStateEnum] = JsonEnumFormat[Schema.IsolationExpectations.ZiRegionStateEnum]
	given fmtRequirementOverride: Format[Schema.RequirementOverride] = Json.format[Schema.RequirementOverride]
	given fmtRequirementOverrideZiOverrideEnum: Format[Schema.RequirementOverride.ZiOverrideEnum] = JsonEnumFormat[Schema.RequirementOverride.ZiOverrideEnum]
	given fmtRequirementOverrideZsOverrideEnum: Format[Schema.RequirementOverride.ZsOverrideEnum] = JsonEnumFormat[Schema.RequirementOverride.ZsOverrideEnum]
	given fmtDirectLocationAssignment: Format[Schema.DirectLocationAssignment] = Json.format[Schema.DirectLocationAssignment]
	given fmtSpannerLocation: Format[Schema.SpannerLocation] = Json.format[Schema.SpannerLocation]
	given fmtCloudAssetComposition: Format[Schema.CloudAssetComposition] = Json.format[Schema.CloudAssetComposition]
	given fmtTenantProjectProxy: Format[Schema.TenantProjectProxy] = Json.format[Schema.TenantProjectProxy]
	given fmtBlobstoreLocation: Format[Schema.BlobstoreLocation] = Json.format[Schema.BlobstoreLocation]
	given fmtPlacerLocation: Format[Schema.PlacerLocation] = Json.format[Schema.PlacerLocation]
	given fmtLocationAssignment: Format[Schema.LocationAssignment] = Json.format[Schema.LocationAssignment]
	given fmtLocationAssignmentLocationTypeEnum: Format[Schema.LocationAssignment.LocationTypeEnum] = JsonEnumFormat[Schema.LocationAssignment.LocationTypeEnum]
	given fmtRegionalMigDistributionPolicy: Format[Schema.RegionalMigDistributionPolicy] = Json.format[Schema.RegionalMigDistributionPolicy]
	given fmtZoneConfiguration: Format[Schema.ZoneConfiguration] = Json.format[Schema.ZoneConfiguration]
}
