package com.boresjo.play.api.google.tagmanager

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListAccountsResponse: Format[Schema.ListAccountsResponse] = Json.format[Schema.ListAccountsResponse]
	given fmtAccount: Format[Schema.Account] = Json.format[Schema.Account]
	given fmtAccountFeatures: Format[Schema.AccountFeatures] = Json.format[Schema.AccountFeatures]
	given fmtUserPermission: Format[Schema.UserPermission] = Json.format[Schema.UserPermission]
	given fmtAccountAccess: Format[Schema.AccountAccess] = Json.format[Schema.AccountAccess]
	given fmtContainerAccess: Format[Schema.ContainerAccess] = Json.format[Schema.ContainerAccess]
	given fmtAccountAccessPermissionEnum: Format[Schema.AccountAccess.PermissionEnum] = JsonEnumFormat[Schema.AccountAccess.PermissionEnum]
	given fmtContainerAccessPermissionEnum: Format[Schema.ContainerAccess.PermissionEnum] = JsonEnumFormat[Schema.ContainerAccess.PermissionEnum]
	given fmtListUserPermissionsResponse: Format[Schema.ListUserPermissionsResponse] = Json.format[Schema.ListUserPermissionsResponse]
	given fmtContainer: Format[Schema.Container] = Json.format[Schema.Container]
	given fmtContainerFeatures: Format[Schema.ContainerFeatures] = Json.format[Schema.ContainerFeatures]
	given fmtContainerUsageContextEnum: Format[Schema.Container.UsageContextEnum] = JsonEnumFormat[Schema.Container.UsageContextEnum]
	given fmtListContainersResponse: Format[Schema.ListContainersResponse] = Json.format[Schema.ListContainersResponse]
	given fmtGetContainerSnippetResponse: Format[Schema.GetContainerSnippetResponse] = Json.format[Schema.GetContainerSnippetResponse]
	given fmtDestination: Format[Schema.Destination] = Json.format[Schema.Destination]
	given fmtListDestinationsResponse: Format[Schema.ListDestinationsResponse] = Json.format[Schema.ListDestinationsResponse]
	given fmtWorkspace: Format[Schema.Workspace] = Json.format[Schema.Workspace]
	given fmtListWorkspacesResponse: Format[Schema.ListWorkspacesResponse] = Json.format[Schema.ListWorkspacesResponse]
	given fmtSyncWorkspaceResponse: Format[Schema.SyncWorkspaceResponse] = Json.format[Schema.SyncWorkspaceResponse]
	given fmtSyncStatus: Format[Schema.SyncStatus] = Json.format[Schema.SyncStatus]
	given fmtMergeConflict: Format[Schema.MergeConflict] = Json.format[Schema.MergeConflict]
	given fmtEntity: Format[Schema.Entity] = Json.format[Schema.Entity]
	given fmtTag: Format[Schema.Tag] = Json.format[Schema.Tag]
	given fmtTrigger: Format[Schema.Trigger] = Json.format[Schema.Trigger]
	given fmtVariable: Format[Schema.Variable] = Json.format[Schema.Variable]
	given fmtFolder: Format[Schema.Folder] = Json.format[Schema.Folder]
	given fmtClient: Format[Schema.Client] = Json.format[Schema.Client]
	given fmtTransformation: Format[Schema.Transformation] = Json.format[Schema.Transformation]
	given fmtZone: Format[Schema.Zone] = Json.format[Schema.Zone]
	given fmtCustomTemplate: Format[Schema.CustomTemplate] = Json.format[Schema.CustomTemplate]
	given fmtBuiltInVariable: Format[Schema.BuiltInVariable] = Json.format[Schema.BuiltInVariable]
	given fmtGtagConfig: Format[Schema.GtagConfig] = Json.format[Schema.GtagConfig]
	given fmtEntityChangeStatusEnum: Format[Schema.Entity.ChangeStatusEnum] = JsonEnumFormat[Schema.Entity.ChangeStatusEnum]
	given fmtParameter: Format[Schema.Parameter] = Json.format[Schema.Parameter]
	given fmtSetupTag: Format[Schema.SetupTag] = Json.format[Schema.SetupTag]
	given fmtTeardownTag: Format[Schema.TeardownTag] = Json.format[Schema.TeardownTag]
	given fmtTagTagFiringOptionEnum: Format[Schema.Tag.TagFiringOptionEnum] = JsonEnumFormat[Schema.Tag.TagFiringOptionEnum]
	given fmtTagConsentSetting: Format[Schema.TagConsentSetting] = Json.format[Schema.TagConsentSetting]
	given fmtParameterTypeEnum: Format[Schema.Parameter.TypeEnum] = JsonEnumFormat[Schema.Parameter.TypeEnum]
	given fmtTagConsentSettingConsentStatusEnum: Format[Schema.TagConsentSetting.ConsentStatusEnum] = JsonEnumFormat[Schema.TagConsentSetting.ConsentStatusEnum]
	given fmtTriggerTypeEnum: Format[Schema.Trigger.TypeEnum] = JsonEnumFormat[Schema.Trigger.TypeEnum]
	given fmtCondition: Format[Schema.Condition] = Json.format[Schema.Condition]
	given fmtConditionTypeEnum: Format[Schema.Condition.TypeEnum] = JsonEnumFormat[Schema.Condition.TypeEnum]
	given fmtVariableFormatValue: Format[Schema.VariableFormatValue] = Json.format[Schema.VariableFormatValue]
	given fmtVariableFormatValueCaseConversionTypeEnum: Format[Schema.VariableFormatValue.CaseConversionTypeEnum] = JsonEnumFormat[Schema.VariableFormatValue.CaseConversionTypeEnum]
	given fmtZoneChildContainer: Format[Schema.ZoneChildContainer] = Json.format[Schema.ZoneChildContainer]
	given fmtZoneBoundary: Format[Schema.ZoneBoundary] = Json.format[Schema.ZoneBoundary]
	given fmtZoneTypeRestriction: Format[Schema.ZoneTypeRestriction] = Json.format[Schema.ZoneTypeRestriction]
	given fmtGalleryReference: Format[Schema.GalleryReference] = Json.format[Schema.GalleryReference]
	given fmtBuiltInVariableTypeEnum: Format[Schema.BuiltInVariable.TypeEnum] = JsonEnumFormat[Schema.BuiltInVariable.TypeEnum]
	given fmtGetWorkspaceStatusResponse: Format[Schema.GetWorkspaceStatusResponse] = Json.format[Schema.GetWorkspaceStatusResponse]
	given fmtQuickPreviewResponse: Format[Schema.QuickPreviewResponse] = Json.format[Schema.QuickPreviewResponse]
	given fmtContainerVersion: Format[Schema.ContainerVersion] = Json.format[Schema.ContainerVersion]
	given fmtCreateContainerVersionRequestVersionOptions: Format[Schema.CreateContainerVersionRequestVersionOptions] = Json.format[Schema.CreateContainerVersionRequestVersionOptions]
	given fmtCreateContainerVersionResponse: Format[Schema.CreateContainerVersionResponse] = Json.format[Schema.CreateContainerVersionResponse]
	given fmtPublishContainerVersionResponse: Format[Schema.PublishContainerVersionResponse] = Json.format[Schema.PublishContainerVersionResponse]
	given fmtListContainerVersionsResponse: Format[Schema.ListContainerVersionsResponse] = Json.format[Schema.ListContainerVersionsResponse]
	given fmtContainerVersionHeader: Format[Schema.ContainerVersionHeader] = Json.format[Schema.ContainerVersionHeader]
	given fmtListVariablesResponse: Format[Schema.ListVariablesResponse] = Json.format[Schema.ListVariablesResponse]
	given fmtRevertVariableResponse: Format[Schema.RevertVariableResponse] = Json.format[Schema.RevertVariableResponse]
	given fmtCreateBuiltInVariableResponse: Format[Schema.CreateBuiltInVariableResponse] = Json.format[Schema.CreateBuiltInVariableResponse]
	given fmtListEnabledBuiltInVariablesResponse: Format[Schema.ListEnabledBuiltInVariablesResponse] = Json.format[Schema.ListEnabledBuiltInVariablesResponse]
	given fmtRevertBuiltInVariableResponse: Format[Schema.RevertBuiltInVariableResponse] = Json.format[Schema.RevertBuiltInVariableResponse]
	given fmtListTriggersResponse: Format[Schema.ListTriggersResponse] = Json.format[Schema.ListTriggersResponse]
	given fmtRevertTriggerResponse: Format[Schema.RevertTriggerResponse] = Json.format[Schema.RevertTriggerResponse]
	given fmtListTagsResponse: Format[Schema.ListTagsResponse] = Json.format[Schema.ListTagsResponse]
	given fmtRevertTagResponse: Format[Schema.RevertTagResponse] = Json.format[Schema.RevertTagResponse]
	given fmtListGtagConfigResponse: Format[Schema.ListGtagConfigResponse] = Json.format[Schema.ListGtagConfigResponse]
	given fmtListTemplatesResponse: Format[Schema.ListTemplatesResponse] = Json.format[Schema.ListTemplatesResponse]
	given fmtRevertTemplateResponse: Format[Schema.RevertTemplateResponse] = Json.format[Schema.RevertTemplateResponse]
	given fmtListFoldersResponse: Format[Schema.ListFoldersResponse] = Json.format[Schema.ListFoldersResponse]
	given fmtFolderEntities: Format[Schema.FolderEntities] = Json.format[Schema.FolderEntities]
	given fmtRevertFolderResponse: Format[Schema.RevertFolderResponse] = Json.format[Schema.RevertFolderResponse]
	given fmtEnvironment: Format[Schema.Environment] = Json.format[Schema.Environment]
	given fmtEnvironmentTypeEnum: Format[Schema.Environment.TypeEnum] = JsonEnumFormat[Schema.Environment.TypeEnum]
	given fmtListEnvironmentsResponse: Format[Schema.ListEnvironmentsResponse] = Json.format[Schema.ListEnvironmentsResponse]
	given fmtListZonesResponse: Format[Schema.ListZonesResponse] = Json.format[Schema.ListZonesResponse]
	given fmtRevertZoneResponse: Format[Schema.RevertZoneResponse] = Json.format[Schema.RevertZoneResponse]
	given fmtListClientsResponse: Format[Schema.ListClientsResponse] = Json.format[Schema.ListClientsResponse]
	given fmtRevertClientResponse: Format[Schema.RevertClientResponse] = Json.format[Schema.RevertClientResponse]
	given fmtListTransformationsResponse: Format[Schema.ListTransformationsResponse] = Json.format[Schema.ListTransformationsResponse]
	given fmtRevertTransformationResponse: Format[Schema.RevertTransformationResponse] = Json.format[Schema.RevertTransformationResponse]
}
