package com.boresjo.play.api.google.recommender

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleCloudRecommenderV1ReliabilityProjection: Format[Schema.GoogleCloudRecommenderV1ReliabilityProjection] = Json.format[Schema.GoogleCloudRecommenderV1ReliabilityProjection]
	given fmtGoogleCloudRecommenderV1ReliabilityProjectionRisksEnum: Format[Schema.GoogleCloudRecommenderV1ReliabilityProjection.RisksEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1ReliabilityProjection.RisksEnum]
	given fmtGoogleCloudRecommenderV1Recommendation: Format[Schema.GoogleCloudRecommenderV1Recommendation] = Json.format[Schema.GoogleCloudRecommenderV1Recommendation]
	given fmtGoogleCloudRecommenderV1RecommendationStateInfo: Format[Schema.GoogleCloudRecommenderV1RecommendationStateInfo] = Json.format[Schema.GoogleCloudRecommenderV1RecommendationStateInfo]
	given fmtGoogleCloudRecommenderV1RecommendationInsightReference: Format[Schema.GoogleCloudRecommenderV1RecommendationInsightReference] = Json.format[Schema.GoogleCloudRecommenderV1RecommendationInsightReference]
	given fmtGoogleCloudRecommenderV1RecommendationContent: Format[Schema.GoogleCloudRecommenderV1RecommendationContent] = Json.format[Schema.GoogleCloudRecommenderV1RecommendationContent]
	given fmtGoogleCloudRecommenderV1RecommendationPriorityEnum: Format[Schema.GoogleCloudRecommenderV1Recommendation.PriorityEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1Recommendation.PriorityEnum]
	given fmtGoogleCloudRecommenderV1Impact: Format[Schema.GoogleCloudRecommenderV1Impact] = Json.format[Schema.GoogleCloudRecommenderV1Impact]
	given fmtGoogleCloudRecommenderV1InsightRecommendationReference: Format[Schema.GoogleCloudRecommenderV1InsightRecommendationReference] = Json.format[Schema.GoogleCloudRecommenderV1InsightRecommendationReference]
	given fmtGoogleCloudRecommenderV1RecommendationStateInfoStateEnum: Format[Schema.GoogleCloudRecommenderV1RecommendationStateInfo.StateEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1RecommendationStateInfo.StateEnum]
	given fmtGoogleCloudRecommenderV1InsightTypeConfig: Format[Schema.GoogleCloudRecommenderV1InsightTypeConfig] = Json.format[Schema.GoogleCloudRecommenderV1InsightTypeConfig]
	given fmtGoogleCloudRecommenderV1InsightTypeGenerationConfig: Format[Schema.GoogleCloudRecommenderV1InsightTypeGenerationConfig] = Json.format[Schema.GoogleCloudRecommenderV1InsightTypeGenerationConfig]
	given fmtGoogleCloudRecommenderV1MarkRecommendationSucceededRequest: Format[Schema.GoogleCloudRecommenderV1MarkRecommendationSucceededRequest] = Json.format[Schema.GoogleCloudRecommenderV1MarkRecommendationSucceededRequest]
	given fmtGoogleCloudRecommenderV1MarkRecommendationClaimedRequest: Format[Schema.GoogleCloudRecommenderV1MarkRecommendationClaimedRequest] = Json.format[Schema.GoogleCloudRecommenderV1MarkRecommendationClaimedRequest]
	given fmtGoogleCloudRecommenderV1RecommenderConfig: Format[Schema.GoogleCloudRecommenderV1RecommenderConfig] = Json.format[Schema.GoogleCloudRecommenderV1RecommenderConfig]
	given fmtGoogleCloudRecommenderV1RecommenderGenerationConfig: Format[Schema.GoogleCloudRecommenderV1RecommenderGenerationConfig] = Json.format[Schema.GoogleCloudRecommenderV1RecommenderGenerationConfig]
	given fmtGoogleCloudRecommenderV1MarkRecommendationDismissedRequest: Format[Schema.GoogleCloudRecommenderV1MarkRecommendationDismissedRequest] = Json.format[Schema.GoogleCloudRecommenderV1MarkRecommendationDismissedRequest]
	given fmtGoogleCloudRecommenderV1ListInsightsResponse: Format[Schema.GoogleCloudRecommenderV1ListInsightsResponse] = Json.format[Schema.GoogleCloudRecommenderV1ListInsightsResponse]
	given fmtGoogleCloudRecommenderV1Insight: Format[Schema.GoogleCloudRecommenderV1Insight] = Json.format[Schema.GoogleCloudRecommenderV1Insight]
	given fmtGoogleCloudRecommenderV1MarkRecommendationFailedRequest: Format[Schema.GoogleCloudRecommenderV1MarkRecommendationFailedRequest] = Json.format[Schema.GoogleCloudRecommenderV1MarkRecommendationFailedRequest]
	given fmtGoogleCloudRecommenderV1ValueMatcher: Format[Schema.GoogleCloudRecommenderV1ValueMatcher] = Json.format[Schema.GoogleCloudRecommenderV1ValueMatcher]
	given fmtGoogleCloudRecommenderV1InsightStateInfo: Format[Schema.GoogleCloudRecommenderV1InsightStateInfo] = Json.format[Schema.GoogleCloudRecommenderV1InsightStateInfo]
	given fmtGoogleCloudRecommenderV1InsightStateInfoStateEnum: Format[Schema.GoogleCloudRecommenderV1InsightStateInfo.StateEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1InsightStateInfo.StateEnum]
	given fmtGoogleCloudRecommenderV1Operation: Format[Schema.GoogleCloudRecommenderV1Operation] = Json.format[Schema.GoogleCloudRecommenderV1Operation]
	given fmtGoogleCloudRecommenderV1SustainabilityProjection: Format[Schema.GoogleCloudRecommenderV1SustainabilityProjection] = Json.format[Schema.GoogleCloudRecommenderV1SustainabilityProjection]
	given fmtGoogleCloudRecommenderV1OperationGroup: Format[Schema.GoogleCloudRecommenderV1OperationGroup] = Json.format[Schema.GoogleCloudRecommenderV1OperationGroup]
	given fmtGoogleCloudRecommenderV1ListRecommendationsResponse: Format[Schema.GoogleCloudRecommenderV1ListRecommendationsResponse] = Json.format[Schema.GoogleCloudRecommenderV1ListRecommendationsResponse]
	given fmtGoogleCloudRecommenderV1InsightCategoryEnum: Format[Schema.GoogleCloudRecommenderV1Insight.CategoryEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1Insight.CategoryEnum]
	given fmtGoogleCloudRecommenderV1InsightSeverityEnum: Format[Schema.GoogleCloudRecommenderV1Insight.SeverityEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1Insight.SeverityEnum]
	given fmtGoogleCloudRecommenderV1MarkInsightAcceptedRequest: Format[Schema.GoogleCloudRecommenderV1MarkInsightAcceptedRequest] = Json.format[Schema.GoogleCloudRecommenderV1MarkInsightAcceptedRequest]
	given fmtGoogleTypeMoney: Format[Schema.GoogleTypeMoney] = Json.format[Schema.GoogleTypeMoney]
	given fmtGoogleCloudRecommenderV1SecurityProjection: Format[Schema.GoogleCloudRecommenderV1SecurityProjection] = Json.format[Schema.GoogleCloudRecommenderV1SecurityProjection]
	given fmtGoogleCloudRecommenderV1ImpactCategoryEnum: Format[Schema.GoogleCloudRecommenderV1Impact.CategoryEnum] = JsonEnumFormat[Schema.GoogleCloudRecommenderV1Impact.CategoryEnum]
	given fmtGoogleCloudRecommenderV1CostProjection: Format[Schema.GoogleCloudRecommenderV1CostProjection] = Json.format[Schema.GoogleCloudRecommenderV1CostProjection]
}
