package com.boresjo.play.api.google.workloadmanager

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtListEvaluationsResponse: Format[Schema.ListEvaluationsResponse] = Json.format[Schema.ListEvaluationsResponse]
	given fmtEvaluation: Format[Schema.Evaluation] = Json.format[Schema.Evaluation]
	given fmtResourceFilter: Format[Schema.ResourceFilter] = Json.format[Schema.ResourceFilter]
	given fmtResourceStatus: Format[Schema.ResourceStatus] = Json.format[Schema.ResourceStatus]
	given fmtBigQueryDestination: Format[Schema.BigQueryDestination] = Json.format[Schema.BigQueryDestination]
	given fmtGceInstanceFilter: Format[Schema.GceInstanceFilter] = Json.format[Schema.GceInstanceFilter]
	given fmtResourceStatusStateEnum: Format[Schema.ResourceStatus.StateEnum] = JsonEnumFormat[Schema.ResourceStatus.StateEnum]
	given fmtListExecutionsResponse: Format[Schema.ListExecutionsResponse] = Json.format[Schema.ListExecutionsResponse]
	given fmtExecution: Format[Schema.Execution] = Json.format[Schema.Execution]
	given fmtExecutionStateEnum: Format[Schema.Execution.StateEnum] = JsonEnumFormat[Schema.Execution.StateEnum]
	given fmtExecutionRunTypeEnum: Format[Schema.Execution.RunTypeEnum] = JsonEnumFormat[Schema.Execution.RunTypeEnum]
	given fmtRuleExecutionResult: Format[Schema.RuleExecutionResult] = Json.format[Schema.RuleExecutionResult]
	given fmtExternalDataSources: Format[Schema.ExternalDataSources] = Json.format[Schema.ExternalDataSources]
	given fmtNotice: Format[Schema.Notice] = Json.format[Schema.Notice]
	given fmtRuleExecutionResultStateEnum: Format[Schema.RuleExecutionResult.StateEnum] = JsonEnumFormat[Schema.RuleExecutionResult.StateEnum]
	given fmtExternalDataSourcesTypeEnum: Format[Schema.ExternalDataSources.TypeEnum] = JsonEnumFormat[Schema.ExternalDataSources.TypeEnum]
	given fmtRunEvaluationRequest: Format[Schema.RunEvaluationRequest] = Json.format[Schema.RunEvaluationRequest]
	given fmtListExecutionResultsResponse: Format[Schema.ListExecutionResultsResponse] = Json.format[Schema.ListExecutionResultsResponse]
	given fmtExecutionResult: Format[Schema.ExecutionResult] = Json.format[Schema.ExecutionResult]
	given fmtResource: Format[Schema.Resource] = Json.format[Schema.Resource]
	given fmtViolationDetails: Format[Schema.ViolationDetails] = Json.format[Schema.ViolationDetails]
	given fmtCommand: Format[Schema.Command] = Json.format[Schema.Command]
	given fmtExecutionResultTypeEnum: Format[Schema.ExecutionResult.TypeEnum] = JsonEnumFormat[Schema.ExecutionResult.TypeEnum]
	given fmtAgentCommand: Format[Schema.AgentCommand] = Json.format[Schema.AgentCommand]
	given fmtShellCommand: Format[Schema.ShellCommand] = Json.format[Schema.ShellCommand]
	given fmtListRulesResponse: Format[Schema.ListRulesResponse] = Json.format[Schema.ListRulesResponse]
	given fmtRule: Format[Schema.Rule] = Json.format[Schema.Rule]
	given fmtListScannedResourcesResponse: Format[Schema.ListScannedResourcesResponse] = Json.format[Schema.ListScannedResourcesResponse]
	given fmtScannedResource: Format[Schema.ScannedResource] = Json.format[Schema.ScannedResource]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtWriteInsightRequest: Format[Schema.WriteInsightRequest] = Json.format[Schema.WriteInsightRequest]
	given fmtInsight: Format[Schema.Insight] = Json.format[Schema.Insight]
	given fmtSapValidation: Format[Schema.SapValidation] = Json.format[Schema.SapValidation]
	given fmtSapDiscovery: Format[Schema.SapDiscovery] = Json.format[Schema.SapDiscovery]
	given fmtSqlserverValidation: Format[Schema.SqlserverValidation] = Json.format[Schema.SqlserverValidation]
	given fmtSapValidationValidationDetail: Format[Schema.SapValidationValidationDetail] = Json.format[Schema.SapValidationValidationDetail]
	given fmtSapValidationValidationDetailSapValidationTypeEnum: Format[Schema.SapValidationValidationDetail.SapValidationTypeEnum] = JsonEnumFormat[Schema.SapValidationValidationDetail.SapValidationTypeEnum]
	given fmtSapDiscoveryMetadata: Format[Schema.SapDiscoveryMetadata] = Json.format[Schema.SapDiscoveryMetadata]
	given fmtSapDiscoveryComponent: Format[Schema.SapDiscoveryComponent] = Json.format[Schema.SapDiscoveryComponent]
	given fmtSapDiscoveryWorkloadProperties: Format[Schema.SapDiscoveryWorkloadProperties] = Json.format[Schema.SapDiscoveryWorkloadProperties]
	given fmtSapDiscoveryResource: Format[Schema.SapDiscoveryResource] = Json.format[Schema.SapDiscoveryResource]
	given fmtSapDiscoveryComponentApplicationProperties: Format[Schema.SapDiscoveryComponentApplicationProperties] = Json.format[Schema.SapDiscoveryComponentApplicationProperties]
	given fmtSapDiscoveryComponentDatabaseProperties: Format[Schema.SapDiscoveryComponentDatabaseProperties] = Json.format[Schema.SapDiscoveryComponentDatabaseProperties]
	given fmtSapDiscoveryComponentTopologyTypeEnum: Format[Schema.SapDiscoveryComponent.TopologyTypeEnum] = JsonEnumFormat[Schema.SapDiscoveryComponent.TopologyTypeEnum]
	given fmtSapDiscoveryResourceResourceTypeEnum: Format[Schema.SapDiscoveryResource.ResourceTypeEnum] = JsonEnumFormat[Schema.SapDiscoveryResource.ResourceTypeEnum]
	given fmtSapDiscoveryResourceResourceKindEnum: Format[Schema.SapDiscoveryResource.ResourceKindEnum] = JsonEnumFormat[Schema.SapDiscoveryResource.ResourceKindEnum]
	given fmtSapDiscoveryResourceInstanceProperties: Format[Schema.SapDiscoveryResourceInstanceProperties] = Json.format[Schema.SapDiscoveryResourceInstanceProperties]
	given fmtSapDiscoveryResourceInstancePropertiesInstanceRoleEnum: Format[Schema.SapDiscoveryResourceInstanceProperties.InstanceRoleEnum] = JsonEnumFormat[Schema.SapDiscoveryResourceInstanceProperties.InstanceRoleEnum]
	given fmtSapDiscoveryResourceInstancePropertiesAppInstance: Format[Schema.SapDiscoveryResourceInstancePropertiesAppInstance] = Json.format[Schema.SapDiscoveryResourceInstancePropertiesAppInstance]
	given fmtSapDiscoveryComponentApplicationPropertiesApplicationTypeEnum: Format[Schema.SapDiscoveryComponentApplicationProperties.ApplicationTypeEnum] = JsonEnumFormat[Schema.SapDiscoveryComponentApplicationProperties.ApplicationTypeEnum]
	given fmtSapDiscoveryComponentDatabasePropertiesDatabaseTypeEnum: Format[Schema.SapDiscoveryComponentDatabaseProperties.DatabaseTypeEnum] = JsonEnumFormat[Schema.SapDiscoveryComponentDatabaseProperties.DatabaseTypeEnum]
	given fmtSapDiscoveryWorkloadPropertiesProductVersion: Format[Schema.SapDiscoveryWorkloadPropertiesProductVersion] = Json.format[Schema.SapDiscoveryWorkloadPropertiesProductVersion]
	given fmtSapDiscoveryWorkloadPropertiesSoftwareComponentProperties: Format[Schema.SapDiscoveryWorkloadPropertiesSoftwareComponentProperties] = Json.format[Schema.SapDiscoveryWorkloadPropertiesSoftwareComponentProperties]
	given fmtSqlserverValidationValidationDetail: Format[Schema.SqlserverValidationValidationDetail] = Json.format[Schema.SqlserverValidationValidationDetail]
	given fmtSqlserverValidationValidationDetailTypeEnum: Format[Schema.SqlserverValidationValidationDetail.TypeEnum] = JsonEnumFormat[Schema.SqlserverValidationValidationDetail.TypeEnum]
	given fmtSqlserverValidationDetails: Format[Schema.SqlserverValidationDetails] = Json.format[Schema.SqlserverValidationDetails]
	given fmtWriteInsightResponse: Format[Schema.WriteInsightResponse] = Json.format[Schema.WriteInsightResponse]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
