package com.boresjo.play.api.google.beyondcorp

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Schema {
	case class GoogleLongrunningListOperationsResponse(
	  /** A list of operations that matches the specified filter in the request. */
		operations: Option[List[Schema.GoogleLongrunningOperation]] = None,
	  /** The standard List next-page token. */
		nextPageToken: Option[String] = None
	)
	
	case class GoogleLongrunningOperation(
	  /** The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`. */
		name: Option[String] = None,
	  /** Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any. */
		metadata: Option[Map[String, JsValue]] = None,
	  /** If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available. */
		done: Option[Boolean] = None,
	  /** The error result of the operation in case of failure or cancellation. */
		error: Option[Schema.GoogleRpcStatus] = None,
	  /** The normal, successful response of the operation. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type `XxxResponse`, where `Xxx` is the original method name. For example, if the original method name is `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`. */
		response: Option[Map[String, JsValue]] = None
	)
	
	case class GoogleRpcStatus(
	  /** The status code, which should be an enum value of google.rpc.Code. */
		code: Option[Int] = None,
	  /** A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client. */
		message: Option[String] = None,
	  /** A list of messages that carry the error details. There is a common set of message types for APIs to use. */
		details: Option[List[Map[String, JsValue]]] = None
	)
	
	case class Empty(
	
	)
	
	case class GoogleLongrunningCancelOperationRequest(
	
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1ListAppConnectionsResponse(
	  /** A list of BeyondCorp AppConnections in the project. */
		appConnections: Option[List[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnection]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	object GoogleCloudBeyondcorpAppconnectionsV1AppConnection {
		enum TypeEnum extends Enum[TypeEnum] { case TYPE_UNSPECIFIED, TCP_PROXY }
		enum StateEnum extends Enum[StateEnum] { case STATE_UNSPECIFIED, CREATING, CREATED, UPDATING, DELETING, DOWN }
	}
	case class GoogleCloudBeyondcorpAppconnectionsV1AppConnection(
	  /** Required. Unique resource name of the AppConnection. The name is ignored when creating a AppConnection. */
		name: Option[String] = None,
	  /** Output only. Timestamp when the resource was created. */
		createTime: Option[String] = None,
	  /** Output only. Timestamp when the resource was last modified. */
		updateTime: Option[String] = None,
	  /** Optional. Resource labels to represent user provided metadata. */
		labels: Option[Map[String, String]] = None,
	  /** Optional. An arbitrary user-provided name for the AppConnection. Cannot exceed 64 characters. */
		displayName: Option[String] = None,
	  /** Output only. A unique identifier for the instance generated by the system. */
		uid: Option[String] = None,
	  /** Required. The type of network connectivity used by the AppConnection. */
		`type`: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnection.TypeEnum] = None,
	  /** Required. Address of the remote application endpoint for the BeyondCorp AppConnection. */
		applicationEndpoint: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnectionApplicationEndpoint] = None,
	  /** Optional. List of [google.cloud.beyondcorp.v1main.Connector.name] that are authorised to be associated with this AppConnection. */
		connectors: Option[List[String]] = None,
	  /** Output only. The current state of the AppConnection. */
		state: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnection.StateEnum] = None,
	  /** Optional. Gateway used by the AppConnection. */
		gateway: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGateway] = None,
	  /** Output only. Reserved for future use. */
		satisfiesPzs: Option[Boolean] = None,
	  /** Output only. Reserved for future use. */
		satisfiesPzi: Option[Boolean] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1AppConnectionApplicationEndpoint(
	  /** Required. Hostname or IP address of the remote application endpoint. */
		host: Option[String] = None,
	  /** Required. Port of the remote application endpoint. */
		port: Option[Int] = None
	)
	
	object GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGateway {
		enum TypeEnum extends Enum[TypeEnum] { case TYPE_UNSPECIFIED, GCP_REGIONAL_MIG }
	}
	case class GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGateway(
	  /** Required. The type of hosting used by the gateway. */
		`type`: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnectionGateway.TypeEnum] = None,
	  /** Output only. Server-defined URI for this resource. */
		uri: Option[String] = None,
	  /** Output only. Ingress port reserved on the gateways for this AppConnection, if not specified or zero, the default port is 19443. */
		ingressPort: Option[Int] = None,
	  /** Required. AppGateway name in following format: `projects/{project_id}/locations/{location_id}/appgateways/{gateway_id}` */
		appGateway: Option[String] = None,
	  /** Output only. L7 private service connection for this resource. */
		l7psc: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponse(
	  /** A list of BeyondCorp AppConnections with details in the project. */
		appConnectionDetails: Option[List[Schema.GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseAppConnectionDetails]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1ResolveAppConnectionsResponseAppConnectionDetails(
	  /** A BeyondCorp AppConnection in the project. */
		appConnection: Option[Schema.GoogleCloudBeyondcorpAppconnectionsV1AppConnection] = None,
	  /** If type=GCP_REGIONAL_MIG, contains most recent VM instances, like `https://www.googleapis.com/compute/v1/projects/{project_id}/zones/{zone_id}/instances/{instance_id}`. */
		recentMigVms: Option[List[String]] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1ListAppConnectorsResponse(
	  /** A list of BeyondCorp AppConnectors in the project. */
		appConnectors: Option[List[Schema.GoogleCloudBeyondcorpAppconnectorsV1AppConnector]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	object GoogleCloudBeyondcorpAppconnectorsV1AppConnector {
		enum StateEnum extends Enum[StateEnum] { case STATE_UNSPECIFIED, CREATING, CREATED, UPDATING, DELETING, DOWN }
	}
	case class GoogleCloudBeyondcorpAppconnectorsV1AppConnector(
	  /** Required. Unique resource name of the AppConnector. The name is ignored when creating a AppConnector. */
		name: Option[String] = None,
	  /** Output only. Timestamp when the resource was created. */
		createTime: Option[String] = None,
	  /** Output only. Timestamp when the resource was last modified. */
		updateTime: Option[String] = None,
	  /** Optional. Resource labels to represent user provided metadata. */
		labels: Option[Map[String, String]] = None,
	  /** Optional. An arbitrary user-provided name for the AppConnector. Cannot exceed 64 characters. */
		displayName: Option[String] = None,
	  /** Output only. A unique identifier for the instance generated by the system. */
		uid: Option[String] = None,
	  /** Output only. The current state of the AppConnector. */
		state: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1AppConnector.StateEnum] = None,
	  /** Required. Principal information about the Identity of the AppConnector. */
		principalInfo: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfo] = None,
	  /** Optional. Resource info of the connector. */
		resourceInfo: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfo(
	  /** A GCP service account. */
		serviceAccount: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoServiceAccount] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1AppConnectorPrincipalInfoServiceAccount(
	  /** Email address of the service account. */
		email: Option[String] = None
	)
	
	object GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo {
		enum StatusEnum extends Enum[StatusEnum] { case HEALTH_STATUS_UNSPECIFIED, HEALTHY, UNHEALTHY, UNRESPONSIVE, DEGRADED }
	}
	case class GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo(
	  /** Required. Unique Id for the resource. */
		id: Option[String] = None,
	  /** Overall health status. Overall status is derived based on the status of each sub level resources. */
		status: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo.StatusEnum] = None,
	  /** Specific details for the resource. This is for internal use only. */
		resource: Option[Map[String, JsValue]] = None,
	  /** The timestamp to collect the info. It is suggested to be set by the topmost level resource only. */
		time: Option[String] = None,
	  /** List of Info for the sub level resources. */
		sub: Option[List[Schema.GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo]] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1ResolveInstanceConfigResponse(
	  /** AppConnectorInstanceConfig. */
		instanceConfig: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1AppConnectorInstanceConfig] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1AppConnectorInstanceConfig(
	  /** Required. A monotonically increasing number generated and maintained by the API provider. Every time a config changes in the backend, the sequenceNumber should be bumped up to reflect the change. */
		sequenceNumber: Option[String] = None,
	  /** The SLM instance agent configuration. */
		instanceConfig: Option[Map[String, JsValue]] = None,
	  /** NotificationConfig defines the notification mechanism that the remote instance should subscribe to in order to receive notification. */
		notificationConfig: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1NotificationConfig] = None,
	  /** ImageConfig defines the GCR images to run for the remote agent's control plane. */
		imageConfig: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1ImageConfig] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1NotificationConfig(
	  /** Cloud Pub/Sub Configuration to receive notifications. */
		pubsubNotification: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigCloudPubSubNotificationConfig] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1NotificationConfigCloudPubSubNotificationConfig(
	  /** The Pub/Sub subscription the AppConnector uses to receive notifications. */
		pubsubSubscription: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1ImageConfig(
	  /** The initial image the remote agent will attempt to run for the control plane. Format would be a gcr image path, e.g.: gcr.io/PROJECT-ID/my-image:tag1 */
		targetImage: Option[String] = None,
	  /** The stable image that the remote agent will fallback to if the target image fails. Format would be a gcr image path, e.g.: gcr.io/PROJECT-ID/my-image:tag1 */
		stableImage: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1ReportStatusRequest(
	  /** Required. Resource info of the connector. */
		resourceInfo: Option[Schema.GoogleCloudBeyondcorpAppconnectorsV1ResourceInfo] = None,
	  /** Optional. An optional request ID to identify requests. Specify a unique request ID so that if you must retry your request, the server will know to ignore the request if it has already been completed. The server will guarantee that for at least 60 minutes since the first request. For example, consider a situation where you make an initial request and the request times out. If you make the request again with the same request ID, the server can check if original operation with the same request ID was received, and if so, will ignore the second request. This prevents clients from accidentally creating duplicate commitments. The request ID must be a valid UUID with the exception that zero UUID is not supported (00000000-0000-0000-0000-000000000000). */
		requestId: Option[String] = None,
	  /** Optional. If set, validates request by executing a dry-run which would not alter the resource in any way. */
		validateOnly: Option[Boolean] = None
	)
	
	case class ListAppGatewaysResponse(
	  /** A list of BeyondCorp AppGateways in the project. */
		appGateways: Option[List[Schema.AppGateway]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	object AppGateway {
		enum TypeEnum extends Enum[TypeEnum] { case TYPE_UNSPECIFIED, TCP_PROXY }
		enum StateEnum extends Enum[StateEnum] { case STATE_UNSPECIFIED, CREATING, CREATED, UPDATING, DELETING, DOWN }
		enum HostTypeEnum extends Enum[HostTypeEnum] { case HOST_TYPE_UNSPECIFIED, GCP_REGIONAL_MIG }
	}
	case class AppGateway(
	  /** Required. Unique resource name of the AppGateway. The name is ignored when creating an AppGateway. */
		name: Option[String] = None,
	  /** Output only. Timestamp when the resource was created. */
		createTime: Option[String] = None,
	  /** Output only. Timestamp when the resource was last modified. */
		updateTime: Option[String] = None,
	  /** Optional. Resource labels to represent user provided metadata. */
		labels: Option[Map[String, String]] = None,
	  /** Optional. An arbitrary user-provided name for the AppGateway. Cannot exceed 64 characters. */
		displayName: Option[String] = None,
	  /** Output only. A unique identifier for the instance generated by the system. */
		uid: Option[String] = None,
	  /** Required. The type of network connectivity used by the AppGateway. */
		`type`: Option[Schema.AppGateway.TypeEnum] = None,
	  /** Output only. The current state of the AppGateway. */
		state: Option[Schema.AppGateway.StateEnum] = None,
	  /** Output only. Server-defined URI for this resource. */
		uri: Option[String] = None,
	  /** Output only. A list of connections allocated for the Gateway */
		allocatedConnections: Option[List[Schema.AllocatedConnection]] = None,
	  /** Required. The type of hosting used by the AppGateway. */
		hostType: Option[Schema.AppGateway.HostTypeEnum] = None,
	  /** Output only. Reserved for future use. */
		satisfiesPzs: Option[Boolean] = None,
	  /** Output only. Reserved for future use. */
		satisfiesPzi: Option[Boolean] = None
	)
	
	case class AllocatedConnection(
	  /** Required. The PSC uri of an allocated connection */
		pscUri: Option[String] = None,
	  /** Required. The ingress port of an allocated connection */
		ingressPort: Option[Int] = None
	)
	
	case class ShouldThrottleResponse(
	  /** Whether the port should be throttled */
		shouldThrottle: Option[Boolean] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1ListSecurityGatewaysResponse(
	  /** A list of BeyondCorp SecurityGateway in the project. */
		securityGateways: Option[List[Schema.GoogleCloudBeyondcorpSecuritygatewaysV1SecurityGateway]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	object GoogleCloudBeyondcorpSecuritygatewaysV1SecurityGateway {
		enum StateEnum extends Enum[StateEnum] { case STATE_UNSPECIFIED, CREATING, UPDATING, DELETING, RUNNING, DOWN, ERROR }
	}
	case class GoogleCloudBeyondcorpSecuritygatewaysV1SecurityGateway(
	  /** Identifier. Name of the resource. */
		name: Option[String] = None,
	  /** Output only. Timestamp when the resource was created. */
		createTime: Option[String] = None,
	  /** Output only. Timestamp when the resource was last modified. */
		updateTime: Option[String] = None,
	  /** Optional. An arbitrary user-provided name for the SecurityGateway. Cannot exceed 64 characters. */
		displayName: Option[String] = None,
	  /** Output only. IP addresses that will be used for establishing connection to the endpoints. */
		externalIps: Option[List[String]] = None,
	  /** Output only. The operational state of the SecurityGateway. */
		state: Option[Schema.GoogleCloudBeyondcorpSecuritygatewaysV1SecurityGateway.StateEnum] = None,
	  /** Optional. Map of Hubs that represents regional data path deployment with GCP region as a key. */
		hubs: Option[Map[String, Schema.GoogleCloudBeyondcorpSecuritygatewaysV1Hub]] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1Hub(
	  /** Optional. Internet Gateway configuration. */
		internetGateway: Option[Schema.GoogleCloudBeyondcorpSecuritygatewaysV1InternetGateway] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1InternetGateway(
	  /** Output only. List of IP addresses assigned to the Cloud NAT. */
		assignedIps: Option[List[String]] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1ListApplicationsResponse(
	  /** A list of BeyondCorp Application in the project. */
		applications: Option[List[Schema.GoogleCloudBeyondcorpSecuritygatewaysV1Application]] = None,
	  /** A token to retrieve the next page of results, or empty if there are no more results in the list. */
		nextPageToken: Option[String] = None,
	  /** A list of locations that could not be reached. */
		unreachable: Option[List[String]] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1Application(
	  /** Identifier. Name of the resource. */
		name: Option[String] = None,
	  /** Required. Endpoint matchers associated with an application. A combination of hostname and ports as endpoint matcher is used to match the application. Match conditions for OR logic. An array of match conditions to allow for multiple matching criteria. The rule is considered a match if one the conditions are met. The conditions can be one of the following combination (Hostname), (Hostname & Ports) EXAMPLES: Hostname - ("&#42;.abc.com"), ("xyz.abc.com") Hostname and Ports - ("abc.com" and "22"), ("abc.com" and "22,33") etc */
		endpointMatchers: Option[List[Schema.GoogleCloudBeyondcorpSecuritygatewaysV1EndpointMatcher]] = None,
	  /** Output only. Timestamp when the resource was created. */
		createTime: Option[String] = None,
	  /** Output only. Timestamp when the resource was last modified. */
		updateTime: Option[String] = None,
	  /** Optional. An arbitrary user-provided name for the Application resource. Cannot exceed 64 characters. */
		displayName: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1EndpointMatcher(
	  /** Required. Hostname of the application. */
		hostname: Option[String] = None,
	  /** Optional. Ports of the application. */
		ports: Option[List[Int]] = None
	)
	
	case class GoogleCloudLocationListLocationsResponse(
	  /** A list of locations that matches the specified filter in the request. */
		locations: Option[List[Schema.GoogleCloudLocationLocation]] = None,
	  /** The standard List next-page token. */
		nextPageToken: Option[String] = None
	)
	
	case class GoogleCloudLocationLocation(
	  /** Resource name for the location, which may vary between implementations. For example: `"projects/example-project/locations/us-east1"` */
		name: Option[String] = None,
	  /** The canonical id for this location. For example: `"us-east1"`. */
		locationId: Option[String] = None,
	  /** The friendly name for this location, typically a nearby city name. For example, "Tokyo". */
		displayName: Option[String] = None,
	  /** Cross-service attributes for the location. For example {"cloud.googleapis.com/region": "us-east1"} */
		labels: Option[Map[String, String]] = None,
	  /** Service-specific metadata. For example the available capacity at the given location. */
		metadata: Option[Map[String, JsValue]] = None
	)
	
	case class GoogleIamV1SetIamPolicyRequest(
	  /** REQUIRED: The complete policy to be applied to the `resource`. The size of the policy is limited to a few 10s of KB. An empty policy is a valid policy but certain Google Cloud services (such as Projects) might reject them. */
		policy: Option[Schema.GoogleIamV1Policy] = None,
	  /** OPTIONAL: A FieldMask specifying which fields of the policy to modify. Only the fields in the mask will be modified. If no mask is provided, the following default mask is used: `paths: "bindings, etag"` */
		updateMask: Option[String] = None
	)
	
	case class GoogleIamV1Policy(
	  /** Specifies the format of the policy. Valid values are `0`, `1`, and `3`. Requests that specify an invalid value are rejected. Any operation that affects conditional role bindings must specify version `3`. This requirement applies to the following operations: &#42; Getting a policy that includes a conditional role binding &#42; Adding a conditional role binding to a policy &#42; Changing a conditional role binding in a policy &#42; Removing any role binding, with or without a condition, from a policy that includes conditions &#42;&#42;Important:&#42;&#42; If you use IAM Conditions, you must include the `etag` field whenever you call `setIamPolicy`. If you omit this field, then IAM allows you to overwrite a version `3` policy with a version `1` policy, and all of the conditions in the version `3` policy are lost. If a policy does not include any conditions, operations on that policy may specify any valid version or leave the field unset. To learn which resources support conditions in their IAM policies, see the [IAM documentation](https://cloud.google.com/iam/help/conditions/resource-policies). */
		version: Option[Int] = None,
	  /** Associates a list of `members`, or principals, with a `role`. Optionally, may specify a `condition` that determines how and when the `bindings` are applied. Each of the `bindings` must contain at least one principal. The `bindings` in a `Policy` can refer to up to 1,500 principals; up to 250 of these principals can be Google groups. Each occurrence of a principal counts towards these limits. For example, if the `bindings` grant 50 different roles to `user:alice@example.com`, and not to any other principal, then you can add another 1,450 principals to the `bindings` in the `Policy`. */
		bindings: Option[List[Schema.GoogleIamV1Binding]] = None,
	  /** Specifies cloud audit logging configuration for this policy. */
		auditConfigs: Option[List[Schema.GoogleIamV1AuditConfig]] = None,
	  /** `etag` is used for optimistic concurrency control as a way to help prevent simultaneous updates of a policy from overwriting each other. It is strongly suggested that systems make use of the `etag` in the read-modify-write cycle to perform policy updates in order to avoid race conditions: An `etag` is returned in the response to `getIamPolicy`, and systems are expected to put that etag in the request to `setIamPolicy` to ensure that their change will be applied to the same version of the policy. &#42;&#42;Important:&#42;&#42; If you use IAM Conditions, you must include the `etag` field whenever you call `setIamPolicy`. If you omit this field, then IAM allows you to overwrite a version `3` policy with a version `1` policy, and all of the conditions in the version `3` policy are lost. */
		etag: Option[String] = None
	)
	
	case class GoogleIamV1Binding(
	  /** Role that is assigned to the list of `members`, or principals. For example, `roles/viewer`, `roles/editor`, or `roles/owner`. For an overview of the IAM roles and permissions, see the [IAM documentation](https://cloud.google.com/iam/docs/roles-overview). For a list of the available pre-defined roles, see [here](https://cloud.google.com/iam/docs/understanding-roles). */
		role: Option[String] = None,
	  /** Specifies the principals requesting access for a Google Cloud resource. `members` can have the following values: &#42; `allUsers`: A special identifier that represents anyone who is on the internet; with or without a Google account. &#42; `allAuthenticatedUsers`: A special identifier that represents anyone who is authenticated with a Google account or a service account. Does not include identities that come from external identity providers (IdPs) through identity federation. &#42; `user:{emailid}`: An email address that represents a specific Google account. For example, `alice@example.com` . &#42; `serviceAccount:{emailid}`: An email address that represents a Google service account. For example, `my-other-app@appspot.gserviceaccount.com`. &#42; `serviceAccount:{projectid}.svc.id.goog[{namespace}/{kubernetes-sa}]`: An identifier for a [Kubernetes service account](https://cloud.google.com/kubernetes-engine/docs/how-to/kubernetes-service-accounts). For example, `my-project.svc.id.goog[my-namespace/my-kubernetes-sa]`. &#42; `group:{emailid}`: An email address that represents a Google group. For example, `admins@example.com`. &#42; `domain:{domain}`: The G Suite domain (primary) that represents all the users of that domain. For example, `google.com` or `example.com`. &#42; `principal://iam.googleapis.com/locations/global/workforcePools/{pool_id}/subject/{subject_attribute_value}`: A single identity in a workforce identity pool. &#42; `principalSet://iam.googleapis.com/locations/global/workforcePools/{pool_id}/group/{group_id}`: All workforce identities in a group. &#42; `principalSet://iam.googleapis.com/locations/global/workforcePools/{pool_id}/attribute.{attribute_name}/{attribute_value}`: All workforce identities with a specific attribute value. &#42; `principalSet://iam.googleapis.com/locations/global/workforcePools/{pool_id}/&#42;`: All identities in a workforce identity pool. &#42; `principal://iam.googleapis.com/projects/{project_number}/locations/global/workloadIdentityPools/{pool_id}/subject/{subject_attribute_value}`: A single identity in a workload identity pool. &#42; `principalSet://iam.googleapis.com/projects/{project_number}/locations/global/workloadIdentityPools/{pool_id}/group/{group_id}`: A workload identity pool group. &#42; `principalSet://iam.googleapis.com/projects/{project_number}/locations/global/workloadIdentityPools/{pool_id}/attribute.{attribute_name}/{attribute_value}`: All identities in a workload identity pool with a certain attribute. &#42; `principalSet://iam.googleapis.com/projects/{project_number}/locations/global/workloadIdentityPools/{pool_id}/&#42;`: All identities in a workload identity pool. &#42; `deleted:user:{emailid}?uid={uniqueid}`: An email address (plus unique identifier) representing a user that has been recently deleted. For example, `alice@example.com?uid=123456789012345678901`. If the user is recovered, this value reverts to `user:{emailid}` and the recovered user retains the role in the binding. &#42; `deleted:serviceAccount:{emailid}?uid={uniqueid}`: An email address (plus unique identifier) representing a service account that has been recently deleted. For example, `my-other-app@appspot.gserviceaccount.com?uid=123456789012345678901`. If the service account is undeleted, this value reverts to `serviceAccount:{emailid}` and the undeleted service account retains the role in the binding. &#42; `deleted:group:{emailid}?uid={uniqueid}`: An email address (plus unique identifier) representing a Google group that has been recently deleted. For example, `admins@example.com?uid=123456789012345678901`. If the group is recovered, this value reverts to `group:{emailid}` and the recovered group retains the role in the binding. &#42; `deleted:principal://iam.googleapis.com/locations/global/workforcePools/{pool_id}/subject/{subject_attribute_value}`: Deleted single identity in a workforce identity pool. For example, `deleted:principal://iam.googleapis.com/locations/global/workforcePools/my-pool-id/subject/my-subject-attribute-value`. */
		members: Option[List[String]] = None,
	  /** The condition that is associated with this binding. If the condition evaluates to `true`, then this binding applies to the current request. If the condition evaluates to `false`, then this binding does not apply to the current request. However, a different role binding might grant the same role to one or more of the principals in this binding. To learn which resources support conditions in their IAM policies, see the [IAM documentation](https://cloud.google.com/iam/help/conditions/resource-policies). */
		condition: Option[Schema.GoogleTypeExpr] = None
	)
	
	case class GoogleTypeExpr(
	  /** Textual representation of an expression in Common Expression Language syntax. */
		expression: Option[String] = None,
	  /** Optional. Title for the expression, i.e. a short string describing its purpose. This can be used e.g. in UIs which allow to enter the expression. */
		title: Option[String] = None,
	  /** Optional. Description of the expression. This is a longer text which describes the expression, e.g. when hovered over it in a UI. */
		description: Option[String] = None,
	  /** Optional. String indicating the location of the expression for error reporting, e.g. a file name and a position in the file. */
		location: Option[String] = None
	)
	
	case class GoogleIamV1AuditConfig(
	  /** Specifies a service that will be enabled for audit logging. For example, `storage.googleapis.com`, `cloudsql.googleapis.com`. `allServices` is a special value that covers all services. */
		service: Option[String] = None,
	  /** The configuration for logging of each type of permission. */
		auditLogConfigs: Option[List[Schema.GoogleIamV1AuditLogConfig]] = None
	)
	
	object GoogleIamV1AuditLogConfig {
		enum LogTypeEnum extends Enum[LogTypeEnum] { case LOG_TYPE_UNSPECIFIED, ADMIN_READ, DATA_WRITE, DATA_READ }
	}
	case class GoogleIamV1AuditLogConfig(
	  /** The log type that this config enables. */
		logType: Option[Schema.GoogleIamV1AuditLogConfig.LogTypeEnum] = None,
	  /** Specifies the identities that do not cause logging for this type of permission. Follows the same format of Binding.members. */
		exemptedMembers: Option[List[String]] = None
	)
	
	case class GoogleIamV1TestIamPermissionsRequest(
	  /** The set of permissions to check for the `resource`. Permissions with wildcards (such as `&#42;` or `storage.&#42;`) are not allowed. For more information see [IAM Overview](https://cloud.google.com/iam/docs/overview#permissions). */
		permissions: Option[List[String]] = None
	)
	
	case class GoogleIamV1TestIamPermissionsResponse(
	  /** A subset of `TestPermissionsRequest.permissions` that the caller is allowed. */
		permissions: Option[List[String]] = None
	)
	
	case class Tunnelv1ProtoTunnelerInfo(
	  /** total_retry_count stores the total number of times the tunneler has been retried by tunManager. */
		totalRetryCount: Option[Int] = None,
	  /** backoff_retry_count stores the number of times the tunneler has been retried by tunManager for current backoff sequence. Gets reset to 0 if time difference between 2 consecutive retries exceeds backoffRetryResetTime. */
		backoffRetryCount: Option[Int] = None,
	  /** latest_err stores the Error for the latest tunneler failure. Gets reset everytime the tunneler is retried by tunManager. */
		latestErr: Option[Schema.Tunnelv1ProtoTunnelerError] = None,
	  /** latest_retry_time stores the time when the tunneler was last restarted. */
		latestRetryTime: Option[String] = None,
	  /** id is the unique id of a tunneler. */
		id: Option[String] = None
	)
	
	case class Tunnelv1ProtoTunnelerError(
	  /** retryable isn't used for now, but we may want to reuse it in the future. */
		retryable: Option[Boolean] = None,
	  /** Original raw error */
		err: Option[String] = None
	)
	
	case class CloudSecurityZerotrustApplinkLogagentProtoLogAgentDetails(
	
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1alphaAppConnectionOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectionsV1AppConnectionOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1alphaAppConnectorOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1AppConnectorOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1alphaRemoteAgentDetails(
	
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1RemoteAgentDetails(
	
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1alphaContainerHealthDetails(
	  /** The version of the expected config. */
		expectedConfigVersion: Option[String] = None,
	  /** The version of the current config. */
		currentConfigVersion: Option[String] = None,
	  /** The extended status. Such as ExitCode, StartedAt, FinishedAt, etc. */
		extendedStatus: Option[Map[String, String]] = None,
	  /** The latest error message. */
		errorMsg: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpAppconnectorsV1ContainerHealthDetails(
	  /** The version of the expected config. */
		expectedConfigVersion: Option[String] = None,
	  /** The version of the current config. */
		currentConfigVersion: Option[String] = None,
	  /** The extended status. Such as ExitCode, StartedAt, FinishedAt, etc. */
		extendedStatus: Option[Map[String, String]] = None,
	  /** The latest error message. */
		errorMsg: Option[String] = None
	)
	
	case class CloudSecurityZerotrustApplinkAppConnectorProtoConnectorDetails(
	
	)
	
	case class CloudSecurityZerotrustApplinkAppConnectorProtoConnectionConfig(
	  /** name is the unique ID for each connection. TODO(b/190732451) returns connection name from user-specified name in config. Now, name = ${application_name}:${application_endpoint} */
		name: Option[String] = None,
	  /** project represents the consumer project the connection belongs to. */
		project: Option[String] = None,
	  /** application_name represents the given name of the application the connection is connecting with. */
		applicationName: Option[String] = None,
	  /** application_endpoint is the endpoint of the application the form of host:port. For example, "localhost:80". */
		applicationEndpoint: Option[String] = None,
	  /** gateway lists all instances running a gateway in GCP. They all connect to a connector on the host. */
		gateway: Option[List[Schema.CloudSecurityZerotrustApplinkAppConnectorProtoGateway]] = None,
	  /** tunnels_per_gateway reflects the number of tunnels between a connector and a gateway. */
		tunnelsPerGateway: Option[Int] = None,
	  /** user_port specifies the reserved port on gateways for user connections. */
		userPort: Option[Int] = None
	)
	
	case class CloudSecurityZerotrustApplinkAppConnectorProtoGateway(
	  /** self_link is the gateway URL in the form https://www.googleapis.com/compute/${version}/projects/${project}/zones/${zone}/instances/${instance} */
		selfLink: Option[String] = None,
	  /** project is the tenant project the gateway belongs to. Different from the project in the connection, it is a BeyondCorpAPI internally created project to manage all the gateways. It is sharing the same network with the consumer project user owned. It is derived from the gateway URL. For example, project=${project} assuming a gateway URL. https://www.googleapis.com/compute/${version}/projects/${project}/zones/${zone}/instances/${instance} */
		project: Option[String] = None,
	  /** zone represents the zone the instance belongs. It is derived from the gateway URL. For example, zone=${zone} assuming a gateway URL. https://www.googleapis.com/compute/${version}/projects/${project}/zones/${zone}/instances/${instance} */
		zone: Option[String] = None,
	  /** name is the name of an instance running a gateway. It is the unique ID for a gateway. All gateways under the same connection have the same prefix. It is derived from the gateway URL. For example, name=${instance} assuming a gateway URL. https://www.googleapis.com/compute/${version}/projects/${project}/zones/${zone}/instances/${instance} */
		name: Option[String] = None,
	  /** interface specifies the network interface of the gateway to connect to. */
		interface: Option[String] = None,
	  /** port specifies the port of the gateway for tunnel connections from the connectors. */
		port: Option[Int] = None
	)
	
	case class GoogleCloudBeyondcorpAppgatewaysV1alphaAppGatewayOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class AppGatewayOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpConnectionsV1alphaConnectionOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpConnectorsV1alphaConnectorOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpConnectorsV1alphaRemoteAgentDetails(
	
	)
	
	case class GoogleCloudBeyondcorpConnectorsV1alphaContainerHealthDetails(
	  /** The version of the expected config. */
		expectedConfigVersion: Option[String] = None,
	  /** The version of the current config. */
		currentConfigVersion: Option[String] = None,
	  /** The extended status. Such as ExitCode, StartedAt, FinishedAt, etc. */
		extendedStatus: Option[Map[String, String]] = None,
	  /** The latest error message. */
		errorMsg: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpPartnerservicesV1mainPartnerServiceOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the caller has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpPartnerservicesV1alphaPartnerServiceOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the caller has requested cancellation of the operation. Operations that have successfully been cancelled have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1alphaSecurityGatewayOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have been cancelled successfully have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
	
	case class GoogleCloudBeyondcorpSecuritygatewaysV1SecurityGatewayOperationMetadata(
	  /** Output only. The time the operation was created. */
		createTime: Option[String] = None,
	  /** Output only. The time the operation finished running. */
		endTime: Option[String] = None,
	  /** Output only. Server-defined resource path for the target of the operation. */
		target: Option[String] = None,
	  /** Output only. Name of the verb executed by the operation. */
		verb: Option[String] = None,
	  /** Output only. Human-readable status of the operation, if any. */
		statusMessage: Option[String] = None,
	  /** Output only. Identifies whether the user has requested cancellation of the operation. Operations that have been cancelled successfully have Operation.error value with a google.rpc.Status.code of 1, corresponding to `Code.CANCELLED`. */
		requestedCancellation: Option[Boolean] = None,
	  /** Output only. API version used to start the operation. */
		apiVersion: Option[String] = None
	)
}
