package com.boresjo.play.api.google.addressvalidation

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtGoogleMapsAddressvalidationV1PlusCode: Format[Schema.GoogleMapsAddressvalidationV1PlusCode] = Json.format[Schema.GoogleMapsAddressvalidationV1PlusCode]
	given fmtGoogleMapsAddressvalidationV1LanguageOptions: Format[Schema.GoogleMapsAddressvalidationV1LanguageOptions] = Json.format[Schema.GoogleMapsAddressvalidationV1LanguageOptions]
	given fmtGoogleMapsAddressvalidationV1ValidateAddressResponse: Format[Schema.GoogleMapsAddressvalidationV1ValidateAddressResponse] = Json.format[Schema.GoogleMapsAddressvalidationV1ValidateAddressResponse]
	given fmtGoogleMapsAddressvalidationV1ValidationResult: Format[Schema.GoogleMapsAddressvalidationV1ValidationResult] = Json.format[Schema.GoogleMapsAddressvalidationV1ValidationResult]
	given fmtGoogleTypePostalAddress: Format[Schema.GoogleTypePostalAddress] = Json.format[Schema.GoogleTypePostalAddress]
	given fmtGoogleMapsAddressvalidationV1Verdict: Format[Schema.GoogleMapsAddressvalidationV1Verdict] = Json.format[Schema.GoogleMapsAddressvalidationV1Verdict]
	given fmtGoogleMapsAddressvalidationV1Address: Format[Schema.GoogleMapsAddressvalidationV1Address] = Json.format[Schema.GoogleMapsAddressvalidationV1Address]
	given fmtGoogleMapsAddressvalidationV1Geocode: Format[Schema.GoogleMapsAddressvalidationV1Geocode] = Json.format[Schema.GoogleMapsAddressvalidationV1Geocode]
	given fmtGoogleMapsAddressvalidationV1AddressMetadata: Format[Schema.GoogleMapsAddressvalidationV1AddressMetadata] = Json.format[Schema.GoogleMapsAddressvalidationV1AddressMetadata]
	given fmtGoogleMapsAddressvalidationV1UspsData: Format[Schema.GoogleMapsAddressvalidationV1UspsData] = Json.format[Schema.GoogleMapsAddressvalidationV1UspsData]
	given fmtGoogleTypeLatLng: Format[Schema.GoogleTypeLatLng] = Json.format[Schema.GoogleTypeLatLng]
	given fmtGoogleGeoTypeViewport: Format[Schema.GoogleGeoTypeViewport] = Json.format[Schema.GoogleGeoTypeViewport]
	given fmtGoogleMapsAddressvalidationV1ComponentName: Format[Schema.GoogleMapsAddressvalidationV1ComponentName] = Json.format[Schema.GoogleMapsAddressvalidationV1ComponentName]
	given fmtGoogleMapsAddressvalidationV1AddressComponent: Format[Schema.GoogleMapsAddressvalidationV1AddressComponent] = Json.format[Schema.GoogleMapsAddressvalidationV1AddressComponent]
	given fmtGoogleMapsAddressvalidationV1AddressComponentConfirmationLevelEnum: Format[Schema.GoogleMapsAddressvalidationV1AddressComponent.ConfirmationLevelEnum] = JsonEnumFormat[Schema.GoogleMapsAddressvalidationV1AddressComponent.ConfirmationLevelEnum]
	given fmtGoogleMapsAddressvalidationV1ValidateAddressRequest: Format[Schema.GoogleMapsAddressvalidationV1ValidateAddressRequest] = Json.format[Schema.GoogleMapsAddressvalidationV1ValidateAddressRequest]
	given fmtGoogleMapsAddressvalidationV1ProvideValidationFeedbackRequest: Format[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackRequest] = Json.format[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackRequest]
	given fmtGoogleMapsAddressvalidationV1ProvideValidationFeedbackRequestConclusionEnum: Format[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackRequest.ConclusionEnum] = JsonEnumFormat[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackRequest.ConclusionEnum]
	given fmtGoogleMapsAddressvalidationV1VerdictGeocodeGranularityEnum: Format[Schema.GoogleMapsAddressvalidationV1Verdict.GeocodeGranularityEnum] = JsonEnumFormat[Schema.GoogleMapsAddressvalidationV1Verdict.GeocodeGranularityEnum]
	given fmtGoogleMapsAddressvalidationV1VerdictValidationGranularityEnum: Format[Schema.GoogleMapsAddressvalidationV1Verdict.ValidationGranularityEnum] = JsonEnumFormat[Schema.GoogleMapsAddressvalidationV1Verdict.ValidationGranularityEnum]
	given fmtGoogleMapsAddressvalidationV1VerdictInputGranularityEnum: Format[Schema.GoogleMapsAddressvalidationV1Verdict.InputGranularityEnum] = JsonEnumFormat[Schema.GoogleMapsAddressvalidationV1Verdict.InputGranularityEnum]
	given fmtGoogleMapsAddressvalidationV1ProvideValidationFeedbackResponse: Format[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackResponse] = Json.format[Schema.GoogleMapsAddressvalidationV1ProvideValidationFeedbackResponse]
	given fmtGoogleMapsAddressvalidationV1UspsAddress: Format[Schema.GoogleMapsAddressvalidationV1UspsAddress] = Json.format[Schema.GoogleMapsAddressvalidationV1UspsAddress]
}
