package com.boresjo.play.api.google.vault

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtMatter: Format[Schema.Matter] = Json.format[Schema.Matter]
	given fmtMatterStateEnum: Format[Schema.Matter.StateEnum] = JsonEnumFormat[Schema.Matter.StateEnum]
	given fmtMatterPermission: Format[Schema.MatterPermission] = Json.format[Schema.MatterPermission]
	given fmtMatterMatterRegionEnum: Format[Schema.Matter.MatterRegionEnum] = JsonEnumFormat[Schema.Matter.MatterRegionEnum]
	given fmtMatterPermissionRoleEnum: Format[Schema.MatterPermission.RoleEnum] = JsonEnumFormat[Schema.MatterPermission.RoleEnum]
	given fmtCloseMatterRequest: Format[Schema.CloseMatterRequest] = Json.format[Schema.CloseMatterRequest]
	given fmtCloseMatterResponse: Format[Schema.CloseMatterResponse] = Json.format[Schema.CloseMatterResponse]
	given fmtReopenMatterRequest: Format[Schema.ReopenMatterRequest] = Json.format[Schema.ReopenMatterRequest]
	given fmtReopenMatterResponse: Format[Schema.ReopenMatterResponse] = Json.format[Schema.ReopenMatterResponse]
	given fmtUndeleteMatterRequest: Format[Schema.UndeleteMatterRequest] = Json.format[Schema.UndeleteMatterRequest]
	given fmtListMattersResponse: Format[Schema.ListMattersResponse] = Json.format[Schema.ListMattersResponse]
	given fmtAddMatterPermissionsRequest: Format[Schema.AddMatterPermissionsRequest] = Json.format[Schema.AddMatterPermissionsRequest]
	given fmtRemoveMatterPermissionsRequest: Format[Schema.RemoveMatterPermissionsRequest] = Json.format[Schema.RemoveMatterPermissionsRequest]
	given fmtCountArtifactsRequest: Format[Schema.CountArtifactsRequest] = Json.format[Schema.CountArtifactsRequest]
	given fmtQuery: Format[Schema.Query] = Json.format[Schema.Query]
	given fmtCountArtifactsRequestViewEnum: Format[Schema.CountArtifactsRequest.ViewEnum] = JsonEnumFormat[Schema.CountArtifactsRequest.ViewEnum]
	given fmtQueryCorpusEnum: Format[Schema.Query.CorpusEnum] = JsonEnumFormat[Schema.Query.CorpusEnum]
	given fmtQueryDataScopeEnum: Format[Schema.Query.DataScopeEnum] = JsonEnumFormat[Schema.Query.DataScopeEnum]
	given fmtQuerySearchMethodEnum: Format[Schema.Query.SearchMethodEnum] = JsonEnumFormat[Schema.Query.SearchMethodEnum]
	given fmtQueryMethodEnum: Format[Schema.Query.MethodEnum] = JsonEnumFormat[Schema.Query.MethodEnum]
	given fmtAccountInfo: Format[Schema.AccountInfo] = Json.format[Schema.AccountInfo]
	given fmtOrgUnitInfo: Format[Schema.OrgUnitInfo] = Json.format[Schema.OrgUnitInfo]
	given fmtSharedDriveInfo: Format[Schema.SharedDriveInfo] = Json.format[Schema.SharedDriveInfo]
	given fmtHangoutsChatInfo: Format[Schema.HangoutsChatInfo] = Json.format[Schema.HangoutsChatInfo]
	given fmtSitesUrlInfo: Format[Schema.SitesUrlInfo] = Json.format[Schema.SitesUrlInfo]
	given fmtTeamDriveInfo: Format[Schema.TeamDriveInfo] = Json.format[Schema.TeamDriveInfo]
	given fmtMailOptions: Format[Schema.MailOptions] = Json.format[Schema.MailOptions]
	given fmtDriveOptions: Format[Schema.DriveOptions] = Json.format[Schema.DriveOptions]
	given fmtHangoutsChatOptions: Format[Schema.HangoutsChatOptions] = Json.format[Schema.HangoutsChatOptions]
	given fmtVoiceOptions: Format[Schema.VoiceOptions] = Json.format[Schema.VoiceOptions]
	given fmtCalendarOptions: Format[Schema.CalendarOptions] = Json.format[Schema.CalendarOptions]
	given fmtMailOptionsClientSideEncryptedOptionEnum: Format[Schema.MailOptions.ClientSideEncryptedOptionEnum] = JsonEnumFormat[Schema.MailOptions.ClientSideEncryptedOptionEnum]
	given fmtDriveOptionsClientSideEncryptedOptionEnum: Format[Schema.DriveOptions.ClientSideEncryptedOptionEnum] = JsonEnumFormat[Schema.DriveOptions.ClientSideEncryptedOptionEnum]
	given fmtVoiceOptionsCoveredDataEnum: Format[Schema.VoiceOptions.CoveredDataEnum] = JsonEnumFormat[Schema.VoiceOptions.CoveredDataEnum]
	given fmtCalendarOptionsResponseStatusesEnum: Format[Schema.CalendarOptions.ResponseStatusesEnum] = JsonEnumFormat[Schema.CalendarOptions.ResponseStatusesEnum]
	given fmtExport: Format[Schema.Export] = Json.format[Schema.Export]
	given fmtUserInfo: Format[Schema.UserInfo] = Json.format[Schema.UserInfo]
	given fmtExportOptions: Format[Schema.ExportOptions] = Json.format[Schema.ExportOptions]
	given fmtExportStatusEnum: Format[Schema.Export.StatusEnum] = JsonEnumFormat[Schema.Export.StatusEnum]
	given fmtExportStats: Format[Schema.ExportStats] = Json.format[Schema.ExportStats]
	given fmtCloudStorageSink: Format[Schema.CloudStorageSink] = Json.format[Schema.CloudStorageSink]
	given fmtMailExportOptions: Format[Schema.MailExportOptions] = Json.format[Schema.MailExportOptions]
	given fmtGroupsExportOptions: Format[Schema.GroupsExportOptions] = Json.format[Schema.GroupsExportOptions]
	given fmtDriveExportOptions: Format[Schema.DriveExportOptions] = Json.format[Schema.DriveExportOptions]
	given fmtHangoutsChatExportOptions: Format[Schema.HangoutsChatExportOptions] = Json.format[Schema.HangoutsChatExportOptions]
	given fmtVoiceExportOptions: Format[Schema.VoiceExportOptions] = Json.format[Schema.VoiceExportOptions]
	given fmtCalendarExportOptions: Format[Schema.CalendarExportOptions] = Json.format[Schema.CalendarExportOptions]
	given fmtExportOptionsRegionEnum: Format[Schema.ExportOptions.RegionEnum] = JsonEnumFormat[Schema.ExportOptions.RegionEnum]
	given fmtMailExportOptionsExportFormatEnum: Format[Schema.MailExportOptions.ExportFormatEnum] = JsonEnumFormat[Schema.MailExportOptions.ExportFormatEnum]
	given fmtGroupsExportOptionsExportFormatEnum: Format[Schema.GroupsExportOptions.ExportFormatEnum] = JsonEnumFormat[Schema.GroupsExportOptions.ExportFormatEnum]
	given fmtHangoutsChatExportOptionsExportFormatEnum: Format[Schema.HangoutsChatExportOptions.ExportFormatEnum] = JsonEnumFormat[Schema.HangoutsChatExportOptions.ExportFormatEnum]
	given fmtVoiceExportOptionsExportFormatEnum: Format[Schema.VoiceExportOptions.ExportFormatEnum] = JsonEnumFormat[Schema.VoiceExportOptions.ExportFormatEnum]
	given fmtCalendarExportOptionsExportFormatEnum: Format[Schema.CalendarExportOptions.ExportFormatEnum] = JsonEnumFormat[Schema.CalendarExportOptions.ExportFormatEnum]
	given fmtCloudStorageFile: Format[Schema.CloudStorageFile] = Json.format[Schema.CloudStorageFile]
	given fmtListExportsResponse: Format[Schema.ListExportsResponse] = Json.format[Schema.ListExportsResponse]
	given fmtHold: Format[Schema.Hold] = Json.format[Schema.Hold]
	given fmtHeldAccount: Format[Schema.HeldAccount] = Json.format[Schema.HeldAccount]
	given fmtHeldOrgUnit: Format[Schema.HeldOrgUnit] = Json.format[Schema.HeldOrgUnit]
	given fmtHoldCorpusEnum: Format[Schema.Hold.CorpusEnum] = JsonEnumFormat[Schema.Hold.CorpusEnum]
	given fmtCorpusQuery: Format[Schema.CorpusQuery] = Json.format[Schema.CorpusQuery]
	given fmtHeldDriveQuery: Format[Schema.HeldDriveQuery] = Json.format[Schema.HeldDriveQuery]
	given fmtHeldMailQuery: Format[Schema.HeldMailQuery] = Json.format[Schema.HeldMailQuery]
	given fmtHeldGroupsQuery: Format[Schema.HeldGroupsQuery] = Json.format[Schema.HeldGroupsQuery]
	given fmtHeldHangoutsChatQuery: Format[Schema.HeldHangoutsChatQuery] = Json.format[Schema.HeldHangoutsChatQuery]
	given fmtHeldVoiceQuery: Format[Schema.HeldVoiceQuery] = Json.format[Schema.HeldVoiceQuery]
	given fmtHeldCalendarQuery: Format[Schema.HeldCalendarQuery] = Json.format[Schema.HeldCalendarQuery]
	given fmtHeldVoiceQueryCoveredDataEnum: Format[Schema.HeldVoiceQuery.CoveredDataEnum] = JsonEnumFormat[Schema.HeldVoiceQuery.CoveredDataEnum]
	given fmtListHoldsResponse: Format[Schema.ListHoldsResponse] = Json.format[Schema.ListHoldsResponse]
	given fmtAddHeldAccountsRequest: Format[Schema.AddHeldAccountsRequest] = Json.format[Schema.AddHeldAccountsRequest]
	given fmtAddHeldAccountsResponse: Format[Schema.AddHeldAccountsResponse] = Json.format[Schema.AddHeldAccountsResponse]
	given fmtAddHeldAccountResult: Format[Schema.AddHeldAccountResult] = Json.format[Schema.AddHeldAccountResult]
	given fmtRemoveHeldAccountsRequest: Format[Schema.RemoveHeldAccountsRequest] = Json.format[Schema.RemoveHeldAccountsRequest]
	given fmtRemoveHeldAccountsResponse: Format[Schema.RemoveHeldAccountsResponse] = Json.format[Schema.RemoveHeldAccountsResponse]
	given fmtListHeldAccountsResponse: Format[Schema.ListHeldAccountsResponse] = Json.format[Schema.ListHeldAccountsResponse]
	given fmtSavedQuery: Format[Schema.SavedQuery] = Json.format[Schema.SavedQuery]
	given fmtListSavedQueriesResponse: Format[Schema.ListSavedQueriesResponse] = Json.format[Schema.ListSavedQueriesResponse]
	given fmtCountArtifactsResponse: Format[Schema.CountArtifactsResponse] = Json.format[Schema.CountArtifactsResponse]
	given fmtMailCountResult: Format[Schema.MailCountResult] = Json.format[Schema.MailCountResult]
	given fmtGroupsCountResult: Format[Schema.GroupsCountResult] = Json.format[Schema.GroupsCountResult]
	given fmtAccountCountError: Format[Schema.AccountCountError] = Json.format[Schema.AccountCountError]
	given fmtAccountCount: Format[Schema.AccountCount] = Json.format[Schema.AccountCount]
	given fmtAccountCountErrorErrorTypeEnum: Format[Schema.AccountCountError.ErrorTypeEnum] = JsonEnumFormat[Schema.AccountCountError.ErrorTypeEnum]
	given fmtCountArtifactsMetadata: Format[Schema.CountArtifactsMetadata] = Json.format[Schema.CountArtifactsMetadata]
}
