package com.boresjo.play.api.google.assuredworkloads

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1MoveImpact: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1MoveImpact], Option[List[Schema.GoogleCloudAssuredworkloadsV1MoveImpact]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1MoveImpact]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequestRestrictionTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequest.RestrictionTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequest.RestrictionTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1RestrictAllowedResourcesRequest.RestrictionTypeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationRemediation: Conversion[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation, Option[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation]] = (fun: Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationStateEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1Violation.StateEnum, Option[Schema.GoogleCloudAssuredworkloadsV1Violation.StateEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1Violation.StateEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationViolationTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1Violation.ViolationTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1Violation.ViolationTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1Violation.ViolationTypeEnum) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1ViolationExceptionContext: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1ViolationExceptionContext], Option[List[Schema.GoogleCloudAssuredworkloadsV1ViolationExceptionContext]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1ViolationExceptionContext]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1Violation: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1Violation], Option[List[Schema.GoogleCloudAssuredworkloadsV1Violation]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1Violation]) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1Workload: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1Workload], Option[List[Schema.GoogleCloudAssuredworkloadsV1Workload]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1Workload]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadComplianceRegimeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1Workload.ComplianceRegimeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1Workload.ComplianceRegimeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1Workload.ComplianceRegimeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadPartnerPermissions: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadPartnerPermissions, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadPartnerPermissions]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadPartnerPermissions) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadKajEnrollmentStateEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1Workload.KajEnrollmentStateEnum, Option[Schema.GoogleCloudAssuredworkloadsV1Workload.KajEnrollmentStateEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1Workload.KajEnrollmentStateEnum) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadComplianceStatus: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadComplianceStatus, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadComplianceStatus]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadComplianceStatus) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1WorkloadResourceInfo: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo], Option[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadKMSSettings: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadKMSSettings, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadKMSSettings]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadKMSSettings) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1WorkloadResourceSettings: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings], Option[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadPartnerEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1Workload.PartnerEnum, Option[Schema.GoogleCloudAssuredworkloadsV1Workload.PartnerEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1Workload.PartnerEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadWorkloadOptionsKajEnrollmentTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions.KajEnrollmentTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions.KajEnrollmentTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadWorkloadOptions.KajEnrollmentTypeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadResourceSettingsResourceTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings.ResourceTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings.ResourceTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceSettings.ResourceTypeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationRemediationRemediationTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation.RemediationTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation.RemediationTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1ViolationRemediation.RemediationTypeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationRemediationInstructions: Conversion[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructions, Option[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructions]] = (fun: Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructions) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsole: Conversion[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsole, Option[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsole]] = (fun: Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsConsole) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloud: Conversion[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloud, Option[Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloud]] = (fun: Schema.GoogleCloudAssuredworkloadsV1ViolationRemediationInstructionsGcloud) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponseSetupStatusEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupStatusEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupStatusEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupStatusEnum) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponseSetupErrorsEnum: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupErrorsEnum], Option[List[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupErrorsEnum]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1WorkloadSaaEnrollmentResponse.SetupErrorsEnum]) => Option(fun)
		given putListSchemaGoogleLongrunningOperation: Conversion[List[Schema.GoogleLongrunningOperation], Option[List[Schema.GoogleLongrunningOperation]]] = (fun: List[Schema.GoogleLongrunningOperation]) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1MoveAnalysisGroup: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisGroup], Option[List[Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisGroup]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisGroup]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1MoveAnalysisResult: Conversion[Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisResult, Option[Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisResult]] = (fun: Schema.GoogleCloudAssuredworkloadsV1MoveAnalysisResult) => Option(fun)
		given putSchemaGoogleRpcStatus: Conversion[Schema.GoogleRpcStatus, Option[Schema.GoogleRpcStatus]] = (fun: Schema.GoogleRpcStatus) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponseEkmProvisioningStateEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningStateEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningStateEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningStateEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponseEkmProvisioningErrorDomainEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorDomainEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorDomainEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorDomainEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponseEkmProvisioningErrorMappingEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorMappingEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorMappingEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadEkmProvisioningResponse.EkmProvisioningErrorMappingEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1WorkloadResourceInfoResourceTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo.ResourceTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo.ResourceTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1WorkloadResourceInfo.ResourceTypeEnum) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadataComplianceRegimeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadata.ComplianceRegimeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadata.ComplianceRegimeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1CreateWorkloadOperationMetadata.ComplianceRegimeEnum) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaGoogleCloudAssuredworkloadsV1AcknowledgeViolationRequestAcknowledgeTypeEnum: Conversion[Schema.GoogleCloudAssuredworkloadsV1AcknowledgeViolationRequest.AcknowledgeTypeEnum, Option[Schema.GoogleCloudAssuredworkloadsV1AcknowledgeViolationRequest.AcknowledgeTypeEnum]] = (fun: Schema.GoogleCloudAssuredworkloadsV1AcknowledgeViolationRequest.AcknowledgeTypeEnum) => Option(fun)
		given putListSchemaGoogleCloudAssuredworkloadsV1AssetMoveAnalysis: Conversion[List[Schema.GoogleCloudAssuredworkloadsV1AssetMoveAnalysis], Option[List[Schema.GoogleCloudAssuredworkloadsV1AssetMoveAnalysis]]] = (fun: List[Schema.GoogleCloudAssuredworkloadsV1AssetMoveAnalysis]) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
