package com.boresjo.play.api.google.games

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtAchievementDefinitionsListResponse: Format[Schema.AchievementDefinitionsListResponse] = Json.format[Schema.AchievementDefinitionsListResponse]
	given fmtAchievementDefinition: Format[Schema.AchievementDefinition] = Json.format[Schema.AchievementDefinition]
	given fmtAchievementDefinitionAchievementTypeEnum: Format[Schema.AchievementDefinition.AchievementTypeEnum] = JsonEnumFormat[Schema.AchievementDefinition.AchievementTypeEnum]
	given fmtAchievementDefinitionInitialStateEnum: Format[Schema.AchievementDefinition.InitialStateEnum] = JsonEnumFormat[Schema.AchievementDefinition.InitialStateEnum]
	given fmtAchievementIncrementResponse: Format[Schema.AchievementIncrementResponse] = Json.format[Schema.AchievementIncrementResponse]
	given fmtPlayerAchievementListResponse: Format[Schema.PlayerAchievementListResponse] = Json.format[Schema.PlayerAchievementListResponse]
	given fmtPlayerAchievement: Format[Schema.PlayerAchievement] = Json.format[Schema.PlayerAchievement]
	given fmtPlayerAchievementAchievementStateEnum: Format[Schema.PlayerAchievement.AchievementStateEnum] = JsonEnumFormat[Schema.PlayerAchievement.AchievementStateEnum]
	given fmtAchievementRevealResponse: Format[Schema.AchievementRevealResponse] = Json.format[Schema.AchievementRevealResponse]
	given fmtAchievementRevealResponseCurrentStateEnum: Format[Schema.AchievementRevealResponse.CurrentStateEnum] = JsonEnumFormat[Schema.AchievementRevealResponse.CurrentStateEnum]
	given fmtAchievementSetStepsAtLeastResponse: Format[Schema.AchievementSetStepsAtLeastResponse] = Json.format[Schema.AchievementSetStepsAtLeastResponse]
	given fmtAchievementUnlockResponse: Format[Schema.AchievementUnlockResponse] = Json.format[Schema.AchievementUnlockResponse]
	given fmtAchievementUpdateMultipleRequest: Format[Schema.AchievementUpdateMultipleRequest] = Json.format[Schema.AchievementUpdateMultipleRequest]
	given fmtAchievementUpdateRequest: Format[Schema.AchievementUpdateRequest] = Json.format[Schema.AchievementUpdateRequest]
	given fmtAchievementUpdateRequestUpdateTypeEnum: Format[Schema.AchievementUpdateRequest.UpdateTypeEnum] = JsonEnumFormat[Schema.AchievementUpdateRequest.UpdateTypeEnum]
	given fmtGamesAchievementIncrement: Format[Schema.GamesAchievementIncrement] = Json.format[Schema.GamesAchievementIncrement]
	given fmtGamesAchievementSetStepsAtLeast: Format[Schema.GamesAchievementSetStepsAtLeast] = Json.format[Schema.GamesAchievementSetStepsAtLeast]
	given fmtAchievementUpdateMultipleResponse: Format[Schema.AchievementUpdateMultipleResponse] = Json.format[Schema.AchievementUpdateMultipleResponse]
	given fmtAchievementUpdateResponse: Format[Schema.AchievementUpdateResponse] = Json.format[Schema.AchievementUpdateResponse]
	given fmtAchievementUpdateResponseCurrentStateEnum: Format[Schema.AchievementUpdateResponse.CurrentStateEnum] = JsonEnumFormat[Schema.AchievementUpdateResponse.CurrentStateEnum]
	given fmtApplication: Format[Schema.Application] = Json.format[Schema.Application]
	given fmtApplicationCategory: Format[Schema.ApplicationCategory] = Json.format[Schema.ApplicationCategory]
	given fmtImageAsset: Format[Schema.ImageAsset] = Json.format[Schema.ImageAsset]
	given fmtInstance: Format[Schema.Instance] = Json.format[Schema.Instance]
	given fmtApplicationEnabledFeaturesEnum: Format[Schema.Application.EnabledFeaturesEnum] = JsonEnumFormat[Schema.Application.EnabledFeaturesEnum]
	given fmtInstancePlatformTypeEnum: Format[Schema.Instance.PlatformTypeEnum] = JsonEnumFormat[Schema.Instance.PlatformTypeEnum]
	given fmtInstanceAndroidDetails: Format[Schema.InstanceAndroidDetails] = Json.format[Schema.InstanceAndroidDetails]
	given fmtInstanceIosDetails: Format[Schema.InstanceIosDetails] = Json.format[Schema.InstanceIosDetails]
	given fmtInstanceWebDetails: Format[Schema.InstanceWebDetails] = Json.format[Schema.InstanceWebDetails]
	given fmtApplicationVerifyResponse: Format[Schema.ApplicationVerifyResponse] = Json.format[Schema.ApplicationVerifyResponse]
	given fmtEndPoint: Format[Schema.EndPoint] = Json.format[Schema.EndPoint]
	given fmtPlayerEventListResponse: Format[Schema.PlayerEventListResponse] = Json.format[Schema.PlayerEventListResponse]
	given fmtPlayerEvent: Format[Schema.PlayerEvent] = Json.format[Schema.PlayerEvent]
	given fmtEventDefinitionListResponse: Format[Schema.EventDefinitionListResponse] = Json.format[Schema.EventDefinitionListResponse]
	given fmtEventDefinition: Format[Schema.EventDefinition] = Json.format[Schema.EventDefinition]
	given fmtEventDefinitionVisibilityEnum: Format[Schema.EventDefinition.VisibilityEnum] = JsonEnumFormat[Schema.EventDefinition.VisibilityEnum]
	given fmtEventChild: Format[Schema.EventChild] = Json.format[Schema.EventChild]
	given fmtEventRecordRequest: Format[Schema.EventRecordRequest] = Json.format[Schema.EventRecordRequest]
	given fmtEventPeriodUpdate: Format[Schema.EventPeriodUpdate] = Json.format[Schema.EventPeriodUpdate]
	given fmtEventPeriodRange: Format[Schema.EventPeriodRange] = Json.format[Schema.EventPeriodRange]
	given fmtEventUpdateRequest: Format[Schema.EventUpdateRequest] = Json.format[Schema.EventUpdateRequest]
	given fmtEventUpdateResponse: Format[Schema.EventUpdateResponse] = Json.format[Schema.EventUpdateResponse]
	given fmtEventBatchRecordFailure: Format[Schema.EventBatchRecordFailure] = Json.format[Schema.EventBatchRecordFailure]
	given fmtEventRecordFailure: Format[Schema.EventRecordFailure] = Json.format[Schema.EventRecordFailure]
	given fmtEventBatchRecordFailureFailureCauseEnum: Format[Schema.EventBatchRecordFailure.FailureCauseEnum] = JsonEnumFormat[Schema.EventBatchRecordFailure.FailureCauseEnum]
	given fmtEventRecordFailureFailureCauseEnum: Format[Schema.EventRecordFailure.FailureCauseEnum] = JsonEnumFormat[Schema.EventRecordFailure.FailureCauseEnum]
	given fmtLeaderboard: Format[Schema.Leaderboard] = Json.format[Schema.Leaderboard]
	given fmtLeaderboardOrderEnum: Format[Schema.Leaderboard.OrderEnum] = JsonEnumFormat[Schema.Leaderboard.OrderEnum]
	given fmtLeaderboardListResponse: Format[Schema.LeaderboardListResponse] = Json.format[Schema.LeaderboardListResponse]
	given fmtMetagameConfig: Format[Schema.MetagameConfig] = Json.format[Schema.MetagameConfig]
	given fmtPlayerLevel: Format[Schema.PlayerLevel] = Json.format[Schema.PlayerLevel]
	given fmtCategoryListResponse: Format[Schema.CategoryListResponse] = Json.format[Schema.CategoryListResponse]
	given fmtCategory: Format[Schema.Category] = Json.format[Schema.Category]
	given fmtPlayer: Format[Schema.Player] = Json.format[Schema.Player]
	given fmtProfileSettings: Format[Schema.ProfileSettings] = Json.format[Schema.ProfileSettings]
	given fmtPlayerNameItem: Format[Schema.Player.NameItem] = Json.format[Schema.Player.NameItem]
	given fmtPlayerExperienceInfo: Format[Schema.PlayerExperienceInfo] = Json.format[Schema.PlayerExperienceInfo]
	given fmtPlayerFriendStatusEnum: Format[Schema.Player.FriendStatusEnum] = JsonEnumFormat[Schema.Player.FriendStatusEnum]
	given fmtProfileSettingsFriendsListVisibilityEnum: Format[Schema.ProfileSettings.FriendsListVisibilityEnum] = JsonEnumFormat[Schema.ProfileSettings.FriendsListVisibilityEnum]
	given fmtScopedPlayerIds: Format[Schema.ScopedPlayerIds] = Json.format[Schema.ScopedPlayerIds]
	given fmtGetMultipleApplicationPlayerIdsResponse: Format[Schema.GetMultipleApplicationPlayerIdsResponse] = Json.format[Schema.GetMultipleApplicationPlayerIdsResponse]
	given fmtApplicationPlayerId: Format[Schema.ApplicationPlayerId] = Json.format[Schema.ApplicationPlayerId]
	given fmtPlayerListResponse: Format[Schema.PlayerListResponse] = Json.format[Schema.PlayerListResponse]
	given fmtRevisionCheckResponse: Format[Schema.RevisionCheckResponse] = Json.format[Schema.RevisionCheckResponse]
	given fmtRevisionCheckResponseRevisionStatusEnum: Format[Schema.RevisionCheckResponse.RevisionStatusEnum] = JsonEnumFormat[Schema.RevisionCheckResponse.RevisionStatusEnum]
	given fmtPlayerLeaderboardScoreListResponse: Format[Schema.PlayerLeaderboardScoreListResponse] = Json.format[Schema.PlayerLeaderboardScoreListResponse]
	given fmtPlayerLeaderboardScore: Format[Schema.PlayerLeaderboardScore] = Json.format[Schema.PlayerLeaderboardScore]
	given fmtLeaderboardScoreRank: Format[Schema.LeaderboardScoreRank] = Json.format[Schema.LeaderboardScoreRank]
	given fmtPlayerLeaderboardScoreTimeSpanEnum: Format[Schema.PlayerLeaderboardScore.TimeSpanEnum] = JsonEnumFormat[Schema.PlayerLeaderboardScore.TimeSpanEnum]
	given fmtLeaderboardScores: Format[Schema.LeaderboardScores] = Json.format[Schema.LeaderboardScores]
	given fmtLeaderboardEntry: Format[Schema.LeaderboardEntry] = Json.format[Schema.LeaderboardEntry]
	given fmtLeaderboardEntryTimeSpanEnum: Format[Schema.LeaderboardEntry.TimeSpanEnum] = JsonEnumFormat[Schema.LeaderboardEntry.TimeSpanEnum]
	given fmtPlayerScoreResponse: Format[Schema.PlayerScoreResponse] = Json.format[Schema.PlayerScoreResponse]
	given fmtPlayerScoreResponseBeatenScoreTimeSpansEnum: Format[Schema.PlayerScoreResponse.BeatenScoreTimeSpansEnum] = JsonEnumFormat[Schema.PlayerScoreResponse.BeatenScoreTimeSpansEnum]
	given fmtPlayerScore: Format[Schema.PlayerScore] = Json.format[Schema.PlayerScore]
	given fmtPlayerScoreTimeSpanEnum: Format[Schema.PlayerScore.TimeSpanEnum] = JsonEnumFormat[Schema.PlayerScore.TimeSpanEnum]
	given fmtPlayerScoreSubmissionList: Format[Schema.PlayerScoreSubmissionList] = Json.format[Schema.PlayerScoreSubmissionList]
	given fmtScoreSubmission: Format[Schema.ScoreSubmission] = Json.format[Schema.ScoreSubmission]
	given fmtPlayerScoreListResponse: Format[Schema.PlayerScoreListResponse] = Json.format[Schema.PlayerScoreListResponse]
	given fmtSnapshot: Format[Schema.Snapshot] = Json.format[Schema.Snapshot]
	given fmtSnapshotTypeEnum: Format[Schema.Snapshot.TypeEnum] = JsonEnumFormat[Schema.Snapshot.TypeEnum]
	given fmtSnapshotImage: Format[Schema.SnapshotImage] = Json.format[Schema.SnapshotImage]
	given fmtSnapshotListResponse: Format[Schema.SnapshotListResponse] = Json.format[Schema.SnapshotListResponse]
	given fmtStatsResponse: Format[Schema.StatsResponse] = Json.format[Schema.StatsResponse]
	given fmtLinkPersonaRequest: Format[Schema.LinkPersonaRequest] = Json.format[Schema.LinkPersonaRequest]
	given fmtLinkPersonaRequestCardinalityConstraintEnum: Format[Schema.LinkPersonaRequest.CardinalityConstraintEnum] = JsonEnumFormat[Schema.LinkPersonaRequest.CardinalityConstraintEnum]
	given fmtLinkPersonaRequestConflictingLinksResolutionPolicyEnum: Format[Schema.LinkPersonaRequest.ConflictingLinksResolutionPolicyEnum] = JsonEnumFormat[Schema.LinkPersonaRequest.ConflictingLinksResolutionPolicyEnum]
	given fmtLinkPersonaResponse: Format[Schema.LinkPersonaResponse] = Json.format[Schema.LinkPersonaResponse]
	given fmtLinkPersonaResponseStateEnum: Format[Schema.LinkPersonaResponse.StateEnum] = JsonEnumFormat[Schema.LinkPersonaResponse.StateEnum]
	given fmtRetrievePlayerTokensResponse: Format[Schema.RetrievePlayerTokensResponse] = Json.format[Schema.RetrievePlayerTokensResponse]
	given fmtRecallToken: Format[Schema.RecallToken] = Json.format[Schema.RecallToken]
	given fmtRetrieveDeveloperGamesLastPlayerTokenResponse: Format[Schema.RetrieveDeveloperGamesLastPlayerTokenResponse] = Json.format[Schema.RetrieveDeveloperGamesLastPlayerTokenResponse]
	given fmtGamePlayerToken: Format[Schema.GamePlayerToken] = Json.format[Schema.GamePlayerToken]
	given fmtRetrieveGamesPlayerTokensResponse: Format[Schema.RetrieveGamesPlayerTokensResponse] = Json.format[Schema.RetrieveGamesPlayerTokensResponse]
	given fmtUnlinkPersonaRequest: Format[Schema.UnlinkPersonaRequest] = Json.format[Schema.UnlinkPersonaRequest]
	given fmtUnlinkPersonaResponse: Format[Schema.UnlinkPersonaResponse] = Json.format[Schema.UnlinkPersonaResponse]
	given fmtResetPersonaRequest: Format[Schema.ResetPersonaRequest] = Json.format[Schema.ResetPersonaRequest]
	given fmtResetPersonaResponse: Format[Schema.ResetPersonaResponse] = Json.format[Schema.ResetPersonaResponse]
	given fmtGeneratePlayGroupingApiTokenResponse: Format[Schema.GeneratePlayGroupingApiTokenResponse] = Json.format[Schema.GeneratePlayGroupingApiTokenResponse]
	given fmtPlayGroupingApiToken: Format[Schema.PlayGroupingApiToken] = Json.format[Schema.PlayGroupingApiToken]
	given fmtGenerateRecallPlayGroupingApiTokenResponse: Format[Schema.GenerateRecallPlayGroupingApiTokenResponse] = Json.format[Schema.GenerateRecallPlayGroupingApiTokenResponse]
}
