package com.boresjo.play.api.google.recommendationengine

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putListSchemaGoogleLongrunningOperation: Conversion[List[Schema.GoogleLongrunningOperation], Option[List[Schema.GoogleLongrunningOperation]]] = (fun: List[Schema.GoogleLongrunningOperation]) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaGoogleRpcStatus: Conversion[Schema.GoogleRpcStatus, Option[Schema.GoogleRpcStatus]] = (fun: Schema.GoogleRpcStatus) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1Catalog: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1Catalog], Option[List[Schema.GoogleCloudRecommendationengineV1beta1Catalog]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1Catalog]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig: Conversion[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig, Option[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1CatalogItemLevelConfigEventItemLevelEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.EventItemLevelEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.EventItemLevelEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.EventItemLevelEnum) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1CatalogItemLevelConfigPredictItemLevelEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.PredictItemLevelEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.PredictItemLevelEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1CatalogItemLevelConfig.PredictItemLevelEnum) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy], Option[List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItemCategoryHierarchy]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1FeatureMap: Conversion[Schema.GoogleCloudRecommendationengineV1beta1FeatureMap, Option[Schema.GoogleCloudRecommendationengineV1beta1FeatureMap]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1FeatureMap) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductCatalogItem: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem) => Option(fun)
		given putMapStringSchemaGoogleCloudRecommendationengineV1beta1FeatureMapStringList: Conversion[Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapStringList], Option[Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapStringList]]] = (fun: Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapStringList]) => Option(fun)
		given putMapStringSchemaGoogleCloudRecommendationengineV1beta1FeatureMapFloatList: Conversion[Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapFloatList], Option[Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapFloatList]]] = (fun: Map[String, Schema.GoogleCloudRecommendationengineV1beta1FeatureMapFloatList]) => Option(fun)
		given putListBigDecimal: Conversion[List[BigDecimal], Option[List[BigDecimal]]] = (fun: List[BigDecimal]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemExactPrice) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItemPriceRange) => Option(fun)
		given putMapStringBigDecimal: Conversion[Map[String, BigDecimal], Option[Map[String, BigDecimal]]] = (fun: Map[String, BigDecimal]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductCatalogItemStockStateEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem.StockStateEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem.StockStateEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductCatalogItem.StockStateEnum) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1Image: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1Image], Option[List[Schema.GoogleCloudRecommendationengineV1beta1Image]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1Image]) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1CatalogItem: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItem], Option[List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItem]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1CatalogItem]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1InputConfig: Conversion[Schema.GoogleCloudRecommendationengineV1beta1InputConfig, Option[Schema.GoogleCloudRecommendationengineV1beta1InputConfig]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1InputConfig) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ImportErrorsConfig: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ImportErrorsConfig, Option[Schema.GoogleCloudRecommendationengineV1beta1ImportErrorsConfig]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ImportErrorsConfig) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1CatalogInlineSource: Conversion[Schema.GoogleCloudRecommendationengineV1beta1CatalogInlineSource, Option[Schema.GoogleCloudRecommendationengineV1beta1CatalogInlineSource]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1CatalogInlineSource) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1GcsSource: Conversion[Schema.GoogleCloudRecommendationengineV1beta1GcsSource, Option[Schema.GoogleCloudRecommendationengineV1beta1GcsSource]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1GcsSource) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1UserEventInlineSource: Conversion[Schema.GoogleCloudRecommendationengineV1beta1UserEventInlineSource, Option[Schema.GoogleCloudRecommendationengineV1beta1UserEventInlineSource]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1UserEventInlineSource) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1BigQuerySource: Conversion[Schema.GoogleCloudRecommendationengineV1beta1BigQuerySource, Option[Schema.GoogleCloudRecommendationengineV1beta1BigQuerySource]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1BigQuerySource) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1UserEvent: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1UserEvent], Option[List[Schema.GoogleCloudRecommendationengineV1beta1UserEvent]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1UserEvent]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1UserInfo: Conversion[Schema.GoogleCloudRecommendationengineV1beta1UserInfo, Option[Schema.GoogleCloudRecommendationengineV1beta1UserInfo]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1UserInfo) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1EventDetail: Conversion[Schema.GoogleCloudRecommendationengineV1beta1EventDetail, Option[Schema.GoogleCloudRecommendationengineV1beta1EventDetail]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1EventDetail) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductEventDetail: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductEventDetail, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductEventDetail]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductEventDetail) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1UserEventEventSourceEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1UserEvent.EventSourceEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1UserEvent.EventSourceEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1UserEvent.EventSourceEnum) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1ProductDetail: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1ProductDetail], Option[List[Schema.GoogleCloudRecommendationengineV1beta1ProductDetail]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1ProductDetail]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1PurchaseTransaction: Conversion[Schema.GoogleCloudRecommendationengineV1beta1PurchaseTransaction, Option[Schema.GoogleCloudRecommendationengineV1beta1PurchaseTransaction]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1PurchaseTransaction) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1ProductDetailStockStateEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1ProductDetail.StockStateEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1ProductDetail.StockStateEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1ProductDetail.StockStateEnum) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration: Conversion[Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration, Option[Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration], Option[List[Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1PredictionApiKeyRegistration]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1UserEvent: Conversion[Schema.GoogleCloudRecommendationengineV1beta1UserEvent, Option[Schema.GoogleCloudRecommendationengineV1beta1UserEvent]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1UserEvent) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putListSchemaGoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult: Conversion[List[Schema.GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult], Option[List[Schema.GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult]]] = (fun: List[Schema.GoogleCloudRecommendationengineV1beta1PredictResponsePredictionResult]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1RejoinUserEventsRequestUserEventRejoinScopeEnum: Conversion[Schema.GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequest.UserEventRejoinScopeEnum, Option[Schema.GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequest.UserEventRejoinScopeEnum]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1RejoinUserEventsRequest.UserEventRejoinScopeEnum) => Option(fun)
		given putListSchemaGoogleRpcStatus: Conversion[List[Schema.GoogleRpcStatus], Option[List[Schema.GoogleRpcStatus]]] = (fun: List[Schema.GoogleRpcStatus]) => Option(fun)
		given putSchemaGoogleCloudRecommendationengineV1beta1UserEventImportSummary: Conversion[Schema.GoogleCloudRecommendationengineV1beta1UserEventImportSummary, Option[Schema.GoogleCloudRecommendationengineV1beta1UserEventImportSummary]] = (fun: Schema.GoogleCloudRecommendationengineV1beta1UserEventImportSummary) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
