package com.boresjo.play.api.google.drive

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtAbout: Format[Schema.About] = Json.format[Schema.About]
	given fmtAboutStorageQuotaItem: Format[Schema.About.StorageQuotaItem] = Json.format[Schema.About.StorageQuotaItem]
	given fmtAboutDriveThemesItem: Format[Schema.About.DriveThemesItem] = Json.format[Schema.About.DriveThemesItem]
	given fmtUser: Format[Schema.User] = Json.format[Schema.User]
	given fmtAboutTeamDriveThemesItem: Format[Schema.About.TeamDriveThemesItem] = Json.format[Schema.About.TeamDriveThemesItem]
	given fmtApp: Format[Schema.App] = Json.format[Schema.App]
	given fmtAppIcons: Format[Schema.AppIcons] = Json.format[Schema.AppIcons]
	given fmtAppList: Format[Schema.AppList] = Json.format[Schema.AppList]
	given fmtStartPageToken: Format[Schema.StartPageToken] = Json.format[Schema.StartPageToken]
	given fmtChangeList: Format[Schema.ChangeList] = Json.format[Schema.ChangeList]
	given fmtChange: Format[Schema.Change] = Json.format[Schema.Change]
	given fmtFile: Format[Schema.File] = Json.format[Schema.File]
	given fmtTeamDrive: Format[Schema.TeamDrive] = Json.format[Schema.TeamDrive]
	given fmtDrive: Format[Schema.Drive] = Json.format[Schema.Drive]
	given fmtFileContentHintsItem: Format[Schema.File.ContentHintsItem] = Json.format[Schema.File.ContentHintsItem]
	given fmtFileContentHintsItemThumbnailItem: Format[Schema.File.ContentHintsItem.ThumbnailItem] = Json.format[Schema.File.ContentHintsItem.ThumbnailItem]
	given fmtPermission: Format[Schema.Permission] = Json.format[Schema.Permission]
	given fmtFileCapabilitiesItem: Format[Schema.File.CapabilitiesItem] = Json.format[Schema.File.CapabilitiesItem]
	given fmtFileImageMediaMetadataItem: Format[Schema.File.ImageMediaMetadataItem] = Json.format[Schema.File.ImageMediaMetadataItem]
	given fmtFileImageMediaMetadataItemLocationItem: Format[Schema.File.ImageMediaMetadataItem.LocationItem] = Json.format[Schema.File.ImageMediaMetadataItem.LocationItem]
	given fmtFileVideoMediaMetadataItem: Format[Schema.File.VideoMediaMetadataItem] = Json.format[Schema.File.VideoMediaMetadataItem]
	given fmtFileShortcutDetailsItem: Format[Schema.File.ShortcutDetailsItem] = Json.format[Schema.File.ShortcutDetailsItem]
	given fmtContentRestriction: Format[Schema.ContentRestriction] = Json.format[Schema.ContentRestriction]
	given fmtFileLinkShareMetadataItem: Format[Schema.File.LinkShareMetadataItem] = Json.format[Schema.File.LinkShareMetadataItem]
	given fmtFileLabelInfoItem: Format[Schema.File.LabelInfoItem] = Json.format[Schema.File.LabelInfoItem]
	given fmtLabel: Format[Schema.Label] = Json.format[Schema.Label]
	given fmtPermissionPermissionDetailsItem: Format[Schema.Permission.PermissionDetailsItem] = Json.format[Schema.Permission.PermissionDetailsItem]
	given fmtPermissionTeamDrivePermissionDetailsItem: Format[Schema.Permission.TeamDrivePermissionDetailsItem] = Json.format[Schema.Permission.TeamDrivePermissionDetailsItem]
	given fmtLabelField: Format[Schema.LabelField] = Json.format[Schema.LabelField]
	given fmtTeamDriveCapabilitiesItem: Format[Schema.TeamDrive.CapabilitiesItem] = Json.format[Schema.TeamDrive.CapabilitiesItem]
	given fmtTeamDriveBackgroundImageFileItem: Format[Schema.TeamDrive.BackgroundImageFileItem] = Json.format[Schema.TeamDrive.BackgroundImageFileItem]
	given fmtTeamDriveRestrictionsItem: Format[Schema.TeamDrive.RestrictionsItem] = Json.format[Schema.TeamDrive.RestrictionsItem]
	given fmtDriveCapabilitiesItem: Format[Schema.Drive.CapabilitiesItem] = Json.format[Schema.Drive.CapabilitiesItem]
	given fmtDriveBackgroundImageFileItem: Format[Schema.Drive.BackgroundImageFileItem] = Json.format[Schema.Drive.BackgroundImageFileItem]
	given fmtDriveRestrictionsItem: Format[Schema.Drive.RestrictionsItem] = Json.format[Schema.Drive.RestrictionsItem]
	given fmtChannel: Format[Schema.Channel] = Json.format[Schema.Channel]
	given fmtComment: Format[Schema.Comment] = Json.format[Schema.Comment]
	given fmtReply: Format[Schema.Reply] = Json.format[Schema.Reply]
	given fmtCommentQuotedFileContentItem: Format[Schema.Comment.QuotedFileContentItem] = Json.format[Schema.Comment.QuotedFileContentItem]
	given fmtCommentList: Format[Schema.CommentList] = Json.format[Schema.CommentList]
	given fmtDriveList: Format[Schema.DriveList] = Json.format[Schema.DriveList]
	given fmtGeneratedIds: Format[Schema.GeneratedIds] = Json.format[Schema.GeneratedIds]
	given fmtFileList: Format[Schema.FileList] = Json.format[Schema.FileList]
	given fmtLabelList: Format[Schema.LabelList] = Json.format[Schema.LabelList]
	given fmtModifyLabelsRequest: Format[Schema.ModifyLabelsRequest] = Json.format[Schema.ModifyLabelsRequest]
	given fmtLabelModification: Format[Schema.LabelModification] = Json.format[Schema.LabelModification]
	given fmtLabelFieldModification: Format[Schema.LabelFieldModification] = Json.format[Schema.LabelFieldModification]
	given fmtModifyLabelsResponse: Format[Schema.ModifyLabelsResponse] = Json.format[Schema.ModifyLabelsResponse]
	given fmtPermissionList: Format[Schema.PermissionList] = Json.format[Schema.PermissionList]
	given fmtReplyList: Format[Schema.ReplyList] = Json.format[Schema.ReplyList]
	given fmtRevision: Format[Schema.Revision] = Json.format[Schema.Revision]
	given fmtRevisionList: Format[Schema.RevisionList] = Json.format[Schema.RevisionList]
	given fmtTeamDriveList: Format[Schema.TeamDriveList] = Json.format[Schema.TeamDriveList]
	given fmtAccessProposal: Format[Schema.AccessProposal] = Json.format[Schema.AccessProposal]
	given fmtAccessProposalRoleAndView: Format[Schema.AccessProposalRoleAndView] = Json.format[Schema.AccessProposalRoleAndView]
	given fmtResolveAccessProposalRequest: Format[Schema.ResolveAccessProposalRequest] = Json.format[Schema.ResolveAccessProposalRequest]
	given fmtResolveAccessProposalRequestActionEnum: Format[Schema.ResolveAccessProposalRequest.ActionEnum] = JsonEnumFormat[Schema.ResolveAccessProposalRequest.ActionEnum]
	given fmtListAccessProposalsResponse: Format[Schema.ListAccessProposalsResponse] = Json.format[Schema.ListAccessProposalsResponse]
}
