package com.boresjo.play.api.google.cloudfunctions

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtFunction: Format[Schema.Function] = Json.format[Schema.Function]
	given fmtBuildConfig: Format[Schema.BuildConfig] = Json.format[Schema.BuildConfig]
	given fmtServiceConfig: Format[Schema.ServiceConfig] = Json.format[Schema.ServiceConfig]
	given fmtEventTrigger: Format[Schema.EventTrigger] = Json.format[Schema.EventTrigger]
	given fmtFunctionStateEnum: Format[Schema.Function.StateEnum] = JsonEnumFormat[Schema.Function.StateEnum]
	given fmtGoogleCloudFunctionsV2StateMessage: Format[Schema.GoogleCloudFunctionsV2StateMessage] = Json.format[Schema.GoogleCloudFunctionsV2StateMessage]
	given fmtFunctionEnvironmentEnum: Format[Schema.Function.EnvironmentEnum] = JsonEnumFormat[Schema.Function.EnvironmentEnum]
	given fmtUpgradeInfo: Format[Schema.UpgradeInfo] = Json.format[Schema.UpgradeInfo]
	given fmtAutomaticUpdatePolicy: Format[Schema.AutomaticUpdatePolicy] = Json.format[Schema.AutomaticUpdatePolicy]
	given fmtOnDeployUpdatePolicy: Format[Schema.OnDeployUpdatePolicy] = Json.format[Schema.OnDeployUpdatePolicy]
	given fmtSource: Format[Schema.Source] = Json.format[Schema.Source]
	given fmtSourceProvenance: Format[Schema.SourceProvenance] = Json.format[Schema.SourceProvenance]
	given fmtBuildConfigDockerRegistryEnum: Format[Schema.BuildConfig.DockerRegistryEnum] = JsonEnumFormat[Schema.BuildConfig.DockerRegistryEnum]
	given fmtStorageSource: Format[Schema.StorageSource] = Json.format[Schema.StorageSource]
	given fmtRepoSource: Format[Schema.RepoSource] = Json.format[Schema.RepoSource]
	given fmtServiceConfigVpcConnectorEgressSettingsEnum: Format[Schema.ServiceConfig.VpcConnectorEgressSettingsEnum] = JsonEnumFormat[Schema.ServiceConfig.VpcConnectorEgressSettingsEnum]
	given fmtServiceConfigIngressSettingsEnum: Format[Schema.ServiceConfig.IngressSettingsEnum] = JsonEnumFormat[Schema.ServiceConfig.IngressSettingsEnum]
	given fmtSecretEnvVar: Format[Schema.SecretEnvVar] = Json.format[Schema.SecretEnvVar]
	given fmtSecretVolume: Format[Schema.SecretVolume] = Json.format[Schema.SecretVolume]
	given fmtServiceConfigSecurityLevelEnum: Format[Schema.ServiceConfig.SecurityLevelEnum] = JsonEnumFormat[Schema.ServiceConfig.SecurityLevelEnum]
	given fmtSecretVersion: Format[Schema.SecretVersion] = Json.format[Schema.SecretVersion]
	given fmtEventFilter: Format[Schema.EventFilter] = Json.format[Schema.EventFilter]
	given fmtEventTriggerRetryPolicyEnum: Format[Schema.EventTrigger.RetryPolicyEnum] = JsonEnumFormat[Schema.EventTrigger.RetryPolicyEnum]
	given fmtGoogleCloudFunctionsV2StateMessageSeverityEnum: Format[Schema.GoogleCloudFunctionsV2StateMessage.SeverityEnum] = JsonEnumFormat[Schema.GoogleCloudFunctionsV2StateMessage.SeverityEnum]
	given fmtUpgradeInfoUpgradeStateEnum: Format[Schema.UpgradeInfo.UpgradeStateEnum] = JsonEnumFormat[Schema.UpgradeInfo.UpgradeStateEnum]
	given fmtListFunctionsResponse: Format[Schema.ListFunctionsResponse] = Json.format[Schema.ListFunctionsResponse]
	given fmtSetupFunctionUpgradeConfigRequest: Format[Schema.SetupFunctionUpgradeConfigRequest] = Json.format[Schema.SetupFunctionUpgradeConfigRequest]
	given fmtAbortFunctionUpgradeRequest: Format[Schema.AbortFunctionUpgradeRequest] = Json.format[Schema.AbortFunctionUpgradeRequest]
	given fmtRedirectFunctionUpgradeTrafficRequest: Format[Schema.RedirectFunctionUpgradeTrafficRequest] = Json.format[Schema.RedirectFunctionUpgradeTrafficRequest]
	given fmtRollbackFunctionUpgradeTrafficRequest: Format[Schema.RollbackFunctionUpgradeTrafficRequest] = Json.format[Schema.RollbackFunctionUpgradeTrafficRequest]
	given fmtCommitFunctionUpgradeRequest: Format[Schema.CommitFunctionUpgradeRequest] = Json.format[Schema.CommitFunctionUpgradeRequest]
	given fmtGenerateUploadUrlRequest: Format[Schema.GenerateUploadUrlRequest] = Json.format[Schema.GenerateUploadUrlRequest]
	given fmtGenerateUploadUrlRequestEnvironmentEnum: Format[Schema.GenerateUploadUrlRequest.EnvironmentEnum] = JsonEnumFormat[Schema.GenerateUploadUrlRequest.EnvironmentEnum]
	given fmtGenerateUploadUrlResponse: Format[Schema.GenerateUploadUrlResponse] = Json.format[Schema.GenerateUploadUrlResponse]
	given fmtGenerateDownloadUrlRequest: Format[Schema.GenerateDownloadUrlRequest] = Json.format[Schema.GenerateDownloadUrlRequest]
	given fmtGenerateDownloadUrlResponse: Format[Schema.GenerateDownloadUrlResponse] = Json.format[Schema.GenerateDownloadUrlResponse]
	given fmtListRuntimesResponse: Format[Schema.ListRuntimesResponse] = Json.format[Schema.ListRuntimesResponse]
	given fmtRuntime: Format[Schema.Runtime] = Json.format[Schema.Runtime]
	given fmtRuntimeStageEnum: Format[Schema.Runtime.StageEnum] = JsonEnumFormat[Schema.Runtime.StageEnum]
	given fmtRuntimeEnvironmentEnum: Format[Schema.Runtime.EnvironmentEnum] = JsonEnumFormat[Schema.Runtime.EnvironmentEnum]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtOperationMetadataV1: Format[Schema.OperationMetadataV1] = Json.format[Schema.OperationMetadataV1]
	given fmtOperationMetadataV1TypeEnum: Format[Schema.OperationMetadataV1.TypeEnum] = JsonEnumFormat[Schema.OperationMetadataV1.TypeEnum]
	given fmtGoogleCloudFunctionsV2OperationMetadata: Format[Schema.GoogleCloudFunctionsV2OperationMetadata] = Json.format[Schema.GoogleCloudFunctionsV2OperationMetadata]
	given fmtGoogleCloudFunctionsV2Stage: Format[Schema.GoogleCloudFunctionsV2Stage] = Json.format[Schema.GoogleCloudFunctionsV2Stage]
	given fmtGoogleCloudFunctionsV2OperationMetadataOperationTypeEnum: Format[Schema.GoogleCloudFunctionsV2OperationMetadata.OperationTypeEnum] = JsonEnumFormat[Schema.GoogleCloudFunctionsV2OperationMetadata.OperationTypeEnum]
	given fmtGoogleCloudFunctionsV2StageNameEnum: Format[Schema.GoogleCloudFunctionsV2Stage.NameEnum] = JsonEnumFormat[Schema.GoogleCloudFunctionsV2Stage.NameEnum]
	given fmtGoogleCloudFunctionsV2StageStateEnum: Format[Schema.GoogleCloudFunctionsV2Stage.StateEnum] = JsonEnumFormat[Schema.GoogleCloudFunctionsV2Stage.StateEnum]
	given fmtGoogleCloudFunctionsV2LocationMetadata: Format[Schema.GoogleCloudFunctionsV2LocationMetadata] = Json.format[Schema.GoogleCloudFunctionsV2LocationMetadata]
	given fmtGoogleCloudFunctionsV2LocationMetadataEnvironmentsEnum: Format[Schema.GoogleCloudFunctionsV2LocationMetadata.EnvironmentsEnum] = JsonEnumFormat[Schema.GoogleCloudFunctionsV2LocationMetadata.EnvironmentsEnum]
}
