package com.boresjo.play.api.google.checks

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putSchemaGoogleChecksReportV1alphaEndpoint: Conversion[Schema.GoogleChecksReportV1alphaEndpoint, Option[Schema.GoogleChecksReportV1alphaEndpoint]] = (fun: Schema.GoogleChecksReportV1alphaEndpoint) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidencePermissionDetails: Conversion[List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidencePermissionDetails], Option[List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidencePermissionDetails]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidencePermissionDetails]) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaTextInput: Conversion[Schema.GoogleChecksAisafetyV1alphaTextInput, Option[Schema.GoogleChecksAisafetyV1alphaTextInput]] = (fun: Schema.GoogleChecksAisafetyV1alphaTextInput) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaSdk: Conversion[Schema.GoogleChecksReportV1alphaSdk, Option[Schema.GoogleChecksReportV1alphaSdk]] = (fun: Schema.GoogleChecksReportV1alphaSdk) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaDataMonitoringResultMetadata: Conversion[Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata, Option[Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata]] = (fun: Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata) => Option(fun)
		given putListSchemaOperation: Conversion[List[Schema.Operation], Option[List[Schema.Operation]]] = (fun: List[Schema.Operation]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidenceSdkDetails: Conversion[List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidenceSdkDetails], Option[List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidenceSdkDetails]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidenceSdkDetails]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckSdkIssueEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckSdkIssueEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckSdkIssueEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckSdkIssueEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckEndpointEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckEndpointEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckEndpointEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckEndpointEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckPrivacyPolicyTextEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckPrivacyPolicyTextEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckPrivacyPolicyTextEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckPrivacyPolicyTextEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckPermissionEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckPermissionEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckPermissionEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckPermissionEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckSdkEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckSdkEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckSdkEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckSdkEvidence]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckDataSecurityEvidence: Conversion[Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidence, Option[Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidence]] = (fun: Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidence) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckPermissionRestrictionViolationEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckSdkRestrictionViolationEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckDataTypeEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidence], Option[List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidence]) => Option(fun)
		given putListSchemaGoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult: Conversion[List[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult], Option[List[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult]]] = (fun: List[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaPolicyFragment: Conversion[Schema.GoogleChecksReportV1alphaPolicyFragment, Option[Schema.GoogleChecksReportV1alphaPolicyFragment]] = (fun: Schema.GoogleChecksReportV1alphaPolicyFragment) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResultViolationResultEnum: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.ViolationResultEnum, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.ViolationResultEnum]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.ViolationResultEnum) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResultPolicyTypeEnum: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.PolicyTypeEnum, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.PolicyTypeEnum]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentResponsePolicyResult.PolicyTypeEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckCitationTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaCheckCitation.TypeEnum, Option[Schema.GoogleChecksReportV1alphaCheckCitation.TypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaCheckCitation.TypeEnum) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckStateMetadataBadgesEnum: Conversion[List[Schema.GoogleChecksReportV1alphaCheckStateMetadata.BadgesEnum], Option[List[Schema.GoogleChecksReportV1alphaCheckStateMetadata.BadgesEnum]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckStateMetadata.BadgesEnum]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckDataSecurityEvidenceDataInTransitInfo: Conversion[List[Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidenceDataInTransitInfo], Option[List[Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidenceDataInTransitInfo]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckDataSecurityEvidenceDataInTransitInfo]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaReport: Conversion[List[Schema.GoogleChecksReportV1alphaReport], Option[List[Schema.GoogleChecksReportV1alphaReport]]] = (fun: List[Schema.GoogleChecksReportV1alphaReport]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataMonitoringDataTypeResult: Conversion[List[Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult], Option[List[Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataMonitoringPermissionResult: Conversion[List[Schema.GoogleChecksReportV1alphaDataMonitoringPermissionResult], Option[List[Schema.GoogleChecksReportV1alphaDataMonitoringPermissionResult]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataMonitoringPermissionResult]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataMonitoringSdkResult: Conversion[List[Schema.GoogleChecksReportV1alphaDataMonitoringSdkResult], Option[List[Schema.GoogleChecksReportV1alphaDataMonitoringSdkResult]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataMonitoringSdkResult]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataMonitoringEndpointResult: Conversion[List[Schema.GoogleChecksReportV1alphaDataMonitoringEndpointResult], Option[List[Schema.GoogleChecksReportV1alphaDataMonitoringEndpointResult]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataMonitoringEndpointResult]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckCitation: Conversion[List[Schema.GoogleChecksReportV1alphaCheckCitation], Option[List[Schema.GoogleChecksReportV1alphaCheckCitation]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckCitation]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckStateMetadata: Conversion[Schema.GoogleChecksReportV1alphaCheckStateMetadata, Option[Schema.GoogleChecksReportV1alphaCheckStateMetadata]] = (fun: Schema.GoogleChecksReportV1alphaCheckStateMetadata) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckSeverityEnum: Conversion[Schema.GoogleChecksReportV1alphaCheck.SeverityEnum, Option[Schema.GoogleChecksReportV1alphaCheck.SeverityEnum]] = (fun: Schema.GoogleChecksReportV1alphaCheck.SeverityEnum) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckStateEnum: Conversion[Schema.GoogleChecksReportV1alphaCheck.StateEnum, Option[Schema.GoogleChecksReportV1alphaCheck.StateEnum]] = (fun: Schema.GoogleChecksReportV1alphaCheck.StateEnum) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaCheck.TypeEnum, Option[Schema.GoogleChecksReportV1alphaCheck.TypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaCheck.TypeEnum) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckEvidence: Conversion[Schema.GoogleChecksReportV1alphaCheckEvidence, Option[Schema.GoogleChecksReportV1alphaCheckEvidence]] = (fun: Schema.GoogleChecksReportV1alphaCheckEvidence) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaAnalyzeUploadRequestAppBinaryFileTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaAnalyzeUploadRequest.AppBinaryFileTypeEnum, Option[Schema.GoogleChecksReportV1alphaAnalyzeUploadRequest.AppBinaryFileTypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaAnalyzeUploadRequest.AppBinaryFileTypeEnum) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidenceEndpointDetails: Conversion[List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidenceEndpointDetails], Option[List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidenceEndpointDetails]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheckEndpointRestrictionViolationEvidenceEndpointDetails]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataMonitoringResultMetadataBadgesEnum: Conversion[List[Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata.BadgesEnum], Option[List[Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata.BadgesEnum]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataMonitoringResultMetadata.BadgesEnum]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaDataTypeEvidence: Conversion[Schema.GoogleChecksReportV1alphaDataTypeEvidence, Option[Schema.GoogleChecksReportV1alphaDataTypeEvidence]] = (fun: Schema.GoogleChecksReportV1alphaDataTypeEvidence) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaCheckDataTypeEvidenceDataTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence.DataTypeEnum, Option[Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence.DataTypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaCheckDataTypeEvidence.DataTypeEnum) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaDataMonitoringDataTypeResultDataTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult.DataTypeEnum, Option[Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult.DataTypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaDataMonitoringDataTypeResult.DataTypeEnum) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaPermission: Conversion[Schema.GoogleChecksReportV1alphaPermission, Option[Schema.GoogleChecksReportV1alphaPermission]] = (fun: Schema.GoogleChecksReportV1alphaPermission) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaDataMonitoring: Conversion[Schema.GoogleChecksReportV1alphaDataMonitoring, Option[Schema.GoogleChecksReportV1alphaDataMonitoring]] = (fun: Schema.GoogleChecksReportV1alphaDataMonitoring) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaCheck: Conversion[List[Schema.GoogleChecksReportV1alphaCheck], Option[List[Schema.GoogleChecksReportV1alphaCheck]]] = (fun: List[Schema.GoogleChecksReportV1alphaCheck]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaAppBundle: Conversion[Schema.GoogleChecksReportV1alphaAppBundle, Option[Schema.GoogleChecksReportV1alphaAppBundle]] = (fun: Schema.GoogleChecksReportV1alphaAppBundle) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaAppBundleReleaseTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaAppBundle.ReleaseTypeEnum, Option[Schema.GoogleChecksReportV1alphaAppBundle.ReleaseTypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaAppBundle.ReleaseTypeEnum) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataTypeEndpointEvidenceEndpointDetails: Conversion[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceEndpointDetails], Option[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceEndpointDetails]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceEndpointDetails]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataTypeEndpointEvidenceAttributedSdk: Conversion[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceAttributedSdk], Option[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceAttributedSdk]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidenceAttributedSdk]) => Option(fun)
		given putSchemaGoogleChecksReportV1alphaDataTypeEndpointEvidenceExfiltratedDataTypeEnum: Conversion[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence.ExfiltratedDataTypeEnum, Option[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence.ExfiltratedDataTypeEnum]] = (fun: Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence.ExfiltratedDataTypeEnum) => Option(fun)
		given putListSchemaGoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig: Conversion[List[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig], Option[List[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig]]] = (fun: List[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig]) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentRequestContext: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestContext, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestContext]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestContext) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentRequestClassifierVersionEnum: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequest.ClassifierVersionEnum, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequest.ClassifierVersionEnum]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentRequest.ClassifierVersionEnum) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentRequestInputContent: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestInputContent, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestInputContent]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestInputContent) => Option(fun)
		given putSchemaGoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfigPolicyTypeEnum: Conversion[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig.PolicyTypeEnum, Option[Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig.PolicyTypeEnum]] = (fun: Schema.GoogleChecksAisafetyV1alphaClassifyContentRequestPolicyConfig.PolicyTypeEnum) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataTypeEndpointEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence], Option[List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataTypeEndpointEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataTypePrivacyPolicyTextEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaDataTypePrivacyPolicyTextEvidence], Option[List[Schema.GoogleChecksReportV1alphaDataTypePrivacyPolicyTextEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataTypePrivacyPolicyTextEvidence]) => Option(fun)
		given putListSchemaGoogleChecksReportV1alphaDataTypePermissionEvidence: Conversion[List[Schema.GoogleChecksReportV1alphaDataTypePermissionEvidence], Option[List[Schema.GoogleChecksReportV1alphaDataTypePermissionEvidence]]] = (fun: List[Schema.GoogleChecksReportV1alphaDataTypePermissionEvidence]) => Option(fun)
		given putListSchemaGoogleChecksAccountV1alphaApp: Conversion[List[Schema.GoogleChecksAccountV1alphaApp], Option[List[Schema.GoogleChecksAccountV1alphaApp]]] = (fun: List[Schema.GoogleChecksAccountV1alphaApp]) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
