package com.boresjo.play.api.google.analyticsdata

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtRunReportRequest: Format[Schema.RunReportRequest] = Json.format[Schema.RunReportRequest]
	given fmtDimension: Format[Schema.Dimension] = Json.format[Schema.Dimension]
	given fmtMetric: Format[Schema.Metric] = Json.format[Schema.Metric]
	given fmtDateRange: Format[Schema.DateRange] = Json.format[Schema.DateRange]
	given fmtFilterExpression: Format[Schema.FilterExpression] = Json.format[Schema.FilterExpression]
	given fmtRunReportRequestMetricAggregationsEnum: Format[Schema.RunReportRequest.MetricAggregationsEnum] = JsonEnumFormat[Schema.RunReportRequest.MetricAggregationsEnum]
	given fmtOrderBy: Format[Schema.OrderBy] = Json.format[Schema.OrderBy]
	given fmtCohortSpec: Format[Schema.CohortSpec] = Json.format[Schema.CohortSpec]
	given fmtComparison: Format[Schema.Comparison] = Json.format[Schema.Comparison]
	given fmtDimensionExpression: Format[Schema.DimensionExpression] = Json.format[Schema.DimensionExpression]
	given fmtCaseExpression: Format[Schema.CaseExpression] = Json.format[Schema.CaseExpression]
	given fmtConcatenateExpression: Format[Schema.ConcatenateExpression] = Json.format[Schema.ConcatenateExpression]
	given fmtFilterExpressionList: Format[Schema.FilterExpressionList] = Json.format[Schema.FilterExpressionList]
	given fmtFilter: Format[Schema.Filter] = Json.format[Schema.Filter]
	given fmtStringFilter: Format[Schema.StringFilter] = Json.format[Schema.StringFilter]
	given fmtInListFilter: Format[Schema.InListFilter] = Json.format[Schema.InListFilter]
	given fmtNumericFilter: Format[Schema.NumericFilter] = Json.format[Schema.NumericFilter]
	given fmtBetweenFilter: Format[Schema.BetweenFilter] = Json.format[Schema.BetweenFilter]
	given fmtStringFilterMatchTypeEnum: Format[Schema.StringFilter.MatchTypeEnum] = JsonEnumFormat[Schema.StringFilter.MatchTypeEnum]
	given fmtNumericFilterOperationEnum: Format[Schema.NumericFilter.OperationEnum] = JsonEnumFormat[Schema.NumericFilter.OperationEnum]
	given fmtNumericValue: Format[Schema.NumericValue] = Json.format[Schema.NumericValue]
	given fmtMetricOrderBy: Format[Schema.MetricOrderBy] = Json.format[Schema.MetricOrderBy]
	given fmtDimensionOrderBy: Format[Schema.DimensionOrderBy] = Json.format[Schema.DimensionOrderBy]
	given fmtPivotOrderBy: Format[Schema.PivotOrderBy] = Json.format[Schema.PivotOrderBy]
	given fmtDimensionOrderByOrderTypeEnum: Format[Schema.DimensionOrderBy.OrderTypeEnum] = JsonEnumFormat[Schema.DimensionOrderBy.OrderTypeEnum]
	given fmtPivotSelection: Format[Schema.PivotSelection] = Json.format[Schema.PivotSelection]
	given fmtCohort: Format[Schema.Cohort] = Json.format[Schema.Cohort]
	given fmtCohortsRange: Format[Schema.CohortsRange] = Json.format[Schema.CohortsRange]
	given fmtCohortReportSettings: Format[Schema.CohortReportSettings] = Json.format[Schema.CohortReportSettings]
	given fmtCohortsRangeGranularityEnum: Format[Schema.CohortsRange.GranularityEnum] = JsonEnumFormat[Schema.CohortsRange.GranularityEnum]
	given fmtRunReportResponse: Format[Schema.RunReportResponse] = Json.format[Schema.RunReportResponse]
	given fmtDimensionHeader: Format[Schema.DimensionHeader] = Json.format[Schema.DimensionHeader]
	given fmtMetricHeader: Format[Schema.MetricHeader] = Json.format[Schema.MetricHeader]
	given fmtRow: Format[Schema.Row] = Json.format[Schema.Row]
	given fmtResponseMetaData: Format[Schema.ResponseMetaData] = Json.format[Schema.ResponseMetaData]
	given fmtPropertyQuota: Format[Schema.PropertyQuota] = Json.format[Schema.PropertyQuota]
	given fmtMetricHeaderTypeEnum: Format[Schema.MetricHeader.TypeEnum] = JsonEnumFormat[Schema.MetricHeader.TypeEnum]
	given fmtDimensionValue: Format[Schema.DimensionValue] = Json.format[Schema.DimensionValue]
	given fmtMetricValue: Format[Schema.MetricValue] = Json.format[Schema.MetricValue]
	given fmtSchemaRestrictionResponse: Format[Schema.SchemaRestrictionResponse] = Json.format[Schema.SchemaRestrictionResponse]
	given fmtSamplingMetadata: Format[Schema.SamplingMetadata] = Json.format[Schema.SamplingMetadata]
	given fmtActiveMetricRestriction: Format[Schema.ActiveMetricRestriction] = Json.format[Schema.ActiveMetricRestriction]
	given fmtActiveMetricRestrictionRestrictedMetricTypesEnum: Format[Schema.ActiveMetricRestriction.RestrictedMetricTypesEnum] = JsonEnumFormat[Schema.ActiveMetricRestriction.RestrictedMetricTypesEnum]
	given fmtQuotaStatus: Format[Schema.QuotaStatus] = Json.format[Schema.QuotaStatus]
	given fmtRunPivotReportRequest: Format[Schema.RunPivotReportRequest] = Json.format[Schema.RunPivotReportRequest]
	given fmtPivot: Format[Schema.Pivot] = Json.format[Schema.Pivot]
	given fmtPivotMetricAggregationsEnum: Format[Schema.Pivot.MetricAggregationsEnum] = JsonEnumFormat[Schema.Pivot.MetricAggregationsEnum]
	given fmtRunPivotReportResponse: Format[Schema.RunPivotReportResponse] = Json.format[Schema.RunPivotReportResponse]
	given fmtPivotHeader: Format[Schema.PivotHeader] = Json.format[Schema.PivotHeader]
	given fmtPivotDimensionHeader: Format[Schema.PivotDimensionHeader] = Json.format[Schema.PivotDimensionHeader]
	given fmtBatchRunReportsRequest: Format[Schema.BatchRunReportsRequest] = Json.format[Schema.BatchRunReportsRequest]
	given fmtBatchRunReportsResponse: Format[Schema.BatchRunReportsResponse] = Json.format[Schema.BatchRunReportsResponse]
	given fmtBatchRunPivotReportsRequest: Format[Schema.BatchRunPivotReportsRequest] = Json.format[Schema.BatchRunPivotReportsRequest]
	given fmtBatchRunPivotReportsResponse: Format[Schema.BatchRunPivotReportsResponse] = Json.format[Schema.BatchRunPivotReportsResponse]
	given fmtMetadata: Format[Schema.Metadata] = Json.format[Schema.Metadata]
	given fmtDimensionMetadata: Format[Schema.DimensionMetadata] = Json.format[Schema.DimensionMetadata]
	given fmtMetricMetadata: Format[Schema.MetricMetadata] = Json.format[Schema.MetricMetadata]
	given fmtComparisonMetadata: Format[Schema.ComparisonMetadata] = Json.format[Schema.ComparisonMetadata]
	given fmtMetricMetadataTypeEnum: Format[Schema.MetricMetadata.TypeEnum] = JsonEnumFormat[Schema.MetricMetadata.TypeEnum]
	given fmtMetricMetadataBlockedReasonsEnum: Format[Schema.MetricMetadata.BlockedReasonsEnum] = JsonEnumFormat[Schema.MetricMetadata.BlockedReasonsEnum]
	given fmtRunRealtimeReportRequest: Format[Schema.RunRealtimeReportRequest] = Json.format[Schema.RunRealtimeReportRequest]
	given fmtRunRealtimeReportRequestMetricAggregationsEnum: Format[Schema.RunRealtimeReportRequest.MetricAggregationsEnum] = JsonEnumFormat[Schema.RunRealtimeReportRequest.MetricAggregationsEnum]
	given fmtMinuteRange: Format[Schema.MinuteRange] = Json.format[Schema.MinuteRange]
	given fmtRunRealtimeReportResponse: Format[Schema.RunRealtimeReportResponse] = Json.format[Schema.RunRealtimeReportResponse]
	given fmtCheckCompatibilityRequest: Format[Schema.CheckCompatibilityRequest] = Json.format[Schema.CheckCompatibilityRequest]
	given fmtCheckCompatibilityRequestCompatibilityFilterEnum: Format[Schema.CheckCompatibilityRequest.CompatibilityFilterEnum] = JsonEnumFormat[Schema.CheckCompatibilityRequest.CompatibilityFilterEnum]
	given fmtCheckCompatibilityResponse: Format[Schema.CheckCompatibilityResponse] = Json.format[Schema.CheckCompatibilityResponse]
	given fmtDimensionCompatibility: Format[Schema.DimensionCompatibility] = Json.format[Schema.DimensionCompatibility]
	given fmtMetricCompatibility: Format[Schema.MetricCompatibility] = Json.format[Schema.MetricCompatibility]
	given fmtDimensionCompatibilityCompatibilityEnum: Format[Schema.DimensionCompatibility.CompatibilityEnum] = JsonEnumFormat[Schema.DimensionCompatibility.CompatibilityEnum]
	given fmtMetricCompatibilityCompatibilityEnum: Format[Schema.MetricCompatibility.CompatibilityEnum] = JsonEnumFormat[Schema.MetricCompatibility.CompatibilityEnum]
	given fmtAudienceExport: Format[Schema.AudienceExport] = Json.format[Schema.AudienceExport]
	given fmtV1betaAudienceDimension: Format[Schema.V1betaAudienceDimension] = Json.format[Schema.V1betaAudienceDimension]
	given fmtAudienceExportStateEnum: Format[Schema.AudienceExport.StateEnum] = JsonEnumFormat[Schema.AudienceExport.StateEnum]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtQueryAudienceExportRequest: Format[Schema.QueryAudienceExportRequest] = Json.format[Schema.QueryAudienceExportRequest]
	given fmtQueryAudienceExportResponse: Format[Schema.QueryAudienceExportResponse] = Json.format[Schema.QueryAudienceExportResponse]
	given fmtV1betaAudienceRow: Format[Schema.V1betaAudienceRow] = Json.format[Schema.V1betaAudienceRow]
	given fmtV1betaAudienceDimensionValue: Format[Schema.V1betaAudienceDimensionValue] = Json.format[Schema.V1betaAudienceDimensionValue]
	given fmtListAudienceExportsResponse: Format[Schema.ListAudienceExportsResponse] = Json.format[Schema.ListAudienceExportsResponse]
	given fmtAudienceListMetadata: Format[Schema.AudienceListMetadata] = Json.format[Schema.AudienceListMetadata]
}
