package com.boresjo.play.api.google.realtimebidding

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtBidder: Format[Schema.Bidder] = Json.format[Schema.Bidder]
	given fmtListBiddersResponse: Format[Schema.ListBiddersResponse] = Json.format[Schema.ListBiddersResponse]
	given fmtEndpoint: Format[Schema.Endpoint] = Json.format[Schema.Endpoint]
	given fmtEndpointTradingLocationEnum: Format[Schema.Endpoint.TradingLocationEnum] = JsonEnumFormat[Schema.Endpoint.TradingLocationEnum]
	given fmtEndpointBidProtocolEnum: Format[Schema.Endpoint.BidProtocolEnum] = JsonEnumFormat[Schema.Endpoint.BidProtocolEnum]
	given fmtListEndpointsResponse: Format[Schema.ListEndpointsResponse] = Json.format[Schema.ListEndpointsResponse]
	given fmtBuyer: Format[Schema.Buyer] = Json.format[Schema.Buyer]
	given fmtListBuyersResponse: Format[Schema.ListBuyersResponse] = Json.format[Schema.ListBuyersResponse]
	given fmtListCreativesResponse: Format[Schema.ListCreativesResponse] = Json.format[Schema.ListCreativesResponse]
	given fmtCreative: Format[Schema.Creative] = Json.format[Schema.Creative]
	given fmtHtmlContent: Format[Schema.HtmlContent] = Json.format[Schema.HtmlContent]
	given fmtVideoContent: Format[Schema.VideoContent] = Json.format[Schema.VideoContent]
	given fmtNativeContent: Format[Schema.NativeContent] = Json.format[Schema.NativeContent]
	given fmtCreativeCreativeFormatEnum: Format[Schema.Creative.CreativeFormatEnum] = JsonEnumFormat[Schema.Creative.CreativeFormatEnum]
	given fmtCreativeRestrictedCategoriesEnum: Format[Schema.Creative.RestrictedCategoriesEnum] = JsonEnumFormat[Schema.Creative.RestrictedCategoriesEnum]
	given fmtCreativeDeclaredAttributesEnum: Format[Schema.Creative.DeclaredAttributesEnum] = JsonEnumFormat[Schema.Creative.DeclaredAttributesEnum]
	given fmtCreativeDeclaredRestrictedCategoriesEnum: Format[Schema.Creative.DeclaredRestrictedCategoriesEnum] = JsonEnumFormat[Schema.Creative.DeclaredRestrictedCategoriesEnum]
	given fmtCreativeServingDecision: Format[Schema.CreativeServingDecision] = Json.format[Schema.CreativeServingDecision]
	given fmtVideoMetadata: Format[Schema.VideoMetadata] = Json.format[Schema.VideoMetadata]
	given fmtVideoMetadataVastVersionEnum: Format[Schema.VideoMetadata.VastVersionEnum] = JsonEnumFormat[Schema.VideoMetadata.VastVersionEnum]
	given fmtMediaFile: Format[Schema.MediaFile] = Json.format[Schema.MediaFile]
	given fmtMediaFileMimeTypeEnum: Format[Schema.MediaFile.MimeTypeEnum] = JsonEnumFormat[Schema.MediaFile.MimeTypeEnum]
	given fmtImage: Format[Schema.Image] = Json.format[Schema.Image]
	given fmtAdvertiserAndBrand: Format[Schema.AdvertiserAndBrand] = Json.format[Schema.AdvertiserAndBrand]
	given fmtCreativeServingDecisionDetectedAttributesEnum: Format[Schema.CreativeServingDecision.DetectedAttributesEnum] = JsonEnumFormat[Schema.CreativeServingDecision.DetectedAttributesEnum]
	given fmtAdTechnologyProviders: Format[Schema.AdTechnologyProviders] = Json.format[Schema.AdTechnologyProviders]
	given fmtPolicyCompliance: Format[Schema.PolicyCompliance] = Json.format[Schema.PolicyCompliance]
	given fmtCreativeServingDecisionDetectedCategoriesTaxonomyEnum: Format[Schema.CreativeServingDecision.DetectedCategoriesTaxonomyEnum] = JsonEnumFormat[Schema.CreativeServingDecision.DetectedCategoriesTaxonomyEnum]
	given fmtPolicyComplianceStatusEnum: Format[Schema.PolicyCompliance.StatusEnum] = JsonEnumFormat[Schema.PolicyCompliance.StatusEnum]
	given fmtPolicyTopicEntry: Format[Schema.PolicyTopicEntry] = Json.format[Schema.PolicyTopicEntry]
	given fmtPolicyTopicEvidence: Format[Schema.PolicyTopicEvidence] = Json.format[Schema.PolicyTopicEvidence]
	given fmtDestinationNotWorkingEvidence: Format[Schema.DestinationNotWorkingEvidence] = Json.format[Schema.DestinationNotWorkingEvidence]
	given fmtDestinationNotCrawlableEvidence: Format[Schema.DestinationNotCrawlableEvidence] = Json.format[Schema.DestinationNotCrawlableEvidence]
	given fmtHttpCallEvidence: Format[Schema.HttpCallEvidence] = Json.format[Schema.HttpCallEvidence]
	given fmtDomainCallEvidence: Format[Schema.DomainCallEvidence] = Json.format[Schema.DomainCallEvidence]
	given fmtHttpCookieEvidence: Format[Schema.HttpCookieEvidence] = Json.format[Schema.HttpCookieEvidence]
	given fmtDestinationUrlEvidence: Format[Schema.DestinationUrlEvidence] = Json.format[Schema.DestinationUrlEvidence]
	given fmtDownloadSizeEvidence: Format[Schema.DownloadSizeEvidence] = Json.format[Schema.DownloadSizeEvidence]
	given fmtDestinationNotWorkingEvidenceDnsErrorEnum: Format[Schema.DestinationNotWorkingEvidence.DnsErrorEnum] = JsonEnumFormat[Schema.DestinationNotWorkingEvidence.DnsErrorEnum]
	given fmtDestinationNotWorkingEvidenceInvalidPageEnum: Format[Schema.DestinationNotWorkingEvidence.InvalidPageEnum] = JsonEnumFormat[Schema.DestinationNotWorkingEvidence.InvalidPageEnum]
	given fmtDestinationNotWorkingEvidenceRedirectionErrorEnum: Format[Schema.DestinationNotWorkingEvidence.RedirectionErrorEnum] = JsonEnumFormat[Schema.DestinationNotWorkingEvidence.RedirectionErrorEnum]
	given fmtDestinationNotWorkingEvidenceUrlRejectedEnum: Format[Schema.DestinationNotWorkingEvidence.UrlRejectedEnum] = JsonEnumFormat[Schema.DestinationNotWorkingEvidence.UrlRejectedEnum]
	given fmtDestinationNotWorkingEvidencePlatformEnum: Format[Schema.DestinationNotWorkingEvidence.PlatformEnum] = JsonEnumFormat[Schema.DestinationNotWorkingEvidence.PlatformEnum]
	given fmtDestinationNotCrawlableEvidenceReasonEnum: Format[Schema.DestinationNotCrawlableEvidence.ReasonEnum] = JsonEnumFormat[Schema.DestinationNotCrawlableEvidence.ReasonEnum]
	given fmtDomainCalls: Format[Schema.DomainCalls] = Json.format[Schema.DomainCalls]
	given fmtUrlDownloadSize: Format[Schema.UrlDownloadSize] = Json.format[Schema.UrlDownloadSize]
	given fmtWatchCreativesRequest: Format[Schema.WatchCreativesRequest] = Json.format[Schema.WatchCreativesRequest]
	given fmtWatchCreativesResponse: Format[Schema.WatchCreativesResponse] = Json.format[Schema.WatchCreativesResponse]
	given fmtListPretargetingConfigsResponse: Format[Schema.ListPretargetingConfigsResponse] = Json.format[Schema.ListPretargetingConfigsResponse]
	given fmtPretargetingConfig: Format[Schema.PretargetingConfig] = Json.format[Schema.PretargetingConfig]
	given fmtPretargetingConfigStateEnum: Format[Schema.PretargetingConfig.StateEnum] = JsonEnumFormat[Schema.PretargetingConfig.StateEnum]
	given fmtPretargetingConfigIncludedFormatsEnum: Format[Schema.PretargetingConfig.IncludedFormatsEnum] = JsonEnumFormat[Schema.PretargetingConfig.IncludedFormatsEnum]
	given fmtNumericTargetingDimension: Format[Schema.NumericTargetingDimension] = Json.format[Schema.NumericTargetingDimension]
	given fmtPretargetingConfigInterstitialTargetingEnum: Format[Schema.PretargetingConfig.InterstitialTargetingEnum] = JsonEnumFormat[Schema.PretargetingConfig.InterstitialTargetingEnum]
	given fmtPretargetingConfigAllowedUserTargetingModesEnum: Format[Schema.PretargetingConfig.AllowedUserTargetingModesEnum] = JsonEnumFormat[Schema.PretargetingConfig.AllowedUserTargetingModesEnum]
	given fmtPretargetingConfigIncludedUserIdTypesEnum: Format[Schema.PretargetingConfig.IncludedUserIdTypesEnum] = JsonEnumFormat[Schema.PretargetingConfig.IncludedUserIdTypesEnum]
	given fmtPretargetingConfigIncludedPlatformsEnum: Format[Schema.PretargetingConfig.IncludedPlatformsEnum] = JsonEnumFormat[Schema.PretargetingConfig.IncludedPlatformsEnum]
	given fmtCreativeDimensions: Format[Schema.CreativeDimensions] = Json.format[Schema.CreativeDimensions]
	given fmtPretargetingConfigIncludedEnvironmentsEnum: Format[Schema.PretargetingConfig.IncludedEnvironmentsEnum] = JsonEnumFormat[Schema.PretargetingConfig.IncludedEnvironmentsEnum]
	given fmtStringTargetingDimension: Format[Schema.StringTargetingDimension] = Json.format[Schema.StringTargetingDimension]
	given fmtAppTargeting: Format[Schema.AppTargeting] = Json.format[Schema.AppTargeting]
	given fmtStringTargetingDimensionTargetingModeEnum: Format[Schema.StringTargetingDimension.TargetingModeEnum] = JsonEnumFormat[Schema.StringTargetingDimension.TargetingModeEnum]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtActivatePretargetingConfigRequest: Format[Schema.ActivatePretargetingConfigRequest] = Json.format[Schema.ActivatePretargetingConfigRequest]
	given fmtSuspendPretargetingConfigRequest: Format[Schema.SuspendPretargetingConfigRequest] = Json.format[Schema.SuspendPretargetingConfigRequest]
	given fmtAddTargetedSitesRequest: Format[Schema.AddTargetedSitesRequest] = Json.format[Schema.AddTargetedSitesRequest]
	given fmtAddTargetedSitesRequestTargetingModeEnum: Format[Schema.AddTargetedSitesRequest.TargetingModeEnum] = JsonEnumFormat[Schema.AddTargetedSitesRequest.TargetingModeEnum]
	given fmtRemoveTargetedSitesRequest: Format[Schema.RemoveTargetedSitesRequest] = Json.format[Schema.RemoveTargetedSitesRequest]
	given fmtAddTargetedAppsRequest: Format[Schema.AddTargetedAppsRequest] = Json.format[Schema.AddTargetedAppsRequest]
	given fmtAddTargetedAppsRequestTargetingModeEnum: Format[Schema.AddTargetedAppsRequest.TargetingModeEnum] = JsonEnumFormat[Schema.AddTargetedAppsRequest.TargetingModeEnum]
	given fmtRemoveTargetedAppsRequest: Format[Schema.RemoveTargetedAppsRequest] = Json.format[Schema.RemoveTargetedAppsRequest]
	given fmtAddTargetedPublishersRequest: Format[Schema.AddTargetedPublishersRequest] = Json.format[Schema.AddTargetedPublishersRequest]
	given fmtAddTargetedPublishersRequestTargetingModeEnum: Format[Schema.AddTargetedPublishersRequest.TargetingModeEnum] = JsonEnumFormat[Schema.AddTargetedPublishersRequest.TargetingModeEnum]
	given fmtRemoveTargetedPublishersRequest: Format[Schema.RemoveTargetedPublishersRequest] = Json.format[Schema.RemoveTargetedPublishersRequest]
	given fmtListPublisherConnectionsResponse: Format[Schema.ListPublisherConnectionsResponse] = Json.format[Schema.ListPublisherConnectionsResponse]
	given fmtPublisherConnection: Format[Schema.PublisherConnection] = Json.format[Schema.PublisherConnection]
	given fmtPublisherConnectionPublisherPlatformEnum: Format[Schema.PublisherConnection.PublisherPlatformEnum] = JsonEnumFormat[Schema.PublisherConnection.PublisherPlatformEnum]
	given fmtPublisherConnectionBiddingStateEnum: Format[Schema.PublisherConnection.BiddingStateEnum] = JsonEnumFormat[Schema.PublisherConnection.BiddingStateEnum]
	given fmtBatchApprovePublisherConnectionsRequest: Format[Schema.BatchApprovePublisherConnectionsRequest] = Json.format[Schema.BatchApprovePublisherConnectionsRequest]
	given fmtBatchApprovePublisherConnectionsResponse: Format[Schema.BatchApprovePublisherConnectionsResponse] = Json.format[Schema.BatchApprovePublisherConnectionsResponse]
	given fmtBatchRejectPublisherConnectionsRequest: Format[Schema.BatchRejectPublisherConnectionsRequest] = Json.format[Schema.BatchRejectPublisherConnectionsRequest]
	given fmtBatchRejectPublisherConnectionsResponse: Format[Schema.BatchRejectPublisherConnectionsResponse] = Json.format[Schema.BatchRejectPublisherConnectionsResponse]
	given fmtUserList: Format[Schema.UserList] = Json.format[Schema.UserList]
	given fmtUserListStatusEnum: Format[Schema.UserList.StatusEnum] = JsonEnumFormat[Schema.UserList.StatusEnum]
	given fmtUrlRestriction: Format[Schema.UrlRestriction] = Json.format[Schema.UrlRestriction]
	given fmtUrlRestrictionRestrictionTypeEnum: Format[Schema.UrlRestriction.RestrictionTypeEnum] = JsonEnumFormat[Schema.UrlRestriction.RestrictionTypeEnum]
	given fmtDate: Format[Schema.Date] = Json.format[Schema.Date]
	given fmtListUserListsResponse: Format[Schema.ListUserListsResponse] = Json.format[Schema.ListUserListsResponse]
	given fmtOpenUserListRequest: Format[Schema.OpenUserListRequest] = Json.format[Schema.OpenUserListRequest]
	given fmtCloseUserListRequest: Format[Schema.CloseUserListRequest] = Json.format[Schema.CloseUserListRequest]
	given fmtGetRemarketingTagResponse: Format[Schema.GetRemarketingTagResponse] = Json.format[Schema.GetRemarketingTagResponse]
}
