package com.boresjo.play.api.google.cloudasset

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putSchemaExportAssetsRequestContentTypeEnum: Conversion[Schema.ExportAssetsRequest.ContentTypeEnum, Option[Schema.ExportAssetsRequest.ContentTypeEnum]] = (fun: Schema.ExportAssetsRequest.ContentTypeEnum) => Option(fun)
		given putSchemaOutputConfig: Conversion[Schema.OutputConfig, Option[Schema.OutputConfig]] = (fun: Schema.OutputConfig) => Option(fun)
		given putSchemaGcsDestination: Conversion[Schema.GcsDestination, Option[Schema.GcsDestination]] = (fun: Schema.GcsDestination) => Option(fun)
		given putSchemaBigQueryDestination: Conversion[Schema.BigQueryDestination, Option[Schema.BigQueryDestination]] = (fun: Schema.BigQueryDestination) => Option(fun)
		given putSchemaPartitionSpec: Conversion[Schema.PartitionSpec, Option[Schema.PartitionSpec]] = (fun: Schema.PartitionSpec) => Option(fun)
		given putSchemaPartitionSpecPartitionKeyEnum: Conversion[Schema.PartitionSpec.PartitionKeyEnum, Option[Schema.PartitionSpec.PartitionKeyEnum]] = (fun: Schema.PartitionSpec.PartitionKeyEnum) => Option(fun)
		given putListSchemaAsset: Conversion[List[Schema.Asset], Option[List[Schema.Asset]]] = (fun: List[Schema.Asset]) => Option(fun)
		given putSchemaResource: Conversion[Schema.Resource, Option[Schema.Resource]] = (fun: Schema.Resource) => Option(fun)
		given putSchemaPolicy: Conversion[Schema.Policy, Option[Schema.Policy]] = (fun: Schema.Policy) => Option(fun)
		given putListSchemaGoogleCloudOrgpolicyV1Policy: Conversion[List[Schema.GoogleCloudOrgpolicyV1Policy], Option[List[Schema.GoogleCloudOrgpolicyV1Policy]]] = (fun: List[Schema.GoogleCloudOrgpolicyV1Policy]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1AccessPolicy: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1AccessPolicy, Option[Schema.GoogleIdentityAccesscontextmanagerV1AccessPolicy]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1AccessPolicy) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1AccessLevel: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1AccessLevel, Option[Schema.GoogleIdentityAccesscontextmanagerV1AccessLevel]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1AccessLevel) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1ServicePerimeter: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter, Option[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter) => Option(fun)
		given putSchemaInventory: Conversion[Schema.Inventory, Option[Schema.Inventory]] = (fun: Schema.Inventory) => Option(fun)
		given putSchemaRelatedAssets: Conversion[Schema.RelatedAssets, Option[Schema.RelatedAssets]] = (fun: Schema.RelatedAssets) => Option(fun)
		given putSchemaRelatedAsset: Conversion[Schema.RelatedAsset, Option[Schema.RelatedAsset]] = (fun: Schema.RelatedAsset) => Option(fun)
		given putListSchemaBinding: Conversion[List[Schema.Binding], Option[List[Schema.Binding]]] = (fun: List[Schema.Binding]) => Option(fun)
		given putListSchemaAuditConfig: Conversion[List[Schema.AuditConfig], Option[List[Schema.AuditConfig]]] = (fun: List[Schema.AuditConfig]) => Option(fun)
		given putSchemaExpr: Conversion[Schema.Expr, Option[Schema.Expr]] = (fun: Schema.Expr) => Option(fun)
		given putListSchemaAuditLogConfig: Conversion[List[Schema.AuditLogConfig], Option[List[Schema.AuditLogConfig]]] = (fun: List[Schema.AuditLogConfig]) => Option(fun)
		given putSchemaAuditLogConfigLogTypeEnum: Conversion[Schema.AuditLogConfig.LogTypeEnum, Option[Schema.AuditLogConfig.LogTypeEnum]] = (fun: Schema.AuditLogConfig.LogTypeEnum) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV1ListPolicy: Conversion[Schema.GoogleCloudOrgpolicyV1ListPolicy, Option[Schema.GoogleCloudOrgpolicyV1ListPolicy]] = (fun: Schema.GoogleCloudOrgpolicyV1ListPolicy) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV1BooleanPolicy: Conversion[Schema.GoogleCloudOrgpolicyV1BooleanPolicy, Option[Schema.GoogleCloudOrgpolicyV1BooleanPolicy]] = (fun: Schema.GoogleCloudOrgpolicyV1BooleanPolicy) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV1RestoreDefault: Conversion[Schema.GoogleCloudOrgpolicyV1RestoreDefault, Option[Schema.GoogleCloudOrgpolicyV1RestoreDefault]] = (fun: Schema.GoogleCloudOrgpolicyV1RestoreDefault) => Option(fun)
		given putSchemaGoogleCloudOrgpolicyV1ListPolicyAllValuesEnum: Conversion[Schema.GoogleCloudOrgpolicyV1ListPolicy.AllValuesEnum, Option[Schema.GoogleCloudOrgpolicyV1ListPolicy.AllValuesEnum]] = (fun: Schema.GoogleCloudOrgpolicyV1ListPolicy.AllValuesEnum) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1BasicLevel: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel, Option[Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1CustomLevel: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1CustomLevel, Option[Schema.GoogleIdentityAccesscontextmanagerV1CustomLevel]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1CustomLevel) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1Condition: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1Condition], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1Condition]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1Condition]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1BasicLevelCombiningFunctionEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel.CombiningFunctionEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel.CombiningFunctionEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1BasicLevel.CombiningFunctionEnum) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1DevicePolicy: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy, Option[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1VpcNetworkSource: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1VpcNetworkSource], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1VpcNetworkSource]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1VpcNetworkSource]) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1DevicePolicyAllowedEncryptionStatusesEnum: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedEncryptionStatusesEnum], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedEncryptionStatusesEnum]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedEncryptionStatusesEnum]) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1OsConstraint: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint]) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1DevicePolicyAllowedDeviceManagementLevelsEnum: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedDeviceManagementLevelsEnum], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedDeviceManagementLevelsEnum]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1DevicePolicy.AllowedDeviceManagementLevelsEnum]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1OsConstraintOsTypeEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint.OsTypeEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint.OsTypeEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1OsConstraint.OsTypeEnum) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1VpcSubNetwork: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1VpcSubNetwork, Option[Schema.GoogleIdentityAccesscontextmanagerV1VpcSubNetwork]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1VpcSubNetwork) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1ServicePerimeterPerimeterTypeEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter.PerimeterTypeEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter.PerimeterTypeEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeter.PerimeterTypeEnum) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1ServicePerimeterConfig: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeterConfig, Option[Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeterConfig]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1ServicePerimeterConfig) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1VpcAccessibleServices: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1VpcAccessibleServices, Option[Schema.GoogleIdentityAccesscontextmanagerV1VpcAccessibleServices]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1VpcAccessibleServices) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1IngressPolicy: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1IngressPolicy], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1IngressPolicy]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1IngressPolicy]) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1EgressPolicy: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1EgressPolicy], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1EgressPolicy]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1EgressPolicy]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1IngressFrom: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom, Option[Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1IngressTo: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1IngressTo, Option[Schema.GoogleIdentityAccesscontextmanagerV1IngressTo]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1IngressTo) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1IngressSource: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1IngressSource], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1IngressSource]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1IngressSource]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1IngressFromIdentityTypeEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom.IdentityTypeEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom.IdentityTypeEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1IngressFrom.IdentityTypeEnum) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1ApiOperation: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1ApiOperation], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1ApiOperation]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1ApiOperation]) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1MethodSelector: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1MethodSelector], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1MethodSelector]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1MethodSelector]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1EgressFrom: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom, Option[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1EgressTo: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1EgressTo, Option[Schema.GoogleIdentityAccesscontextmanagerV1EgressTo]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1EgressTo) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1EgressFromIdentityTypeEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.IdentityTypeEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.IdentityTypeEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.IdentityTypeEnum) => Option(fun)
		given putListSchemaGoogleIdentityAccesscontextmanagerV1EgressSource: Conversion[List[Schema.GoogleIdentityAccesscontextmanagerV1EgressSource], Option[List[Schema.GoogleIdentityAccesscontextmanagerV1EgressSource]]] = (fun: List[Schema.GoogleIdentityAccesscontextmanagerV1EgressSource]) => Option(fun)
		given putSchemaGoogleIdentityAccesscontextmanagerV1EgressFromSourceRestrictionEnum: Conversion[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.SourceRestrictionEnum, Option[Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.SourceRestrictionEnum]] = (fun: Schema.GoogleIdentityAccesscontextmanagerV1EgressFrom.SourceRestrictionEnum) => Option(fun)
		given putSchemaOsInfo: Conversion[Schema.OsInfo, Option[Schema.OsInfo]] = (fun: Schema.OsInfo) => Option(fun)
		given putMapStringSchemaItem: Conversion[Map[String, Schema.Item], Option[Map[String, Schema.Item]]] = (fun: Map[String, Schema.Item]) => Option(fun)
		given putSchemaItemOriginTypeEnum: Conversion[Schema.Item.OriginTypeEnum, Option[Schema.Item.OriginTypeEnum]] = (fun: Schema.Item.OriginTypeEnum) => Option(fun)
		given putSchemaItemTypeEnum: Conversion[Schema.Item.TypeEnum, Option[Schema.Item.TypeEnum]] = (fun: Schema.Item.TypeEnum) => Option(fun)
		given putSchemaSoftwarePackage: Conversion[Schema.SoftwarePackage, Option[Schema.SoftwarePackage]] = (fun: Schema.SoftwarePackage) => Option(fun)
		given putSchemaVersionedPackage: Conversion[Schema.VersionedPackage, Option[Schema.VersionedPackage]] = (fun: Schema.VersionedPackage) => Option(fun)
		given putSchemaZypperPatch: Conversion[Schema.ZypperPatch, Option[Schema.ZypperPatch]] = (fun: Schema.ZypperPatch) => Option(fun)
		given putSchemaWindowsUpdatePackage: Conversion[Schema.WindowsUpdatePackage, Option[Schema.WindowsUpdatePackage]] = (fun: Schema.WindowsUpdatePackage) => Option(fun)
		given putSchemaWindowsQuickFixEngineeringPackage: Conversion[Schema.WindowsQuickFixEngineeringPackage, Option[Schema.WindowsQuickFixEngineeringPackage]] = (fun: Schema.WindowsQuickFixEngineeringPackage) => Option(fun)
		given putSchemaWindowsApplication: Conversion[Schema.WindowsApplication, Option[Schema.WindowsApplication]] = (fun: Schema.WindowsApplication) => Option(fun)
		given putListSchemaWindowsUpdateCategory: Conversion[List[Schema.WindowsUpdateCategory], Option[List[Schema.WindowsUpdateCategory]]] = (fun: List[Schema.WindowsUpdateCategory]) => Option(fun)
		given putSchemaDate: Conversion[Schema.Date, Option[Schema.Date]] = (fun: Schema.Date) => Option(fun)
		given putSchemaRelationshipAttributes: Conversion[Schema.RelationshipAttributes, Option[Schema.RelationshipAttributes]] = (fun: Schema.RelationshipAttributes) => Option(fun)
		given putListSchemaRelatedAsset: Conversion[List[Schema.RelatedAsset], Option[List[Schema.RelatedAsset]]] = (fun: List[Schema.RelatedAsset]) => Option(fun)
		given putListSchemaTemporalAsset: Conversion[List[Schema.TemporalAsset], Option[List[Schema.TemporalAsset]]] = (fun: List[Schema.TemporalAsset]) => Option(fun)
		given putSchemaTimeWindow: Conversion[Schema.TimeWindow, Option[Schema.TimeWindow]] = (fun: Schema.TimeWindow) => Option(fun)
		given putSchemaAsset: Conversion[Schema.Asset, Option[Schema.Asset]] = (fun: Schema.Asset) => Option(fun)
		given putSchemaTemporalAssetPriorAssetStateEnum: Conversion[Schema.TemporalAsset.PriorAssetStateEnum, Option[Schema.TemporalAsset.PriorAssetStateEnum]] = (fun: Schema.TemporalAsset.PriorAssetStateEnum) => Option(fun)
		given putSchemaFeed: Conversion[Schema.Feed, Option[Schema.Feed]] = (fun: Schema.Feed) => Option(fun)
		given putSchemaFeedContentTypeEnum: Conversion[Schema.Feed.ContentTypeEnum, Option[Schema.Feed.ContentTypeEnum]] = (fun: Schema.Feed.ContentTypeEnum) => Option(fun)
		given putSchemaFeedOutputConfig: Conversion[Schema.FeedOutputConfig, Option[Schema.FeedOutputConfig]] = (fun: Schema.FeedOutputConfig) => Option(fun)
		given putSchemaPubsubDestination: Conversion[Schema.PubsubDestination, Option[Schema.PubsubDestination]] = (fun: Schema.PubsubDestination) => Option(fun)
		given putListSchemaFeed: Conversion[List[Schema.Feed], Option[List[Schema.Feed]]] = (fun: List[Schema.Feed]) => Option(fun)
		given putListSchemaResourceSearchResult: Conversion[List[Schema.ResourceSearchResult], Option[List[Schema.ResourceSearchResult]]] = (fun: List[Schema.ResourceSearchResult]) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putListSchemaVersionedResource: Conversion[List[Schema.VersionedResource], Option[List[Schema.VersionedResource]]] = (fun: List[Schema.VersionedResource]) => Option(fun)
		given putListSchemaAttachedResource: Conversion[List[Schema.AttachedResource], Option[List[Schema.AttachedResource]]] = (fun: List[Schema.AttachedResource]) => Option(fun)
		given putMapStringSchemaRelatedResources: Conversion[Map[String, Schema.RelatedResources], Option[Map[String, Schema.RelatedResources]]] = (fun: Map[String, Schema.RelatedResources]) => Option(fun)
		given putListSchemaTag: Conversion[List[Schema.Tag], Option[List[Schema.Tag]]] = (fun: List[Schema.Tag]) => Option(fun)
		given putListSchemaEffectiveTagDetails: Conversion[List[Schema.EffectiveTagDetails], Option[List[Schema.EffectiveTagDetails]]] = (fun: List[Schema.EffectiveTagDetails]) => Option(fun)
		given putListSchemaAssetEnrichment: Conversion[List[Schema.AssetEnrichment], Option[List[Schema.AssetEnrichment]]] = (fun: List[Schema.AssetEnrichment]) => Option(fun)
		given putListSchemaRelatedResource: Conversion[List[Schema.RelatedResource], Option[List[Schema.RelatedResource]]] = (fun: List[Schema.RelatedResource]) => Option(fun)
		given putSchemaResourceOwners: Conversion[Schema.ResourceOwners, Option[Schema.ResourceOwners]] = (fun: Schema.ResourceOwners) => Option(fun)
		given putListSchemaIamPolicySearchResult: Conversion[List[Schema.IamPolicySearchResult], Option[List[Schema.IamPolicySearchResult]]] = (fun: List[Schema.IamPolicySearchResult]) => Option(fun)
		given putSchemaExplanation: Conversion[Schema.Explanation, Option[Schema.Explanation]] = (fun: Schema.Explanation) => Option(fun)
		given putMapStringSchemaPermissions: Conversion[Map[String, Schema.Permissions], Option[Map[String, Schema.Permissions]]] = (fun: Map[String, Schema.Permissions]) => Option(fun)
		given putSchemaIamPolicyAnalysis: Conversion[Schema.IamPolicyAnalysis, Option[Schema.IamPolicyAnalysis]] = (fun: Schema.IamPolicyAnalysis) => Option(fun)
		given putListSchemaIamPolicyAnalysis: Conversion[List[Schema.IamPolicyAnalysis], Option[List[Schema.IamPolicyAnalysis]]] = (fun: List[Schema.IamPolicyAnalysis]) => Option(fun)
		given putSchemaIamPolicyAnalysisQuery: Conversion[Schema.IamPolicyAnalysisQuery, Option[Schema.IamPolicyAnalysisQuery]] = (fun: Schema.IamPolicyAnalysisQuery) => Option(fun)
		given putListSchemaIamPolicyAnalysisResult: Conversion[List[Schema.IamPolicyAnalysisResult], Option[List[Schema.IamPolicyAnalysisResult]]] = (fun: List[Schema.IamPolicyAnalysisResult]) => Option(fun)
		given putListSchemaIamPolicyAnalysisState: Conversion[List[Schema.IamPolicyAnalysisState], Option[List[Schema.IamPolicyAnalysisState]]] = (fun: List[Schema.IamPolicyAnalysisState]) => Option(fun)
		given putSchemaResourceSelector: Conversion[Schema.ResourceSelector, Option[Schema.ResourceSelector]] = (fun: Schema.ResourceSelector) => Option(fun)
		given putSchemaIdentitySelector: Conversion[Schema.IdentitySelector, Option[Schema.IdentitySelector]] = (fun: Schema.IdentitySelector) => Option(fun)
		given putSchemaAccessSelector: Conversion[Schema.AccessSelector, Option[Schema.AccessSelector]] = (fun: Schema.AccessSelector) => Option(fun)
		given putSchemaOptions: Conversion[Schema.Options, Option[Schema.Options]] = (fun: Schema.Options) => Option(fun)
		given putSchemaConditionContext: Conversion[Schema.ConditionContext, Option[Schema.ConditionContext]] = (fun: Schema.ConditionContext) => Option(fun)
		given putSchemaBinding: Conversion[Schema.Binding, Option[Schema.Binding]] = (fun: Schema.Binding) => Option(fun)
		given putListSchemaGoogleCloudAssetV1AccessControlList: Conversion[List[Schema.GoogleCloudAssetV1AccessControlList], Option[List[Schema.GoogleCloudAssetV1AccessControlList]]] = (fun: List[Schema.GoogleCloudAssetV1AccessControlList]) => Option(fun)
		given putSchemaGoogleCloudAssetV1IdentityList: Conversion[Schema.GoogleCloudAssetV1IdentityList, Option[Schema.GoogleCloudAssetV1IdentityList]] = (fun: Schema.GoogleCloudAssetV1IdentityList) => Option(fun)
		given putListSchemaGoogleCloudAssetV1Resource: Conversion[List[Schema.GoogleCloudAssetV1Resource], Option[List[Schema.GoogleCloudAssetV1Resource]]] = (fun: List[Schema.GoogleCloudAssetV1Resource]) => Option(fun)
		given putListSchemaGoogleCloudAssetV1Access: Conversion[List[Schema.GoogleCloudAssetV1Access], Option[List[Schema.GoogleCloudAssetV1Access]]] = (fun: List[Schema.GoogleCloudAssetV1Access]) => Option(fun)
		given putListSchemaGoogleCloudAssetV1Edge: Conversion[List[Schema.GoogleCloudAssetV1Edge], Option[List[Schema.GoogleCloudAssetV1Edge]]] = (fun: List[Schema.GoogleCloudAssetV1Edge]) => Option(fun)
		given putSchemaConditionEvaluation: Conversion[Schema.ConditionEvaluation, Option[Schema.ConditionEvaluation]] = (fun: Schema.ConditionEvaluation) => Option(fun)
		given putSchemaIamPolicyAnalysisState: Conversion[Schema.IamPolicyAnalysisState, Option[Schema.IamPolicyAnalysisState]] = (fun: Schema.IamPolicyAnalysisState) => Option(fun)
		given putSchemaIamPolicyAnalysisStateCodeEnum: Conversion[Schema.IamPolicyAnalysisState.CodeEnum, Option[Schema.IamPolicyAnalysisState.CodeEnum]] = (fun: Schema.IamPolicyAnalysisState.CodeEnum) => Option(fun)
		given putSchemaConditionEvaluationEvaluationValueEnum: Conversion[Schema.ConditionEvaluation.EvaluationValueEnum, Option[Schema.ConditionEvaluation.EvaluationValueEnum]] = (fun: Schema.ConditionEvaluation.EvaluationValueEnum) => Option(fun)
		given putListSchemaGoogleCloudAssetV1Identity: Conversion[List[Schema.GoogleCloudAssetV1Identity], Option[List[Schema.GoogleCloudAssetV1Identity]]] = (fun: List[Schema.GoogleCloudAssetV1Identity]) => Option(fun)
		given putSchemaIamPolicyAnalysisOutputConfig: Conversion[Schema.IamPolicyAnalysisOutputConfig, Option[Schema.IamPolicyAnalysisOutputConfig]] = (fun: Schema.IamPolicyAnalysisOutputConfig) => Option(fun)
		given putSchemaGoogleCloudAssetV1GcsDestination: Conversion[Schema.GoogleCloudAssetV1GcsDestination, Option[Schema.GoogleCloudAssetV1GcsDestination]] = (fun: Schema.GoogleCloudAssetV1GcsDestination) => Option(fun)
		given putSchemaGoogleCloudAssetV1BigQueryDestination: Conversion[Schema.GoogleCloudAssetV1BigQueryDestination, Option[Schema.GoogleCloudAssetV1BigQueryDestination]] = (fun: Schema.GoogleCloudAssetV1BigQueryDestination) => Option(fun)
		given putSchemaGoogleCloudAssetV1BigQueryDestinationPartitionKeyEnum: Conversion[Schema.GoogleCloudAssetV1BigQueryDestination.PartitionKeyEnum, Option[Schema.GoogleCloudAssetV1BigQueryDestination.PartitionKeyEnum]] = (fun: Schema.GoogleCloudAssetV1BigQueryDestination.PartitionKeyEnum) => Option(fun)
		given putListSchemaMoveAnalysis: Conversion[List[Schema.MoveAnalysis], Option[List[Schema.MoveAnalysis]]] = (fun: List[Schema.MoveAnalysis]) => Option(fun)
		given putSchemaMoveAnalysisResult: Conversion[Schema.MoveAnalysisResult, Option[Schema.MoveAnalysisResult]] = (fun: Schema.MoveAnalysisResult) => Option(fun)
		given putListSchemaMoveImpact: Conversion[List[Schema.MoveImpact], Option[List[Schema.MoveImpact]]] = (fun: List[Schema.MoveImpact]) => Option(fun)
		given putSchemaQueryAssetsOutputConfig: Conversion[Schema.QueryAssetsOutputConfig, Option[Schema.QueryAssetsOutputConfig]] = (fun: Schema.QueryAssetsOutputConfig) => Option(fun)
		given putSchemaGoogleCloudAssetV1QueryAssetsOutputConfigBigQueryDestination: Conversion[Schema.GoogleCloudAssetV1QueryAssetsOutputConfigBigQueryDestination, Option[Schema.GoogleCloudAssetV1QueryAssetsOutputConfigBigQueryDestination]] = (fun: Schema.GoogleCloudAssetV1QueryAssetsOutputConfigBigQueryDestination) => Option(fun)
		given putSchemaQueryResult: Conversion[Schema.QueryResult, Option[Schema.QueryResult]] = (fun: Schema.QueryResult) => Option(fun)
		given putSchemaTableSchema: Conversion[Schema.TableSchema, Option[Schema.TableSchema]] = (fun: Schema.TableSchema) => Option(fun)
		given putListSchemaTableFieldSchema: Conversion[List[Schema.TableFieldSchema], Option[List[Schema.TableFieldSchema]]] = (fun: List[Schema.TableFieldSchema]) => Option(fun)
		given putSchemaQueryContent: Conversion[Schema.QueryContent, Option[Schema.QueryContent]] = (fun: Schema.QueryContent) => Option(fun)
		given putListSchemaSavedQuery: Conversion[List[Schema.SavedQuery], Option[List[Schema.SavedQuery]]] = (fun: List[Schema.SavedQuery]) => Option(fun)
		given putListSchemaEffectiveIamPolicy: Conversion[List[Schema.EffectiveIamPolicy], Option[List[Schema.EffectiveIamPolicy]]] = (fun: List[Schema.EffectiveIamPolicy]) => Option(fun)
		given putListSchemaPolicyInfo: Conversion[List[Schema.PolicyInfo], Option[List[Schema.PolicyInfo]]] = (fun: List[Schema.PolicyInfo]) => Option(fun)
		given putListSchemaOrgPolicyResult: Conversion[List[Schema.OrgPolicyResult], Option[List[Schema.OrgPolicyResult]]] = (fun: List[Schema.OrgPolicyResult]) => Option(fun)
		given putSchemaAnalyzerOrgPolicyConstraint: Conversion[Schema.AnalyzerOrgPolicyConstraint, Option[Schema.AnalyzerOrgPolicyConstraint]] = (fun: Schema.AnalyzerOrgPolicyConstraint) => Option(fun)
		given putSchemaAnalyzerOrgPolicy: Conversion[Schema.AnalyzerOrgPolicy, Option[Schema.AnalyzerOrgPolicy]] = (fun: Schema.AnalyzerOrgPolicy) => Option(fun)
		given putListSchemaAnalyzerOrgPolicy: Conversion[List[Schema.AnalyzerOrgPolicy], Option[List[Schema.AnalyzerOrgPolicy]]] = (fun: List[Schema.AnalyzerOrgPolicy]) => Option(fun)
		given putListSchemaGoogleCloudAssetV1Rule: Conversion[List[Schema.GoogleCloudAssetV1Rule], Option[List[Schema.GoogleCloudAssetV1Rule]]] = (fun: List[Schema.GoogleCloudAssetV1Rule]) => Option(fun)
		given putSchemaGoogleCloudAssetV1StringValues: Conversion[Schema.GoogleCloudAssetV1StringValues, Option[Schema.GoogleCloudAssetV1StringValues]] = (fun: Schema.GoogleCloudAssetV1StringValues) => Option(fun)
		given putSchemaGoogleCloudAssetV1Constraint: Conversion[Schema.GoogleCloudAssetV1Constraint, Option[Schema.GoogleCloudAssetV1Constraint]] = (fun: Schema.GoogleCloudAssetV1Constraint) => Option(fun)
		given putSchemaGoogleCloudAssetV1CustomConstraint: Conversion[Schema.GoogleCloudAssetV1CustomConstraint, Option[Schema.GoogleCloudAssetV1CustomConstraint]] = (fun: Schema.GoogleCloudAssetV1CustomConstraint) => Option(fun)
		given putSchemaGoogleCloudAssetV1ConstraintConstraintDefaultEnum: Conversion[Schema.GoogleCloudAssetV1Constraint.ConstraintDefaultEnum, Option[Schema.GoogleCloudAssetV1Constraint.ConstraintDefaultEnum]] = (fun: Schema.GoogleCloudAssetV1Constraint.ConstraintDefaultEnum) => Option(fun)
		given putSchemaGoogleCloudAssetV1ListConstraint: Conversion[Schema.GoogleCloudAssetV1ListConstraint, Option[Schema.GoogleCloudAssetV1ListConstraint]] = (fun: Schema.GoogleCloudAssetV1ListConstraint) => Option(fun)
		given putSchemaGoogleCloudAssetV1BooleanConstraint: Conversion[Schema.GoogleCloudAssetV1BooleanConstraint, Option[Schema.GoogleCloudAssetV1BooleanConstraint]] = (fun: Schema.GoogleCloudAssetV1BooleanConstraint) => Option(fun)
		given putListSchemaGoogleCloudAssetV1CustomConstraintMethodTypesEnum: Conversion[List[Schema.GoogleCloudAssetV1CustomConstraint.MethodTypesEnum], Option[List[Schema.GoogleCloudAssetV1CustomConstraint.MethodTypesEnum]]] = (fun: List[Schema.GoogleCloudAssetV1CustomConstraint.MethodTypesEnum]) => Option(fun)
		given putSchemaGoogleCloudAssetV1CustomConstraintActionTypeEnum: Conversion[Schema.GoogleCloudAssetV1CustomConstraint.ActionTypeEnum, Option[Schema.GoogleCloudAssetV1CustomConstraint.ActionTypeEnum]] = (fun: Schema.GoogleCloudAssetV1CustomConstraint.ActionTypeEnum) => Option(fun)
		given putListSchemaGoogleCloudAssetV1GovernedContainer: Conversion[List[Schema.GoogleCloudAssetV1GovernedContainer], Option[List[Schema.GoogleCloudAssetV1GovernedContainer]]] = (fun: List[Schema.GoogleCloudAssetV1GovernedContainer]) => Option(fun)
		given putListSchemaGoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedAsset: Conversion[List[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedAsset], Option[List[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedAsset]]] = (fun: List[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedAsset]) => Option(fun)
		given putSchemaGoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedResource: Conversion[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedResource, Option[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedResource]] = (fun: Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedResource) => Option(fun)
		given putSchemaGoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedIamPolicy: Conversion[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedIamPolicy, Option[Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedIamPolicy]] = (fun: Schema.GoogleCloudAssetV1AnalyzeOrgPolicyGovernedAssetsResponseGovernedIamPolicy) => Option(fun)
		given putSchemaGoogleCloudAssetV1p7beta1Resource: Conversion[Schema.GoogleCloudAssetV1p7beta1Resource, Option[Schema.GoogleCloudAssetV1p7beta1Resource]] = (fun: Schema.GoogleCloudAssetV1p7beta1Resource) => Option(fun)
		given putSchemaGoogleCloudAssetV1p7beta1RelatedAssets: Conversion[Schema.GoogleCloudAssetV1p7beta1RelatedAssets, Option[Schema.GoogleCloudAssetV1p7beta1RelatedAssets]] = (fun: Schema.GoogleCloudAssetV1p7beta1RelatedAssets) => Option(fun)
		given putSchemaGoogleCloudAssetV1p7beta1RelationshipAttributes: Conversion[Schema.GoogleCloudAssetV1p7beta1RelationshipAttributes, Option[Schema.GoogleCloudAssetV1p7beta1RelationshipAttributes]] = (fun: Schema.GoogleCloudAssetV1p7beta1RelationshipAttributes) => Option(fun)
		given putListSchemaGoogleCloudAssetV1p7beta1RelatedAsset: Conversion[List[Schema.GoogleCloudAssetV1p7beta1RelatedAsset], Option[List[Schema.GoogleCloudAssetV1p7beta1RelatedAsset]]] = (fun: List[Schema.GoogleCloudAssetV1p7beta1RelatedAsset]) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
