package com.boresjo.play.api.google.analyticshub

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListDataExchangesResponse: Format[Schema.ListDataExchangesResponse] = Json.format[Schema.ListDataExchangesResponse]
	given fmtDataExchange: Format[Schema.DataExchange] = Json.format[Schema.DataExchange]
	given fmtSharingEnvironmentConfig: Format[Schema.SharingEnvironmentConfig] = Json.format[Schema.SharingEnvironmentConfig]
	given fmtDataExchangeDiscoveryTypeEnum: Format[Schema.DataExchange.DiscoveryTypeEnum] = JsonEnumFormat[Schema.DataExchange.DiscoveryTypeEnum]
	given fmtDefaultExchangeConfig: Format[Schema.DefaultExchangeConfig] = Json.format[Schema.DefaultExchangeConfig]
	given fmtDcrExchangeConfig: Format[Schema.DcrExchangeConfig] = Json.format[Schema.DcrExchangeConfig]
	given fmtListOrgDataExchangesResponse: Format[Schema.ListOrgDataExchangesResponse] = Json.format[Schema.ListOrgDataExchangesResponse]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtListListingsResponse: Format[Schema.ListListingsResponse] = Json.format[Schema.ListListingsResponse]
	given fmtListing: Format[Schema.Listing] = Json.format[Schema.Listing]
	given fmtBigQueryDatasetSource: Format[Schema.BigQueryDatasetSource] = Json.format[Schema.BigQueryDatasetSource]
	given fmtPubSubTopicSource: Format[Schema.PubSubTopicSource] = Json.format[Schema.PubSubTopicSource]
	given fmtListingStateEnum: Format[Schema.Listing.StateEnum] = JsonEnumFormat[Schema.Listing.StateEnum]
	given fmtDataProvider: Format[Schema.DataProvider] = Json.format[Schema.DataProvider]
	given fmtListingCategoriesEnum: Format[Schema.Listing.CategoriesEnum] = JsonEnumFormat[Schema.Listing.CategoriesEnum]
	given fmtPublisher: Format[Schema.Publisher] = Json.format[Schema.Publisher]
	given fmtRestrictedExportConfig: Format[Schema.RestrictedExportConfig] = Json.format[Schema.RestrictedExportConfig]
	given fmtListingDiscoveryTypeEnum: Format[Schema.Listing.DiscoveryTypeEnum] = JsonEnumFormat[Schema.Listing.DiscoveryTypeEnum]
	given fmtListingResourceTypeEnum: Format[Schema.Listing.ResourceTypeEnum] = JsonEnumFormat[Schema.Listing.ResourceTypeEnum]
	given fmtSelectedResource: Format[Schema.SelectedResource] = Json.format[Schema.SelectedResource]
	given fmtRestrictedExportPolicy: Format[Schema.RestrictedExportPolicy] = Json.format[Schema.RestrictedExportPolicy]
	given fmtSubscribeListingRequest: Format[Schema.SubscribeListingRequest] = Json.format[Schema.SubscribeListingRequest]
	given fmtDestinationDataset: Format[Schema.DestinationDataset] = Json.format[Schema.DestinationDataset]
	given fmtDestinationPubSubSubscription: Format[Schema.DestinationPubSubSubscription] = Json.format[Schema.DestinationPubSubSubscription]
	given fmtDestinationDatasetReference: Format[Schema.DestinationDatasetReference] = Json.format[Schema.DestinationDatasetReference]
	given fmtGooglePubsubV1Subscription: Format[Schema.GooglePubsubV1Subscription] = Json.format[Schema.GooglePubsubV1Subscription]
	given fmtPushConfig: Format[Schema.PushConfig] = Json.format[Schema.PushConfig]
	given fmtBigQueryConfig: Format[Schema.BigQueryConfig] = Json.format[Schema.BigQueryConfig]
	given fmtCloudStorageConfig: Format[Schema.CloudStorageConfig] = Json.format[Schema.CloudStorageConfig]
	given fmtExpirationPolicy: Format[Schema.ExpirationPolicy] = Json.format[Schema.ExpirationPolicy]
	given fmtDeadLetterPolicy: Format[Schema.DeadLetterPolicy] = Json.format[Schema.DeadLetterPolicy]
	given fmtRetryPolicy: Format[Schema.RetryPolicy] = Json.format[Schema.RetryPolicy]
	given fmtGooglePubsubV1SubscriptionStateEnum: Format[Schema.GooglePubsubV1Subscription.StateEnum] = JsonEnumFormat[Schema.GooglePubsubV1Subscription.StateEnum]
	given fmtAnalyticsHubSubscriptionInfo: Format[Schema.AnalyticsHubSubscriptionInfo] = Json.format[Schema.AnalyticsHubSubscriptionInfo]
	given fmtOidcToken: Format[Schema.OidcToken] = Json.format[Schema.OidcToken]
	given fmtPubsubWrapper: Format[Schema.PubsubWrapper] = Json.format[Schema.PubsubWrapper]
	given fmtNoWrapper: Format[Schema.NoWrapper] = Json.format[Schema.NoWrapper]
	given fmtBigQueryConfigStateEnum: Format[Schema.BigQueryConfig.StateEnum] = JsonEnumFormat[Schema.BigQueryConfig.StateEnum]
	given fmtTextConfig: Format[Schema.TextConfig] = Json.format[Schema.TextConfig]
	given fmtAvroConfig: Format[Schema.AvroConfig] = Json.format[Schema.AvroConfig]
	given fmtCloudStorageConfigStateEnum: Format[Schema.CloudStorageConfig.StateEnum] = JsonEnumFormat[Schema.CloudStorageConfig.StateEnum]
	given fmtSubscribeListingResponse: Format[Schema.SubscribeListingResponse] = Json.format[Schema.SubscribeListingResponse]
	given fmtSubscription: Format[Schema.Subscription] = Json.format[Schema.Subscription]
	given fmtSubscriptionStateEnum: Format[Schema.Subscription.StateEnum] = JsonEnumFormat[Schema.Subscription.StateEnum]
	given fmtLinkedResource: Format[Schema.LinkedResource] = Json.format[Schema.LinkedResource]
	given fmtSubscriptionResourceTypeEnum: Format[Schema.Subscription.ResourceTypeEnum] = JsonEnumFormat[Schema.Subscription.ResourceTypeEnum]
	given fmtSubscribeDataExchangeRequest: Format[Schema.SubscribeDataExchangeRequest] = Json.format[Schema.SubscribeDataExchangeRequest]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtRefreshSubscriptionRequest: Format[Schema.RefreshSubscriptionRequest] = Json.format[Schema.RefreshSubscriptionRequest]
	given fmtListSubscriptionsResponse: Format[Schema.ListSubscriptionsResponse] = Json.format[Schema.ListSubscriptionsResponse]
	given fmtListSharedResourceSubscriptionsResponse: Format[Schema.ListSharedResourceSubscriptionsResponse] = Json.format[Schema.ListSharedResourceSubscriptionsResponse]
	given fmtRevokeSubscriptionRequest: Format[Schema.RevokeSubscriptionRequest] = Json.format[Schema.RevokeSubscriptionRequest]
	given fmtRevokeSubscriptionResponse: Format[Schema.RevokeSubscriptionResponse] = Json.format[Schema.RevokeSubscriptionResponse]
	given fmtGetIamPolicyRequest: Format[Schema.GetIamPolicyRequest] = Json.format[Schema.GetIamPolicyRequest]
	given fmtGetPolicyOptions: Format[Schema.GetPolicyOptions] = Json.format[Schema.GetPolicyOptions]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtSubscribeDataExchangeResponse: Format[Schema.SubscribeDataExchangeResponse] = Json.format[Schema.SubscribeDataExchangeResponse]
	given fmtRefreshSubscriptionResponse: Format[Schema.RefreshSubscriptionResponse] = Json.format[Schema.RefreshSubscriptionResponse]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
