package com.boresjo.play.api.google.authorizedbuyersmarketplace

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtAuctionPackage: Format[Schema.AuctionPackage] = Json.format[Schema.AuctionPackage]
	given fmtMediaPlanner: Format[Schema.MediaPlanner] = Json.format[Schema.MediaPlanner]
	given fmtListAuctionPackagesResponse: Format[Schema.ListAuctionPackagesResponse] = Json.format[Schema.ListAuctionPackagesResponse]
	given fmtSubscribeAuctionPackageRequest: Format[Schema.SubscribeAuctionPackageRequest] = Json.format[Schema.SubscribeAuctionPackageRequest]
	given fmtUnsubscribeAuctionPackageRequest: Format[Schema.UnsubscribeAuctionPackageRequest] = Json.format[Schema.UnsubscribeAuctionPackageRequest]
	given fmtSubscribeClientsRequest: Format[Schema.SubscribeClientsRequest] = Json.format[Schema.SubscribeClientsRequest]
	given fmtUnsubscribeClientsRequest: Format[Schema.UnsubscribeClientsRequest] = Json.format[Schema.UnsubscribeClientsRequest]
	given fmtClientUser: Format[Schema.ClientUser] = Json.format[Schema.ClientUser]
	given fmtClientUserStateEnum: Format[Schema.ClientUser.StateEnum] = JsonEnumFormat[Schema.ClientUser.StateEnum]
	given fmtListClientUsersResponse: Format[Schema.ListClientUsersResponse] = Json.format[Schema.ListClientUsersResponse]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtActivateClientUserRequest: Format[Schema.ActivateClientUserRequest] = Json.format[Schema.ActivateClientUserRequest]
	given fmtDeactivateClientUserRequest: Format[Schema.DeactivateClientUserRequest] = Json.format[Schema.DeactivateClientUserRequest]
	given fmtClient: Format[Schema.Client] = Json.format[Schema.Client]
	given fmtClientRoleEnum: Format[Schema.Client.RoleEnum] = JsonEnumFormat[Schema.Client.RoleEnum]
	given fmtClientStateEnum: Format[Schema.Client.StateEnum] = JsonEnumFormat[Schema.Client.StateEnum]
	given fmtListClientsResponse: Format[Schema.ListClientsResponse] = Json.format[Schema.ListClientsResponse]
	given fmtActivateClientRequest: Format[Schema.ActivateClientRequest] = Json.format[Schema.ActivateClientRequest]
	given fmtDeactivateClientRequest: Format[Schema.DeactivateClientRequest] = Json.format[Schema.DeactivateClientRequest]
	given fmtDeal: Format[Schema.Deal] = Json.format[Schema.Deal]
	given fmtProgrammaticGuaranteedTerms: Format[Schema.ProgrammaticGuaranteedTerms] = Json.format[Schema.ProgrammaticGuaranteedTerms]
	given fmtPreferredDealTerms: Format[Schema.PreferredDealTerms] = Json.format[Schema.PreferredDealTerms]
	given fmtPrivateAuctionTerms: Format[Schema.PrivateAuctionTerms] = Json.format[Schema.PrivateAuctionTerms]
	given fmtDealDealTypeEnum: Format[Schema.Deal.DealTypeEnum] = JsonEnumFormat[Schema.Deal.DealTypeEnum]
	given fmtMoney: Format[Schema.Money] = Json.format[Schema.Money]
	given fmtTimeZone: Format[Schema.TimeZone] = Json.format[Schema.TimeZone]
	given fmtMarketplaceTargeting: Format[Schema.MarketplaceTargeting] = Json.format[Schema.MarketplaceTargeting]
	given fmtCreativeRequirements: Format[Schema.CreativeRequirements] = Json.format[Schema.CreativeRequirements]
	given fmtDeliveryControl: Format[Schema.DeliveryControl] = Json.format[Schema.DeliveryControl]
	given fmtPrice: Format[Schema.Price] = Json.format[Schema.Price]
	given fmtProgrammaticGuaranteedTermsReservationTypeEnum: Format[Schema.ProgrammaticGuaranteedTerms.ReservationTypeEnum] = JsonEnumFormat[Schema.ProgrammaticGuaranteedTerms.ReservationTypeEnum]
	given fmtPriceTypeEnum: Format[Schema.Price.TypeEnum] = JsonEnumFormat[Schema.Price.TypeEnum]
	given fmtCriteriaTargeting: Format[Schema.CriteriaTargeting] = Json.format[Schema.CriteriaTargeting]
	given fmtInventorySizeTargeting: Format[Schema.InventorySizeTargeting] = Json.format[Schema.InventorySizeTargeting]
	given fmtTechnologyTargeting: Format[Schema.TechnologyTargeting] = Json.format[Schema.TechnologyTargeting]
	given fmtPlacementTargeting: Format[Schema.PlacementTargeting] = Json.format[Schema.PlacementTargeting]
	given fmtVideoTargeting: Format[Schema.VideoTargeting] = Json.format[Schema.VideoTargeting]
	given fmtDayPartTargeting: Format[Schema.DayPartTargeting] = Json.format[Schema.DayPartTargeting]
	given fmtInventoryTypeTargeting: Format[Schema.InventoryTypeTargeting] = Json.format[Schema.InventoryTypeTargeting]
	given fmtAdSize: Format[Schema.AdSize] = Json.format[Schema.AdSize]
	given fmtAdSizeTypeEnum: Format[Schema.AdSize.TypeEnum] = JsonEnumFormat[Schema.AdSize.TypeEnum]
	given fmtOperatingSystemTargeting: Format[Schema.OperatingSystemTargeting] = Json.format[Schema.OperatingSystemTargeting]
	given fmtUriTargeting: Format[Schema.UriTargeting] = Json.format[Schema.UriTargeting]
	given fmtMobileApplicationTargeting: Format[Schema.MobileApplicationTargeting] = Json.format[Schema.MobileApplicationTargeting]
	given fmtFirstPartyMobileApplicationTargeting: Format[Schema.FirstPartyMobileApplicationTargeting] = Json.format[Schema.FirstPartyMobileApplicationTargeting]
	given fmtVideoTargetingTargetedPositionTypesEnum: Format[Schema.VideoTargeting.TargetedPositionTypesEnum] = JsonEnumFormat[Schema.VideoTargeting.TargetedPositionTypesEnum]
	given fmtVideoTargetingExcludedPositionTypesEnum: Format[Schema.VideoTargeting.ExcludedPositionTypesEnum] = JsonEnumFormat[Schema.VideoTargeting.ExcludedPositionTypesEnum]
	given fmtDayPartTargetingTimeZoneTypeEnum: Format[Schema.DayPartTargeting.TimeZoneTypeEnum] = JsonEnumFormat[Schema.DayPartTargeting.TimeZoneTypeEnum]
	given fmtDayPart: Format[Schema.DayPart] = Json.format[Schema.DayPart]
	given fmtDayPartDayOfWeekEnum: Format[Schema.DayPart.DayOfWeekEnum] = JsonEnumFormat[Schema.DayPart.DayOfWeekEnum]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtInventoryTypeTargetingInventoryTypesEnum: Format[Schema.InventoryTypeTargeting.InventoryTypesEnum] = JsonEnumFormat[Schema.InventoryTypeTargeting.InventoryTypesEnum]
	given fmtCreativeRequirementsCreativePreApprovalPolicyEnum: Format[Schema.CreativeRequirements.CreativePreApprovalPolicyEnum] = JsonEnumFormat[Schema.CreativeRequirements.CreativePreApprovalPolicyEnum]
	given fmtCreativeRequirementsCreativeSafeFrameCompatibilityEnum: Format[Schema.CreativeRequirements.CreativeSafeFrameCompatibilityEnum] = JsonEnumFormat[Schema.CreativeRequirements.CreativeSafeFrameCompatibilityEnum]
	given fmtCreativeRequirementsProgrammaticCreativeSourceEnum: Format[Schema.CreativeRequirements.ProgrammaticCreativeSourceEnum] = JsonEnumFormat[Schema.CreativeRequirements.ProgrammaticCreativeSourceEnum]
	given fmtCreativeRequirementsCreativeFormatEnum: Format[Schema.CreativeRequirements.CreativeFormatEnum] = JsonEnumFormat[Schema.CreativeRequirements.CreativeFormatEnum]
	given fmtCreativeRequirementsSkippableAdTypeEnum: Format[Schema.CreativeRequirements.SkippableAdTypeEnum] = JsonEnumFormat[Schema.CreativeRequirements.SkippableAdTypeEnum]
	given fmtDeliveryControlDeliveryRateTypeEnum: Format[Schema.DeliveryControl.DeliveryRateTypeEnum] = JsonEnumFormat[Schema.DeliveryControl.DeliveryRateTypeEnum]
	given fmtFrequencyCap: Format[Schema.FrequencyCap] = Json.format[Schema.FrequencyCap]
	given fmtDeliveryControlRoadblockingTypeEnum: Format[Schema.DeliveryControl.RoadblockingTypeEnum] = JsonEnumFormat[Schema.DeliveryControl.RoadblockingTypeEnum]
	given fmtDeliveryControlCompanionDeliveryTypeEnum: Format[Schema.DeliveryControl.CompanionDeliveryTypeEnum] = JsonEnumFormat[Schema.DeliveryControl.CompanionDeliveryTypeEnum]
	given fmtDeliveryControlCreativeRotationTypeEnum: Format[Schema.DeliveryControl.CreativeRotationTypeEnum] = JsonEnumFormat[Schema.DeliveryControl.CreativeRotationTypeEnum]
	given fmtFrequencyCapTimeUnitTypeEnum: Format[Schema.FrequencyCap.TimeUnitTypeEnum] = JsonEnumFormat[Schema.FrequencyCap.TimeUnitTypeEnum]
	given fmtBatchUpdateDealsRequest: Format[Schema.BatchUpdateDealsRequest] = Json.format[Schema.BatchUpdateDealsRequest]
	given fmtUpdateDealRequest: Format[Schema.UpdateDealRequest] = Json.format[Schema.UpdateDealRequest]
	given fmtBatchUpdateDealsResponse: Format[Schema.BatchUpdateDealsResponse] = Json.format[Schema.BatchUpdateDealsResponse]
	given fmtListDealsResponse: Format[Schema.ListDealsResponse] = Json.format[Schema.ListDealsResponse]
	given fmtFinalizedDeal: Format[Schema.FinalizedDeal] = Json.format[Schema.FinalizedDeal]
	given fmtFinalizedDealDealServingStatusEnum: Format[Schema.FinalizedDeal.DealServingStatusEnum] = JsonEnumFormat[Schema.FinalizedDeal.DealServingStatusEnum]
	given fmtDealPausingInfo: Format[Schema.DealPausingInfo] = Json.format[Schema.DealPausingInfo]
	given fmtRtbMetrics: Format[Schema.RtbMetrics] = Json.format[Schema.RtbMetrics]
	given fmtDealPausingInfoPauseRoleEnum: Format[Schema.DealPausingInfo.PauseRoleEnum] = JsonEnumFormat[Schema.DealPausingInfo.PauseRoleEnum]
	given fmtListFinalizedDealsResponse: Format[Schema.ListFinalizedDealsResponse] = Json.format[Schema.ListFinalizedDealsResponse]
	given fmtPauseFinalizedDealRequest: Format[Schema.PauseFinalizedDealRequest] = Json.format[Schema.PauseFinalizedDealRequest]
	given fmtResumeFinalizedDealRequest: Format[Schema.ResumeFinalizedDealRequest] = Json.format[Schema.ResumeFinalizedDealRequest]
	given fmtAddCreativeRequest: Format[Schema.AddCreativeRequest] = Json.format[Schema.AddCreativeRequest]
	given fmtSetReadyToServeRequest: Format[Schema.SetReadyToServeRequest] = Json.format[Schema.SetReadyToServeRequest]
	given fmtProposal: Format[Schema.Proposal] = Json.format[Schema.Proposal]
	given fmtProposalDealTypeEnum: Format[Schema.Proposal.DealTypeEnum] = JsonEnumFormat[Schema.Proposal.DealTypeEnum]
	given fmtProposalStateEnum: Format[Schema.Proposal.StateEnum] = JsonEnumFormat[Schema.Proposal.StateEnum]
	given fmtProposalOriginatorRoleEnum: Format[Schema.Proposal.OriginatorRoleEnum] = JsonEnumFormat[Schema.Proposal.OriginatorRoleEnum]
	given fmtPrivateData: Format[Schema.PrivateData] = Json.format[Schema.PrivateData]
	given fmtContact: Format[Schema.Contact] = Json.format[Schema.Contact]
	given fmtProposalLastUpdaterOrCommentorRoleEnum: Format[Schema.Proposal.LastUpdaterOrCommentorRoleEnum] = JsonEnumFormat[Schema.Proposal.LastUpdaterOrCommentorRoleEnum]
	given fmtNote: Format[Schema.Note] = Json.format[Schema.Note]
	given fmtNoteCreatorRoleEnum: Format[Schema.Note.CreatorRoleEnum] = JsonEnumFormat[Schema.Note.CreatorRoleEnum]
	given fmtListProposalsResponse: Format[Schema.ListProposalsResponse] = Json.format[Schema.ListProposalsResponse]
	given fmtCancelNegotiationRequest: Format[Schema.CancelNegotiationRequest] = Json.format[Schema.CancelNegotiationRequest]
	given fmtAcceptProposalRequest: Format[Schema.AcceptProposalRequest] = Json.format[Schema.AcceptProposalRequest]
	given fmtAddNoteRequest: Format[Schema.AddNoteRequest] = Json.format[Schema.AddNoteRequest]
	given fmtSendRfpRequest: Format[Schema.SendRfpRequest] = Json.format[Schema.SendRfpRequest]
	given fmtPublisherProfile: Format[Schema.PublisherProfile] = Json.format[Schema.PublisherProfile]
	given fmtPublisherProfileMobileApplication: Format[Schema.PublisherProfileMobileApplication] = Json.format[Schema.PublisherProfileMobileApplication]
	given fmtPublisherProfileMobileApplicationAppStoreEnum: Format[Schema.PublisherProfileMobileApplication.AppStoreEnum] = JsonEnumFormat[Schema.PublisherProfileMobileApplication.AppStoreEnum]
	given fmtListPublisherProfilesResponse: Format[Schema.ListPublisherProfilesResponse] = Json.format[Schema.ListPublisherProfilesResponse]
}
