package com.boresjo.play.api.google.jobs

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtCompany: Format[Schema.Company] = Json.format[Schema.Company]
	given fmtCompanySizeEnum: Format[Schema.Company.SizeEnum] = JsonEnumFormat[Schema.Company.SizeEnum]
	given fmtCompanyDerivedInfo: Format[Schema.CompanyDerivedInfo] = Json.format[Schema.CompanyDerivedInfo]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtLocationLocationTypeEnum: Format[Schema.Location.LocationTypeEnum] = JsonEnumFormat[Schema.Location.LocationTypeEnum]
	given fmtPostalAddress: Format[Schema.PostalAddress] = Json.format[Schema.PostalAddress]
	given fmtLatLng: Format[Schema.LatLng] = Json.format[Schema.LatLng]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtListCompaniesResponse: Format[Schema.ListCompaniesResponse] = Json.format[Schema.ListCompaniesResponse]
	given fmtResponseMetadata: Format[Schema.ResponseMetadata] = Json.format[Schema.ResponseMetadata]
	given fmtCompleteQueryResponse: Format[Schema.CompleteQueryResponse] = Json.format[Schema.CompleteQueryResponse]
	given fmtCompletionResult: Format[Schema.CompletionResult] = Json.format[Schema.CompletionResult]
	given fmtCompletionResultTypeEnum: Format[Schema.CompletionResult.TypeEnum] = JsonEnumFormat[Schema.CompletionResult.TypeEnum]
	given fmtClientEvent: Format[Schema.ClientEvent] = Json.format[Schema.ClientEvent]
	given fmtJobEvent: Format[Schema.JobEvent] = Json.format[Schema.JobEvent]
	given fmtJobEventTypeEnum: Format[Schema.JobEvent.TypeEnum] = JsonEnumFormat[Schema.JobEvent.TypeEnum]
	given fmtJob: Format[Schema.Job] = Json.format[Schema.Job]
	given fmtApplicationInfo: Format[Schema.ApplicationInfo] = Json.format[Schema.ApplicationInfo]
	given fmtJobJobBenefitsEnum: Format[Schema.Job.JobBenefitsEnum] = JsonEnumFormat[Schema.Job.JobBenefitsEnum]
	given fmtCompensationInfo: Format[Schema.CompensationInfo] = Json.format[Schema.CompensationInfo]
	given fmtCustomAttribute: Format[Schema.CustomAttribute] = Json.format[Schema.CustomAttribute]
	given fmtJobDegreeTypesEnum: Format[Schema.Job.DegreeTypesEnum] = JsonEnumFormat[Schema.Job.DegreeTypesEnum]
	given fmtJobEmploymentTypesEnum: Format[Schema.Job.EmploymentTypesEnum] = JsonEnumFormat[Schema.Job.EmploymentTypesEnum]
	given fmtJobJobLevelEnum: Format[Schema.Job.JobLevelEnum] = JsonEnumFormat[Schema.Job.JobLevelEnum]
	given fmtJobPostingRegionEnum: Format[Schema.Job.PostingRegionEnum] = JsonEnumFormat[Schema.Job.PostingRegionEnum]
	given fmtJobVisibilityEnum: Format[Schema.Job.VisibilityEnum] = JsonEnumFormat[Schema.Job.VisibilityEnum]
	given fmtJobDerivedInfo: Format[Schema.JobDerivedInfo] = Json.format[Schema.JobDerivedInfo]
	given fmtProcessingOptions: Format[Schema.ProcessingOptions] = Json.format[Schema.ProcessingOptions]
	given fmtCompensationEntry: Format[Schema.CompensationEntry] = Json.format[Schema.CompensationEntry]
	given fmtCompensationRange: Format[Schema.CompensationRange] = Json.format[Schema.CompensationRange]
	given fmtCompensationEntryTypeEnum: Format[Schema.CompensationEntry.TypeEnum] = JsonEnumFormat[Schema.CompensationEntry.TypeEnum]
	given fmtCompensationEntryUnitEnum: Format[Schema.CompensationEntry.UnitEnum] = JsonEnumFormat[Schema.CompensationEntry.UnitEnum]
	given fmtMoney: Format[Schema.Money] = Json.format[Schema.Money]
	given fmtJobDerivedInfoJobCategoriesEnum: Format[Schema.JobDerivedInfo.JobCategoriesEnum] = JsonEnumFormat[Schema.JobDerivedInfo.JobCategoriesEnum]
	given fmtProcessingOptionsHtmlSanitizationEnum: Format[Schema.ProcessingOptions.HtmlSanitizationEnum] = JsonEnumFormat[Schema.ProcessingOptions.HtmlSanitizationEnum]
	given fmtBatchCreateJobsRequest: Format[Schema.BatchCreateJobsRequest] = Json.format[Schema.BatchCreateJobsRequest]
	given fmtBatchUpdateJobsRequest: Format[Schema.BatchUpdateJobsRequest] = Json.format[Schema.BatchUpdateJobsRequest]
	given fmtBatchDeleteJobsRequest: Format[Schema.BatchDeleteJobsRequest] = Json.format[Schema.BatchDeleteJobsRequest]
	given fmtListJobsResponse: Format[Schema.ListJobsResponse] = Json.format[Schema.ListJobsResponse]
	given fmtSearchJobsRequest: Format[Schema.SearchJobsRequest] = Json.format[Schema.SearchJobsRequest]
	given fmtSearchJobsRequestSearchModeEnum: Format[Schema.SearchJobsRequest.SearchModeEnum] = JsonEnumFormat[Schema.SearchJobsRequest.SearchModeEnum]
	given fmtRequestMetadata: Format[Schema.RequestMetadata] = Json.format[Schema.RequestMetadata]
	given fmtJobQuery: Format[Schema.JobQuery] = Json.format[Schema.JobQuery]
	given fmtHistogramQuery: Format[Schema.HistogramQuery] = Json.format[Schema.HistogramQuery]
	given fmtSearchJobsRequestJobViewEnum: Format[Schema.SearchJobsRequest.JobViewEnum] = JsonEnumFormat[Schema.SearchJobsRequest.JobViewEnum]
	given fmtSearchJobsRequestDiversificationLevelEnum: Format[Schema.SearchJobsRequest.DiversificationLevelEnum] = JsonEnumFormat[Schema.SearchJobsRequest.DiversificationLevelEnum]
	given fmtCustomRankingInfo: Format[Schema.CustomRankingInfo] = Json.format[Schema.CustomRankingInfo]
	given fmtSearchJobsRequestKeywordMatchModeEnum: Format[Schema.SearchJobsRequest.KeywordMatchModeEnum] = JsonEnumFormat[Schema.SearchJobsRequest.KeywordMatchModeEnum]
	given fmtDeviceInfo: Format[Schema.DeviceInfo] = Json.format[Schema.DeviceInfo]
	given fmtDeviceInfoDeviceTypeEnum: Format[Schema.DeviceInfo.DeviceTypeEnum] = JsonEnumFormat[Schema.DeviceInfo.DeviceTypeEnum]
	given fmtLocationFilter: Format[Schema.LocationFilter] = Json.format[Schema.LocationFilter]
	given fmtJobQueryJobCategoriesEnum: Format[Schema.JobQuery.JobCategoriesEnum] = JsonEnumFormat[Schema.JobQuery.JobCategoriesEnum]
	given fmtCommuteFilter: Format[Schema.CommuteFilter] = Json.format[Schema.CommuteFilter]
	given fmtCompensationFilter: Format[Schema.CompensationFilter] = Json.format[Schema.CompensationFilter]
	given fmtJobQueryEmploymentTypesEnum: Format[Schema.JobQuery.EmploymentTypesEnum] = JsonEnumFormat[Schema.JobQuery.EmploymentTypesEnum]
	given fmtTimestampRange: Format[Schema.TimestampRange] = Json.format[Schema.TimestampRange]
	given fmtLocationFilterTelecommutePreferenceEnum: Format[Schema.LocationFilter.TelecommutePreferenceEnum] = JsonEnumFormat[Schema.LocationFilter.TelecommutePreferenceEnum]
	given fmtCommuteFilterCommuteMethodEnum: Format[Schema.CommuteFilter.CommuteMethodEnum] = JsonEnumFormat[Schema.CommuteFilter.CommuteMethodEnum]
	given fmtCommuteFilterRoadTrafficEnum: Format[Schema.CommuteFilter.RoadTrafficEnum] = JsonEnumFormat[Schema.CommuteFilter.RoadTrafficEnum]
	given fmtTimeOfDay: Format[Schema.TimeOfDay] = Json.format[Schema.TimeOfDay]
	given fmtCompensationFilterTypeEnum: Format[Schema.CompensationFilter.TypeEnum] = JsonEnumFormat[Schema.CompensationFilter.TypeEnum]
	given fmtCompensationFilterUnitsEnum: Format[Schema.CompensationFilter.UnitsEnum] = JsonEnumFormat[Schema.CompensationFilter.UnitsEnum]
	given fmtCustomRankingInfoImportanceLevelEnum: Format[Schema.CustomRankingInfo.ImportanceLevelEnum] = JsonEnumFormat[Schema.CustomRankingInfo.ImportanceLevelEnum]
	given fmtSearchJobsResponse: Format[Schema.SearchJobsResponse] = Json.format[Schema.SearchJobsResponse]
	given fmtMatchingJob: Format[Schema.MatchingJob] = Json.format[Schema.MatchingJob]
	given fmtHistogramQueryResult: Format[Schema.HistogramQueryResult] = Json.format[Schema.HistogramQueryResult]
	given fmtSpellingCorrection: Format[Schema.SpellingCorrection] = Json.format[Schema.SpellingCorrection]
	given fmtCommuteInfo: Format[Schema.CommuteInfo] = Json.format[Schema.CommuteInfo]
	given fmtTenant: Format[Schema.Tenant] = Json.format[Schema.Tenant]
	given fmtListTenantsResponse: Format[Schema.ListTenantsResponse] = Json.format[Schema.ListTenantsResponse]
	given fmtBatchOperationMetadata: Format[Schema.BatchOperationMetadata] = Json.format[Schema.BatchOperationMetadata]
	given fmtBatchOperationMetadataStateEnum: Format[Schema.BatchOperationMetadata.StateEnum] = JsonEnumFormat[Schema.BatchOperationMetadata.StateEnum]
	given fmtBatchCreateJobsResponse: Format[Schema.BatchCreateJobsResponse] = Json.format[Schema.BatchCreateJobsResponse]
	given fmtJobResult: Format[Schema.JobResult] = Json.format[Schema.JobResult]
	given fmtBatchUpdateJobsResponse: Format[Schema.BatchUpdateJobsResponse] = Json.format[Schema.BatchUpdateJobsResponse]
	given fmtBatchDeleteJobsResponse: Format[Schema.BatchDeleteJobsResponse] = Json.format[Schema.BatchDeleteJobsResponse]
}
