package com.boresjo.play.api.google.dataform

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListRepositoriesResponse: Format[Schema.ListRepositoriesResponse] = Json.format[Schema.ListRepositoriesResponse]
	given fmtRepository: Format[Schema.Repository] = Json.format[Schema.Repository]
	given fmtGitRemoteSettings: Format[Schema.GitRemoteSettings] = Json.format[Schema.GitRemoteSettings]
	given fmtWorkspaceCompilationOverrides: Format[Schema.WorkspaceCompilationOverrides] = Json.format[Schema.WorkspaceCompilationOverrides]
	given fmtDataEncryptionState: Format[Schema.DataEncryptionState] = Json.format[Schema.DataEncryptionState]
	given fmtSshAuthenticationConfig: Format[Schema.SshAuthenticationConfig] = Json.format[Schema.SshAuthenticationConfig]
	given fmtGitRemoteSettingsTokenStatusEnum: Format[Schema.GitRemoteSettings.TokenStatusEnum] = JsonEnumFormat[Schema.GitRemoteSettings.TokenStatusEnum]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCommitRepositoryChangesRequest: Format[Schema.CommitRepositoryChangesRequest] = Json.format[Schema.CommitRepositoryChangesRequest]
	given fmtCommitMetadata: Format[Schema.CommitMetadata] = Json.format[Schema.CommitMetadata]
	given fmtFileOperation: Format[Schema.FileOperation] = Json.format[Schema.FileOperation]
	given fmtCommitAuthor: Format[Schema.CommitAuthor] = Json.format[Schema.CommitAuthor]
	given fmtWriteFile: Format[Schema.WriteFile] = Json.format[Schema.WriteFile]
	given fmtDeleteFile: Format[Schema.DeleteFile] = Json.format[Schema.DeleteFile]
	given fmtCommitRepositoryChangesResponse: Format[Schema.CommitRepositoryChangesResponse] = Json.format[Schema.CommitRepositoryChangesResponse]
	given fmtReadRepositoryFileResponse: Format[Schema.ReadRepositoryFileResponse] = Json.format[Schema.ReadRepositoryFileResponse]
	given fmtQueryRepositoryDirectoryContentsResponse: Format[Schema.QueryRepositoryDirectoryContentsResponse] = Json.format[Schema.QueryRepositoryDirectoryContentsResponse]
	given fmtDirectoryEntry: Format[Schema.DirectoryEntry] = Json.format[Schema.DirectoryEntry]
	given fmtFetchRepositoryHistoryResponse: Format[Schema.FetchRepositoryHistoryResponse] = Json.format[Schema.FetchRepositoryHistoryResponse]
	given fmtCommitLogEntry: Format[Schema.CommitLogEntry] = Json.format[Schema.CommitLogEntry]
	given fmtComputeRepositoryAccessTokenStatusResponse: Format[Schema.ComputeRepositoryAccessTokenStatusResponse] = Json.format[Schema.ComputeRepositoryAccessTokenStatusResponse]
	given fmtComputeRepositoryAccessTokenStatusResponseTokenStatusEnum: Format[Schema.ComputeRepositoryAccessTokenStatusResponse.TokenStatusEnum] = JsonEnumFormat[Schema.ComputeRepositoryAccessTokenStatusResponse.TokenStatusEnum]
	given fmtFetchRemoteBranchesResponse: Format[Schema.FetchRemoteBranchesResponse] = Json.format[Schema.FetchRemoteBranchesResponse]
	given fmtListWorkspacesResponse: Format[Schema.ListWorkspacesResponse] = Json.format[Schema.ListWorkspacesResponse]
	given fmtWorkspace: Format[Schema.Workspace] = Json.format[Schema.Workspace]
	given fmtInstallNpmPackagesRequest: Format[Schema.InstallNpmPackagesRequest] = Json.format[Schema.InstallNpmPackagesRequest]
	given fmtInstallNpmPackagesResponse: Format[Schema.InstallNpmPackagesResponse] = Json.format[Schema.InstallNpmPackagesResponse]
	given fmtPullGitCommitsRequest: Format[Schema.PullGitCommitsRequest] = Json.format[Schema.PullGitCommitsRequest]
	given fmtPushGitCommitsRequest: Format[Schema.PushGitCommitsRequest] = Json.format[Schema.PushGitCommitsRequest]
	given fmtFetchFileGitStatusesResponse: Format[Schema.FetchFileGitStatusesResponse] = Json.format[Schema.FetchFileGitStatusesResponse]
	given fmtUncommittedFileChange: Format[Schema.UncommittedFileChange] = Json.format[Schema.UncommittedFileChange]
	given fmtUncommittedFileChangeStateEnum: Format[Schema.UncommittedFileChange.StateEnum] = JsonEnumFormat[Schema.UncommittedFileChange.StateEnum]
	given fmtFetchGitAheadBehindResponse: Format[Schema.FetchGitAheadBehindResponse] = Json.format[Schema.FetchGitAheadBehindResponse]
	given fmtCommitWorkspaceChangesRequest: Format[Schema.CommitWorkspaceChangesRequest] = Json.format[Schema.CommitWorkspaceChangesRequest]
	given fmtResetWorkspaceChangesRequest: Format[Schema.ResetWorkspaceChangesRequest] = Json.format[Schema.ResetWorkspaceChangesRequest]
	given fmtFetchFileDiffResponse: Format[Schema.FetchFileDiffResponse] = Json.format[Schema.FetchFileDiffResponse]
	given fmtQueryDirectoryContentsResponse: Format[Schema.QueryDirectoryContentsResponse] = Json.format[Schema.QueryDirectoryContentsResponse]
	given fmtSearchFilesResponse: Format[Schema.SearchFilesResponse] = Json.format[Schema.SearchFilesResponse]
	given fmtSearchResult: Format[Schema.SearchResult] = Json.format[Schema.SearchResult]
	given fmtFileSearchResult: Format[Schema.FileSearchResult] = Json.format[Schema.FileSearchResult]
	given fmtDirectorySearchResult: Format[Schema.DirectorySearchResult] = Json.format[Schema.DirectorySearchResult]
	given fmtMakeDirectoryRequest: Format[Schema.MakeDirectoryRequest] = Json.format[Schema.MakeDirectoryRequest]
	given fmtMakeDirectoryResponse: Format[Schema.MakeDirectoryResponse] = Json.format[Schema.MakeDirectoryResponse]
	given fmtRemoveDirectoryRequest: Format[Schema.RemoveDirectoryRequest] = Json.format[Schema.RemoveDirectoryRequest]
	given fmtMoveDirectoryRequest: Format[Schema.MoveDirectoryRequest] = Json.format[Schema.MoveDirectoryRequest]
	given fmtMoveDirectoryResponse: Format[Schema.MoveDirectoryResponse] = Json.format[Schema.MoveDirectoryResponse]
	given fmtReadFileResponse: Format[Schema.ReadFileResponse] = Json.format[Schema.ReadFileResponse]
	given fmtRemoveFileRequest: Format[Schema.RemoveFileRequest] = Json.format[Schema.RemoveFileRequest]
	given fmtMoveFileRequest: Format[Schema.MoveFileRequest] = Json.format[Schema.MoveFileRequest]
	given fmtMoveFileResponse: Format[Schema.MoveFileResponse] = Json.format[Schema.MoveFileResponse]
	given fmtWriteFileRequest: Format[Schema.WriteFileRequest] = Json.format[Schema.WriteFileRequest]
	given fmtWriteFileResponse: Format[Schema.WriteFileResponse] = Json.format[Schema.WriteFileResponse]
	given fmtListReleaseConfigsResponse: Format[Schema.ListReleaseConfigsResponse] = Json.format[Schema.ListReleaseConfigsResponse]
	given fmtReleaseConfig: Format[Schema.ReleaseConfig] = Json.format[Schema.ReleaseConfig]
	given fmtCodeCompilationConfig: Format[Schema.CodeCompilationConfig] = Json.format[Schema.CodeCompilationConfig]
	given fmtScheduledReleaseRecord: Format[Schema.ScheduledReleaseRecord] = Json.format[Schema.ScheduledReleaseRecord]
	given fmtNotebookRuntimeOptions: Format[Schema.NotebookRuntimeOptions] = Json.format[Schema.NotebookRuntimeOptions]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtListCompilationResultsResponse: Format[Schema.ListCompilationResultsResponse] = Json.format[Schema.ListCompilationResultsResponse]
	given fmtCompilationResult: Format[Schema.CompilationResult] = Json.format[Schema.CompilationResult]
	given fmtCompilationError: Format[Schema.CompilationError] = Json.format[Schema.CompilationError]
	given fmtTarget: Format[Schema.Target] = Json.format[Schema.Target]
	given fmtQueryCompilationResultActionsResponse: Format[Schema.QueryCompilationResultActionsResponse] = Json.format[Schema.QueryCompilationResultActionsResponse]
	given fmtCompilationResultAction: Format[Schema.CompilationResultAction] = Json.format[Schema.CompilationResultAction]
	given fmtRelation: Format[Schema.Relation] = Json.format[Schema.Relation]
	given fmtOperations: Format[Schema.Operations] = Json.format[Schema.Operations]
	given fmtAssertion: Format[Schema.Assertion] = Json.format[Schema.Assertion]
	given fmtDeclaration: Format[Schema.Declaration] = Json.format[Schema.Declaration]
	given fmtNotebook: Format[Schema.Notebook] = Json.format[Schema.Notebook]
	given fmtRelationDescriptor: Format[Schema.RelationDescriptor] = Json.format[Schema.RelationDescriptor]
	given fmtRelationRelationTypeEnum: Format[Schema.Relation.RelationTypeEnum] = JsonEnumFormat[Schema.Relation.RelationTypeEnum]
	given fmtIncrementalTableConfig: Format[Schema.IncrementalTableConfig] = Json.format[Schema.IncrementalTableConfig]
	given fmtColumnDescriptor: Format[Schema.ColumnDescriptor] = Json.format[Schema.ColumnDescriptor]
	given fmtListWorkflowConfigsResponse: Format[Schema.ListWorkflowConfigsResponse] = Json.format[Schema.ListWorkflowConfigsResponse]
	given fmtWorkflowConfig: Format[Schema.WorkflowConfig] = Json.format[Schema.WorkflowConfig]
	given fmtInvocationConfig: Format[Schema.InvocationConfig] = Json.format[Schema.InvocationConfig]
	given fmtScheduledExecutionRecord: Format[Schema.ScheduledExecutionRecord] = Json.format[Schema.ScheduledExecutionRecord]
	given fmtListWorkflowInvocationsResponse: Format[Schema.ListWorkflowInvocationsResponse] = Json.format[Schema.ListWorkflowInvocationsResponse]
	given fmtWorkflowInvocation: Format[Schema.WorkflowInvocation] = Json.format[Schema.WorkflowInvocation]
	given fmtWorkflowInvocationStateEnum: Format[Schema.WorkflowInvocation.StateEnum] = JsonEnumFormat[Schema.WorkflowInvocation.StateEnum]
	given fmtInterval: Format[Schema.Interval] = Json.format[Schema.Interval]
	given fmtCancelWorkflowInvocationRequest: Format[Schema.CancelWorkflowInvocationRequest] = Json.format[Schema.CancelWorkflowInvocationRequest]
	given fmtQueryWorkflowInvocationActionsResponse: Format[Schema.QueryWorkflowInvocationActionsResponse] = Json.format[Schema.QueryWorkflowInvocationActionsResponse]
	given fmtWorkflowInvocationAction: Format[Schema.WorkflowInvocationAction] = Json.format[Schema.WorkflowInvocationAction]
	given fmtBigQueryAction: Format[Schema.BigQueryAction] = Json.format[Schema.BigQueryAction]
	given fmtNotebookAction: Format[Schema.NotebookAction] = Json.format[Schema.NotebookAction]
	given fmtWorkflowInvocationActionStateEnum: Format[Schema.WorkflowInvocationAction.StateEnum] = JsonEnumFormat[Schema.WorkflowInvocationAction.StateEnum]
	given fmtConfig: Format[Schema.Config] = Json.format[Schema.Config]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
