package com.boresjo.play.api.google.domains

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtListOperationsResponse: Format[Schema.ListOperationsResponse] = Json.format[Schema.ListOperationsResponse]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtSearchDomainsResponse: Format[Schema.SearchDomainsResponse] = Json.format[Schema.SearchDomainsResponse]
	given fmtRegisterParameters: Format[Schema.RegisterParameters] = Json.format[Schema.RegisterParameters]
	given fmtRegisterParametersAvailabilityEnum: Format[Schema.RegisterParameters.AvailabilityEnum] = JsonEnumFormat[Schema.RegisterParameters.AvailabilityEnum]
	given fmtRegisterParametersSupportedPrivacyEnum: Format[Schema.RegisterParameters.SupportedPrivacyEnum] = JsonEnumFormat[Schema.RegisterParameters.SupportedPrivacyEnum]
	given fmtRegisterParametersDomainNoticesEnum: Format[Schema.RegisterParameters.DomainNoticesEnum] = JsonEnumFormat[Schema.RegisterParameters.DomainNoticesEnum]
	given fmtMoney: Format[Schema.Money] = Json.format[Schema.Money]
	given fmtRetrieveRegisterParametersResponse: Format[Schema.RetrieveRegisterParametersResponse] = Json.format[Schema.RetrieveRegisterParametersResponse]
	given fmtRegisterDomainRequest: Format[Schema.RegisterDomainRequest] = Json.format[Schema.RegisterDomainRequest]
	given fmtRegistration: Format[Schema.Registration] = Json.format[Schema.Registration]
	given fmtRegisterDomainRequestDomainNoticesEnum: Format[Schema.RegisterDomainRequest.DomainNoticesEnum] = JsonEnumFormat[Schema.RegisterDomainRequest.DomainNoticesEnum]
	given fmtRegisterDomainRequestContactNoticesEnum: Format[Schema.RegisterDomainRequest.ContactNoticesEnum] = JsonEnumFormat[Schema.RegisterDomainRequest.ContactNoticesEnum]
	given fmtRegistrationStateEnum: Format[Schema.Registration.StateEnum] = JsonEnumFormat[Schema.Registration.StateEnum]
	given fmtRegistrationIssuesEnum: Format[Schema.Registration.IssuesEnum] = JsonEnumFormat[Schema.Registration.IssuesEnum]
	given fmtManagementSettings: Format[Schema.ManagementSettings] = Json.format[Schema.ManagementSettings]
	given fmtDnsSettings: Format[Schema.DnsSettings] = Json.format[Schema.DnsSettings]
	given fmtContactSettings: Format[Schema.ContactSettings] = Json.format[Schema.ContactSettings]
	given fmtRegistrationSupportedPrivacyEnum: Format[Schema.Registration.SupportedPrivacyEnum] = JsonEnumFormat[Schema.Registration.SupportedPrivacyEnum]
	given fmtRegistrationRegisterFailureReasonEnum: Format[Schema.Registration.RegisterFailureReasonEnum] = JsonEnumFormat[Schema.Registration.RegisterFailureReasonEnum]
	given fmtRegistrationTransferFailureReasonEnum: Format[Schema.Registration.TransferFailureReasonEnum] = JsonEnumFormat[Schema.Registration.TransferFailureReasonEnum]
	given fmtRegistrationDomainPropertiesEnum: Format[Schema.Registration.DomainPropertiesEnum] = JsonEnumFormat[Schema.Registration.DomainPropertiesEnum]
	given fmtManagementSettingsRenewalMethodEnum: Format[Schema.ManagementSettings.RenewalMethodEnum] = JsonEnumFormat[Schema.ManagementSettings.RenewalMethodEnum]
	given fmtManagementSettingsPreferredRenewalMethodEnum: Format[Schema.ManagementSettings.PreferredRenewalMethodEnum] = JsonEnumFormat[Schema.ManagementSettings.PreferredRenewalMethodEnum]
	given fmtManagementSettingsTransferLockStateEnum: Format[Schema.ManagementSettings.TransferLockStateEnum] = JsonEnumFormat[Schema.ManagementSettings.TransferLockStateEnum]
	given fmtManagementSettingsEffectiveTransferLockStateEnum: Format[Schema.ManagementSettings.EffectiveTransferLockStateEnum] = JsonEnumFormat[Schema.ManagementSettings.EffectiveTransferLockStateEnum]
	given fmtCustomDns: Format[Schema.CustomDns] = Json.format[Schema.CustomDns]
	given fmtGoogleDomainsDns: Format[Schema.GoogleDomainsDns] = Json.format[Schema.GoogleDomainsDns]
	given fmtGlueRecord: Format[Schema.GlueRecord] = Json.format[Schema.GlueRecord]
	given fmtDsRecord: Format[Schema.DsRecord] = Json.format[Schema.DsRecord]
	given fmtDsRecordAlgorithmEnum: Format[Schema.DsRecord.AlgorithmEnum] = JsonEnumFormat[Schema.DsRecord.AlgorithmEnum]
	given fmtDsRecordDigestTypeEnum: Format[Schema.DsRecord.DigestTypeEnum] = JsonEnumFormat[Schema.DsRecord.DigestTypeEnum]
	given fmtGoogleDomainsDnsDsStateEnum: Format[Schema.GoogleDomainsDns.DsStateEnum] = JsonEnumFormat[Schema.GoogleDomainsDns.DsStateEnum]
	given fmtContactSettingsPrivacyEnum: Format[Schema.ContactSettings.PrivacyEnum] = JsonEnumFormat[Schema.ContactSettings.PrivacyEnum]
	given fmtContact: Format[Schema.Contact] = Json.format[Schema.Contact]
	given fmtPostalAddress: Format[Schema.PostalAddress] = Json.format[Schema.PostalAddress]
	given fmtRetrieveTransferParametersResponse: Format[Schema.RetrieveTransferParametersResponse] = Json.format[Schema.RetrieveTransferParametersResponse]
	given fmtTransferParameters: Format[Schema.TransferParameters] = Json.format[Schema.TransferParameters]
	given fmtTransferParametersTransferLockStateEnum: Format[Schema.TransferParameters.TransferLockStateEnum] = JsonEnumFormat[Schema.TransferParameters.TransferLockStateEnum]
	given fmtTransferParametersSupportedPrivacyEnum: Format[Schema.TransferParameters.SupportedPrivacyEnum] = JsonEnumFormat[Schema.TransferParameters.SupportedPrivacyEnum]
	given fmtTransferDomainRequest: Format[Schema.TransferDomainRequest] = Json.format[Schema.TransferDomainRequest]
	given fmtTransferDomainRequestContactNoticesEnum: Format[Schema.TransferDomainRequest.ContactNoticesEnum] = JsonEnumFormat[Schema.TransferDomainRequest.ContactNoticesEnum]
	given fmtAuthorizationCode: Format[Schema.AuthorizationCode] = Json.format[Schema.AuthorizationCode]
	given fmtRetrieveImportableDomainsResponse: Format[Schema.RetrieveImportableDomainsResponse] = Json.format[Schema.RetrieveImportableDomainsResponse]
	given fmtDomain: Format[Schema.Domain] = Json.format[Schema.Domain]
	given fmtDomainResourceStateEnum: Format[Schema.Domain.ResourceStateEnum] = JsonEnumFormat[Schema.Domain.ResourceStateEnum]
	given fmtImportDomainRequest: Format[Schema.ImportDomainRequest] = Json.format[Schema.ImportDomainRequest]
	given fmtListRegistrationsResponse: Format[Schema.ListRegistrationsResponse] = Json.format[Schema.ListRegistrationsResponse]
	given fmtConfigureManagementSettingsRequest: Format[Schema.ConfigureManagementSettingsRequest] = Json.format[Schema.ConfigureManagementSettingsRequest]
	given fmtConfigureDnsSettingsRequest: Format[Schema.ConfigureDnsSettingsRequest] = Json.format[Schema.ConfigureDnsSettingsRequest]
	given fmtRetrieveGoogleDomainsDnsRecordsResponse: Format[Schema.RetrieveGoogleDomainsDnsRecordsResponse] = Json.format[Schema.RetrieveGoogleDomainsDnsRecordsResponse]
	given fmtResourceRecordSet: Format[Schema.ResourceRecordSet] = Json.format[Schema.ResourceRecordSet]
	given fmtRRSetRoutingPolicy: Format[Schema.RRSetRoutingPolicy] = Json.format[Schema.RRSetRoutingPolicy]
	given fmtGeoPolicy: Format[Schema.GeoPolicy] = Json.format[Schema.GeoPolicy]
	given fmtWrrPolicy: Format[Schema.WrrPolicy] = Json.format[Schema.WrrPolicy]
	given fmtPrimaryBackupPolicy: Format[Schema.PrimaryBackupPolicy] = Json.format[Schema.PrimaryBackupPolicy]
	given fmtGeoPolicyItem: Format[Schema.GeoPolicyItem] = Json.format[Schema.GeoPolicyItem]
	given fmtHealthCheckTargets: Format[Schema.HealthCheckTargets] = Json.format[Schema.HealthCheckTargets]
	given fmtLoadBalancerTarget: Format[Schema.LoadBalancerTarget] = Json.format[Schema.LoadBalancerTarget]
	given fmtLoadBalancerTargetLoadBalancerTypeEnum: Format[Schema.LoadBalancerTarget.LoadBalancerTypeEnum] = JsonEnumFormat[Schema.LoadBalancerTarget.LoadBalancerTypeEnum]
	given fmtLoadBalancerTargetIpProtocolEnum: Format[Schema.LoadBalancerTarget.IpProtocolEnum] = JsonEnumFormat[Schema.LoadBalancerTarget.IpProtocolEnum]
	given fmtWrrPolicyItem: Format[Schema.WrrPolicyItem] = Json.format[Schema.WrrPolicyItem]
	given fmtRetrieveGoogleDomainsForwardingConfigResponse: Format[Schema.RetrieveGoogleDomainsForwardingConfigResponse] = Json.format[Schema.RetrieveGoogleDomainsForwardingConfigResponse]
	given fmtDomainForwarding: Format[Schema.DomainForwarding] = Json.format[Schema.DomainForwarding]
	given fmtEmailForwarding: Format[Schema.EmailForwarding] = Json.format[Schema.EmailForwarding]
	given fmtDomainForwardingRedirectTypeEnum: Format[Schema.DomainForwarding.RedirectTypeEnum] = JsonEnumFormat[Schema.DomainForwarding.RedirectTypeEnum]
	given fmtConfigureContactSettingsRequest: Format[Schema.ConfigureContactSettingsRequest] = Json.format[Schema.ConfigureContactSettingsRequest]
	given fmtConfigureContactSettingsRequestContactNoticesEnum: Format[Schema.ConfigureContactSettingsRequest.ContactNoticesEnum] = JsonEnumFormat[Schema.ConfigureContactSettingsRequest.ContactNoticesEnum]
	given fmtExportRegistrationRequest: Format[Schema.ExportRegistrationRequest] = Json.format[Schema.ExportRegistrationRequest]
	given fmtResetAuthorizationCodeRequest: Format[Schema.ResetAuthorizationCodeRequest] = Json.format[Schema.ResetAuthorizationCodeRequest]
	given fmtInitiatePushTransferRequest: Format[Schema.InitiatePushTransferRequest] = Json.format[Schema.InitiatePushTransferRequest]
	given fmtRenewDomainRequest: Format[Schema.RenewDomainRequest] = Json.format[Schema.RenewDomainRequest]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
}
