package com.boresjo.play.api.google.ondemandscanning

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, RequestSigner, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Helpers {
	import Schema.*
	object AutoOption {
		given putListSchemaOperation: Conversion[List[Schema.Operation], Option[List[Schema.Operation]]] = (fun: List[Schema.Operation]) => Option(fun)
		given putString: Conversion[String, Option[String]] = (fun: String) => Option(fun)
		given putMapStringJsValue: Conversion[Map[String, JsValue], Option[Map[String, JsValue]]] = (fun: Map[String, JsValue]) => Option(fun)
		given putBoolean: Conversion[Boolean, Option[Boolean]] = (fun: Boolean) => Option(fun)
		given putSchemaStatus: Conversion[Schema.Status, Option[Schema.Status]] = (fun: Schema.Status) => Option(fun)
		given putInt: Conversion[Int, Option[Int]] = (fun: Int) => Option(fun)
		given putListMapStringJsValue: Conversion[List[Map[String, JsValue]], Option[List[Map[String, JsValue]]]] = (fun: List[Map[String, JsValue]]) => Option(fun)
		given putListSchemaPackageData: Conversion[List[Schema.PackageData], Option[List[Schema.PackageData]]] = (fun: List[Schema.PackageData]) => Option(fun)
		given putSchemaPackageDataPackageTypeEnum: Conversion[Schema.PackageData.PackageTypeEnum, Option[Schema.PackageData.PackageTypeEnum]] = (fun: Schema.PackageData.PackageTypeEnum) => Option(fun)
		given putListSchemaFileLocation: Conversion[List[Schema.FileLocation], Option[List[Schema.FileLocation]]] = (fun: List[Schema.FileLocation]) => Option(fun)
		given putListString: Conversion[List[String], Option[List[String]]] = (fun: List[String]) => Option(fun)
		given putListSchemaLanguagePackageDependency: Conversion[List[Schema.LanguagePackageDependency], Option[List[Schema.LanguagePackageDependency]]] = (fun: List[Schema.LanguagePackageDependency]) => Option(fun)
		given putSchemaMaintainer: Conversion[Schema.Maintainer, Option[Schema.Maintainer]] = (fun: Schema.Maintainer) => Option(fun)
		given putSchemaPackageVersion: Conversion[Schema.PackageVersion, Option[Schema.PackageVersion]] = (fun: Schema.PackageVersion) => Option(fun)
		given putListSchemaBinarySourceInfo: Conversion[List[Schema.BinarySourceInfo], Option[List[Schema.BinarySourceInfo]]] = (fun: List[Schema.BinarySourceInfo]) => Option(fun)
		given putListSchemaOccurrence: Conversion[List[Schema.Occurrence], Option[List[Schema.Occurrence]]] = (fun: List[Schema.Occurrence]) => Option(fun)
		given putSchemaOccurrenceKindEnum: Conversion[Schema.Occurrence.KindEnum, Option[Schema.Occurrence.KindEnum]] = (fun: Schema.Occurrence.KindEnum) => Option(fun)
		given putSchemaVulnerabilityOccurrence: Conversion[Schema.VulnerabilityOccurrence, Option[Schema.VulnerabilityOccurrence]] = (fun: Schema.VulnerabilityOccurrence) => Option(fun)
		given putSchemaBuildOccurrence: Conversion[Schema.BuildOccurrence, Option[Schema.BuildOccurrence]] = (fun: Schema.BuildOccurrence) => Option(fun)
		given putSchemaImageOccurrence: Conversion[Schema.ImageOccurrence, Option[Schema.ImageOccurrence]] = (fun: Schema.ImageOccurrence) => Option(fun)
		given putSchemaPackageOccurrence: Conversion[Schema.PackageOccurrence, Option[Schema.PackageOccurrence]] = (fun: Schema.PackageOccurrence) => Option(fun)
		given putSchemaDeploymentOccurrence: Conversion[Schema.DeploymentOccurrence, Option[Schema.DeploymentOccurrence]] = (fun: Schema.DeploymentOccurrence) => Option(fun)
		given putSchemaDiscoveryOccurrence: Conversion[Schema.DiscoveryOccurrence, Option[Schema.DiscoveryOccurrence]] = (fun: Schema.DiscoveryOccurrence) => Option(fun)
		given putSchemaAttestationOccurrence: Conversion[Schema.AttestationOccurrence, Option[Schema.AttestationOccurrence]] = (fun: Schema.AttestationOccurrence) => Option(fun)
		given putSchemaUpgradeOccurrence: Conversion[Schema.UpgradeOccurrence, Option[Schema.UpgradeOccurrence]] = (fun: Schema.UpgradeOccurrence) => Option(fun)
		given putSchemaComplianceOccurrence: Conversion[Schema.ComplianceOccurrence, Option[Schema.ComplianceOccurrence]] = (fun: Schema.ComplianceOccurrence) => Option(fun)
		given putSchemaDSSEAttestationOccurrence: Conversion[Schema.DSSEAttestationOccurrence, Option[Schema.DSSEAttestationOccurrence]] = (fun: Schema.DSSEAttestationOccurrence) => Option(fun)
		given putSchemaSBOMReferenceOccurrence: Conversion[Schema.SBOMReferenceOccurrence, Option[Schema.SBOMReferenceOccurrence]] = (fun: Schema.SBOMReferenceOccurrence) => Option(fun)
		given putSchemaEnvelope: Conversion[Schema.Envelope, Option[Schema.Envelope]] = (fun: Schema.Envelope) => Option(fun)
		given putSchemaVulnerabilityOccurrenceSeverityEnum: Conversion[Schema.VulnerabilityOccurrence.SeverityEnum, Option[Schema.VulnerabilityOccurrence.SeverityEnum]] = (fun: Schema.VulnerabilityOccurrence.SeverityEnum) => Option(fun)
		given putBigDecimal: Conversion[BigDecimal, Option[BigDecimal]] = (fun: BigDecimal) => Option(fun)
		given putSchemaCVSS: Conversion[Schema.CVSS, Option[Schema.CVSS]] = (fun: Schema.CVSS) => Option(fun)
		given putListSchemaPackageIssue: Conversion[List[Schema.PackageIssue], Option[List[Schema.PackageIssue]]] = (fun: List[Schema.PackageIssue]) => Option(fun)
		given putListSchemaRelatedUrl: Conversion[List[Schema.RelatedUrl], Option[List[Schema.RelatedUrl]]] = (fun: List[Schema.RelatedUrl]) => Option(fun)
		given putSchemaVulnerabilityOccurrenceEffectiveSeverityEnum: Conversion[Schema.VulnerabilityOccurrence.EffectiveSeverityEnum, Option[Schema.VulnerabilityOccurrence.EffectiveSeverityEnum]] = (fun: Schema.VulnerabilityOccurrence.EffectiveSeverityEnum) => Option(fun)
		given putSchemaVulnerabilityOccurrenceCvssVersionEnum: Conversion[Schema.VulnerabilityOccurrence.CvssVersionEnum, Option[Schema.VulnerabilityOccurrence.CvssVersionEnum]] = (fun: Schema.VulnerabilityOccurrence.CvssVersionEnum) => Option(fun)
		given putSchemaVexAssessment: Conversion[Schema.VexAssessment, Option[Schema.VexAssessment]] = (fun: Schema.VexAssessment) => Option(fun)
		given putSchemaCVSSAttackVectorEnum: Conversion[Schema.CVSS.AttackVectorEnum, Option[Schema.CVSS.AttackVectorEnum]] = (fun: Schema.CVSS.AttackVectorEnum) => Option(fun)
		given putSchemaCVSSAttackComplexityEnum: Conversion[Schema.CVSS.AttackComplexityEnum, Option[Schema.CVSS.AttackComplexityEnum]] = (fun: Schema.CVSS.AttackComplexityEnum) => Option(fun)
		given putSchemaCVSSAuthenticationEnum: Conversion[Schema.CVSS.AuthenticationEnum, Option[Schema.CVSS.AuthenticationEnum]] = (fun: Schema.CVSS.AuthenticationEnum) => Option(fun)
		given putSchemaCVSSPrivilegesRequiredEnum: Conversion[Schema.CVSS.PrivilegesRequiredEnum, Option[Schema.CVSS.PrivilegesRequiredEnum]] = (fun: Schema.CVSS.PrivilegesRequiredEnum) => Option(fun)
		given putSchemaCVSSUserInteractionEnum: Conversion[Schema.CVSS.UserInteractionEnum, Option[Schema.CVSS.UserInteractionEnum]] = (fun: Schema.CVSS.UserInteractionEnum) => Option(fun)
		given putSchemaCVSSScopeEnum: Conversion[Schema.CVSS.ScopeEnum, Option[Schema.CVSS.ScopeEnum]] = (fun: Schema.CVSS.ScopeEnum) => Option(fun)
		given putSchemaCVSSConfidentialityImpactEnum: Conversion[Schema.CVSS.ConfidentialityImpactEnum, Option[Schema.CVSS.ConfidentialityImpactEnum]] = (fun: Schema.CVSS.ConfidentialityImpactEnum) => Option(fun)
		given putSchemaCVSSIntegrityImpactEnum: Conversion[Schema.CVSS.IntegrityImpactEnum, Option[Schema.CVSS.IntegrityImpactEnum]] = (fun: Schema.CVSS.IntegrityImpactEnum) => Option(fun)
		given putSchemaCVSSAvailabilityImpactEnum: Conversion[Schema.CVSS.AvailabilityImpactEnum, Option[Schema.CVSS.AvailabilityImpactEnum]] = (fun: Schema.CVSS.AvailabilityImpactEnum) => Option(fun)
		given putSchemaVersion: Conversion[Schema.Version, Option[Schema.Version]] = (fun: Schema.Version) => Option(fun)
		given putSchemaPackageIssueEffectiveSeverityEnum: Conversion[Schema.PackageIssue.EffectiveSeverityEnum, Option[Schema.PackageIssue.EffectiveSeverityEnum]] = (fun: Schema.PackageIssue.EffectiveSeverityEnum) => Option(fun)
		given putListSchemaGrafeasV1FileLocation: Conversion[List[Schema.GrafeasV1FileLocation], Option[List[Schema.GrafeasV1FileLocation]]] = (fun: List[Schema.GrafeasV1FileLocation]) => Option(fun)
		given putSchemaVersionKindEnum: Conversion[Schema.Version.KindEnum, Option[Schema.Version.KindEnum]] = (fun: Schema.Version.KindEnum) => Option(fun)
		given putSchemaVexAssessmentStateEnum: Conversion[Schema.VexAssessment.StateEnum, Option[Schema.VexAssessment.StateEnum]] = (fun: Schema.VexAssessment.StateEnum) => Option(fun)
		given putListSchemaRemediation: Conversion[List[Schema.Remediation], Option[List[Schema.Remediation]]] = (fun: List[Schema.Remediation]) => Option(fun)
		given putSchemaJustification: Conversion[Schema.Justification, Option[Schema.Justification]] = (fun: Schema.Justification) => Option(fun)
		given putSchemaRemediationRemediationTypeEnum: Conversion[Schema.Remediation.RemediationTypeEnum, Option[Schema.Remediation.RemediationTypeEnum]] = (fun: Schema.Remediation.RemediationTypeEnum) => Option(fun)
		given putSchemaRelatedUrl: Conversion[Schema.RelatedUrl, Option[Schema.RelatedUrl]] = (fun: Schema.RelatedUrl) => Option(fun)
		given putSchemaJustificationJustificationTypeEnum: Conversion[Schema.Justification.JustificationTypeEnum, Option[Schema.Justification.JustificationTypeEnum]] = (fun: Schema.Justification.JustificationTypeEnum) => Option(fun)
		given putSchemaBuildProvenance: Conversion[Schema.BuildProvenance, Option[Schema.BuildProvenance]] = (fun: Schema.BuildProvenance) => Option(fun)
		given putSchemaInTotoProvenance: Conversion[Schema.InTotoProvenance, Option[Schema.InTotoProvenance]] = (fun: Schema.InTotoProvenance) => Option(fun)
		given putSchemaInTotoStatement: Conversion[Schema.InTotoStatement, Option[Schema.InTotoStatement]] = (fun: Schema.InTotoStatement) => Option(fun)
		given putSchemaInTotoSlsaProvenanceV1: Conversion[Schema.InTotoSlsaProvenanceV1, Option[Schema.InTotoSlsaProvenanceV1]] = (fun: Schema.InTotoSlsaProvenanceV1) => Option(fun)
		given putListSchemaCommand: Conversion[List[Schema.Command], Option[List[Schema.Command]]] = (fun: List[Schema.Command]) => Option(fun)
		given putListSchemaArtifact: Conversion[List[Schema.Artifact], Option[List[Schema.Artifact]]] = (fun: List[Schema.Artifact]) => Option(fun)
		given putSchemaSource: Conversion[Schema.Source, Option[Schema.Source]] = (fun: Schema.Source) => Option(fun)
		given putMapStringString: Conversion[Map[String, String], Option[Map[String, String]]] = (fun: Map[String, String]) => Option(fun)
		given putMapStringSchemaFileHashes: Conversion[Map[String, Schema.FileHashes], Option[Map[String, Schema.FileHashes]]] = (fun: Map[String, Schema.FileHashes]) => Option(fun)
		given putSchemaSourceContext: Conversion[Schema.SourceContext, Option[Schema.SourceContext]] = (fun: Schema.SourceContext) => Option(fun)
		given putListSchemaSourceContext: Conversion[List[Schema.SourceContext], Option[List[Schema.SourceContext]]] = (fun: List[Schema.SourceContext]) => Option(fun)
		given putListSchemaHash: Conversion[List[Schema.Hash], Option[List[Schema.Hash]]] = (fun: List[Schema.Hash]) => Option(fun)
		given putSchemaCloudRepoSourceContext: Conversion[Schema.CloudRepoSourceContext, Option[Schema.CloudRepoSourceContext]] = (fun: Schema.CloudRepoSourceContext) => Option(fun)
		given putSchemaGerritSourceContext: Conversion[Schema.GerritSourceContext, Option[Schema.GerritSourceContext]] = (fun: Schema.GerritSourceContext) => Option(fun)
		given putSchemaGitSourceContext: Conversion[Schema.GitSourceContext, Option[Schema.GitSourceContext]] = (fun: Schema.GitSourceContext) => Option(fun)
		given putSchemaRepoId: Conversion[Schema.RepoId, Option[Schema.RepoId]] = (fun: Schema.RepoId) => Option(fun)
		given putSchemaAliasContext: Conversion[Schema.AliasContext, Option[Schema.AliasContext]] = (fun: Schema.AliasContext) => Option(fun)
		given putSchemaProjectRepoId: Conversion[Schema.ProjectRepoId, Option[Schema.ProjectRepoId]] = (fun: Schema.ProjectRepoId) => Option(fun)
		given putSchemaAliasContextKindEnum: Conversion[Schema.AliasContext.KindEnum, Option[Schema.AliasContext.KindEnum]] = (fun: Schema.AliasContext.KindEnum) => Option(fun)
		given putSchemaBuilderConfig: Conversion[Schema.BuilderConfig, Option[Schema.BuilderConfig]] = (fun: Schema.BuilderConfig) => Option(fun)
		given putSchemaRecipe: Conversion[Schema.Recipe, Option[Schema.Recipe]] = (fun: Schema.Recipe) => Option(fun)
		given putSchemaMetadata: Conversion[Schema.Metadata, Option[Schema.Metadata]] = (fun: Schema.Metadata) => Option(fun)
		given putSchemaCompleteness: Conversion[Schema.Completeness, Option[Schema.Completeness]] = (fun: Schema.Completeness) => Option(fun)
		given putListSchemaSubject: Conversion[List[Schema.Subject], Option[List[Schema.Subject]]] = (fun: List[Schema.Subject]) => Option(fun)
		given putSchemaSlsaProvenance: Conversion[Schema.SlsaProvenance, Option[Schema.SlsaProvenance]] = (fun: Schema.SlsaProvenance) => Option(fun)
		given putSchemaSlsaProvenanceZeroTwo: Conversion[Schema.SlsaProvenanceZeroTwo, Option[Schema.SlsaProvenanceZeroTwo]] = (fun: Schema.SlsaProvenanceZeroTwo) => Option(fun)
		given putSchemaSlsaBuilder: Conversion[Schema.SlsaBuilder, Option[Schema.SlsaBuilder]] = (fun: Schema.SlsaBuilder) => Option(fun)
		given putSchemaSlsaRecipe: Conversion[Schema.SlsaRecipe, Option[Schema.SlsaRecipe]] = (fun: Schema.SlsaRecipe) => Option(fun)
		given putSchemaSlsaMetadata: Conversion[Schema.SlsaMetadata, Option[Schema.SlsaMetadata]] = (fun: Schema.SlsaMetadata) => Option(fun)
		given putListSchemaMaterial: Conversion[List[Schema.Material], Option[List[Schema.Material]]] = (fun: List[Schema.Material]) => Option(fun)
		given putSchemaSlsaCompleteness: Conversion[Schema.SlsaCompleteness, Option[Schema.SlsaCompleteness]] = (fun: Schema.SlsaCompleteness) => Option(fun)
		given putSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaBuilder: Conversion[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaBuilder, Option[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaBuilder]] = (fun: Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaBuilder) => Option(fun)
		given putSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaInvocation: Conversion[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaInvocation, Option[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaInvocation]] = (fun: Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaInvocation) => Option(fun)
		given putSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaMetadata: Conversion[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMetadata, Option[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMetadata]] = (fun: Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMetadata) => Option(fun)
		given putListSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaMaterial: Conversion[List[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMaterial], Option[List[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMaterial]]] = (fun: List[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaMaterial]) => Option(fun)
		given putSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaConfigSource: Conversion[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaConfigSource, Option[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaConfigSource]] = (fun: Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaConfigSource) => Option(fun)
		given putSchemaGrafeasV1SlsaProvenanceZeroTwoSlsaCompleteness: Conversion[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaCompleteness, Option[Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaCompleteness]] = (fun: Schema.GrafeasV1SlsaProvenanceZeroTwoSlsaCompleteness) => Option(fun)
		given putSchemaSlsaProvenanceV1: Conversion[Schema.SlsaProvenanceV1, Option[Schema.SlsaProvenanceV1]] = (fun: Schema.SlsaProvenanceV1) => Option(fun)
		given putSchemaBuildDefinition: Conversion[Schema.BuildDefinition, Option[Schema.BuildDefinition]] = (fun: Schema.BuildDefinition) => Option(fun)
		given putSchemaRunDetails: Conversion[Schema.RunDetails, Option[Schema.RunDetails]] = (fun: Schema.RunDetails) => Option(fun)
		given putListSchemaResourceDescriptor: Conversion[List[Schema.ResourceDescriptor], Option[List[Schema.ResourceDescriptor]]] = (fun: List[Schema.ResourceDescriptor]) => Option(fun)
		given putSchemaProvenanceBuilder: Conversion[Schema.ProvenanceBuilder, Option[Schema.ProvenanceBuilder]] = (fun: Schema.ProvenanceBuilder) => Option(fun)
		given putSchemaBuildMetadata: Conversion[Schema.BuildMetadata, Option[Schema.BuildMetadata]] = (fun: Schema.BuildMetadata) => Option(fun)
		given putSchemaFingerprint: Conversion[Schema.Fingerprint, Option[Schema.Fingerprint]] = (fun: Schema.Fingerprint) => Option(fun)
		given putListSchemaLayer: Conversion[List[Schema.Layer], Option[List[Schema.Layer]]] = (fun: List[Schema.Layer]) => Option(fun)
		given putListSchemaLocation: Conversion[List[Schema.Location], Option[List[Schema.Location]]] = (fun: List[Schema.Location]) => Option(fun)
		given putSchemaPackageOccurrenceArchitectureEnum: Conversion[Schema.PackageOccurrence.ArchitectureEnum, Option[Schema.PackageOccurrence.ArchitectureEnum]] = (fun: Schema.PackageOccurrence.ArchitectureEnum) => Option(fun)
		given putSchemaLicense: Conversion[Schema.License, Option[Schema.License]] = (fun: Schema.License) => Option(fun)
		given putSchemaDeploymentOccurrencePlatformEnum: Conversion[Schema.DeploymentOccurrence.PlatformEnum, Option[Schema.DeploymentOccurrence.PlatformEnum]] = (fun: Schema.DeploymentOccurrence.PlatformEnum) => Option(fun)
		given putSchemaDiscoveryOccurrenceContinuousAnalysisEnum: Conversion[Schema.DiscoveryOccurrence.ContinuousAnalysisEnum, Option[Schema.DiscoveryOccurrence.ContinuousAnalysisEnum]] = (fun: Schema.DiscoveryOccurrence.ContinuousAnalysisEnum) => Option(fun)
		given putSchemaDiscoveryOccurrenceAnalysisStatusEnum: Conversion[Schema.DiscoveryOccurrence.AnalysisStatusEnum, Option[Schema.DiscoveryOccurrence.AnalysisStatusEnum]] = (fun: Schema.DiscoveryOccurrence.AnalysisStatusEnum) => Option(fun)
		given putSchemaAnalysisCompleted: Conversion[Schema.AnalysisCompleted, Option[Schema.AnalysisCompleted]] = (fun: Schema.AnalysisCompleted) => Option(fun)
		given putListSchemaStatus: Conversion[List[Schema.Status], Option[List[Schema.Status]]] = (fun: List[Schema.Status]) => Option(fun)
		given putSchemaSBOMStatus: Conversion[Schema.SBOMStatus, Option[Schema.SBOMStatus]] = (fun: Schema.SBOMStatus) => Option(fun)
		given putSchemaSBOMStatusSbomStateEnum: Conversion[Schema.SBOMStatus.SbomStateEnum, Option[Schema.SBOMStatus.SbomStateEnum]] = (fun: Schema.SBOMStatus.SbomStateEnum) => Option(fun)
		given putListSchemaSignature: Conversion[List[Schema.Signature], Option[List[Schema.Signature]]] = (fun: List[Schema.Signature]) => Option(fun)
		given putListSchemaJwt: Conversion[List[Schema.Jwt], Option[List[Schema.Jwt]]] = (fun: List[Schema.Jwt]) => Option(fun)
		given putSchemaUpgradeDistribution: Conversion[Schema.UpgradeDistribution, Option[Schema.UpgradeDistribution]] = (fun: Schema.UpgradeDistribution) => Option(fun)
		given putSchemaWindowsUpdate: Conversion[Schema.WindowsUpdate, Option[Schema.WindowsUpdate]] = (fun: Schema.WindowsUpdate) => Option(fun)
		given putSchemaIdentity: Conversion[Schema.Identity, Option[Schema.Identity]] = (fun: Schema.Identity) => Option(fun)
		given putListSchemaCategory: Conversion[List[Schema.Category], Option[List[Schema.Category]]] = (fun: List[Schema.Category]) => Option(fun)
		given putListSchemaNonCompliantFile: Conversion[List[Schema.NonCompliantFile], Option[List[Schema.NonCompliantFile]]] = (fun: List[Schema.NonCompliantFile]) => Option(fun)
		given putSchemaComplianceVersion: Conversion[Schema.ComplianceVersion, Option[Schema.ComplianceVersion]] = (fun: Schema.ComplianceVersion) => Option(fun)
		given putListSchemaEnvelopeSignature: Conversion[List[Schema.EnvelopeSignature], Option[List[Schema.EnvelopeSignature]]] = (fun: List[Schema.EnvelopeSignature]) => Option(fun)
		given putSchemaSbomReferenceIntotoPayload: Conversion[Schema.SbomReferenceIntotoPayload, Option[Schema.SbomReferenceIntotoPayload]] = (fun: Schema.SbomReferenceIntotoPayload) => Option(fun)
		given putSchemaSbomReferenceIntotoPredicate: Conversion[Schema.SbomReferenceIntotoPredicate, Option[Schema.SbomReferenceIntotoPredicate]] = (fun: Schema.SbomReferenceIntotoPredicate) => Option(fun)
	}
	object OptionDefault {
		given getString: Conversion[Option[String], String] = (fun: Option[String]) => fun.getOrElse("")
	}
}
