package com.boresjo.play.api.google.cloudbuild

import play.api.libs.json.*
import play.api.libs.ws.{WSClient, WSRequest}
import com.boresjo.play.api.{PlayApi, AuthToken, JsonEnumFormat}

import javax.inject.*
import scala.concurrent.{ExecutionContext, Future}

object Formats {
	given fmtInstallationState: Format[Schema.InstallationState] = Json.format[Schema.InstallationState]
	given fmtInstallationStateStageEnum: Format[Schema.InstallationState.StageEnum] = JsonEnumFormat[Schema.InstallationState.StageEnum]
	given fmtStepRef: Format[Schema.StepRef] = Json.format[Schema.StepRef]
	given fmtStepRefResolverEnum: Format[Schema.StepRef.ResolverEnum] = JsonEnumFormat[Schema.StepRef.ResolverEnum]
	given fmtParam: Format[Schema.Param] = Json.format[Schema.Param]
	given fmtParamValue: Format[Schema.ParamValue] = Json.format[Schema.ParamValue]
	given fmtWorker: Format[Schema.Worker] = Json.format[Schema.Worker]
	given fmtSkippedTask: Format[Schema.SkippedTask] = Json.format[Schema.SkippedTask]
	given fmtWhenExpression: Format[Schema.WhenExpression] = Json.format[Schema.WhenExpression]
	given fmtOperation: Format[Schema.Operation] = Json.format[Schema.Operation]
	given fmtStatus: Format[Schema.Status] = Json.format[Schema.Status]
	given fmtBitbucketCloudConfig: Format[Schema.BitbucketCloudConfig] = Json.format[Schema.BitbucketCloudConfig]
	given fmtUserCredential: Format[Schema.UserCredential] = Json.format[Schema.UserCredential]
	given fmtPipelineRun: Format[Schema.PipelineRun] = Json.format[Schema.PipelineRun]
	given fmtWorkspaceBinding: Format[Schema.WorkspaceBinding] = Json.format[Schema.WorkspaceBinding]
	given fmtChildStatusReference: Format[Schema.ChildStatusReference] = Json.format[Schema.ChildStatusReference]
	given fmtProvenance: Format[Schema.Provenance] = Json.format[Schema.Provenance]
	given fmtGoogleDevtoolsCloudbuildV2Condition: Format[Schema.GoogleDevtoolsCloudbuildV2Condition] = Json.format[Schema.GoogleDevtoolsCloudbuildV2Condition]
	given fmtPipelineRunResult: Format[Schema.PipelineRunResult] = Json.format[Schema.PipelineRunResult]
	given fmtPipelineSpec: Format[Schema.PipelineSpec] = Json.format[Schema.PipelineSpec]
	given fmtSecurity: Format[Schema.Security] = Json.format[Schema.Security]
	given fmtPipelineRunPipelineRunStatusEnum: Format[Schema.PipelineRun.PipelineRunStatusEnum] = JsonEnumFormat[Schema.PipelineRun.PipelineRunStatusEnum]
	given fmtPipelineRef: Format[Schema.PipelineRef] = Json.format[Schema.PipelineRef]
	given fmtTimeoutFields: Format[Schema.TimeoutFields] = Json.format[Schema.TimeoutFields]
	given fmtPropertySpec: Format[Schema.PropertySpec] = Json.format[Schema.PropertySpec]
	given fmtPropertySpecTypeEnum: Format[Schema.PropertySpec.TypeEnum] = JsonEnumFormat[Schema.PropertySpec.TypeEnum]
	given fmtEnvVar: Format[Schema.EnvVar] = Json.format[Schema.EnvVar]
	given fmtGitHubConfig: Format[Schema.GitHubConfig] = Json.format[Schema.GitHubConfig]
	given fmtOAuthCredential: Format[Schema.OAuthCredential] = Json.format[Schema.OAuthCredential]
	given fmtBinding: Format[Schema.Binding] = Json.format[Schema.Binding]
	given fmtExpr: Format[Schema.Expr] = Json.format[Schema.Expr]
	given fmtEmpty: Format[Schema.Empty] = Json.format[Schema.Empty]
	given fmtCancelOperationRequest: Format[Schema.CancelOperationRequest] = Json.format[Schema.CancelOperationRequest]
	given fmtGoogleDevtoolsCloudbuildV2GitHubEnterpriseConfig: Format[Schema.GoogleDevtoolsCloudbuildV2GitHubEnterpriseConfig] = Json.format[Schema.GoogleDevtoolsCloudbuildV2GitHubEnterpriseConfig]
	given fmtGoogleDevtoolsCloudbuildV2ServiceDirectoryConfig: Format[Schema.GoogleDevtoolsCloudbuildV2ServiceDirectoryConfig] = Json.format[Schema.GoogleDevtoolsCloudbuildV2ServiceDirectoryConfig]
	given fmtListLocationsResponse: Format[Schema.ListLocationsResponse] = Json.format[Schema.ListLocationsResponse]
	given fmtLocation: Format[Schema.Location] = Json.format[Schema.Location]
	given fmtTestIamPermissionsResponse: Format[Schema.TestIamPermissionsResponse] = Json.format[Schema.TestIamPermissionsResponse]
	given fmtParamSpec: Format[Schema.ParamSpec] = Json.format[Schema.ParamSpec]
	given fmtParamSpecTypeEnum: Format[Schema.ParamSpec.TypeEnum] = JsonEnumFormat[Schema.ParamSpec.TypeEnum]
	given fmtWorkspacePipelineTaskBinding: Format[Schema.WorkspacePipelineTaskBinding] = Json.format[Schema.WorkspacePipelineTaskBinding]
	given fmtVolumeSource: Format[Schema.VolumeSource] = Json.format[Schema.VolumeSource]
	given fmtEmptyDirVolumeSource: Format[Schema.EmptyDirVolumeSource] = Json.format[Schema.EmptyDirVolumeSource]
	given fmtListConnectionsResponse: Format[Schema.ListConnectionsResponse] = Json.format[Schema.ListConnectionsResponse]
	given fmtConnection: Format[Schema.Connection] = Json.format[Schema.Connection]
	given fmtStepTemplate: Format[Schema.StepTemplate] = Json.format[Schema.StepTemplate]
	given fmtVolumeMount: Format[Schema.VolumeMount] = Json.format[Schema.VolumeMount]
	given fmtFetchReadTokenRequest: Format[Schema.FetchReadTokenRequest] = Json.format[Schema.FetchReadTokenRequest]
	given fmtStep: Format[Schema.Step] = Json.format[Schema.Step]
	given fmtSecurityContext: Format[Schema.SecurityContext] = Json.format[Schema.SecurityContext]
	given fmtStepOnErrorEnum: Format[Schema.Step.OnErrorEnum] = JsonEnumFormat[Schema.Step.OnErrorEnum]
	given fmtParamValueTypeEnum: Format[Schema.ParamValue.TypeEnum] = JsonEnumFormat[Schema.ParamValue.TypeEnum]
	given fmtAuditLogConfig: Format[Schema.AuditLogConfig] = Json.format[Schema.AuditLogConfig]
	given fmtAuditLogConfigLogTypeEnum: Format[Schema.AuditLogConfig.LogTypeEnum] = JsonEnumFormat[Schema.AuditLogConfig.LogTypeEnum]
	given fmtHttpBody: Format[Schema.HttpBody] = Json.format[Schema.HttpBody]
	given fmtPipelineResult: Format[Schema.PipelineResult] = Json.format[Schema.PipelineResult]
	given fmtPipelineTask: Format[Schema.PipelineTask] = Json.format[Schema.PipelineTask]
	given fmtPipelineWorkspaceDeclaration: Format[Schema.PipelineWorkspaceDeclaration] = Json.format[Schema.PipelineWorkspaceDeclaration]
	given fmtBatchCreateRepositoriesRequest: Format[Schema.BatchCreateRepositoriesRequest] = Json.format[Schema.BatchCreateRepositoriesRequest]
	given fmtCreateRepositoryRequest: Format[Schema.CreateRepositoryRequest] = Json.format[Schema.CreateRepositoryRequest]
	given fmtFetchGitRefsResponse: Format[Schema.FetchGitRefsResponse] = Json.format[Schema.FetchGitRefsResponse]
	given fmtSetIamPolicyRequest: Format[Schema.SetIamPolicyRequest] = Json.format[Schema.SetIamPolicyRequest]
	given fmtPolicy: Format[Schema.Policy] = Json.format[Schema.Policy]
	given fmtEmbeddedTask: Format[Schema.EmbeddedTask] = Json.format[Schema.EmbeddedTask]
	given fmtTaskSpec: Format[Schema.TaskSpec] = Json.format[Schema.TaskSpec]
	given fmtGoogleDevtoolsCloudbuildV2ConditionStatusEnum: Format[Schema.GoogleDevtoolsCloudbuildV2Condition.StatusEnum] = JsonEnumFormat[Schema.GoogleDevtoolsCloudbuildV2Condition.StatusEnum]
	given fmtGoogleDevtoolsCloudbuildV2ConditionSeverityEnum: Format[Schema.GoogleDevtoolsCloudbuildV2Condition.SeverityEnum] = JsonEnumFormat[Schema.GoogleDevtoolsCloudbuildV2Condition.SeverityEnum]
	given fmtTaskRef: Format[Schema.TaskRef] = Json.format[Schema.TaskRef]
	given fmtRepository: Format[Schema.Repository] = Json.format[Schema.Repository]
	given fmtFetchReadWriteTokenResponse: Format[Schema.FetchReadWriteTokenResponse] = Json.format[Schema.FetchReadWriteTokenResponse]
	given fmtSecretVolumeSource: Format[Schema.SecretVolumeSource] = Json.format[Schema.SecretVolumeSource]
	given fmtBitbucketDataCenterConfig: Format[Schema.BitbucketDataCenterConfig] = Json.format[Schema.BitbucketDataCenterConfig]
	given fmtGoogleDevtoolsCloudbuildV2GitLabConfig: Format[Schema.GoogleDevtoolsCloudbuildV2GitLabConfig] = Json.format[Schema.GoogleDevtoolsCloudbuildV2GitLabConfig]
	given fmtPipelineRefResolverEnum: Format[Schema.PipelineRef.ResolverEnum] = JsonEnumFormat[Schema.PipelineRef.ResolverEnum]
	given fmtBatchCreateRepositoriesResponse: Format[Schema.BatchCreateRepositoriesResponse] = Json.format[Schema.BatchCreateRepositoriesResponse]
	given fmtGoogleDevtoolsCloudbuildV2OperationMetadata: Format[Schema.GoogleDevtoolsCloudbuildV2OperationMetadata] = Json.format[Schema.GoogleDevtoolsCloudbuildV2OperationMetadata]
	given fmtListRepositoriesResponse: Format[Schema.ListRepositoriesResponse] = Json.format[Schema.ListRepositoriesResponse]
	given fmtPipelineResultTypeEnum: Format[Schema.PipelineResult.TypeEnum] = JsonEnumFormat[Schema.PipelineResult.TypeEnum]
	given fmtResultValue: Format[Schema.ResultValue] = Json.format[Schema.ResultValue]
	given fmtTaskResult: Format[Schema.TaskResult] = Json.format[Schema.TaskResult]
	given fmtTaskResultTypeEnum: Format[Schema.TaskResult.TypeEnum] = JsonEnumFormat[Schema.TaskResult.TypeEnum]
	given fmtTaskRefResolverEnum: Format[Schema.TaskRef.ResolverEnum] = JsonEnumFormat[Schema.TaskRef.ResolverEnum]
	given fmtFetchLinkableRepositoriesResponse: Format[Schema.FetchLinkableRepositoriesResponse] = Json.format[Schema.FetchLinkableRepositoriesResponse]
	given fmtFetchReadWriteTokenRequest: Format[Schema.FetchReadWriteTokenRequest] = Json.format[Schema.FetchReadWriteTokenRequest]
	given fmtWhenExpressionExpressionOperatorEnum: Format[Schema.WhenExpression.ExpressionOperatorEnum] = JsonEnumFormat[Schema.WhenExpression.ExpressionOperatorEnum]
	given fmtAuditConfig: Format[Schema.AuditConfig] = Json.format[Schema.AuditConfig]
	given fmtRunWorkflowCustomOperationMetadata: Format[Schema.RunWorkflowCustomOperationMetadata] = Json.format[Schema.RunWorkflowCustomOperationMetadata]
	given fmtTestIamPermissionsRequest: Format[Schema.TestIamPermissionsRequest] = Json.format[Schema.TestIamPermissionsRequest]
	given fmtProvenanceEnabledEnum: Format[Schema.Provenance.EnabledEnum] = JsonEnumFormat[Schema.Provenance.EnabledEnum]
	given fmtProvenanceStorageEnum: Format[Schema.Provenance.StorageEnum] = JsonEnumFormat[Schema.Provenance.StorageEnum]
	given fmtProvenanceRegionEnum: Format[Schema.Provenance.RegionEnum] = JsonEnumFormat[Schema.Provenance.RegionEnum]
	given fmtExecAction: Format[Schema.ExecAction] = Json.format[Schema.ExecAction]
	given fmtWorkspaceDeclaration: Format[Schema.WorkspaceDeclaration] = Json.format[Schema.WorkspaceDeclaration]
	given fmtCapabilities: Format[Schema.Capabilities] = Json.format[Schema.Capabilities]
	given fmtTaskSpecManagedSidecarsEnum: Format[Schema.TaskSpec.ManagedSidecarsEnum] = JsonEnumFormat[Schema.TaskSpec.ManagedSidecarsEnum]
	given fmtSidecar: Format[Schema.Sidecar] = Json.format[Schema.Sidecar]
	given fmtOperationMetadata: Format[Schema.OperationMetadata] = Json.format[Schema.OperationMetadata]
	given fmtProbe: Format[Schema.Probe] = Json.format[Schema.Probe]
	given fmtSecurityPrivilegeModeEnum: Format[Schema.Security.PrivilegeModeEnum] = JsonEnumFormat[Schema.Security.PrivilegeModeEnum]
	given fmtFetchReadTokenResponse: Format[Schema.FetchReadTokenResponse] = Json.format[Schema.FetchReadTokenResponse]
	given fmtChildStatusReferenceTypeEnum: Format[Schema.ChildStatusReference.TypeEnum] = JsonEnumFormat[Schema.ChildStatusReference.TypeEnum]
	given fmtResultValueTypeEnum: Format[Schema.ResultValue.TypeEnum] = JsonEnumFormat[Schema.ResultValue.TypeEnum]
}
